### PR TITLE
[file-search] don't mess around with given glob patterns

### LINKED ISSUE #4599: [workspace] workspace.findFiles does not work correct
### Description
As a result of `workspace.findFiles('**​/*.js', '**​/node_modules/**', 10)` I expect to get only `.js` files from the workspace. But files like `file1.jsblabla`, `file2.js.bla` also match to this pattern.

### PR DESCRIPTION
**Pull request by akosyakov**
fix #4599

### CODE REVIEW

**Comment by akosyakov** [comment]
@svor Could you check whether it fixes your concrete case?
@elaihau If you could verify with npm vscode extension it would be great.

File: packages/file-search/src/node/file-search-service-impl.ts [hunk 1]
```diff
@@ -110,14 +110,7 @@ export class FileSearchServiceImpl implements FileSearchService {
...
             for (const includePattern of options.includePatterns) {
-                let includeGlob = includePattern;
-                if (!includeGlob.endsWith('*')) {
-                    includeGlob = `${includeGlob}*`;
-                }
-                if (!includeGlob.startsWith('*')) {
-                    includeGlob = `*${includeGlob}`;
-                }
-                args.push('--glob', includeGlob);
+                args.push('--glob', includePattern);
```
Comment (elaihau) [inline packages/file-search/src/node/file-search-service-impl.ts]: we probably should do the same thing to the ignored patterns too. Line 122 - 131

Comment (elaihau) [inline packages/file-search/src/node/file-search-service-impl.ts]: should we do this to the ignored patterns too ? line 122 - 131

Comment (akosyakov) [reply packages/file-search/src/node/file-search-service-impl.ts]: good question, for vscode APIs i believe so

They were introduced for quick file though. Do you remember for which use cases?

Comment (elaihau) [reply packages/file-search/src/node/file-search-service-impl.ts]: the ignored pattern was there long time ago with the default value of `.git`. so i guess it was used to skip files in the `.git` folder. 
maybe we should leave line 122 - 131 as is, at least for now, as we have no idea if clients can possibly pass string literals (instead of globs) with `option.defaultIgnorePatterns`.

Comment (akosyakov) [reply packages/file-search/src/node/file-search-service-impl.ts]: i will introduce a new option for vscode extensions, e.g. `excludPatterns` and deprecate `defaultIgnorePatterns`. Magic around `defaultIgnorePatterns` should go to the quick file client.

Comment (akosyakov) [reply packages/file-search/src/node/file-search-service-impl.ts]: I think we misdesigned search APIs again :) `includePatterns` and `excludePatterns` should per a root URI, not for all root URIs

By default VS Code extensions expect that settings like `files.exclude` and `search.exclude` are applied and it can be different for each root.

It's actually the same for the quick file in VS Code, so you cannot search in `node_modules` without adjusting `search.exclude` folder. I like how it works now in Theia that you can toggle it. Should we align it as in VS Code? cc @svenefftinge

Comment (akosyakov) [reply packages/file-search/src/node/file-search-service-impl.ts]: I did not change how the quick file works, but improved APIs to support vscode APIs.

**Comment by akosyakov** [comment]
@elaihau @svor Could you please try again, now exclude patterns should be supported as well and respect `files.exclude` for vs code extension APIs.

File: tsconfig.json [hunk 2]
```diff
@@ -111,6 +111,15 @@
       ],
       "@theia/getting-started/lib/*": [
         "packages/getting-started/src/*"
+      ],
```
Comment (benoitf) [inline tsconfig.json]: hello, why do we need this as part of this PR ?

Comment (akosyakov) [reply tsconfig.json]: because navigation does not work, one cannot see that file search is used in plugin ext

File: packages/file-search/src/common/file-search-service.ts [hunk 3]
```diff
@@ -33,13 +33,24 @@ export interface FileSearchService {
 
 export const FileSearchService = Symbol('FileSearchService');
 export namespace FileSearchService {
-    export interface Options {
-        rootUris: string[]
+    export interface BaseOptions {
+        useGitIgnore?: boolean
```
Comment (elaihau) [inline packages/file-search/src/common/file-search-service.ts]: just wondering: why is gitignore more special than the others?

File: packages/file-search/src/common/file-search-service.ts [hunk 4]
```diff
@@ -33,13 +33,24 @@ export interface FileSearchService {
...
+        includePatterns?: string[]
+        excludePatterns?: string[]
+    }
+    export interface Roots {
+        [rootUri: string]: BaseOptions
+    }
+    export interface Options extends BaseOptions {
+        rootUris?: string[]
+        roots?: Roots
```
Comment (elaihau) [inline packages/file-search/src/common/file-search-service.ts]: does this mean "option per root" ? if so, could we rename it into something more descriptive ? i have no idea what it could be renamed into as I am bad at naming things :)

Comment (akosyakov) [reply packages/file-search/src/common/file-search-service.ts]: `rootOptions`?

File: packages/file-search/src/common/file-search-service.ts (hunk 3 above)
Comment (akosyakov) [reply packages/file-search/src/common/file-search-service.ts]: I have not thought about semantics fo `useGitIgnore` (only about globs) in this PR and moved it here to be able to pass it tor https://github.com/theia-ide/theia/pull/4602/files/b8c3cff127161cc5509089b0f1bbb3f7ef5196ce#diff-6ba24f8b01d65a9959cba7e78f9a050bR131

Would it be alright to rethink it separately? Could you open an issue?


Renaming it would be a breaking change,

Comment (elaihau) [reply packages/file-search/src/common/file-search-service.ts]: yea for sure it doesn't belong to this PR even if other .ignore files need to be supported.

**Comment by elaihau** [comment]
> Could you please try again, now exclude patterns should be supported as well and respect `files.exclude` for vs code extension APIs.

tested. it is working. :+1:

File: packages/file-search/src/common/file-search-service.ts (hunk 4 above)
Comment (akosyakov) [reply packages/file-search/src/common/file-search-service.ts]: It's confusing as well. It means options for a root, not per a root. Do you have better suggestion or we stick with `roots`? To me is fine, since each property is a root with an associated options.

Comment (elaihau) [reply packages/file-search/src/common/file-search-service.ts]: how does "optionPerRoot" or "perRootOption" sound?

Comment (akosyakov) [reply packages/file-search/src/common/file-search-service.ts]: i would rename it to `rootOptions` later, `optionPerRoot` looks very atypical

**Comment by svor** [comment]
@akosyakov works nice!

File: packages/file-search/src/common/file-search-service.ts (hunk 4 above)
Comment (akosyakov) [reply packages/file-search/src/common/file-search-service.ts]: @elaihau I've renamed to `rootOptions`, good to merge now?

Comment (elaihau) [reply packages/file-search/src/common/file-search-service.ts]: yes for sure. the pr approval is still in place :)
