### PR TITLE
[monaco] Fix regex for the electron runtime

### LINKED ISSUE #3745: [electron] Cannot start the electron application
431d12a5

```
Uncaught (in promise) SyntaxError: Invalid regular expression: /(?<!\!\s*)isInDiffEditor/: Invalid group
    at MonacoKeybindingContribution.push.../../packages/monaco/lib/browser/monaco-keybinding.js.MonacoKeybindingContribution.registerKeybindings (/Users/akos.kitta/Desktop/theia/examples/electron/lib/47.bundle.js:1238)
    at KeybindingRegistry.../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.onStart (bundle.js:75896)
    at FrontendApplication.<anonymous> (bundle.js:75393)
    at step (bundle.js:75048)
    at Object.next (bundle.js:75029)
    at bundle.js:75023
    at Promise (<anonymous>)
    at ../../packages/core/lib/browser/frontend-application.js.__awaiter (bundle.js:75019)
    at FrontendApplication.../../packages/core/lib/browser/frontend-application.js.FrontendApplication.startContributions (bundle.js:75361)
    at FrontendApplication.<anonymous> (bundle.js:75125)
```

### PR DESCRIPTION
**Pull request by marechal-p**
The Electron version we use embbeds Node 8.2.1 which doesn't support
negative-lookbehinds in regexs.

Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

Fix #3745

### CODE REVIEW

File: packages/monaco/src/browser/monaco-keybinding.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ export class MonacoKeybindingContribution implements KeybindingContribution {
                             keybinding = { ...keybinding, ctrlKey: true, metaKey: false };
                         }
                     }
-                    const isInDiffEditor = item.when && /(?<!\!\s*)isInDiffEditor/gm.test(item.when.serialize());
+                    const isInDiffEditor = item.when && /([^!]|\s*)isInDiffEditor/gm.test(item.when.serialize());
```
Comment (marechal-p) [inline packages/monaco/src/browser/monaco-keybinding.ts]: Ah, because I reused the same regex object for my tests, turns out it wronged the results.

TODO: Find an other regex.

File: packages/monaco/src/browser/monaco-keybinding.ts [hunk 2]
```diff
@@ -50,7 +50,7 @@ export class MonacoKeybindingContribution implements KeybindingContribution {
                             keybinding = { ...keybinding, ctrlKey: true, metaKey: false };
                         }
                     }
-                    const isInDiffEditor = item.when && /(?<!\!\s*)isInDiffEditor/gm.test(item.when.serialize());
+                    const isInDiffEditor = item.when && /\b[^!]isInDiffEditor/gm.test(item.when.serialize());
```
Comment (marechal-p) [inline packages/monaco/src/browser/monaco-keybinding.ts]: Still not good... Am I going crazy?

Comment (marechal-p) [reply packages/monaco/src/browser/monaco-keybinding.ts]: Please, next time someone stop me from doing regexs.

**Comment by marechal-p** [comment]
@kittaakos This should fix the issue on Electron.

**Comment by kittaakos** [comment]
Awesome! I am checking it...

**Comment by kittaakos** [comment]
I can confirm, the app starts.

But I do not know whether we have fixed the keybinding collision issue or not.
According to the "old" logs, the following keybindings had collision:
```
{"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"diffEditorTextFocus"}
{"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"diffEditorTextFocus"}


{"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"diffEditorTextFocus"}
{"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"diffEditorTextFocus"}
```

With your patch, when I open a diff editor, and I do <kbd>Shift</kbd>+<kbd>F7</kbd> something else happens. I expected some word highlight related action. Instead, the diff editor has closed.

screencast 2018-12-06 08-45-05

**Comment by kittaakos** [comment]
Thanks for the review @AlexTugarev. I am merging this.

**Comment by marechal-p** [comment]
FYI: Here are the contexts tested against the old and new regex:

```
textInputFocus old(false) new(false)
textInputFocus && !editorReadonly old(false) new(false)
textInputFocus && !editorReadonly old(false) new(false)
textInputFocus && !editorReadonly old(false) new(false)
editorFocus old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
textInputFocus && !editorReadonly old(false) new(false)
isInDiffEditor old(true) new(true)
isInDiffEditor old(true) new(true)
editorTextFocus && !editorReadonly old(false) new(false)
editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor old(false) new(false)
editorFocus old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus old(false) new(false)
editorTextFocus old(false) new(false)
editorTextFocus old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus old(false) new(false)
editorFocus && !editorReadonly old(false) new(false)
editorFocus && !editorReadonly old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorFocus old(false) new(false)
editorFocus old(false) new(false)
editorFocus old(false) new(false)
editorTextFocus && !editorReadonly && supportedCodeAction =~ /(s|^)source.organizeImport/ old(false) new(false)
editorTextFocus && !editorReadonly old(false) new(false)
editorHasImplementationProvider && editorTextFocus && !isInEmbeddedEditor old(false) new(false)
editorHasDefinitionProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor old(false) new(false)
editorFocus old(false) new(false)
editorFocus old(false) new(false)
editorFocus old(false) new(false)
editorHasCodeActionsProvider && editorTextFocus && !editorReadonly old(false) new(false)
editorFocus && editorHasDocumentSymbolProvider old(false) new(false)
editorHasCodeActionsProvider && editorTextFocus && !editorReadonly old(false) new(false)
editorHasReferenceProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor old(false) new(false)
editorHasRenameProvider && editorTextFocus && !editorReadonly old(false) new(false)
editorFocus old(false) new(false)
editorFocus old(false) new(false)
textInputFocus old(false) new(false)
editorTextFocus old(false) new(false)
editorTextFocus old(false) new(false)
textInputFocus && !editorReadonly old(false) new(false)
editorHasSignatureHelpProvider && editorTextFocus old(false) new(false)
editorHasCompletionItemProvider && textInputFocus && !editorReadonly old(false) new(false)
editorTextFocus && hasWordHighlights old(false) new(false)
editorTextFocus old(false) new(false)
editorTextFocus old(false) new(false)
```
