### PR TITLE
Fixes #4741 allow creation of sub-files and/or sub-folders if name has "/"

### LINKED ISSUE #4741: [UX] Creating multiple folders with / in the name
### Description
Let say I need to create `src/main/java` folder, I need to create first `src` then `main` then `java` while typically on IDE I can enter directly `src/main/java` and all three folders are automatically created

In Theia it displays `Invalid name, try other`

### Reproduction Steps
Menu File / New Folder
enter `src/main/java`

**OS and Theia version:**
macOS / master

**Diagnostics:** 
N/A

### PR DESCRIPTION
**Pull request by uniibu**
Fixes https://github.com/theia-ide/theia/issues/4741. Creation of sub-files and/or sub-folders are already available,however, validation check does not allow `/` on the input box, making it impossible to create nested sub-folders and/or sub-files.

This PR allows recursive creation of folders or files via `/` .
- allow recursive creation for New File and New Folder only.
- do not allow creation of files and folders that starts with `/` 
- do not allow creation of files and folders that starts and ends with a whitepsace.
- do not allow recursive create on Rename.

Example:
- Creating a file using `test/scripts/index.js` will create test and `test/scripts` folder if it still does not exists and lastly it creates the file `test/scripts/index.js`

Signed-off-by: Uni Sayo <unibtc@gmail.com>

### CODE REVIEW

File: packages/core/src/browser/dialogs.ts [hunk 1]
```diff
@@ -194,7 +194,9 @@ export abstract class AbstractDialog<T> extends BaseWidget {
         this.activeElement = undefined;
         super.close();
     }
-
+    error(error: string): void {
```
Comment (akosyakov) [inline packages/core/src/browser/dialogs.ts]: please remove, there a contract that the validation callback should provide an error and it is called at the appropriate moment

File: packages/workspace/src/browser/workspace-commands.ts [hunk 2]
```diff
@@ -308,18 +311,26 @@ export class WorkspaceCommandContribution implements CommandContribution {
...
+            return 'Invalid file or folder name';
         }
+        const fileName = path.basename(name);
+        if (!validFilename(fileName) || name.startsWith('/') || name.startsWith(' ') || name.endsWith(' ')) {
+            return `The name <strong>${fileName}</strong> is not a valid file or folder name.`;
+        }
+        const childUri = new URI(parent.uri).resolve(name).toString();
+        this.fileSystem.exists(childUri).then(exists => {
+            if (exists && dialog) {
+                dialog.error(`A file or folder <strong>${fileName}</strong> already exists at this location.`);
```
Comment (akosyakov) [inline packages/workspace/src/browser/workspace-commands.ts]: We should change a type of validation function to `MaybPromise<DialogError>` to allow async validation. Inside the dialog we will need to make sure that concurrent validation does not occur, i.e. queue them or cancel.

**Comment by akosyakov** [comment]
I wonder can we override `CtrlCmd + N` browser short cut to create a new file, so annoying to click each time.

**Comment by akosyakov** [comment]
It does not work if i create the same path twice from the root, it seems to pick the wrong parent then which is very confusing. Not sure whether it is a new bug or something which was not apparent before. In order to reprdoce with Theia repo:
- right click on `theia` folder -> `New File` -> `configs/Untitled.txt` and create a file
- do the same again without doing anything else

I would expect an error, but there are non and the second file is created at the bogus location: `theia/configs/configs/Untitled.txt`

**Comment by uniibu** [comment]
> It does not work if i create the same path twice from the root, it seems to pick the wrong parent then which is very confusing. Not sure whether it is a new bug or something which was not apparent before. In order to reprdoce with Theia repo:
> 
> * right click on `theia` folder -> `New File` -> `configs/Untitled.txt` and create a file
> * do the same again without doing anything else
> 
> I would expect an error, but there are non and the second file is created at the bogus location: `theia/configs/configs/Untitled.txt`

This is because of inconsistent selection bug when creating a new file. Sometimes the new file gets selected on creation (which is what it is supposed to do) and sometimes it doesn't. 
This is due to this line:
https://github.com/theia-ide/theia/blob/636533952fd4b42cfc834e346ec3402f0c5db343/packages/filesystem/src/browser/file-resource.ts#L119
which needs to be `if (!await this.fileSystem.exists(this.uriString)) { `

I've patched this on the latest commit.

File: packages/workspace/src/browser/workspace-commands.ts [hunk 3]
```diff
@@ -16,6 +16,7 @@
 
 import { inject, injectable } from 'inversify';
 import URI from '@theia/core/lib/common/uri';
+import * as path from 'path';
```
Comment (akosyakov) [inline packages/workspace/src/browser/workspace-commands.ts]: it is not allowed to use node.js apis in browser cone, please use core URI and Path

File: packages/filesystem/src/browser/file-dialog/file-dialog.ts [hunk 4]
```diff
@@ -261,7 +261,7 @@ export class OpenFileDialog extends FileDialog<MaybeArray<FileStatNode>> {
         }
     }
 
-    protected accept(): void {
+    protected async accept(): Promise<void> {
```
Comment (akosyakov) [inline packages/filesystem/src/browser/file-dialog/file-dialog.ts]: we need to update CHANGELOG with a breaking change, that `validate` and `accept` in Dialog gets promisified since it is breaking here

It should go under 0.6.0

File: packages/filesystem/src/browser/file-resource.ts [hunk 5]
```diff
@@ -116,7 +116,7 @@ export class FileResource implements Resource {
     }
 
     protected async getFileStat(): Promise<FileStat | undefined> {
-        if (!this.fileSystem.exists(this.uriString)) {
+        if (!await this.fileSystem.exists(this.uriString)) {
```
Comment (akosyakov) [inline packages/filesystem/src/browser/file-resource.ts]: how it used to work! ❤️ for fixing it!

File: packages/core/src/browser/dialogs.ts [hunk 6]
```diff
@@ -194,25 +194,24 @@ export abstract class AbstractDialog<T> extends BaseWidget {
...
         super.close();
     }
-
     protected onUpdateRequest(msg: Message): void {
         super.onUpdateRequest(msg);
         this.validate();
     }
 
-    protected validate(): void {
+    protected async validate(): Promise<void> {
```
Comment (akosyakov) [inline packages/core/src/browser/dialogs.ts]: please apply cancellation pattern here and in accept method (accept should have own cancellation source):
```ts
    protected validateCancellationSource = new CancellationTokenSource();
    protected async validate(): Promise<void> {
        if (!this.resolve) {
            return;
        }
        this.validateCancellationSource.cancel();
        this.validateCancellationSource = new CancellationTokenSource();
        const token = this.validateCancellationSource.token;
        const value = this.value;
        const error = await this.isValid(value, 'preview');
        if (token.isCancellationRequested) {
            return;
        }
        this.setErrorMessage(error);
    }
```

The issue is that if `validate` is triggered twice then only last should win. The same for accept.

File: packages/core/src/browser/dialogs.ts [hunk 7]
```diff
@@ -194,31 +194,45 @@ export abstract class AbstractDialog<T> extends BaseWidget {
...
-            } else {
-                this.resolve(value);
-                Widget.detach(this);
-            }
+    protected acceptCancellationSource = new CancellationTokenSource();
+    protected async accept(): Promise<void> {
+        if (!this.resolve) {
+            return;
+        }
+        this.validateCancellationSource.cancel();
```
Comment (akosyakov) [inline packages/core/src/browser/dialogs.ts]: `acceptCancellationSource` in this method

Comment (uniibu) [reply packages/core/src/browser/dialogs.ts]: ah, a bad copy and paste 🤣

File: packages/workspace/src/browser/workspace-commands.ts [hunk 8]
```diff
@@ -308,20 +310,34 @@ export class WorkspaceCommandContribution implements CommandContribution {
...
-                }
-            }
+        // do not allow recursive rename
+        if (!recursive && !validFilename(name)) {
+            return 'Invalid file or folder name';
+        }
+        // check and validate each sub-paths
+        const names = name.split(/[\\/]/).some(file => !file || !validFilename(file) || /^\s+$/.test(file));
+        if (names || name.startsWith('/') || name.startsWith(' ') || name.endsWith(' ')) {
+            return `The name <strong>${this.trimFileName(name)}</strong> is not a valid file or folder name.`;
```
Comment (benoitf) [inline packages/workspace/src/browser/workspace-commands.ts]: if there is space in the name the error message will display them but error message may be a little bit wired (hard to see spaces). Maybe it will be nice to say to the user specific error message like there are invalid spaces at the beginning or that it shouldn't start with a / instead of saying (not valid)

File: packages/workspace/src/browser/workspace-commands.ts [hunk 9]
```diff
@@ -421,6 +436,7 @@ export class WorkspaceRootUriAwareCommandHandler extends UriAwareCommandHandler<
         if (uri) {
             return uri;
         }
+
```
Comment (benoitf) [inline packages/workspace/src/browser/workspace-commands.ts]: maybe remove this line that do nothing ?

Comment (uniibu) [reply packages/workspace/src/browser/workspace-commands.ts]: i think this is needed so it doesn't continue with 
``` 
const root = this.workspaceService.tryGetRoots()[0];
return root && new URI(root.uri);
```

I can just simplify it with
```
if (this.workspaceService.isMultiRootWorkspaceOpened || uri) {
      return uri;
}
```

Comment (benoitf) [reply packages/workspace/src/browser/workspace-commands.ts]: @uniibu I was just referencing the empty line

Comment (uniibu) [reply packages/workspace/src/browser/workspace-commands.ts]: ah my bad. 👍

File: packages/workspace/src/browser/workspace-commands.ts (hunk 8 above)
Comment (uniibu) [reply packages/workspace/src/browser/workspace-commands.ts]: i could separate those and have it like this:
```
        // check and validate each sub-paths
        if (name.split(/[\\/]/).some(file => !file || !validFilename(file) || /^\s+$/.test(file))) {
            return `The name <strong>${this.trimFileName(name)}</strong> is not a valid file or folder name.`;
        } else if (name.startsWith('/')) {
            return 'Absolute paths or names that starts with / are not allowed';
        } else if (name.startsWith(' ') || name.endsWith(' ')) {
            return 'Names with leading or trailing whitespaces are not allowed'
        }
```

Comment (uniibu) [reply packages/workspace/src/browser/workspace-commands.ts]: actually, absolute path check must go first, so itll be like :
```
        if (name.startsWith('/')) {
            return 'Absolute paths or names that starts with / are not allowed';
        } else if (name.startsWith(' ') || name.endsWith(' ')) {
            return 'Names with leading or trailing whitespaces are not allowed';
        }
        // check and validate each sub-paths
        if (name.split(/[\\/]/).some(file => !file || !validFilename(file) || /^\s+$/.test(file))) {
            return `The name <strong>${this.trimFileName(name)}</strong> is not a valid file or folder name.`;
        } 
```

**Comment by uniibu** [comment]
i've separated the validation checks for absolute paths and leading and trailing spaces as per suggested. Squashed commits.
