### PR TITLE
[file-search] remove separator when no recent results are found in the quick-file-open

### LINKED ISSUE #5547: [file-search] remove separator border when no recent results are found
**Description**

When performing the `quick-file-search` (<kbd>ctrlcmd</kbd>+<kbd>p</kbd>) and no recent results are present, we still display the separator incorrectly. The separator should only be displayed if there **are** recent results.

<div align='center'>

image

</div>

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #5547

Currently, when no recent results are found when performing the quick-file-open, we display a separator incorrectly. The separator should only be displayed to differentiate between two groups of items and thus
should only be displayed if there currently are recent results. The PR addresses the issue by only displaying the separator if the recent results list has one or more values.

| With Recent Results | Without Recent Results |
|:---:|:---:|
|image|image |

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

File: packages/file-search/src/browser/quick-file-open.ts [hunk 1]
```diff
@@ -192,7 +192,7 @@ export class QuickFileOpenService implements QuickOpenModel, QuickOpenHandler {
                 const first = sortedResults[0];
                 sortedResults.shift();
                 if (first) {
-                    const item = await this.toItem(first.getUri()!, { groupLabel: 'file results', showBorder: true });
+                    const item = await this.toItem(first.getUri()!, { groupLabel: 'file results', showBorder: !!recentlyUsedItems.length ? true : false });
```
Comment (elaihau) [inline packages/file-search/src/browser/quick-file-open.ts]: i guess there is no need to have `? true : false ` ?

Comment (vince-fugnitto) [reply packages/file-search/src/browser/quick-file-open.ts]: Ohh true! :see_no_evil:

Comment (vince-fugnitto) [reply packages/file-search/src/browser/quick-file-open.ts]: @elaihau updated, thank you!
