### PR TITLE
 [core/cluster] Try to close each process gracefully

### LINKED ISSUE #1883: [question][quality] The backend should terminate when the address is already in use
Currently, we just log the error and that's all. It would be better to terminate the process, wouldn't it?

```
{"name":"Theia","hostname":"Akoss-MacBook-Pro.local","pid":16249,"level":50,"msg":"Uncaught Exception:  [ 'Error: bind EADDRINUSE 127.0.0.1:3000' ]","time":"2018-05-10T14:11:12.849Z","v":0}
{"name":"Theia","hostname":"Akoss-MacBook-Pro.local","pid":16249,"level":50,"msg":"Error: bind EADDRINUSE 127.0.0.1:3000\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at listenOnMasterHandle (net.js:1414:16)\n    at rr (internal/cluster/child.js:111:12)\n    at Worker.send (internal/cluster/child.js:78:7)\n    at process.onInternalMessage (internal/cluster/utils.js:42:8)\n    at emitTwo (events.js:130:20)\n    at process.emit (events.js:213:7)\n    at emit (internal/child_process.js:774:12)\n    at _combinedTickCallback (internal/process/next_tick.js:141:11) []","time":"2018-05-10T14:11:12.850Z","v":0}
```

CC: @akosyakov, @svenefftinge

### PR DESCRIPTION
**Pull request by marechal-p**
When the backend closes, processes spawned when running in cluster mode don't always close properly, making the terminal where Theia was started hang.
Cause can be unfulfilled promises keeping the event-loop alive.

Solution was to make sure that in case an error happens, it is detected and call `process.exit()`.

Fixes #1883

Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
I have restarted the AppVeyor build; it was failing with an unrelated FS test.

So did we eventually decide how to handle the `EADDRINUSE` errors? (Or handle them at all?) I have just raised a question, but we did not yet make a call how to tackle this.

I put the review on hold until we have a decision.

File: packages/core/src/node/backend-application.ts [hunk 1]
```diff
@@ -150,6 +151,13 @@ export class BackendApplication {
             server = http.createServer(this.app);
         }
 
+        server.on('error', error => {
+            deferred.reject(error);
+            /* The backend might run in a separate process,
+             * so we defer `process.exit` to let time for logging in the parent process */
+            setTimeout(process.exit, 0, 1);
```
Comment (akosyakov) [inline packages/core/src/node/backend-application.ts]: What logging do you mean?

File: packages/core/src/node/cluster/master-process.ts [hunk 2]
```diff
@@ -33,8 +40,11 @@ export class MasterProcess extends EventEmitter {
         if (!this.serverWorker) {
             throw new Error('Server worker is not running.');
         }
+        this.isRestarting = true;
         this.emit('restarting', this.serverWorker);
         console.log(`Restarting the server worker is requested.`);
+
+        await this.serverWorker.stop();
```
Comment (akosyakov) [inline packages/core/src/node/cluster/master-process.ts]: An old worker should be stopped only in the case if a new worker is successfully started and initialized, please rollback.

File: packages/core/src/node/cluster/master-process.ts [hunk 3]
```diff
@@ -49,14 +59,15 @@ export class MasterProcess extends EventEmitter {
             throw new Error(message);
         }
         this.serverWorker = serverWorker;
+        this.isRestarting = false;
```
Comment (akosyakov) [inline packages/core/src/node/cluster/master-process.ts]: please use do it in `final` closure.

File: packages/core/src/node/cluster/master-process.ts [hunk 4]
```diff
@@ -8,13 +8,20 @@
 import { EventEmitter } from 'events';
 import { ServerWorker } from './server-worker';
 
-export type MasterProcessEvent = 'started' | 'restarted' | 'restarting';
+export type MasterProcessEvent = 'started' | 'restarted' | 'restarting' | 'exited';
 export class MasterProcess extends EventEmitter {
 
     protected serverWorker: ServerWorker | undefined;
+    protected isRestarting: boolean = false;
```
Comment (akosyakov) [inline packages/core/src/node/cluster/master-process.ts]: `restarting`, `is` for method names

File: dev-packages/application-manager/src/generator/backend-generator.ts [hunk 5]
```diff
@@ -33,9 +33,9 @@ container.load(messagingBackendModule);
 container.load(loggerBackendModule);
 
 function load(raw) {
-    return Promise.resolve(raw.default).then(module =>
```
[the remark this answers is not in the document]
Comment (marechal-p) [reply dev-packages/application-manager/src/generator/backend-generator.ts]: Ok my bad, it looked weird, thanks for explaining.

File: packages/core/src/node/backend-application.ts (hunk 1 above)
Comment (marechal-p) [reply packages/core/src/node/backend-application.ts]: Any logging, errors or messages thrown by the process aren't channelled through the root terminal process if we don't let just a bit of time pass. I don't clearly understand why it happens, but my guess would be that the IPC channels that bubble errors up might be registered in the eventloop, and registering `process.exit` at the end of the event stack might allow the logging to be sent ?

File: packages/core/src/node/cluster/master-process.ts (hunk 2 above)
Comment (marechal-p) [reply packages/core/src/node/cluster/master-process.ts]: I don't really understand, because I made this PR so that we would try to shutdown processes gracefully on backend startup errors, such as `EADDRINUSE`. If we try to start a new worker while the old one is still running and still bound to `localhost:3000`, then the new worker would crash just by trying to start, right ?

Tell me if I missed something.

File: packages/core/src/node/cluster/master-process.ts (hunk 4 above)
Comment (marechal-p) [reply packages/core/src/node/cluster/master-process.ts]: `restarting` is used to return some kind of promise, but it is for a ponctual event and it is not a lock / flag, which we would need here ?

Tell me if I missed something again.

File: packages/core/src/node/cluster/master-process.ts (hunk 3 above)
Comment (marechal-p) [reply packages/core/src/node/cluster/master-process.ts]: Sorry, I don't get your idea...

File: packages/core/src/node/backend-application.ts (hunk 1 above)
Comment (marechal-p) [reply packages/core/src/node/backend-application.ts]: _(if I don't do this `setTimeout(exit, 0ms, ...)` no messages get logged in the root terminal used to start Theia; `setImmediate(...)` doesn't work either)_

Comment (marechal-p) [reply packages/core/src/node/backend-application.ts]: _(if you want an example, try to run 2 Theias instance on the same endpoint, this will throw an error)_

File: packages/core/src/node/cluster/master-process.ts (hunk 2 above)
Comment (akosyakov) [reply packages/core/src/node/cluster/master-process.ts]: `restart` is called when a new extension is installed to spawn a new server worker If a new server worker cannot be started or initialized with that extension then we should continue using the old. Only when a new worker is successfully started and initialized it is allowed to stop old.

Our issues does not have anything to do with restarting, only with an initial start. It would be nice to minimize scope of changes to avoid breaking something.

File: packages/core/src/node/cluster/master-process.ts (hunk 3 above)
Comment (akosyakov) [reply packages/core/src/node/cluster/master-process.ts]: it should be in `final` closure to make sure that a flag is restored even if there are some exceptions, although if there is a solution not touching `restart` method i would prefer it

File: packages/core/src/node/cluster/master-process.ts (hunk 4 above)
Comment (akosyakov) [reply packages/core/src/node/cluster/master-process.ts]: it is minor, just about naming, if you add a method returning `isRestarting`, you will need to name it differently since it will collide with a property, because of it a property usually called `restarting` and access method `isRestarting`.

File: packages/core/src/node/backend-application.ts (hunk 1 above)
Comment (akosyakov) [reply packages/core/src/node/backend-application.ts]: Maybe we should enrich the protocol that the server worker asks the master process to stop it then the master will have all control.

**Comment by marechal-p** [comment]
Thanks to your comments I was able to better understand the context of these methods. Now looking for a way to do this better.

**Comment by marechal-p** [comment]
@akosyakov would this be better ? I tried to impact as little things as possible. I didn't understand the full scope of the class I was modifying at first, now it should be lighter.

File: packages/core/src/node/cluster/master-process.ts [hunk 6]
```diff
@@ -8,13 +8,15 @@
...
-export type MasterProcessEvent = 'started' | 'restarted' | 'restarting';
+export type MasterProcessEvent = 'started' | 'restarted' | 'restarting' | 'exit';
 export class MasterProcess extends EventEmitter {
 
     protected serverWorker: ServerWorker | undefined;
 
     protected fork(): ServerWorker {
-        return new ServerWorker(() => this.restart());
+        const worker = new ServerWorker(() => this.restart());
+        worker.exit.then(() => this.emit('exit', worker));
```
Comment (akosyakov) [inline packages/core/src/node/cluster/master-process.ts]: What about propagating the exit code? i.e.
`worker.exit.then(code => this.emit('exit', code))` and exiting the main process with the same code

Comment (akosyakov) [reply packages/core/src/node/cluster/master-process.ts]: For `restart` this listener should be installed only a new worker is successfully initialized, i.e. at https://github.com/theia-ide/theia/pull/1893/files#diff-5ae26f56a8fb4b14d6f3f63382663531R54

File: packages/core/src/node/cluster/main.ts [hunk 7]
```diff
@@ -36,6 +36,10 @@ export interface Address {
 export async function start(serverPath: string): Promise<Address> {
     if (isMaster) {
         const master = new MasterProcess();
+        master.on('exit', () =>
+            Object.keys(cluster.workers).length === 0
```
Comment (akosyakov) [inline packages/core/src/node/cluster/main.ts]: checking workers should not be necessary if you do https://github.com/theia-ide/theia/pull/1893#discussion_r189159070

File: packages/core/src/node/test/cluster-test-worker.ts [hunk 8]
```diff
@@ -15,9 +15,9 @@ const jobs: { [id: string]: (() => Promise<void>) | undefined } = {
         try {
             await server.restart();
             firstRestartFailed = false;
-        } catch (e) {
-            if ((e as Error).message.indexOf('failed to restart') === -1) {
-                throw e;
+        } catch (error) {
+            if (!/failed to (re)?start/.test(error.message)) {
```
Comment (akosyakov) [inline packages/core/src/node/test/cluster-test-worker.ts]: `(re)?` - redundant?

File: packages/core/src/node/cluster/master-process.ts [hunk 9]
```diff
@@ -8,25 +8,52 @@
 import { EventEmitter } from 'events';
 import { ServerWorker } from './server-worker';
 
+class ProcessError extends Error {
+    returnCode: number = -1;
```
Comment (akosyakov) [inline packages/core/src/node/cluster/master-process.ts]: How about `1` to indicate failure by default?

File: packages/core/src/node/test/cluster-test-worker.ts (hunk 8 above)
Comment (marechal-p) [reply packages/core/src/node/test/cluster-test-worker.ts]: it is one of the cases where I would really love to have something along https://github.com/theia-ide/theia/pull/1536

File: packages/core/src/node/cluster/master-process.ts [hunk 10]
```diff
@@ -8,27 +8,55 @@
...
+            worker.stop();
+            error.returnCode = await worker.exit;
+            throw error;
+        }
+
+        // Success
+        this.workerCount++;
+        worker.exit.then(code => {
+            if (--this.workerCount === 0) {
+                super.emit('exit', code);
```
[the remark this answers is not in the document]
Comment (akosyakov) [reply packages/core/src/node/cluster/master-process.ts]: ok, it is fine, although sounds like it can be solved by cleaning exit listeners for old worker

[the remark this answers is not in the document]
Comment (marechal-p) [reply packages/core/src/node/cluster/master-process.ts]: you are right, but we are doin a `Promise.then`, is there a way to remove the callback from the promise ? or should I poll inside the callback for some flag ?

[the remark this answers is not in the document]
Comment (akosyakov) [reply packages/core/src/node/cluster/master-process.ts]: it is fine with me as it is done now
