### PR TITLE
Fix quick-pick initiated by the plugins not displaying with 1 item

### LINKED ISSUE #6050: quickpick didn't open with 1 item
### Description
In the new version of theia  ( theiaide/theia-full:next ) when I open quickpick with one item it doesn't show the item.
It works with multi items.

### Reproduction Steps
I created vsix from github ( with 1 item)
https://github.com/i053322/quickpickexample
Load the VSIX and press F1 and choose Hello World

**OS and Theia version:**
master

**Diagnostics:** 
I checked it on version 0.9.0 and it worked.
It it also worked on VS CODE

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #6050

- fixes issue where `quick-pick` which were initiated by the plugins was
not displayed when it only contains a single item. The fix is to include
a new flag `runIfSingle` which is used to determine if the quick-pick
should display or execute the item.
- The default value for `runIfSingle` is set to `true`.
- The `plugin-ext` sets the `runIfSingle` to `false` so it always displays
the quick-pick regardless if an single item is present. This behavior is aligned
with previous versions of Theia and VSCode.

#### How to test

1. test that quick-pick with 1 items contributed through the plugin system always displays:
1.1. clone the example https://github.com/i053322/quickpickexample
1.2. `cd quickpickexample && npm i && npm run compile`
1.3. copy the `quickpickexample` under the `plugins` folder
1.4. start the application, run the command `Hello World` (quick-pick should display)

2. verify that quick-pick with 1 item work as usual in the app
2.2. start the app (with a single workspace), run the command `New Terminal` (no quick-pick should be displayed)

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

File: packages/core/src/common/quick-pick-service.ts [hunk 1]
```diff
@@ -77,6 +77,12 @@ export interface QuickPickOptions {
      * The prefill value.
      */
     value?: string;
+
+    /**
+     * Determines if the quick pick with a single item should
+     * execute the item instead of displaying.
```
Comment (akosyakov) [inline packages/core/src/common/quick-pick-service.ts]: Please document default.

**Comment by akosyakov** [comment]
@vince-fugnitto please merge

**Comment by vince-fugnitto** [comment]
Thanks for the review @JPinkney @vinokurig :)
