### PR TITLE
fix #5294: 1. reopen file with another encoding; 2. set default encod…

### LINKED ISSUE #5294: Open file with specific encoding/charset
#### Problem
Using UTF-8 all-the-time is truly a relief. But in reality, it happens that the source files are not encoded in UTF-8 and it looks bad then opened in theia. An example is shown below:

image

>The screenshot comes from a file that is encoded in GB 2312. And the garbled line is supposed to be a comment in Chinese.

#### Solution of Visual Studio Code
There seems to be a solution on vscode where I found this on the right bottom window:

image

After clicking this, two commands pumped up:

image

Executing the first command, I got this:

image

which is really nice because everything works fine after I chose the recommended encoding. I couldn't find anything related on theia, not even a setting. I could have, of course, re-encoded all my files into UTF-8, but the way how vscode does this is just more elegant.

#### In the End
If there happens to be some other way to set the encoding/charset on theia, please tell me. If not, it will be really nice to have the feature on theia in some later version.

### Reproduction Steps
None

**OS and Theia version:**
OS: Linux
Version: 0.6.0

**Diagnostics:** 
None

### PR DESCRIPTION
**Pull request by a1994846931931**
…ing;

Signed-off-by: Cai Xuye <a1994846931931@gmail.com>

- [x] Register [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20161)

#### What it does
1. Add "editor.defaultEncoding" configuration, so that one can specify a proper default encoding for his project;
2. Add encoding item to the status bar, which shows the current encoding used;
3. Pump out a list of encoding for one to choose from when clicking on the encoding status item, or command 'textEditor.change.encoding' is executed. In addition, a guessed encoding will be shown on top of the list if possible.

Added dependencies:
1. "iconv-lite"  of version 0.4.23 is used to encode/decode files.
2. The same version of ""jschardet" (1.6.0) as the one on VSCode is used to guess the encoding of a file based on its content.

#### How to test

**Test File**
>Encoding of each provided file is used as its filename
- [GB2312.txt](https://github.com/theia-ide/theia/files/3491974/GB2312.txt)
- [Shift-JIS.txt](https://github.com/theia-ide/theia/files/3491975/Shift-JIS.txt)
- Or create your own files

**TEST1**
>Make sure that the default encoding works fine.

Preparation:
- Set `files.encoding` to `utf8`
- Prepare some files that are encoded in UTF-8

Process:
1. Open a file that's encoded in UTF-8 and check its content;
2. Create a file, edit it, save it, close it, and reopen it. Just make some modification as you like, and check if the editor is working properly;
3. Also, the encoding item on the status bar should show "UFT-8";
4. Use another test file and repeat.

**TEST2**
>Make sure that the "Reopen with Encoding" action functions well.

Preparation:
- Set `files.encoding` to `utf8`
- Prepare some files that are encoded in something different from UTF-8

Process:
1. Open a test file, for example, GB2312.txt, and check it's content. There should be some weird chars like � in the editor, which shows that the file is not decoded correctly;
2. Run "Editor: Change File Encoding" command or click the block on the status bar that shows "UTF-8", and choose "Reopen with Encoding" action;
3. In the selection list, the first item should be a guessed encoding item. The encoding is guessed from the file's content;
4. If you open files that are provided above, the guessed encoding should be correct (the correct encodings are the same as their filenames). If other files are used, the guessed encoding could be either right or wrong, which is normal. But basically, guessed encoding have a better chance to win if more content is put into the file;
5. Choose the right encoding, either from the guessed item or from your own select, and check if it's reopened correctly;
6. Use another test file and repeat.

**TEST3**
>Make sure that the "Save with Encoding" action functions well.

Preparation:
- Set `files.encoding` to `utf8`
- Prepare some files that are encoded in something different from UTF-8

Process:
1. Follow 1-5 of TEST2, so that the test file is opened in a correct encoding;
2. Run "Editor: Change File Encoding" command or click the block on the status bar that shows "UTF-8", and choose "Save with Encoding" action;
3. Then choose "UTF-8" or any other encoding you want to test, and check if the encoding of the file is changed correctly. You can do the check by reopening it, opening it with other software, or executing `file -i ${FILENAME}` command on linux (though it could be wrong);
4. Also, you can make some modification, and check if "Save with Encoding" action could handle dirty file correctly (apply content changes and encoding change as well)
5. Use another test file and repeat.

**TEST4**
>Make sure that `files.encoding` configuration works.

Preparation:
- Prepare some files that are encoded in something different from UTF-8

Process:
1. Change `files.encoding` (Files -> encoding) to the encoding of your test file;
2. Open the test file, do some editing, and check if it works fine;
3. Use another test file and repeat.

**NOTE**
Currently, I have only tested it on Ubuntu.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by a1994846931931** [comment]
Demos are shown below:

encoding-support-demo-1

encoding-support-demo-2

File: packages/editor/src/browser/editor-command.ts [hunk 1]
```diff
@@ -59,6 +63,11 @@ export namespace EditorCommands {
         category: EDITOR_CATEGORY,
         label: 'Change Language Mode'
     };
+    export const CHANGE_ENCODING: Command = {
+        id: 'textEditor.change.encoding',
+        category: EDITOR_CATEGORY,
+        label: 'Change FILE Encoding'
```
Comment (vince-fugnitto) [inline packages/editor/src/browser/editor-command.ts]: For consistency, perhaps rename this to **`Change File Encoding`**.

File: packages/editor/src/browser/encoding.ts [hunk 2]
```diff
@@ -0,0 +1,257 @@
+/********************************************************************************
+ * Copyright (C) 2018 TypeFox and others.
```
Comment (vince-fugnitto) [inline packages/editor/src/browser/encoding.ts]: I may be mistaken, but I don't believe `TypeFox` would be the correct company in your case.

File: packages/editor/src/browser/encoding.ts [hunk 3]
```diff
@@ -0,0 +1,257 @@
...
+ * This Source Code may also be made available under the following Secondary
+ * Licenses when the conditions for such availability set forth in the Eclipse
+ * Public License v. 2.0 are satisfied: GNU General Public License, version 2
+ * with the GNU Classpath Exception which is available at
+ * https://www.gnu.org/software/classpath/license.html.
+ *
+ * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
+ ********************************************************************************/
+
+// copied from https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textfiles.ts
```
Comment (vince-fugnitto) [inline packages/editor/src/browser/encoding.ts]: @marcdumais-work we will likely need a CQ for this copied code.

File: packages/filesystem/src/node/encoding.ts [hunk 4]
```diff
@@ -0,0 +1,48 @@
+/********************************************************************************
+ * Copyright (C) 2018 TypeFox and others.
```
Comment (vince-fugnitto) [inline packages/filesystem/src/node/encoding.ts]: Same as the comment above.

File: packages/filesystem/src/node/encoding.ts [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+ * This Source Code may also be made available under the following Secondary
+ * Licenses when the conditions for such availability set forth in the Eclipse
+ * Public License v. 2.0 are satisfied: GNU General Public License, version 2
+ * with the GNU Classpath Exception which is available at
+ * https://www.gnu.org/software/classpath/license.html.
+ *
+ * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
+ ********************************************************************************/
+
+// copied from vscode: https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/encoding.ts
```
Comment (vince-fugnitto) [inline packages/filesystem/src/node/encoding.ts]: Another CQ?

File: packages/editor/src/browser/encoding.ts (hunk 3 above)
Comment (marcdumais-work) [reply packages/editor/src/browser/encoding.ts]: Yes, indeed.

File: packages/filesystem/src/node/encoding.ts (hunk 5 above)
Comment (marcdumais-work) [reply packages/filesystem/src/node/encoding.ts]: It's from the same upstream project, so a single CQ covering both files is sufficient. 

@vince-fugnitto a committer has to open the CQ - would you please take care of it? See these [instructions](https://github.com/theia-ide/theia/wiki/Registering-CQs#case-3rd-party-project-code-copiedforked-from-another-project-into-eclipse-theia-maintained-by-us) and let me know if you have questions.

File: packages/editor/src/browser/editor-command.ts (hunk 1 above)
Comment (a1994846931931) [reply packages/editor/src/browser/editor-command.ts]: Yes, you're right.

File: packages/editor/src/browser/encoding.ts (hunk 2 above)
Comment (a1994846931931) [reply packages/editor/src/browser/encoding.ts]: Yes, you are right. I failed to notice. So should I change it to something like "Copyright (c) Microsoft Corporation and others. All rights reserved.", since it's copied from VSCode?

File: packages/editor/src/browser/editor-command.ts (hunk 1 above)
Comment (a1994846931931) [reply packages/editor/src/browser/editor-command.ts]: @vince-fugnitto Hi, I've just fixed the consistency problem.

File: packages/filesystem/src/node/encoding.ts (hunk 4 above)
Comment (a1994846931931) [reply packages/filesystem/src/node/encoding.ts]: @vince-fugnitto I removed the "Copyright" line and replaced it with my name and e-mail, nevertheless not sure whether it's the right way to correct it. Any advice?

File: packages/filesystem/src/node/encoding.ts (hunk 5 above)
Comment (a1994846931931) [reply packages/filesystem/src/node/encoding.ts]: @vince-fugnitto @marcdumais-work Hi! Is there anything that I need to do?

File: packages/filesystem/src/node/encoding.ts (hunk 4 above)
Comment (vince-fugnitto) [reply packages/filesystem/src/node/encoding.ts]: It looks fine to me :)

File: packages/editor/src/browser/encoding.ts (hunk 2 above)
Comment (vince-fugnitto) [reply packages/editor/src/browser/encoding.ts]: I believe you can do something similar to other examples present in the repo:

https://github.com/theia-ide/theia/blob/1f54a26e63e0af5125020d2315886500db4e316c/packages/core/src/common/json-schema.ts#L17-L22

File: packages/filesystem/src/node/encoding.ts (hunk 5 above)
Comment (vince-fugnitto) [reply packages/filesystem/src/node/encoding.ts]: @a1994846931931 I'll have to open a CQ for you so we can continue with the review :)

Comment (vince-fugnitto) [reply packages/filesystem/src/node/encoding.ts]: The CQ was created and is linked in the PR's description.

File: packages/editor/src/browser/encoding.ts (hunk 2 above)
Comment (a1994846931931) [reply packages/editor/src/browser/encoding.ts]: @vince-fugnitto Hey, thank you! I just revised the two files according to the example. Is it correct? And is there any further modification to be done?

Comment (vince-fugnitto) [reply packages/editor/src/browser/encoding.ts]: Yes the copyrights look great

File: packages/editor/src/browser/editor-preferences.ts [hunk 6]
```diff
@@ -474,6 +475,11 @@ export const editorPreferenceSchema: PreferenceSchema = {
             'default': EDITOR_FONT_DEFAULTS.fontWeight,
             'description': 'Controls the editor\'s font weight.'
         },
+        'editor.defaultEncoding': {
```
Comment (svenefftinge) [inline packages/editor/src/browser/editor-preferences.ts]: should be  `files.encoding` to better support vs code settings and VS code extension expectations.

File: packages/monaco/src/browser/monaco-editor-model.ts [hunk 7]
```diff
@@ -58,24 +58,48 @@ export class MonacoEditorModel implements ITextEditorModel, TextEditorDocument {
...
+        }
+        if (this.dirty) {
+            return;
+        }
+        this.preferredEncoding = encoding;
+        this.sync();
+    }
+
+    saveWithEncoding(encoding: string) {
+        // FIXME: need the ability from 'filesystem' to overwrite the encoding of file.
```
Comment (svenefftinge) [inline packages/monaco/src/browser/monaco-editor-model.ts]: could you explain what's missing?

File: packages/editor/src/browser/editor-preferences.ts (hunk 6 above)
Comment (a1994846931931) [reply packages/editor/src/browser/editor-preferences.ts]: I see. It's fixed now.

File: packages/monaco/src/browser/monaco-editor-model.ts (hunk 7 above)
Comment (a1994846931931) [reply packages/monaco/src/browser/monaco-editor-model.ts]: @svenefftinge Actually I figured out how to overwrite the encoding. Now, "Save with Encoding" is available as well. Here are two additional demos:

1. save with encoding (unchanged file)
encoding-support-demo-3

2. save with encoding (dirty file)
encoding-support-demo-4

What do you think?

File: packages/editor/src/browser/editor-preferences.ts (hunk 6 above)
Comment (a1994846931931) [reply packages/editor/src/browser/editor-preferences.ts]: @svenefftinge Hi, Efftinge, could you please take a look at this?

**Comment by akosyakov** [comment]
This PR introduces implicit dependencies between editor and filesystem extensions. It should be refactored to remove coupling.

**Comment by a1994846931931** [comment]
@akosyakov Thanks for your advice! I removed the coupling between editor and filesystem extensions by introducing 'Resource'. Codes are updated. Could you please make a further review?

> This PR introduces implicit dependencies between editor and filesystem extensions. It should be refactored to remove coupling. These extensions cannot depend each other. There should be some sort of intermediate API to make it work.

**Comment by a1994846931931** [comment]
All commits merged into one and rebased to solve the conflict.

File: packages/filesystem/src/node/encoding.ts [hunk 8]
```diff
@@ -0,0 +1,51 @@
...
+/*---------------------------------------------------------------------------------------------
+ *  Copyright (c) Microsoft Corporation. All rights reserved.
+ *  Licensed under the MIT License. See License.txt in the project root for license information.
+ *--------------------------------------------------------------------------------------------*/
+
+const jschardet = require('jschardet');
+const MINIMUM_THRESHOLD = 0.2;
+jschardet.Constants.MINIMUM_THRESHOLD = MINIMUM_THRESHOLD;
+const IGNORE_ENCODINGS = ['ascii', 'utf-8', 'utf-16', 'utf-32'];
+export async function guessEncodingByBuffer(buffer: Buffer): Promise<string | undefined> {
```
Comment (akosyakov) [inline packages/filesystem/src/node/encoding.ts]: please put them in DI context, see https://github.com/theia-ide/theia/wiki/Coding-Guidelines#di-function-export

File: packages/core/src/common/resource.ts [hunk 9]
```diff
@@ -30,12 +30,13 @@ export interface Resource extends Disposable {
...
     saveContentChanges?(changes: TextDocumentContentChangeEvent[], options?: { encoding?: string }): Promise<void>;
     readonly onDidChangeContents?: Event<void>;
+    guessEncoding?(): Promise<string | undefined>
 }
 export namespace Resource {
     export interface SaveContext {
         content: string
         changes?: TextDocumentContentChangeEvent[]
-        options?: { encoding?: string }
+        options?: { encoding?: string, overwriteEncoding?: string }
```
Comment (akosyakov) [inline packages/core/src/common/resource.ts]: Could you elaborate why do we need `overwriteEncoding` and cannot just use `encoding`?

File: packages/editor/src/browser/encoding.ts [hunk 10]
```diff
@@ -0,0 +1,262 @@
...
+ * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
+ ********************************************************************************/
+
+// copied from vscode: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textfiles.ts
+/*---------------------------------------------------------------------------------------------
+ *  Copyright (c) Microsoft Corporation. All rights reserved.
+ *  Licensed under the MIT License. See License.txt in the project root for license information.
+ *--------------------------------------------------------------------------------------------*/
+
+export const SUPPORTED_ENCODINGS: { [encoding: string]: { labelLong: string; labelShort: string; order: number; encodeOnly?: boolean; alias?: string } } = {
```
Comment (akosyakov) [inline packages/editor/src/browser/encoding.ts]: please name a file after the main concept in the file, i.e. `supported-encodings`, see naming conventions: https://github.com/theia-ide/theia/wiki/Coding-Guidelines#names

File: packages/editor/src/browser/editor.ts [hunk 11]
```diff
@@ -148,7 +148,33 @@ export interface EditorMouseEvent {
...
+     */
+    Encode,
+
+    /**
+     * Instructs the encoding support to decode the current input with the provided encoding
+     */
+    Decode
+}
+
+export interface IEncodingSupport {
```
Comment (akosyakov) [inline packages/editor/src/browser/editor.ts]: please don't use I prefixes, see https://github.com/theia-ide/theia/wiki/Coding-Guidelines#interfaces

Comment (akosyakov) [reply packages/editor/src/browser/editor.ts]: Can we inline it into `TextEditor`? I don't see `IEncodingSupport` type is used anywhere.

File: packages/editor/src/browser/editor-command.ts [hunk 12]
```diff
@@ -165,6 +185,76 @@ export class EditorCommandContribution implements CommandContribution {
...
+            placeholder: 'Select Action'
+        });
+        if (!action) {
+            return;
+        }
+        const isReopenWithEncoding = (action === reopenWithEncodingPick.value);
+
+        const configuredEncoding = this.preferencesService.get(EditorCommandContribution.DEFAULT_ENCODING_PREFERENCE);
+
+        const resource = await this.resourceProvider(editor.uri);
```
Comment (akosyakov) [inline packages/editor/src/browser/editor-command.ts]: at what point do you release a resource?

File: packages/editor/src/browser/editor-command.ts [hunk 13]
```diff
@@ -165,6 +185,76 @@ export class EditorCommandContribution implements CommandContribution {
...
+        ];
+        const action = await this.quickPick.show(actionItems, {
+            placeholder: 'Select Action'
+        });
+        if (!action) {
+            return;
+        }
+        const isReopenWithEncoding = (action === reopenWithEncodingPick.value);
+
+        const configuredEncoding = this.preferencesService.get(EditorCommandContribution.DEFAULT_ENCODING_PREFERENCE);
```
Comment (akosyakov) [inline packages/editor/src/browser/editor-command.ts]: you can use editor preferences instead to get a statically typed interface

File: packages/monaco/src/browser/monaco-editor-provider.ts [hunk 14]
```diff
@@ -351,7 +351,7 @@ export class MonacoEditorProvider {
                 uri,
                 readContents: async () => '',
                 dispose: () => { }
-            }, this.m2p, this.p2m);
+            }, this.m2p, this.p2m, { encoding: this.editorPreferences.get('files.encoding') });
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-editor-provider.ts]: inline editors never read anythign from the disk, they are for repls and brekapoints editing

File: packages/core/src/common/resource.ts (hunk 9 above)
Comment (a1994846931931) [reply packages/core/src/common/resource.ts]: So if you want to overwrite the encoding of a file, you will need 1. the original encoding of the file; 2. the new encoding.

To be clearer, when only 'encoding' parameter is presented, it means one wants to read and write a file in that encoding. And when 'overwriteEncoding' is explicitly used, it means that the file will be read in 'encoding', and be written in 'overwriteEncoding'.

File: packages/editor/src/browser/editor.ts (hunk 11 above)
Comment (a1994846931931) [reply packages/editor/src/browser/editor.ts]: The interface 'IEncodingSupport' comes from VSCode. Not sure if we should rename it or inline it into TextEditor. What do you think?

File: packages/editor/src/browser/editor-command.ts (hunk 12 above)
Comment (a1994846931931) [reply packages/editor/src/browser/editor-command.ts]: @akosyakov I see. It should be disposed. I can fix it.

File: packages/editor/src/browser/editor-command.ts (hunk 13 above)
Comment (a1994846931931) [reply packages/editor/src/browser/editor-command.ts]: Fixing soon...

File: packages/monaco/src/browser/monaco-editor-provider.ts (hunk 14 above)
Comment (a1994846931931) [reply packages/monaco/src/browser/monaco-editor-provider.ts]: @akosyakov Sorry, I mistook the concept of 'inline editor'. I thought it has something to do with the editor shown in zone widget. I'm fixing it now. But what is the 'repls', by the way?

**Comment by a1994846931931** [comment]
@akosyakov Hi, I fixed all but the 'IEncodingSupport' and 'overwriteEncoding' (please see comments above). Thanks for your precious advice. And please tell me if further modifications should be made.

File: packages/editor/src/browser/editor.ts (hunk 11 above)
Comment (akosyakov) [reply packages/editor/src/browser/editor.ts]: It is fine to modify copied code. Otherwise we will end up with a lot of code not confirmed to our standards. Just add a link that code originally copied and modified from there.

File: packages/core/src/common/resource.ts (hunk 9 above)
Comment (akosyakov) [reply packages/core/src/common/resource.ts]: Should not we just call once `setContent` with old content and new encoding to overwrite the original content and then use new encoding for consequent `setContent` and `updateContent` methods? then we don't need `overwriteEncoding`?

File: packages/editor/src/browser/editor.ts (hunk 11 above)
Comment (marcdumais-work) [reply packages/editor/src/browser/editor.ts]: Hi @a1994846931931 

> The interface 'IEncodingSupport' comes from VSCode

Please clarify if only the name `IEncodingSupport` was copied from VS Code or also the content of the interface? 

I have not followed closely, but has a CQ been registered to cover the part(s) of this PR that have been copied from somewhere, if applicable?

File: packages/core/src/common/resource.ts (hunk 9 above)
Comment (a1994846931931) [reply packages/core/src/common/resource.ts]: Please look at "node-filesystem.ts/updateContent()". If "contentChanges.length === 0", this method returns directly, and no encoding changes will be applied.

File: packages/editor/src/browser/editor.ts (hunk 11 above)
Comment (a1994846931931) [reply packages/editor/src/browser/editor.ts]: @akosyakov `IEncodingSupport ` is inlined into `TextEditor` now. Could you check it, please?

**Comment by a1994846931931** [comment]
@akosyakov Could you please take a further look at this? The PR has been up here for over a month, so I want to focus on it in the following few days and hopefully meet your requirement soon.

**Comment by akosyakov** [comment]
> Could you please take a further look at this? The PR has been up here for over two months, so I want to focus on it in the following few days and hopefully meet your requirement soon.

We have many PRs and work sorry. PRs addressing VS Code API compatibility issues gets highest priority right now on my list. I will have a look when i have time.

File: packages/filesystem/src/node/node-filesystem.ts [hunk 15]
```diff
@@ -94,15 +97,16 @@ export class FileSystemNode implements FileSystem {
             throw this.createOutOfSyncError(file, stat);
         }
         const encoding = await this.doGetEncoding(options);
-        await fs.writeFile(FileUri.fsPath(_uri), content, { encoding });
```
Comment (akosyakov) [inline packages/filesystem/src/node/node-filesystem.ts]: What is better about `iconv` compare to passing `encoding` to node.js?

File: packages/monaco/src/browser/monaco-editor-model.ts [hunk 16]
```diff
@@ -344,12 +372,16 @@ export class MonacoEditorModel implements ITextEditorModel, TextEditorDocument {
...
         const changes = this.popContentChanges();
-        if (changes.length === 0) {
+        if (changes.length === 0 && overwriteEncoding === undefined) {
             return;
         }
 
         const content = this.model.getValue();
-        await Resource.save(this.resource, { changes, content }, token);
+        if (this.getEncoding() || overwriteEncoding) {
+            await Resource.save(this.resource, { changes, content, options: { encoding: this.getEncoding(), overwriteEncoding } }, token);
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-editor-model.ts]: Why not just this line? `this.getEncoding` is undefined then `encoding` will be undefined, the same about `overwriteEncoding`

File: packages/monaco/src/browser/monaco-editor-model.ts [hunk 17]
```diff
@@ -234,6 +259,9 @@ export class MonacoEditorModel implements ITextEditorModel, TextEditorDocument {
     }
     protected async readContents(): Promise<string | undefined> {
         try {
+            if (this.getEncoding()) {
+                return await this.resource.readContents({ encoding: this.getEncoding() });
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-editor-model.ts]: this line seems to be enough

File: packages/monaco/src/browser/monaco-editor-model.ts [hunk 18]
```diff
@@ -59,24 +59,49 @@ export class MonacoEditorModel implements ITextEditorModel, TextEditorDocument {
...
-        this.resolveModel = resource.readContents().then(content => this.initialize(content));
+        this.resolveModel = resource.readContents(options).then(content => this.initialize(content));
+        this.defaultEncoding = options && options.encoding ? options.encoding : undefined;
     }
 
     dispose(): void {
         this.toDispose.dispose();
     }
 
+    async reopenWithEncoding(encoding: string) {
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-editor-model.ts]: please rebase and apply latest tslint rules, `return types` are mandator according to the coding guidelines

File: packages/filesystem/src/node/node-filesystem.ts [hunk 19]
```diff
@@ -94,15 +97,16 @@ export class FileSystemNode implements FileSystem {
...
+        await fs.writeFile(FileUri.fsPath(_uri), encodedContent);
         const newStat = await this.doGetStat(_uri, 1);
         if (newStat) {
             return newStat;
         }
         throw FileSystemError.FileNotFound(file.uri, 'Error occurred while writing file content.');
     }
 
-    async updateContent(file: FileStat, contentChanges: TextDocumentContentChangeEvent[], options?: { encoding?: string }): Promise<FileStat> {
+    async updateContent(file: FileStat, contentChanges: TextDocumentContentChangeEvent[], options?: { encoding?: string, overwriteEncoding?: string }): Promise<FileStat> {
```
Comment (akosyakov) [inline packages/filesystem/src/node/node-filesystem.ts]: we need to update `filesystem` api then

I'm still not sure about `overwriteEncoding`. Could not we call `setContent` with a new encoding separately? Does it happen that one changes content and encoding at the same time?

File: packages/filesystem/src/node/node-filesystem.ts [hunk 20]
```diff
@@ -77,7 +79,8 @@ export class FileSystemNode implements FileSystem {
             throw FileSystemError.FileIsDirectory(uri, 'Cannot resolve the content.');
         }
         const encoding = await this.doGetEncoding(options);
-        const content = await fs.readFile(FileUri.fsPath(_uri), { encoding });
+        const contentBuffer = await fs.readFile(FileUri.fsPath(_uri));
+        const content = iconv.decode(contentBuffer, encoding);
```
Comment (akosyakov) [inline packages/filesystem/src/node/node-filesystem.ts]: wonder here as well, what `iconv` does what nodejs cannot with passed encoding. It seemed to work before

File: packages/filesystem/src/node/encoding-util.ts [hunk 21]
```diff
@@ -0,0 +1,54 @@
+/********************************************************************************
+ * Written by Xuye Cai <a1994846931931@gmail.com>, June 2019
```
Comment (akosyakov) [inline packages/filesystem/src/node/encoding-util.ts]: use our Copyright template, only update name of an entity and the year, please review new files in the PR

**Comment by akosyakov** [comment]
Could someone testing against similar behaviour in VS Code? We also need to look out for race conditions with saving, i.e. changing encoding and starting typing immediately or with delay and see whether it leads to any troubles.

File: yarn.lock [hunk 22]
```diff
@@ -5510,6 +5510,11 @@ jsbn@~0.1.0:
   version "0.1.1"
   resolved "https://registry.yarnpkg.com/jsbn/-/jsbn-0.1.1.tgz#a5e654c2e5a2deb5f201d96cefbca80c0ef2f513"
 
+jschardet@1.6.0:
```
Comment (akosyakov) [inline yarn.lock]: @theia-ide/ip-help it is not MIT, can we use it?

Comment (marcdumais-work) [reply yarn.lock]: Normally we would not be able to use/distribute such a `LGPL-licensed` dependency, but in this specific instance, we already requested a special permission for `jschardet v1.6.0`, that was granted by the Eclipse Foundation Board. So I think it's ok.  

See this CQ for more details: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20251

File: packages/filesystem/src/node/node-filesystem.ts (hunk 15 above)
Comment (a1994846931931) [reply packages/filesystem/src/node/node-filesystem.ts]: Iconv-lite is better because its list of supported encoding is much longer than node.js. Encodings like GB2312 and Shift-JIS, which are shown in my demos, will not be supported in if we don't use a third-party package. It is a necessary approach to introduce a wide range of supported encodings if we want theia to be used worldwide. In addition to that, iconv-lite is a popular, if not the most popular package concerning encoding support, and is adopted by VSCode as well.

Reference
1. https://stackoverflow.com/questions/14551608/list-of-encodings-that-node-js-supports
2. https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings
3. https://github.com/microsoft/vscode/blob/master/src/vs/base/node/encoding.ts

Comment (a1994846931931) [reply packages/filesystem/src/node/node-filesystem.ts]: > What is better about `iconv` compare to passing `encoding` to node.js?

Iconv-lite is better because its list of supported encoding is much longer than node.js. Encodings like GB2312 and Shift-JIS, which are shown in my demos, will not be supported in if we don't use a third-party package. It is a necessary approach to introduce a wide range of supported encodings if we want theia to be used worldwide. In addition to that, iconv-lite is a popular, if not the most popular package concerning encoding support, and is adopted by VSCode as well.

Reference
1. https://stackoverflow.com/questions/14551608/list-of-encodings-that-node-js-supports
2. https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings
3. https://github.com/microsoft/vscode/blob/master/src/vs/base/node/encoding.ts

File: packages/filesystem/src/node/node-filesystem.ts (hunk 19 above)
Comment (a1994846931931) [reply packages/filesystem/src/node/node-filesystem.ts]: > we need to update filesystem api then
>
> I'm still not sure about `overwriteEncoding`. Could not we call `setContent` with a new encoding separately? Does it happen that one changes content and encoding at the same time?

@akosyakov As I see it, the initial implementation of filesystem did not pay much attention to encodings. The "overwriteEncoding" is introduced merely because I want to solve the problem with as lease modification as possible. If we want to do it in a better, and more elegant way, then the filesystem would probably need a thorough re-design.

For the latter question, I think the answer is "yes". For example, one is editing a file encoded in a strange encoding. Just when he/she is about to save the file, he/she thinks that it's probably better to save it in UTF-8. It may not common, but it does exist and need to be handled.

File: packages/filesystem/src/node/encoding-util.ts (hunk 21 above)
Comment (a1994846931931) [reply packages/filesystem/src/node/encoding-util.ts]: Does the concept of "entity" refer to a natural person as well? I changed them to `Copyright (C) 2019 Xuye Cai and others.` Is it OK?

File: packages/filesystem/src/node/node-filesystem.ts (hunk 20 above)
Comment (a1994846931931) [reply packages/filesystem/src/node/node-filesystem.ts]: see above.

File: packages/monaco/src/browser/monaco-editor-model.ts (hunk 16 above)
Comment (a1994846931931) [reply packages/monaco/src/browser/monaco-editor-model.ts]: True! Fixed now.

File: packages/monaco/src/browser/monaco-editor-model.ts (hunk 17 above)
Comment (a1994846931931) [reply packages/monaco/src/browser/monaco-editor-model.ts]: Fixed

File: packages/monaco/src/browser/monaco-editor-model.ts (hunk 18 above)
Comment (a1994846931931) [reply packages/monaco/src/browser/monaco-editor-model.ts]: Done

File: yarn.lock (hunk 22 above)
Comment (a1994846931931) [reply yarn.lock]: Hey, I wonder how can I view this website: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20251? I tried to log in with my eclipse account, but it shows "The username or password you entered is not valid." Is it that only committer of Eclipse can use ipzilla?

Comment (akosyakov) [reply yarn.lock]: @a1994846931931 Do you have an eclipse account? @theia-ide/ip-help is it true that only official Eclipse Theia Committer can access it?

File: packages/filesystem/src/node/encoding-util.ts (hunk 21 above)
Comment (akosyakov) [reply packages/filesystem/src/node/encoding-util.ts]: yes, it is the standard Eclipse template

File: packages/filesystem/src/node/node-filesystem.ts (hunk 15 above)
Comment (akosyakov) [reply packages/filesystem/src/node/node-filesystem.ts]: Maybe we can add it as a comment to `iconv-lite` import int this file. Thank you for links.

File: packages/filesystem/src/node/node-filesystem.ts (hunk 19 above)
Comment (akosyakov) [reply packages/filesystem/src/node/node-filesystem.ts]: Could you give high-level overview of re-design? I don't want to do it now, just want to understand what you mean and estimate impact. I think we stick with your current proposal for now.

Comment (a1994846931931) [reply packages/filesystem/src/node/node-filesystem.ts]: > Could you give high-level overview of re-design? I don't want to do it now, just want to understand what you mean and estimate impact. I think we stick with your current proposal for now.

@akosyakov I agree that we should stick to this PR. For now, maybe we can just use the "overwriteEncoding" parameter? Because it clearly indicates that we want another encoding for saving files.

File: packages/filesystem/src/common/filesystem.ts [hunk 23]
```diff
@@ -105,6 +105,11 @@ export interface FileSystem extends JsonRpcServer<FileSystemClient> {
      */
     getEncoding(uri: string): Promise<string>;
 
+    /**
+     * Guess encoding of a given file besed on its content.
+     */
+    guessEncoding(uri: string): Promise<string | undefined>;
```
Comment (akosyakov) [inline packages/filesystem/src/common/filesystem.ts]: we should update `updateContent` method here that it accepts a new options `overwriteEncoding` and document what is the difference to `encoding` and how it should be used.

Comment (a1994846931931) [reply packages/filesystem/src/common/filesystem.ts]: > we should update `updateContent` method here that it accepts a new options `overwriteEncoding` and document what is the difference to `encoding` and how it should be used.

@akosyakov `updateContent` method and document updated.

File: yarn.lock (hunk 22 above)
Comment (a1994846931931) [reply yarn.lock]: @akosyakov I have an eclipse account, but I am only a contributor, not a committer.

Comment (marcdumais-work) [reply yarn.lock]: > @a1994846931931 Do you have an eclipse account? @theia-ide/ip-help is it true that only official Eclipse Theia Committer can access it?

Yes, IIRC this is correct. Committers are expected to take care of CQs.

File: packages/filesystem/src/node/encoding-util.ts [hunk 24]
```diff
@@ -0,0 +1,54 @@
...
+ * This Source Code may also be made available under the following Secondary
+ * Licenses when the conditions for such availability set forth in the Eclipse
+ * Public License v. 2.0 are satisfied: GNU General Public License, version 2
+ * with the GNU Classpath Exception which is available at
+ * https://www.gnu.org/software/classpath/license.html.
+ *
+ * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
+ ********************************************************************************/
+
+// copied from vscode: https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/encoding.ts
```
Comment (marcdumais-work) [inline packages/filesystem/src/node/encoding-util.ts]: @vince-fugnitto I received an email notification about probably needing a CQ for this, but I can't find the comment here. What was the conclusion?

Comment (vince-fugnitto) [reply packages/filesystem/src/node/encoding-util.ts]: I believe the initial CQ for the PR did not cover these files (and potentially others in the PR).
I guess we should change our ways of working a little to only register CQs when a PR is completed and ready to be merged as not to create intermediate CQs.

File: packages/filesystem/src/node/node-filesystem.ts (hunk 19 above)
Comment (akosyakov) [reply packages/filesystem/src/node/node-filesystem.ts]: ok, let's go with it

I just wanted to understand what you mean under `the filesystem would probably need a thorough re-design.`. That something needs thorough re-design is quite a strong statement. So far we tried to align filesystem API with apis from node.js and VS Code, that devs feel familiar working with it. That's why I'm reluctant to accept `overwriteEncoding`, it is an unusual api. I wonder why we would need to step aside from standard apis and re-design it.

File: packages/filesystem/src/node/encoding-util.ts (hunk 24 above)
Comment (akosyakov) [reply packages/filesystem/src/node/encoding-util.ts]: @vince-fugnitto since @marcdumais-work is away could you take care of ip issues for this PR?

Also @vince-fugnitto @tolusha would it be alright if i add you to ip-team as well? I think you are familiar enough with the process.

Comment (tolusha) [reply packages/filesystem/src/node/encoding-util.ts]: @akosyakov I don't mind.

**Comment by a1994846931931** [comment]
> @a1994846931931 Could you define tests for this PR? We will test that changes don't break anything without changing encoding and then use your tests to test encoding/decoding plus check whether expectations of tests are aligned with behaviour of VS Code. If everything is fine we land it.
> 
> Also just FYI: https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#checklist-build-and-test

@akosyakov I have rewritten the PR message, based on the new PR template. So `How to test` is updated, too. One problem, however, is that I have only tested it on Ubuntu. Maybe someone could have it tested on other platforms, following my tests list?

**Comment by akosyakov** [comment]
@westbury @kittaakos If you can try tests from `How to test` section on windows it would help. I will check them on linux.

@westbury @kittaakos maybe we can have os-windows team? 🤔

File: packages/filesystem/src/node/encoding-util.ts (hunk 24 above)
Comment (vince-fugnitto) [reply packages/filesystem/src/node/encoding-util.ts]: @akosyakov I'm fine as well being part of the ip-team.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto please can you clarify your suspicious about CQs? We cannot merge without it.

I think it's alright, the original CQ covered both the [`encoding.ts`](https://github.com/microsoft/vscode/blob/master/src/vs/base/node/encoding.ts) and [`textfile.ts`](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textfiles.ts) files.
