### PR TITLE
Clarify error when language server fails to initialize

### LINKED ISSUE #982: "Connection got disposed" when a language server is not present/installed
Using master as of today,
I don't have "pyls" or clangd installed. If I open either *.py of *.cpp files, I get *two* messages "Connection got disposed".

screen shot 2017-12-13 at 16 15 33

### PR DESCRIPTION
**Pull request by MarkZ3**
When a language server fails to launch, an error message "Connection got
disposed" is shown to the user. This could be confusing because it could mean
that the connection to the backend was lost. This commit changes the message to
"Failed to start language server $NAME".

Further improvements would be to display full instructions to install the server
by adding actions to the notification and also possibly an action to never show
the message again. This could be addressed in separate commits.

Fixes #982

Signed-off-by: Marc-Andre Laperle <marc-andre.laperle@ericsson.com>

### CODE REVIEW

File: packages/languages/src/browser/language-client-contribution.ts [hunk 1]
```diff
@@ -80,6 +82,10 @@ export abstract class BaseLanguageClientContribution implements LanguageClientCo
 
     protected createLanguageClient(): ILanguageClient {
         const clientOptions = this.createOptions();
+        clientOptions.initializationFailedHandler = () => {
```
Comment (akosyakov) [inline packages/languages/src/browser/language-client-contribution.ts]: How often does it happen? For example, if the connection is lost `LanguageClient` tries to reconnect 5 times will a user see 5 notifications?

Comment (MarkZ3) [reply packages/languages/src/browser/language-client-contribution.ts]: It happens 2-5 times from what I saw. Before this patch, it displays "Connection got
disposed" 2-5 times. With the patch, it displays "Failed to start language server $NAME" which is at least clearer.

**Comment by MarkZ3** [comment]
Moved the code to createOptions where it makes more sense.

File: packages/languages/src/browser/language-client-contribution.ts [hunk 2]
```diff
@@ -87,7 +89,11 @@ export abstract class BaseLanguageClientContribution implements LanguageClientCo
         const fileEvents = this.createFileEvents();
         return {
             documentSelector: this.documentSelector,
-            synchronize: { fileEvents }
+            synchronize: { fileEvents },
+            initializationFailedHandler: () => {
+                this.messageService.error("Failed to start language server '" + this.name + "'.");
+                return false;
```
Comment (akosyakov) [inline packages/languages/src/browser/language-client-contribution.ts]: Does it mean don’t try to restart?

Comment (MarkZ3) [reply packages/languages/src/browser/language-client-contribution.ts]: It still tries to restart. From what I read in the code, the boolean can be set to true in order to call initialize again, perhaps with different options in case of failure. But if set to false, it still gets restarted at a higher level by BaseLanguageClient.handleConnectionClosed

Comment (akosyakov) [reply packages/languages/src/browser/language-client-contribution.ts]: Ok, could you extract the function to create `initializationFailedHandler` that clients can change the default behavior, please?
