### PR TITLE
[menus] Restore the focus for context menu and main menu bar (fixes #481)

### LINKED ISSUE #481: [COPY/PASTE] does not work in context menus
If one uses the copy command in a context menu it does not work. 
After right click the focus on the clicked element gets lost.

### PR DESCRIPTION
**Pull request by svenefftinge**
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>

### CODE REVIEW

File: packages/core/src/browser/menu/browser-menu-plugin.ts [hunk 1]
```diff
@@ -96,6 +96,7 @@ class DynamicMenuBarWidget extends MenuBarWidget {
             super['_openChildMenu']();
         };
     }
+
```
Comment (hexa00) [inline packages/core/src/browser/menu/browser-menu-plugin.ts]: empty line

Comment (svenefftinge) [reply packages/core/src/browser/menu/browser-menu-plugin.ts]: Do we have agreed on such formatting? I do like it better with an empty line (not that I really want to get into a discussion about it :-))

Comment (hexa00) [reply packages/core/src/browser/menu/browser-menu-plugin.ts]: We have not discussed it I assumed it from the rest of the code and I also prefer that...
It looked like a left over to me since no other code was touched in that function.

Comment (svenefftinge) [reply packages/core/src/browser/menu/browser-menu-plugin.ts]: It actually was a formatting change, because I like that empty line :)

Comment (svenefftinge) [reply packages/core/src/browser/menu/browser-menu-plugin.ts]: We can maybe discuss how to go about such things in today's meeting.
