### PR TITLE
fix theia-ide#5114. Support multiple files to drag and drop.

### LINKED ISSUE #5114: Unable to open multiple files in editor by dragging and dropping them to tab bar
Currently, it is not possible to drag multiple files from the Explorer panel to the Tab Bar to open them all. Dragging and dropping multiple files to the Tab bar would only open **one file that is clicked on**.

I am wondering if this feature can be implemented as it is done in other IDEs, such as VS Code?

### PR DESCRIPTION
**Pull request by BroKun**
fix #5114 

- [filesystem] Drag and drop event transfer node list instead of single node. 
- [filesystem] Support to move multiple files by dnd.
- [navigator] Support to open multiple files by dnd.
- ~~Rename `setTreeNodeAsData` to `setTreeNodesAsData` ,`getTreeNodeFromData` to `getTreeNodesFromData`~~
- [filesystem] Add getSelectedTreeNodesFromData api in file-tree-widget

Signed-off-by: Brokun <brokun0128@gmail.com>

### CODE REVIEW

**Comment by BroKun** [comment]
#4023 has alse been fixed.

File: packages/filesystem/src/browser/file-tree/file-tree-widget.tsx [hunk 1]
```diff
@@ -152,14 +162,16 @@ export class FileTreeWidget extends TreeWidget {
...
-        data.setData('tree-node', node.id);
+    protected setTreeNodesAsData(data: DataTransfer, nodes: TreeNode[]): void {
+        data.setData('tree-nodes', JSON.stringify(nodes.map(node => node.id)));
     }
 
-    protected getTreeNodeFromData(data: DataTransfer): TreeNode | undefined {
-        const id = data.getData('tree-node');
-        return this.model.getNode(id);
+    protected getTreeNodesFromData(data: DataTransfer) {
+        const resources = data.getData('tree-nodes');
```
Comment (akosyakov) [inline packages/filesystem/src/browser/file-tree/file-tree-widget.tsx]: please keep `tree-node` as well for backward compatibility

File: packages/filesystem/src/browser/file-tree/file-tree-widget.tsx [hunk 2]
```diff
@@ -152,14 +162,16 @@ export class FileTreeWidget extends TreeWidget {
             }
         }
     }
-
-    protected setTreeNodeAsData(data: DataTransfer, node: TreeNode): void {
-        data.setData('tree-node', node.id);
+    protected setTreeNodesAsData(data: DataTransfer, nodes: TreeNode[]): void {
```
Comment (akosyakov) [inline packages/filesystem/src/browser/file-tree/file-tree-widget.tsx]: let's introduce new methods to set/get `nodes` instead of `node` for backward compatibility

**Comment by akosyakov** [comment]
@BroKun that's awesome! but please do it in the backward compatible mode, i know there are clients and subclasses relying on presence of `tree-node` and changed APIs

File: packages/filesystem/src/browser/file-tree/file-tree-widget.tsx [hunk 3]
```diff
@@ -152,14 +162,20 @@ export class FileTreeWidget extends TreeWidget {
...
     }
-
-    protected setTreeNodeAsData(data: DataTransfer, node: TreeNode): void {
-        data.setData('tree-node', node.id);
+    protected setTreeNodeAsData(data: DataTransfer, sourceNode: TreeNode, relatedNodes: TreeNode[]): void {
+        data.setData('tree-node', sourceNode.id);
+        data.setData('selected-tree-nodes', JSON.stringify(relatedNodes.map(node => node.id)));
     }
-
-    protected getTreeNodeFromData(data: DataTransfer): TreeNode | undefined {
```
Comment (akosyakov) [inline packages/filesystem/src/browser/file-tree/file-tree-widget.tsx]: please always declare return types in order to avoid surprising breaking changes by changing method body

File: packages/navigator/src/browser/navigator-widget.tsx [hunk 4]
```diff
@@ -101,11 +101,8 @@ export class FileNavigatorWidget extends FileTreeWidget {
     protected enableDndOnMainPanel(): void {
         const mainPanelNode = this.shell.mainPanel.node;
         this.addEventListener(mainPanelNode, 'drop', async ({ dataTransfer }) => {
-            const treeNode = dataTransfer && this.getTreeNodeFromData(dataTransfer) || undefined;
-
-            if (FileNode.is(treeNode)) {
-                this.commandService.executeCommand(CommonCommands.OPEN.id, treeNode.uri);
-            }
+            const treeNodes = dataTransfer && this.getSelectedTreeNodesFromData(dataTransfer) || [];
```
Comment (akosyakov) [inline packages/navigator/src/browser/navigator-widget.tsx]: `|| []`? looking at implementation of `getSelectedTreeNodesFromData` it cannot return `undefined`, please declare a return type explicitly

Comment (BroKun) [reply packages/navigator/src/browser/navigator-widget.tsx]: This is for the case when dataTransfer value is null.

File: packages/filesystem/src/browser/file-tree/file-tree-widget.tsx [hunk 5]
```diff
@@ -152,14 +162,20 @@ export class FileTreeWidget extends TreeWidget {
             }
         }
     }
-
-    protected setTreeNodeAsData(data: DataTransfer, node: TreeNode): void {
-        data.setData('tree-node', node.id);
+    protected setTreeNodeAsData(data: DataTransfer, sourceNode: TreeNode, relatedNodes: TreeNode[]): void {
```
Comment (akosyakov) [inline packages/filesystem/src/browser/file-tree/file-tree-widget.tsx]: the last argument should be optional, otherwise it is a breaking change for subclasses calling this method without 3rd arg

File: packages/filesystem/src/browser/file-tree/file-tree-widget.tsx [hunk 6]
```diff
@@ -152,14 +162,20 @@ export class FileTreeWidget extends TreeWidget {
...
+        data.setData('tree-node', sourceNode.id);
+        data.setData('selected-tree-nodes', JSON.stringify(relatedNodes.map(node => node.id)));
     }
-
     protected getTreeNodeFromData(data: DataTransfer): TreeNode | undefined {
         const id = data.getData('tree-node');
         return this.model.getNode(id);
     }
-
+    protected getSelectedTreeNodesFromData(data: DataTransfer): (TreeNode | undefined)[] {
```
Comment (akosyakov) [inline packages/filesystem/src/browser/file-tree/file-tree-widget.tsx]: Could we filter `undefined` for clients?

File: packages/filesystem/src/browser/file-tree/file-tree-widget.tsx (hunk 5 above)
Comment (akosyakov) [reply packages/filesystem/src/browser/file-tree/file-tree-widget.tsx]: or we add a new method instead, i.e. `setSelectedTreeNodesAsData`, which calls to `setTreeNodeAsData` in addition to setting `selected-tree-nodes`, and leave original method without modifications

**Comment by akosyakov** [comment]
@BroKun please fixup all commits after addressing comments that we can merge it

File: packages/filesystem/src/browser/file-tree/file-tree-widget.tsx (hunk 5 above)
Comment (BroKun) [reply packages/filesystem/src/browser/file-tree/file-tree-widget.tsx]: I think the second implementation is a bit better, but I think the original method should be marked as deprecated. With reference to vscode, their drag event data is always an array, not passing the original element that generated the event. So I don't think the node array is an optional parameter and should be used as the main parameter.

**Comment by BroKun** [comment]
CI test failed, it seems to be due to network problems

File: packages/filesystem/src/browser/file-tree/file-tree-widget.tsx (hunk 5 above)
Comment (akosyakov) [reply packages/filesystem/src/browser/file-tree/file-tree-widget.tsx]: marking deprecated and adding depreciation, i.e since when and what to use instead, sounds fine

**Comment by akosyakov** [comment]
When drag and drop animation shows only one file still though, it would be nice to improve animation as well, i.e. align it with VS code, they show number of files. @BroKun Could you open a follow-up issue?

**Comment by BroKun** [comment]
I am glad to solve these problems, thank you for your coding suggestions.
