### PR TITLE
[electron] electron-main.js fixes

### LINKED ISSUE #3531: [electron][generator] Check the main window before loading the URL
It's a minor issue. We have to add a guard to the generated `electron-main` module.

The reproducibility heavily depends on timing; I ran into this accidentally. The window was closed by the time we started to load the URL.

```
prprpr:theia akos.kitta$ yarn --cwd ./examples/electron/ start
yarn run v1.12.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 24720]
^C
prprpr:theia akos.kitta$ Server worker has been disconnected. [ID: 1 | PID: 24720]
Server worker failed to start within 5000 milliseconds.
Pass a greater value as '--startup-timeout' option to increase the timeout or a negative to disable.
root INFO Server worker has been stopped. [ID: 1 | PID: 24720]
root INFO Theia app listening on http://localhost:59088.
root ERROR Error: Object has been destroyed
    at BrowserWindow.loadURL (/Users/akos.kitta/Desktop/theia/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/browser-window.js:167:16)
    at loadMainWindow (/Users/akos.kitta/Desktop/theia/examples/electron/src-gen/frontend/electron-main.js:63:24)
    at require.then.address (/Users/akos.kitta/Desktop/theia/examples/electron/src-gen/frontend/electron-main.js:71:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
root INFO Started watching: /Users/akos.kitta/Desktop/theia/examples/electron/package.json

prprpr:theia akos.kitta$
```

See: [`BrowserWindow.isDestroyed()`](https://electronjs.org/docs/api/browser-window#winisdestroyed)

### PR DESCRIPTION
**Pull request by marechal-p**
- Do not open links with `window.open` in an Electron Browser (security hazard).
- Fix #3531

Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
> * Do not open links with `window.open` in an Electron Browser (security hazard).

Please tell me about this before I start the review.

**Comment by marechal-p** [comment]
Well, in a markdown file, [`window.open` is used to open links](https://github.com/theia-ide/theia/blob/ecc9c1b04f6b11937a81f98e6bbd751445f59729/packages/core/src/browser/http-open-handler.ts#L31).

So if you have a link to a third party website, and that website would detect the user agent and see an Electron client, who knows what kind of JS that server could send? Node integration is on by default in the BrowserWindows that got opened, so that left a lot of room for security hazards.

On the other hand, why would we open a http link in an electron window? Say http://www.google.ca/, why would we open that in a BrowserWindow?

Hence this patch that intercepts the calls to `window.open` and open the URL in a proper web browser that doesn't expose all the risks that Electron does.

Also we already have a `WindowService` that handles the opening of new BrowserWindows.

**Comment by kittaakos** [comment]
> Well, in a markdown file, [`window.open` is used to open links](https://github.com/theia-ide/theia/blob/ecc9c1b04f6b11937a81f98e6bbd751445f59729/packages/core/src/browser/http-open-handler.ts#L31).

We should use the [`WindowService`](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/window/window-service.ts), right?

What I do not understand is why did you delete the `windows` from the `electron-main` and got rid of the logic to support multiple windows?

**Comment by marechal-p** [comment]
Multiple windows are still supported, I just left the tracking to Electron, not to our `electron-main.js`.

**Comment by marechal-p** [comment]
> We should use the WindowService, right?

I could add a `openExternal` member to the `WindowService` API, but I would still handle the case when someone tries to use `window.open` to open in an external web browser, as a fail-safe default.

WDYT? Should I add this API?

**Comment by marechal-p** [comment]
@kittaakos I added a commit that provides this new API.
TBH I'm not very fond of it...

Thoughts?

(cc @akosyakov?)

**Comment by kittaakos** [comment]
> @kittaakos I added a commit that provides this new API.
> TBH I'm not very fond of it...

Why? What would you suggest instead? We can have a `open(url: string, external?: boolean)` API too. What is your concern?

**Comment by kittaakos** [comment]
Please fix the compiler error:
```
[compile] src/browser/window/test/mock-window-service.ts(20,14): error TS2420: Class 'MockWindowService' incorrectly implements interface 'WindowService'.
[compile]   Property 'openExternal' is missing in type 'MockWindowService'.
[compile] theiaext compile exited with code 2
```
Happened with dfbc0f7b. Thanks!

**Comment by marechal-p** [comment]
> What is your concern? (New WindowService API)

My only concern is that now we will have to inject the service instead of using an already existing global function, but so far so good. I will make the changes as suggested :)

**Comment by marechal-p** [comment]
@kittaakos added the option to `openNewWindow`, everything should be good :)

**Comment by kittaakos** [comment]
Can you please check the test failure?

```
1) "before all" hook
  0 passing (15ms)
  1 failing
  1)  "before all" hook:
     Error: No matching bindings found for serviceIdentifier: Symbol(WindowService)
      at _validateActiveBindingCount (/home/travis/build/theia-ide/theia/node_modules/inversify/lib/planning/planner.js:62:23)
      at _getActiveBindings (/home/travis/build/theia-ide/theia/node_modules/inversify/lib/planning/planner.js:48:5)
      at _createSubRequests (/home/travis/build/theia-ide/theia/node_modules/inversify/lib/planning/planner.js:91:26)
      at /home/travis/build/theia-ide/theia/node_modules/inversify/lib/planning/planner.js:115:17
      at Array.forEach (<anonymous>)
      at /home/travis/build/theia-ide/theia/node_modules/inversify/lib/planning/planner.js:114:26
      at Array.forEach (<anonymous>)
      at _createSubRequests (/home/travis/build/theia-ide/theia/node_modules/inversify/lib/planning/planner.js:94:20)
      at Object.plan (/home/travis/build/theia-ide/theia/node_modules/inversify/lib/planning/planner.js:136:9)
      at /home/travis/build/theia-ide/theia/node_modules/inversify/lib/container/container.js:317:37
      at Container._get (/home/travis/build/theia-ide/theia/node_modules/inversify/lib/container/container.js:310:44)
      at Container.get (/home/travis/build/theia-ide/theia/node_modules/inversify/lib/container/container.js:230:21)
      at Context.<anonymous> (src/browser/storage-service.spec.ts:44:36)
      at <anonymous>
```

File: dev-packages/application-manager/src/generator/frontend-generator.ts [hunk 1]
```diff
@@ -111,9 +111,9 @@ const electron = require('electron');
 const { join, resolve } = require('path');
 const { isMaster } = require('cluster');
 const { fork } = require('child_process');
-const { app, BrowserWindow, ipcMain, Menu } = electron;
+const { app, shell, BrowserWindow, ipcMain, Menu } = electron;
 
-const applicationName = \`${this.pck.props.frontend.config.applicationName}\`;
+const applicationName = '${this.pck.props.frontend.config.applicationName}';
```
Comment (kittaakos) [inline dev-packages/application-manager/src/generator/frontend-generator.ts]: Why? Please do not include irrelevant changes.

If I use the `What's wrong with this application name` application name, I will have the following generated code:
```js
const applicationName = 'What's wrong with this application name';
```

It has compiler errors.

Comment (marechal-p) [reply dev-packages/application-manager/src/generator/frontend-generator.ts]: Well, if I want to call the application `${fork}` with the old string delimiters there would also be the an issue. Thanks for pointing one more corner case.

This only mean that we should escape whatever is passed, as safety.

**Comment by marechal-p** [comment]
Reverted the string delimitation change, but it is currently flaky when using either `"` (double quotes) or template parts such as `${process.cwd()}` in the application name.

**Comment by marechal-p** [comment]
@kittaakos

**Comment by kittaakos** [comment]
It used to quit the application when I closed the last window on OS X, and now, it does not. Is this the desired behavior?

**Comment by marechal-p** [comment]
> It used to quit the application when I closed the last window on OS X, and now, it does not. Is this the desired behavior?

It is to better match the following lines:
https://github.com/theia-ide/theia/blob/369dcff9d6d13d6a616b526eb021f6a97dd9e763/dev-packages/application-manager/src/generator/frontend-generator.ts#L153-L157

From what I understand, OSX application usually keep running even without windows.

Currently I don't think we handle opening new Electron windows from the OSX dock panel, but that's something that could(should?) be added later.

Also, under Ubuntu, `app.quit()` is correctly triggered, but for some reason the process doesn't terminate properly, I suspect it being due to the subprocesses keeping the eventloop alive? Not sure...

> Is this the desired behavior?

I think that this question is still opened? I can add something that would forcibly close the application like there was before, although I am not fond of it.

**Comment by marechal-p** [comment]
@kittaakos sorry to bother you again, but I wanted to know if you had any other concerns?

I just made so that the app quits once no more windows exist, no matter what OS it is running on.

**Comment by kittaakos** [comment]
I am trying it now...

File: packages/core/src/browser/window/window-service.ts [hunk 2]
```diff
@@ -16,6 +16,10 @@
 
 import { injectable } from 'inversify';
 
+export interface NewWindowOptions {
+    external?: boolean;
```
Comment (kittaakos) [inline packages/core/src/browser/window/window-service.ts]: Didn't you want to add the `readonly` keyword?

**Comment by marechal-p** [comment]
Ah thanks for the approval, finally got time to respond, thank you!
