### PR TITLE
GH-5385: Do not spawn electron for the TS LS.

### LINKED ISSUE #5385: [electron] Multiple electron menus/appIcons when starting the electron example
### Description
 

I can see multiple application icons on my Dock on macOS when I start the electron example.

Screen Shot 2019-06-06 at 21 53 53

Each has a different application menu.
 1. The visible:
Screen Shot 2019-06-06 at 21 56 54

 2. The "hidden?":
Screen Shot 2019-06-06 at 21 56 47

### Reproduction Steps
`yarn --cwd ./examples/electron/ start`

**OS and Theia version:**
macOS

0b1b8532f

It is just a wild guess but #5360 could be related. We start something else we did not do before. Smells like a regression.

### PR DESCRIPTION
**Pull request by kittaakos**
When spawning/forking a new node process with Node.js bundled into
electron, we have to explicitly disable the electron part.

Closes #5385.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@kittaakos Thanks for doing this - @vince-fugnitto and myself are having a look.

File: dev-packages/application-package/src/environment.ts [hunk 1]
```diff
@@ -49,6 +49,28 @@ class ElectronEnv {
...
+     * If called from the backend and the `env` argument is not defined, it falls back to `process.env` such as Node.js behaves
+     * with the [`SpawnOptions`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options).
+     * If `env` is defined, it will be shallow-copied.
+     *
+     * Calling this function from the frontend does not make any sense, hence throw an error.
+     */
+    // tslint:disable-next-line:no-any
+    runAsNodeEnv(env?: any): any & { ELECTRON_RUN_AS_NODE: 1 } {
+        if (typeof process === 'undefined') {
+            throw new Error('Calling this function from the frontend does not make sense. Does it?');
```
Comment (vince-fugnitto) [inline dev-packages/application-package/src/environment.ts]: [minor] it's unlikely to happen, but should this error message be improved to display something more meaningful?

Comment (kittaakos) [reply dev-packages/application-package/src/environment.ts]: 👍 Sure, let's improve it. Do you have anything specific in mind?

Comment (vince-fugnitto) [reply dev-packages/application-package/src/environment.ts]: @kittaakos I don't have anything specific in mind, it just felt odd to me that we said it doesn't make sense to call the method from the frontend, but then said 'does it?' like we weren't sure. :see_no_evil: 

A generic error message stating the process is `undefined` may be sufficient.

**Comment by marcdumais-work** [comment]
I tested by building this PR locally, publishing it to a local [verdaccio](https://github.com/verdaccio/verdaccio) NPM registry and using that to build the `theia-apps/theia-electron` application as a Debian package. 

I then tried to start the installed Electron app, normally (with node from nvm in my path) and also momentarily removing nvm from my environment. In both cases the TypeScript and JSON LS were able to start and work normally. 

I was unable to reproduce #5385 on master on my Ubuntu machine, so I can't confirm for certain that it's fixed. @vince-fugnitto will try on the Mac to confirm that the example Electron app no longer has this issue.

**Comment by kittaakos** [comment]
Thank you all for the review!
