### PR TITLE
Fix terminal startup

### LINKED ISSUE #449: Remove sourcing the .profile when starting a term
When starting a terminal we always do:

```
term.write(`cd ${uri.path} && `);
term.write("source ~/.profile\n");
```

This makes no sense on linux and even less on windows. So we need to remove it for those for sure.

And it seems like an ugly hack for macOS, it's even worse that the user sees that displayed when starting a term.

@kittaakos  @akosyakov do you object to remove that entirely ? 
I remember discussing that with @svenefftinge for macOS but forgot what the issue was exactly on osx... but it seems like it should be fixed another way.

### PR DESCRIPTION
**Pull request by hexa00**
This fixes #449 

And also fixes some minor issues along the way.

### CODE REVIEW

File: packages/core/src/common/path.ts [hunk 1]
```diff
@@ -49,14 +46,12 @@ export class Path {
...
         this.base = lastIndex === -1 ? raw : raw.substr(lastIndex + 1);
         this.isRoot = this.isAbsolute && firstIndex === lastIndex && (!this.base || Path.isDrive(this.base));
-        this.root = this.computeRoot();
-
         const extIndex = this.base.lastIndexOf('.');
         this.name = extIndex === -1 ? this.base : this.base.substr(0, extIndex);
         this.ext = extIndex === -1 ? '' : this.base.substr(extIndex);
     }
 
-    protected computeRoot(): Path | undefined {
```
Comment (akosyakov) [inline packages/core/src/common/path.ts]: @hexa00 Could you point out the code where it breaks.

Comment (hexa00) [reply packages/core/src/common/path.ts]: I used to have a console.log(`${JSON.stringify(path)}`) and that broke.... I since removed it but I still think it's a good idea to have that just as a accessor

Comment (akosyakov) [reply packages/core/src/common/path.ts]: you can do `console.log(path)`, `root` accessor will create all parents on each call

Comment (hexa00) [reply packages/core/src/common/path.ts]: so you mean with console.log(path) it will still blow up since it will call the accessors?
It's not the case with stringify at least

**Comment by hexa00** [comment]
@svenefftinge can you test if you still have an issue with .profile?

**Comment by svenefftinge** [comment]
It somehow doesn't source my `.profile`. Vscode terminal does

**Comment by svenefftinge** [comment]
I added a symlink, and now it works `ln -s .profile .bashrc`.

**Comment by hexa00** [comment]
OK I opened #514 about it
