### PR TITLE
fix bug: CompletionResultDto does not have a property named _id

### LINKED ISSUE #6012: CompletionAdapter's cache cannot be cleaned up
### Description
release_id

### Reproduction Steps
1、Block java and javadebug，eg: Delete dependency of java and javadebug at examples/brower/package.json
2、install vscode plugins：
redhat.java-0.47.0.vsix  -- https://marketplace.visualstudio.com/items?itemName=redhat.java
vscjava.vscode-java-debug-0.20.0.vsix -- https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug
vscjava.vscode-maven-0.18.1.vsix -- https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven
3、Increase print information in function of releaseCompletionItems at packages/plugin-ext/src/plugin/languages/completion.ts,eg:
捕获

**OS and Theia version:**
1、Ubuntu:18.04
2、theia:0.9.0

### PR DESCRIPTION
**Pull request by xieyuanhuata**
Signed-off-by: xieyuanhu <xieyuanhuata@163.com>

#### What it does
fix #6012 

#### How to test
show log into debug console
##before:
release_id
##after
update1
update2

#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/main/browser/languages-main.ts [hunk 1]
```diff
@@ -113,7 +113,7 @@ export class LanguagesMainImpl implements LanguagesMain {
                         suggestions: result.completions,
                         incomplete: result.incomplete,
                         // tslint:disable-next-line:no-any
-                        dispose: () => this.proxy.$releaseCompletionItems(handle, (<any>result)._id)
+                        dispose: () => this.proxy.$releaseCompletionItems(handle, (<any>result).id)
```
Comment (tsmaeder) [inline packages/plugin-ext/src/main/browser/languages-main.ts]: Please get rid of the cast to <any>. If we're sure that result.id is set, we can write "result.id!". Generally, I don't really see why the id field is optional, but that goes beyond the scope of this PR.

Comment (kpge) [reply packages/plugin-ext/src/main/browser/languages-main.ts]: @evidolob can you explain why the id field is optional in `CompletionResultDto`
https://github.com/theia-ide/theia/blob/44a2ec7b3a8b31ebe8832c8ff00f3987910066fa/packages/plugin-ext/src/common/plugin-api-rpc-model.ts#L185-L196

Comment (akosyakov) [reply packages/plugin-ext/src/main/browser/languages-main.ts]: @kpge there are different classes extending `IdObject` and for some it can be optional. Since it is never a case `CompletionResultDto` then you can define more restrict type in the subclass, i.e. redeclare `id: string`.

**Comment by akosyakov** [comment]
> show log into debug console

We should write down how to profile and inspect things. Using logging does not guarantee that there is no memory leak, i.e. that an object is not hold somewhere else.

**Comment by akosyakov** [comment]
Checked that a single completion is properly garbage collected after closing the suggest widget:
Screen Shot 2019-09-03 at 10 22 13

In order to reproduce with ts vscode extension:
  - uninstall native typescript extension in example package.json
  - build the example app
  - unzip [ts_plugins.zip](https://github.com/theia-ide/theia/files/3513239/ts_plugins.zip) into plugins folder
  - start the example app:  `yarn start ../.. --hosted-plugin-inspect`
  - open the app in chrome
  - connect to plugin host process with Chrome devtools, take a memory snapshot with opened suggest widget and then with closed, in both cases collect the garbage before
  - find a completion item object in the first snapshot
  - make a diff between 2 snapshots and check that an object for class and instance id is garbage collected

**Comment by akosyakov** [comment]
(off-topic) Strange thing that ts vscode extension should register only 3 completion providers by looking at the code, but during profiling 6 of them. But it is another issue.
