### PR TITLE
prefer listed plugins to dependencies

### LINKED ISSUE #6036: plugin system should prefer listed plugins instead of dependencies
In order to reproduce:
- put a flutter and dart VS Code extensions as vsix files to plugins folder
- start Theia
- you will see that instead of deploying Dart from vsix file the plugin system download dart extension from the marketplace

cc @JPinkney @theia-ide/plugin-system

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

It's a bug fix for https://github.com/theia-ide/theia/pull/5379. We should either test and merge this PR for 0.10.0, or revert #5379. Right now it breaks all products which consumes from local files.

- fix #6036: otherwise the wrong version gets installed from a marketplace instead of from local vsix file for example

#### How to test

- put a flutter and dart VS Code extensions as vsix files to plugins folder
- start Theia
- make sure that dart extension is loaded from vsix file, not downloaded from the marketplace
  - you can do it by looking at backend logs
  - in order to be sure you can also build dart extension from sources that unzipping it not involved:
    - check out https://github.com/Dart-Code/Dart-Code under `plugins` instead of vsix
    - `npm install`
    - enable skipLibCheck in tsconfig and do `npm run watch` to compile

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/main/node/plugin-deployer-impl.ts [hunk 1]
```diff
@@ -108,47 +108,39 @@ export class PluginDeployerImpl implements PluginDeployer {
...
-            const pluginDeployerEntries = await this.resolvePlugin(currentPlugin);
+            const pluginDeployerEntries = await this.resolvePlugin(current);
 
             // now that we have plugins check if we have File Handler for them
             await this.applyFileHandlers(pluginDeployerEntries);
 
             // ok now ask for directory handlers
             await this.applyDirectoryFileHandlers(pluginDeployerEntries);
 
-            // add current plugin deployer entries first because dependencies to be installed first
```
Comment (akosyakov) [inline packages/plugin-ext/src/main/node/plugin-deployer-impl.ts]: @JPinkney It does not matter in which order plugins are deployed. They are only loaded when a frontend is connected by then all plugins should be already on the disk.

**Comment by akosyakov** [comment]
@vince-fugnitto @marcdumais-work it is important for 0.10.0

**Comment by akosyakov** [comment]
@AlexTugarev could you please approve it as well @JPinkney is not an official committer yet, unfortunately, PR can be only merged after the approve by a committer
