### PR TITLE
Fixed #5289: fixed rendering/animation issue in the Search-in-Workspa…

### LINKED ISSUE #5289: [search] Blinking number when search content changes
In the search widget, the number of files displayed seems to be blinking when as the search content changes. It seems the number goes to '0' before switching to the new result. Small bug, but it can look glitchy sometimes.

(OS: Linux; browser: Chrome 74)

### PR DESCRIPTION
**Pull request by fangnx**
Fixed #5289.

Fixed the "glitchy animation" problem in the Search-in-Workspace widget that happens when the content in the search box changes. The updated code introduced additional checks to exclude the case `resultNumber > 0 && fileNumber === 0` that caused the re-rendering issue. This way the `searchForContainer` component would not re-render in this case.

### CODE REVIEW

File: packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx [hunk 1]
```diff
@@ -248,8 +248,10 @@ export class SearchInWorkspaceWidget extends BaseWidget implements StatefulWidge
 
     protected onUpdateRequest(msg: Message): void {
         super.onUpdateRequest(msg);
-        ReactDOM.render(<React.Fragment>{this.renderSearchHeader()}{this.renderSearchInfo()}</React.Fragment>, this.searchFormContainer);
-        this.onDidUpdateEmitter.fire(undefined);
+        if (this.renderSearchInfo()) {
```
Comment (akosyakov) [inline packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx]: please extract a result of `this.renderSearchInfo()` to a local variable, otherwise you render it twice

File: packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx [hunk 2]
```diff
@@ -248,8 +248,10 @@ export class SearchInWorkspaceWidget extends BaseWidget implements StatefulWidge
...
+            ReactDOM.render(<React.Fragment>{this.renderSearchHeader()}{this.renderSearchInfo()}</React.Fragment>, this.searchFormContainer);
+            this.onDidUpdateEmitter.fire(undefined);
```
Comment (akosyakov) [inline packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx]: it was called before always, not only sometimes. Does it change semantic for some clients?

Comment (fangnx) [reply packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx]: It would render as long as the *searchInfo* is correct (i.e. it only excludes the case **xx results in 0 file**, which caused the glitch previously). The change should not have impacts on how the component and the search function is used.
