### PR TITLE
Fix 'Close Workspace'

### LINKED ISSUE #2662: 'Close Workspace` does not work properly on all browsers
The command `Close Workspace` does work properly on **Firefox** and potentially other browsers.
The command does however seem to work on both Chrome and Electron instance.

In essence the command does not perform anything (simply shows loader) and restores back to the workspace.

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #2662

- Fixed issue with the command `Close Workspace` which did not work on all browsers
- Since the function `setMostRecentlyUsedWorkspace` returns a Promise, it was necessary to `await` until the data is saved in `recentWorkspace.json` before reloading Theia

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

File: packages/workspace/src/browser/workspace-service.ts [hunk 1]
```diff
@@ -318,11 +318,11 @@ export class WorkspaceService implements FrontendApplicationContribution {
     /**
      * Clears current workspace root.
      */
-    close(): void {
+    async close(): Promise<void> {
         this._workspace = undefined;
         this._roots.length = 0;
 
-        this.server.setMostRecentlyUsedWorkspace('');
+        await this.server.setMostRecentlyUsedWorkspace('');
```
Comment (simark) [inline packages/workspace/src/browser/workspace-service.ts]: I'm looking at the implementation of `setMostRecentlyUserWorkspace`, here:

https://github.com/theia-ide/theia/blob/master/packages/workspace/src/node/default-workspace-server.ts#L105

Do you think the call to `writeToUserHome` would need to be awaited, to be sure it's completed before we try to reload?

Comment (simark) [reply packages/workspace/src/browser/workspace-service.ts]: It doesn't seem necessary, when reloading we get the most recent path from memory (`this.root` in `DefaultWorkspaceServer`), not from the json file. So nevermind.

**Comment by vince-fugnitto** [comment]
thanks @simark, I'll wait to see what @elaihau thinks too

File: packages/workspace/src/browser/workspace-service.ts [hunk 2]
```diff
@@ -318,11 +318,11 @@ export class WorkspaceService implements FrontendApplicationContribution {
     /**
      * Clears current workspace root.
      */
-    close(): void {
+    async close(): Promise<void> {
         this._workspace = undefined;
         this._roots.length = 0;
 
-        this.server.setMostRecentlyUsedWorkspace('');
```
Comment (elaihau) [inline packages/workspace/src/browser/workspace-service.ts]: Maybe we could talk on Monday in person. Like Simon, I don't really understand the difference.

Comment (vince-fugnitto) [reply packages/workspace/src/browser/workspace-service.ts]: I had to make sure to `await` the call `this.server.setMostRecentlyUsedWorkspace('')` in order for the backend to properly finish updating before Theia can reload. What I noticed in Firefox for example is that the update never resolves so when Theia reloads it reloads with the workspace that was opened before the `Close Workspace` was called.
