### PR TITLE
 [plug-in] Add document.registerDocumentSymbolProvider API

### LINKED ISSUE #3200: [plug-in][languages] Register a document symbol provider
Register a document symbol provider.

Multiple providers can be registered for a language. In that case providers are asked in parallel and the results are merged. A failing provider (rejected promise or exception) will not cause a failure of the whole operation.

https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L2523

### PR DESCRIPTION
**Pull request by azatsarynnyy**
This PR replaces previously added mock for `document.registerDocumentSymbolProvider` API with the implementation.
Closes #3200 
Sample plugin is here https://github.com/eclipse/che-theia-samples/pull/16

### CODE REVIEW

File: packages/plugin-ext/src/api/model.ts [hunk 1]
```diff
@@ -299,3 +299,42 @@ export interface WorkspaceEdit {
     edits: Array<ResourceTextEdit | ResourceFileEdit>;
     rejectReason?: string;
 }
+
+export enum SymbolKind {
```
Comment (benoitf) [inline packages/plugin-ext/src/api/model.ts]: hello, does it conflict with https://github.com/theia-ide/theia/blob/b9d9bba4bf1ad1bccde86b02230f4b143be7d189/packages/plugin-ext/src/plugin/types-impl.ts#L1101 ? (like removing one or the other)

Comment (azatsarynnyy) [reply packages/plugin-ext/src/api/model.ts]: @benoitf  I'm not sure whether it's a good idea.
If I understand correctly, the `model.ts` is an API for main<->ext communication. But the `types-impl.ts` contains the types for using by the plugins. Correct me if I'm wrong, please.

Comment (evidolob) [reply packages/plugin-ext/src/api/model.ts]: @azatsarynnyy You are right, types `model.ts` is for main<->ext communication. `types-impl.ts` contains implementation described in `theia.d.ts`

Comment (azatsarynnyy) [reply packages/plugin-ext/src/api/model.ts]: Are there any objections to merging this PR?

**Comment by azatsarynnyy** [comment]
@benoitf don't you mind to merge this PR?

**Comment by azatsarynnyy** [comment]
rebased on master
