### PR TITLE
GH-3736: Use the system Git in electron.

### LINKED ISSUE #3571: [git][electron] Cannot push to a public repository from the bundled electron application
I go the following error when I tried to push from the UI.
```
Request push failed with message: git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': Device not configured
```

I can push from the terminal. Also, the `credential.helper` looks good:
```
$ git config --global credential.helper
osxkeychain
```

### LINKED ISSUE #3736: [git] System/Global level `credential.helper` is not available from the electron application
This is a follow-up of #3397. Even if one [configures the `credential.helper`](https://help.github.com/articles/caching-your-github-password-in-git/) for Git, Theia does not use the system Git by default, so it has no effect.

Related #3571.

### PR DESCRIPTION
**Pull request by kittaakos**
If Git does not exist on the `PATH`,
fall back to the embedded Git.

Closes #3736.
Closes #3571.

### CODE REVIEW

**Comment by kittaakos** [comment]
The Windows build fails with
```
lerna ERR! execute callback with error
2210lerna ERR! Error: Command failed: yarn run test
2211lerna ERR! error Command failed with exit code 4.
2212lerna ERR! 
2213lerna ERR! $ theiaext test
2214lerna ERR! 
2215lerna ERR! 
2216lerna ERR!   TypescriptVersionServiceImpl
2217lerna ERR!     1) resolveBundledVersionInApplicationPath
2218lerna ERR!     2) resolveBundledVersionWithRequire
2219lerna ERR!     3) resolveBundledVersionAsExecutable
2220lerna ERR!     4) getVersions
2221lerna ERR! 
2222lerna ERR!   typescript package
2223lerna ERR!     √ should support code coverage statistics
2224lerna ERR! 
2225lerna ERR! 
2226lerna ERR!   1 passing (3s)
2227lerna ERR!   4 failing
2228lerna ERR! 
2229lerna ERR!   1) TypescriptVersionServiceImpl resolveBundledVersionInApplicationPath:
2230lerna ERR!      AssertionError [ERR_ASSERTION]: undefined == 'node_modules/typescript/lib'
2231lerna ERR!       at Suite.<anonymous> (src\node\typescript-version-service-impl.spec.ts:43:16)
2232lerna ERR!       at step (src\node\typescript-version-service-impl.spec.ts:47:23)
2233lerna ERR!       at Object.next (src\node\typescript-version-service-impl.spec.ts:28:53)
2234lerna ERR!       at fulfilled (src\node\typescript-version-service-impl.spec.ts:19:58)
2235lerna ERR!       at <anonymous>
2236lerna ERR! 
2237lerna ERR!   2) TypescriptVersionServiceImpl resolveBundledVersionWithRequire:
2238lerna ERR!      AssertionError [ERR_ASSERTION]: undefined == 'node_modules/typescript/lib'
2239lerna ERR!       at Suite.<anonymous> (src\node\typescript-version-service-impl.spec.ts:48:16)
2240lerna ERR!       at step (src\node\typescript-version-service-impl.spec.ts:47:23)
2241lerna ERR!       at Object.next (src\node\typescript-version-service-impl.spec.ts:28:53)
2242lerna ERR!       at fulfilled (src\node\typescript-version-service-impl.spec.ts:19:58)
2243lerna ERR!       at <anonymous>
2244lerna ERR! 
2245lerna ERR!   3) TypescriptVersionServiceImpl resolveBundledVersionAsExecutable:
2246lerna ERR!      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
2247lerna ERR!       at <anonymous>
2248lerna ERR! 
2249lerna ERR!   4) TypescriptVersionServiceImpl getVersions:
2250lerna ERR! 
2251lerna ERR!       AssertionError [ERR_ASSERTION]: 'Bundled: undefined\r\nWorkspace: undefined' == 'Bundled: node_modules/typescript/lib\r\nWorkspace: node_modules/typescript/lib'
2252lerna ERR!       + expected - actual
2253lerna ERR! 
2254lerna ERR!       -Bundled: undefined
2255lerna ERR!       -Workspace: undefined
2256lerna ERR!       +Bundled: node_modules/typescript/lib
2257lerna ERR!       +Workspace: node_modules/typescript/lib
2258lerna ERR!       
2259lerna ERR!       at Suite.<anonymous> (src\node\typescript-version-service-impl.spec.ts:60:16)
2260lerna ERR!       at step (src\node\typescript-version-service-impl.spec.ts:47:23)
2261lerna ERR!       at Object.next (src\node\typescript-version-service-impl.spec.ts:28:53)
2262lerna ERR!       at fulfilled (src\node\typescript-version-service-impl.spec.ts:19:58)
2263lerna ERR!       at <anonymous>
2264lerna ERR! 
2265lerna ERR! 
2266lerna ERR! 
2267lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2268lerna ERR! 
2269lerna ERR!     at Promise.all.then.arr (C:\projects\theia\node_modules\lerna\node_modules\execa\index.js:236:11)
2270lerna ERR!     at <anonymous>
2271{ Error: Command failed: yarn run test
2272error Command failed with exit code 4.
2273
```

Although I do not have the failing `typescript-version-service-impl.spec.ts` module in [my branch](https://github.com/theia-ide/theia/tree/GH-3736/packages/typescript/src). Any ideas what's oging on, @akosyakov?

**Comment by kittaakos** [comment]
@svenefftinge, @AlexTugarev can one of you look into this? Thanks!

File: packages/git/src/electron-node/init/electron-git-init.ts [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+            } catch (err) {
+                await this.handleExternalNotFound(err);
+            }
+        }
+    }
+
+    // tslint:disable-next-line:no-any
+    protected async handleExternalNotFound(err?: any): Promise<void> {
+        if (err) {
+            this.logger.error(err);
```
Comment (AlexTugarev) [inline packages/git/src/electron-node/init/electron-git-init.ts]: Should we notify users in such cases?

Comment (kittaakos) [reply packages/git/src/electron-node/init/electron-git-init.ts]: 👍 Oh sure. I did not want to log the stack trace; the user cannot do much with that, but I wanted to "log" _Could not find Git on the PATH. Falling back to the embedded Git._ via the `messageService`.

**Comment by kittaakos** [comment]
@AlexTugarev, please retake a look. This time, the PR is without the message service notifications. We can handle it in a follow-up if needed.

File: packages/git/src/electron-node/init/electron-git-init.ts [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+        const { env } = process;
+        if (typeof env.LOCAL_GIT_DIRECTORY !== 'undefined' || typeof env.GIT_EXEC_PATH !== 'undefined') {
+            await this.handleExternalNotFound('Cannot use Git from the PATH when the LOCAL_GIT_DIRECTORY or the GIT_EXEC_PATH environment variables are set.');
+        } else {
+            try {
+                const { execPath, path, version } = await findGit();
+                if (!!execPath && !!path && !!version) {
+                    // https://github.com/desktop/dugite/issues/111#issuecomment-323222834
+                    // Instead of the executable path, we need the root directory of Git.
+                    const dir = dirname(dirname(path));
```
Comment (AlexTugarev) [inline packages/git/src/electron-node/init/electron-git-init.ts]: if `path` is e.g. `/usr/local/bin/git`, `dir` is supposed to be `/usr/local`?

Comment (kittaakos) [reply packages/git/src/electron-node/init/electron-git-init.ts]: ☝️ Yes, there is the [comment](https://github.com/desktop/dugite/issues/111#issuecomment-323222834) above the code.

Comment (AlexTugarev) [reply packages/git/src/electron-node/init/electron-git-init.ts]: Thanks! ;-)

**Comment by AlexTugarev** [comment]
Works fine! 

Just verified, that the git from `PATH` is found:
```
root INFO Using Git [2.19.1] from the PATH. (/usr/local/bin/git)
```

Then, after managing to "disable" Apple's default git, I could test the fallback to embedded git as well.
```
root INFO Could not find Git on the PATH. Falling back to the embedded Git.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
```
Also, put a breakpoint into dugite code, just to make sure it shows the proper git location.
```
"/Users/tugarev/Projects/theia/B/node_modules/dugite/git/bin/git"
```

**Comment by kittaakos** [comment]
Wow, thanks for the review @AlexTugarev! The Windows build is the good old
```
Error: An unknown server-side error occurred while processing the command.\n    at execute("return window.__coverage__;") - C:\projects\theia\node_modules\wdio-sync\build\index.js:244:37\n    at elements("div#theia-statusBar") - 
```

I am going to merge this.
