### PR TITLE
tolerate missing internet access while deploying plugins

### LINKED ISSUE #6055: plugins are not loaded when theia is started without internet access
### Description
All the vscode plugins can not be loaded when my host machine has no Internat access.

we have two local vscode extensions which we downloaded from vscode marketplace:
1 [vscjava.vscode-java-dependency](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency)
2 [redhat.java](https://marketplace.visualstudio.com/items?itemName=redhat.java)

It should be noted that the **vscjava.vscode-java-dependency** extension depends on **redhat.java**(see https://github.com/microsoft/vscode-java-dependency/blob/master/package.json#L165).
When I start theia, theia plugin system will still try to download **redhat.java** from vscode marketplace. If my host has no Internat access, then all the plugins can not be loaded.

### Reproduction Steps

**OS and Theia version:**
centos 7
theia [6c4fa9c7](https://github.com/theia-ide/theia/commit/6c4fa9c7ff074ec9a028ae552ec096d6057ea9fd)
**Diagnostics:** 

related to https://github.com/theia-ide/theia/pull/5379 and https://github.com/theia-ide/theia/pull/6038

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

- fix #6055: 
  - check whether a plugin is already to be deployed by an id
  - fix to use canonical plugin ids to resolve and activate plugins
  - make sure that dependencies only resolved after listed plugin entries
  - don't fail the entire deployment if a resolution of a single plugin entry failed
- closes https://github.com/theia-ide/theia/pull/6056 (superseded)

#### How to test

1 download two vscode plugins from vscode marketplac

-  [vscjava.vscode-java-dependency](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency)
- [redhat.java](https://marketplace.visualstudio.com/items?itemName=redhat.java)

2 copy these two plugins to `plugins` directory
3 then start theia(`cd examples/browser; yarn start`), and check if all of the vscode extensins can be loaded successfully

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext/src/main/node/plugin-deployer-impl.ts [hunk 1]
```diff
@@ -114,27 +114,46 @@ export class PluginDeployerImpl implements PluginDeployer {
...
-                    pluginsToDeploy.set(metadata.model.id, deployerEntry);
-                    if (metadata.model.extensionDependencies) {
-                        queue.push(...metadata.model.extensionDependencies);
+            for (const metadata of chunk) {
+                const extensionDependencies = metadata.source.extensionDependencies;
+                const deployableExtensionDependencies = metadata.model.extensionDependencies;
+                if (extensionDependencies && deployableExtensionDependencies) {
+                    for (let dependencyIndex = 0; dependencyIndex < extensionDependencies.length; dependencyIndex++) {
+                        const dependencyId = extensionDependencies[dependencyIndex].toLowerCase();
+                        if (!pluginsToDeploy.has(dependencyId)) {
```
Comment (akosyakov) [inline packages/plugin-ext/src/main/node/plugin-deployer-impl.ts]: @tom-shan check to prevent resolution of extension dependencies is done here based on canonical plugin ids

Comment (tom-shan) [reply packages/plugin-ext/src/main/node/plugin-deployer-impl.ts]: nice!

File: packages/plugin-ext/src/main/node/plugin-deployer-impl.ts [hunk 2]
```diff
@@ -114,27 +114,46 @@ export class PluginDeployerImpl implements PluginDeployer {
...
-                continue;
+            const chunk = [];
+            while (queue.length) {
+                const current = queue.shift()!;
+                if (visited.has(current)) {
+                    continue;
+                }
+                visited.add(current);
+                try {
+                    // resolve plugins
```
Comment (akosyakov) [inline packages/plugin-ext/src/main/node/plugin-deployer-impl.ts]: delete comments, they just repeat method names without any useful info

**Comment by akosyakov** [comment]
It should be enough, although it does not ensure that plugins are properly working, but it would be another issue.

**Comment by akosyakov** [comment]
@vince-fugnitto I've addressed your comments. In addition, you can try locally whether they get deployed when you switch off internet connection.

**Comment by tom-shan** [comment]
I have tried without Internet access, it works as expected.

**Comment by tom-shan** [comment]
> With internet enabled: I had the java dependency viewer extension in the plugins folder and it automatically downloaded redhat.java but the java extension doesn't seem to work. From the logs, It looks the client sends the initialize request but the java language server doesn't respond.

@JPinkney Could you provide the error logs and the auto downloaded vscode-java-dependency version?

**Comment by akosyakov** [comment]
> With internet disabled: if you only have the java dependency viewer extension in the plugins folder and then start a workspace it will load the extension but the extension dependency isn't respected (i.e. it doesn't care that redhat.java isn't there). I'm not sure if we should show a notification in this case or what we should do.

The extension should be activated if its dependencies cannot be activated. I will push a commit for it. We probably should notify a user as well.

> With internet enabled: I had the java dependency viewer extension in the plugins folder and it automatically downloaded redhat.java but the java extension doesn't seem to work. From the logs, It looks the client sends the initialize request but the java language server doesn't respond.

@JPinkney Could we address it separately? It does not seem to be an issue with deployment, but redhat.java does not work for some reasons, maybe latest versions is using some missing apis?

**Comment by akosyakov** [comment]
> The extension should NOT be activated if its dependencies cannot be activated. I will push a commit for it. We probably should notify a user as well.

I will open a follow-up issue for it to handle loading and activation errors properly. It is very involving to change before a release.

**Comment by akosyakov** [comment]
@JPinkney i am going to merge it to fix a regression for 0.10.0. Please file an issue for broken redhat.java when it is auto downloaded.
