### PR TITLE
Fixed leaking widgets

### LINKED ISSUE #1882: [quality] The `OutputChannelManager` should provide `OutputChannel` instead of `OutputChannelImpl`
I ran into this when I was going through the code. Currently, it returns with the implementations and not with the interfaces. Is it on purpose or just a minor leftover thing?

The current state of the `OutputChannelManager`:
```typescript
  ...
  getChannel(name: string): OutputChannelImpl;
  getChannels(): OutputChannelImpl[];
  ...
```

### PR DESCRIPTION
**Pull request by akosyakov**
It fixes #1882, #1570 and makes sure that widgets are not leaking. There is one commit per a widget.

The widget leaks if its instance is not garbaged collected after closing or there are multiple widgets for a singleton widget after several reopening.

### CODE REVIEW

**Comment by kittaakos** [comment]
I am starting the review right now.

**Comment by akosyakov** [comment]
@AlexTugarev added you to review because of the preview widget

**Comment by akosyakov** [comment]
Main pitfalls:
- forget to collect and dispose event emitters or listeners
- forget to collect and dispose disposable which are not singleton
- overlooked that a disposable is created async at the time when the owner is already disposed
- DOM listeners are added prematurely and never removed, they should be added in `onBeforeAttach` widget lifecycle callback and removed in `onAfterDetach`. `BaseWidget` has a convenient method `this.addEventListener(node, ...` for it.

**Comment by AlexTugarev** [comment]
This is great!

File: packages/navigator/src/browser/navigator-container.ts [hunk 1]
```diff
@@ -41,6 +42,9 @@ export function createFileNavigatorContainer(parent: interfaces.Container): Cont
     child.rebind(TreeDecoratorService).toDynamicValue(ctx => ctx.container.get(NavigatorDecoratorService)).inSingletonScope();
     bindContributionProvider(child, NavigatorTreeDecorator);
 
+    child.bind(FileNavigatorSearch).toSelf().inSingletonScope();
+    child.bind(NavigatorTreeDecorator).toService(FileNavigatorSearch);
```
Comment (kittaakos) [inline packages/navigator/src/browser/navigator-container.ts]: [question]: Moving this (from the `navigator-frontend-module.ts`) here ensures that we have a new search and decorator instance each time we create a new widget after a disposal. Is that correct? If no, could you explain? Thanks!

File: packages/navigator/src/browser/navigator-widget.ts [hunk 2]
```diff
@@ -57,30 +78,11 @@ export class FileNavigatorWidget extends FileTreeWidget {
                         this.model.expandNode(child);
                     }
                 }
-            }),
-            this.navigatorSearch,
```
Comment (kittaakos) [inline packages/navigator/src/browser/navigator-widget.ts]: Did you omit this on purpose or by accident? (Or I am simply blind.)

File: packages/navigator/src/browser/navigator-container.ts (hunk 1 above)
Comment (akosyakov) [reply packages/navigator/src/browser/navigator-container.ts]: `FileNavigatorSearch` injects `Tree` which should exists only in the scope of the navigator container, otherwise even the navigator widget is disposed, a reference to it kept from `FileNavigatorSearch`.

**Comment by akosyakov** [comment]
It is ready for review.

@kittaakos go ahead with the coding guideline

**Comment by kittaakos** [comment]
> go ahead with the coding guideline

Let's create a follow-up, I will assign it to me, but I do not have time for that now, and I do not want to hold this PR back. Any objections, @akosyakov?

**Comment by akosyakov** [comment]
@kittaakos sounds good

File: packages/navigator/src/browser/navigator-widget.ts [hunk 3]
```diff
@@ -57,30 +79,22 @@ export class FileNavigatorWidget extends FileTreeWidget {
...
+    protected updateGlobalSelection(selection: ReadonlyArray<Readonly<SelectableTreeNode>>): void {
+        if (this.shell.activeWidget !== this) {
+            return;
         }
-        );
+        this.selectionService.selection = selection;
+        const removeGlobalSelection = this.toDispose.push(Disposable.create(() =>
+            this.selectionService.selection = undefined
+        ));
+        this.toDispose.push(this.selectionService.onSelectionChanged(() => removeGlobalSelection.dispose()));
```
Comment (svenefftinge) [inline packages/navigator/src/browser/navigator-widget.ts]: same here

File: packages/core/src/common/event.ts [hunk 4]
```diff
@@ -109,6 +124,8 @@ export class Emitter<T> {
 
     private _event: Event<T>;
     private _callbacks: CallbackList | undefined;
+    private _disposed = false;
+    private _maxListeners = 30;
```
[the remark this answers is not in the document]
Comment (svenefftinge) [reply packages/core/src/common/event.ts]: I guess that's an arbitrary number, so no need to change. I just would like to understand if you have reasons to not make it 20 or 40. :-)

File: packages/navigator/src/browser/navigator-widget.ts (hunk 3 above)
Comment (AlexTugarev) [reply packages/navigator/src/browser/navigator-widget.ts]: where is the caller of `updateGlobalSelection`?

File: packages/core/src/common/event.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (akosyakov) [reply packages/core/src/common/event.ts]: I've tried with 10 and it was too low, for instance if you open 10 editors there are already some listeners which start complaining, i am lazy to tune these listeners :) I set the higher threshold that it does not produce to much false positive but still have a chance to stop leaking listeners.

File: packages/editor/src/browser/editor-widget.ts [hunk 5]
```diff
@@ -36,7 +36,15 @@ export class EditorWidget extends BaseWidget implements SaveableSource, Navigata
...
         this.editor.focus();
+        this.updateGlobalSelection();
+    }
+
+    protected updateGlobalSelection(): void {
         this.selectionService.selection = this.editor;
+        const removeGlobalSelection = this.toDispose.push(Disposable.create(() =>
+            this.selectionService.selection = undefined
+        ));
+        this.toDispose.push(this.selectionService.onSelectionChanged(() => removeGlobalSelection.dispose()));
```
[the remark this answers is not in the document]
Comment (akosyakov) [reply packages/editor/src/browser/editor-widget.ts]: i have to rename it 😁 disposing `removeGlobalSelection` removes a disposable from `this.toDispose`, it does not execute it

[the remark this answers is not in the document]
Comment (svenefftinge) [reply packages/editor/src/browser/editor-widget.ts]: ok, got it

**Comment by akosyakov** [comment]
https://github.com/theia-ide/theia/pull/1886/commits/f6c014aa8c00dd2d70a3a1875653ff25d1f461d2 - added code that removes a global selection if it gets disposed. Could you have a look at this comitt? 

With it clients can do as before `this.selectionService = this.editor` without worrying about leaking selections. It works only if clients provide a disposable selection, otherwise they are responsible for cleaning. For example the navigator used to provide an array of nodes as selection, I’ve changed it to provide the navigator model.

While doing it, discovered that the switch command in the cpp extension was broken: it was assuming that there is always an URI selection and the navigator provides the URI selection which is not true since mutliselection support in the navigator.

File: packages/core/src/common/selection-service.ts [hunk 6]
```diff
@@ -15,22 +16,30 @@ export interface SelectionProvider<T> {
 }
 
 @injectable()
-export class SelectionService implements SelectionProvider<any> {
+export class SelectionService implements SelectionProvider<Object | undefined> {
```
Comment (svenefftinge) [inline packages/core/src/common/selection-service.ts]: why not any? Having a string as the selection would make sense, no?

File: packages/core/src/common/selection-service.ts [hunk 7]
```diff
@@ -15,22 +16,30 @@ export interface SelectionProvider<T> {
...
-
-    get onSelectionChanged(): Event<any> {
-        return this.selectionListeners.event;
+        if (Disposable.is(selection)) {
+            const disposeSelection = selection.dispose;
+            selection.dispose = () => {
+                this.selection = undefined;
+                disposeSelection.bind(selection)();
+            };
+            this.toDisposeOnSelection.push(Disposable.create(() => selection.dispose = disposeSelection));
```
Comment (svenefftinge) [inline packages/core/src/common/selection-service.ts]: Not sure such magic is worth it. After all selections have a rather short life, so even if the selection handler would keep a reference to a disposed object, it will not kept for long, as selections are overridden all the time.

**Comment by AlexTugarev** [comment]
Can we do something about this?

```
bundle.js:127024 Error: Possible Emitter memory leak detected. 30 exit listeners added. Use event.maxListeners to increase limit
    at Emitter.../../packages/core/lib/common/event.js.Emitter.checkMaxListeners (bundle.js:126735)
    at ExtensionManager._event.Object.assign.maxListeners (bundle.js:126696)
    at new Extension (bundle.js:134056)
    at bundle.js:134162
    at Array.map (<anonymous>)
    at bundle.js:134161
```

File: packages/core/src/common/selection-service.ts (hunk 6 above)
Comment (akosyakov) [reply packages/core/src/common/selection-service.ts]: with `any` there is no way to distinguish between `undefined` and value, with `Object | undefined` they are forced to check for `undefined` and add a proper type guard

File: packages/core/src/common/selection-service.ts (hunk 7 above)
Comment (akosyakov) [reply packages/core/src/common/selection-service.ts]: ok, let's rollback it

**Comment by akosyakov** [comment]
@AlexTugarev how did you get it? Would it happen in real?

**Comment by AlexTugarev** [comment]
I think so. I just opened a couple of workspaces, it's always there.

File: packages/core/src/common/selection-service.ts (hunk 6 above)
Comment (akosyakov) [reply packages/core/src/common/selection-service.ts]: `Object` allows `string`, `object` does not allow

**Comment by akosyakov** [comment]
@svenefftinge i've rolled back auto removing global selections.
@AlexTugarev It was a good call, i've tried to tune `maxListeners` and turned out that it was not possible at all :) Now should be fixed.

Please look at changes once more.

File: packages/core/src/common/uri-command-handler.ts [hunk 8]
```diff
@@ -72,29 +72,14 @@ export class UriAwareCommandHandler<T extends MaybeArray<URI>> implements Comman
...
-                if (UriSelection.is(firstItem)) {
-                    return firstItem.uri as T;
-                }
-            }
+        const uris = UriSelection.getUris(selection);
+        if (this.options && this.options.isValid) {
+            return (this.options.isValid(uris) ? uris : undefined) as T;
         }
-        return undefined;
+        return uris as T;
```
Comment (AlexTugarev) [inline packages/core/src/common/uri-command-handler.ts]: @akosyakov, I'm not sure, which line of `getUri` to mark, but it breaks the Files navigator. Try to open context menu, you'll see that it returns `currentSelection` from selection service, which is not URI as expected by `OpenHandler`s.

**Comment by akosyakov** [comment]
@AlexTugarev please check again

**Comment by AlexTugarev** [comment]
@akosyakov, please ask someone else to check. I‘m traveling today.

**Comment by akosyakov** [comment]
@svenefftinge Is it fine to merge?

**Comment by svenefftinge** [comment]
Yes, please merge.
