### PR TITLE
[Plugin-API] Apply window.createQuickPick()

### LINKED ISSUE #4987: [Plugin-API] Apply window.createQuickPick() function
### Description
 
Related VsCode function:
https://github.com/Microsoft/vscode/blob/d9d621ee9ef00cc6cb589954db72b50b3ea5ab67/src/vs/vscode.d.ts#L6512-L6522

Is needed for https://github.com/theia-ide/theia/pull/4279, https://github.com/theia-ide/theia/issues/4266
### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by vinokurig**
Apply `window.createQuickPick()` plugin API function. The function wraps `QuickOpenExtImpl` to set and show a QuickPick menu. Other functionality is not implemented because it require a lot of changes in the Theia quick-open model.
Is needed for https://github.com/theia-ide/theia/issues/4266
fixes #4987

### CODE REVIEW

**Comment by benoitf** [comment]
Hi @vinokurig do you have run https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/singlefolder-tests/quickInput.test.ts against this ?

**Comment by akosyakov** [comment]
> Other functionality is not implemented because it require a lot of changes in the Theia quick-open model.

Could you please open an issue to list everything what should be implemented? that it does not get lost in the code

**Comment by vinokurig** [comment]
@akosyakov
> Could you please open an issue to list everything what should be implemented? that it does not get lost in the code... or don't declare what is not implemented if it does no cause runtime issues

Opened related issue for missing functionality: https://github.com/theia-ide/theia/issues/5059

**Comment by vinokurig** [comment]
@benoitf 
> Hi @vinokurig do you have run https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/singlefolder-tests/quickInput.test.ts against this ?

Those are VsCode tests, they will probably fail because we have related issues for not implemented functionality: https://github.com/theia-ide/theia/issues/5059

**Comment by akosyakov** [comment]
I'm trying to test with https://github.com/Microsoft/vscode-extension-samples/tree/master/quickinput-sample

but plugin host process cannot start for me with this PR:
```
root INFO Theia app listening on http://localhost:3000.
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /workspace/theia/plugins/quickinput-sample
root INFO Resolved "quickinput-sample" to a VS Code extension "quickinput-sample@0.0.1" with engines: { vscode: '^1.26.0' }
root INFO Deploying backend plugin "quickinput-sample@0.0.1" from "/workspace/theia/plugins/quickinput-sample/out/extension.js"
root WARN Collided keybinding is ignored;  {"command":"terminal:new:active:workspace","keybinding":"ctrl+`"}  collided with  {"command":"terminal:new","keybinding":"ctrl+shift+`"}
root WARN Could not register keybinding:
  {"command":"terminal:new:active:workspace","keybinding":"ctrl+`"}
Error: "ctrl+`" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 121.40500009991229 ms
root INFO Using Git [2.19.1] from the PATH. (/usr/bin/git)
root INFO [nsfw-watcher: 7716] Started watching: /home/gitpod/.theia
root ERROR [hosted-plugin: 7731] /workspace/theia/node_modules/inversify/lib/annotation/decorator_utils.js:22
    if (Reflect.hasOwnMetadata(metadataKey, annotationTarget)) {
                ^

TypeError: Reflect.hasOwnMetadata is not a function
    at _tagParameterOrProperty (/workspace/theia/node_modules/inversify/lib/annotation/decorator_utils.js:22:17)
    at Object.tagParameter (/workspace/theia/node_modules/inversify/lib/annotation/decorator_utils.js:7:5)
    at /workspace/theia/node_modules/inversify/lib/annotation/named.js:10:31
    at /workspace/theia/packages/core/lib/common/command.js:27:37
    at __decorate (/workspace/theia/packages/core/lib/common/command.js:20:95)
    at /workspace/theia/packages/core/lib/common/command.js:386:23
    at Object.<anonymous> (/workspace/theia/packages/core/lib/common/command.js:392:2)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

**Comment by akosyakov** [comment]
@vinokurig How can I test it?

**Comment by vinokurig** [comment]
@akosyakov Fixed the error, now you can test it with the sample plugin

File: packages/plugin-ext/src/plugin/quick-open.ts [hunk 1]
```diff
@@ -123,3 +130,123 @@ export class QuickOpenExtImpl implements QuickOpenExt {
...
+        this.dispose();
+    }
+
+    show(): void {
+        const selectItem = (item: T) => {
+            this.activeItems = [item];
+            this.onDidAcceptEmitter.fire(undefined);
+            this.onDidChangeSelectionEmitter.fire([item]);
+            this.onDidHideEmitter.fire(undefined);
+            this.dispose();
```
Comment (akosyakov) [inline packages/plugin-ext/src/plugin/quick-open.ts]: Should not it be done by a client? Can a client call `show` several items on the same instance of quick open?

File: packages/plugin-ext/src/plugin/quick-open.ts [hunk 2]
```diff
@@ -123,3 +130,123 @@ export class QuickOpenExtImpl implements QuickOpenExt {
...
+        };
+        this.quickOpen.showQuickPick(this.items.map(item => item as T), {
+            // tslint:disable-next-line:no-any
+            onDidSelectItem(item: T | string): any {
+                if (typeof item !== 'string') {
+                    selectItem(item);
```
Comment (akosyakov) [inline packages/plugin-ext/src/plugin/quick-open.ts]: what about a case when item is not defined? Should not fire did hide event at least?

**Comment by akosyakov** [comment]
I'm getting errors in the backend console trying different combinations from the sample extension:
```
root ERROR [hosted-plugin: 4427] TypeError: vscode_1.window.createInputBox is not a function
    at Promise (/workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:233:51)
    at new Promise (<anonymous>)
    at MultiStepInput.<anonymous> (/workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:232:30)
    at Generator.next (<anonymous>)
    at /workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:7:12)
    at MultiStepInput.showInputBox (/workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:229:16)
    at /workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:80:42
    at Generator.next (<anonymous>)

root ERROR [hosted-plugin: 4427] TypeError: Cannot read property 'map' of undefined
    at QuickPickExt.show (/workspace/theia/packages/plugin-ext/lib/plugin/quick-open.js:225:49)
    at Promise (/workspace/theia/plugins/quickinput-sample/out/quickOpen.js:105:23)
    at new Promise (<anonymous>)
    at /workspace/theia/plugins/quickinput-sample/out/quickOpen.js:56:26
    at Generator.next (<anonymous>)
    at /workspace/theia/plugins/quickinput-sample/out/quickOpen.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/theia/plugins/quickinput-sample/out/quickOpen.js:7:12)
    at pickFile (/workspace/theia/plugins/quickinput-sample/out/quickOpen.js:53:12)
    at Object.<anonymous> (/workspace/theia/plugins/quickinput-sample/out/quickOpen.js:27:27)
```

File: packages/plugin-ext/src/plugin/quick-open.ts (hunk 1 above)
Comment (vinokurig) [reply packages/plugin-ext/src/plugin/quick-open.ts]: Make sens

File: packages/plugin-ext/src/plugin/quick-open.ts (hunk 2 above)
Comment (vinokurig) [reply packages/plugin-ext/src/plugin/quick-open.ts]: fixed

**Comment by vinokurig** [comment]
@akosyakov 
> I'm getting errors in the backend console trying different combinations from the sample extension:
```root ERROR [hosted-plugin: 4427] TypeError: vscode_1.window.createInputBox is not a function
    at Promise (/workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:233:51)
    at new Promise (<anonymous>)
    at MultiStepInput.<anonymous> (/workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:232:30)
    at Generator.next (<anonymous>)
    at /workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:7:12)
    at MultiStepInput.showInputBox (/workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:229:16)
    at /workspace/theia/plugins/quickinput-sample/out/multiStepInput.js:80:42
    at Generator.next (<anonymous>)

root ERROR [hosted-plugin: 4427] TypeError: Cannot read property 'map' of undefined
    at QuickPickExt.show (/workspace/theia/packages/plugin-ext/lib/plugin/quick-open.js:225:49)
    at Promise (/workspace/theia/plugins/quickinput-sample/out/quickOpen.js:105:23)
    at new Promise (<anonymous>)
    at /workspace/theia/plugins/quickinput-sample/out/quickOpen.js:56:26
    at Generator.next (<anonymous>)
    at /workspace/theia/plugins/quickinput-sample/out/quickOpen.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/theia/plugins/quickinput-sample/out/quickOpen.js:7:12)
    at pickFile (/workspace/theia/plugins/quickinput-sample/out/quickOpen.js:53:12)
    at Object.<anonymous> (/workspace/theia/plugins/quickinput-sample/out/quickOpen.js:27:27)```

That's because `window.createInputBox` API method is not implemented yet

**Comment by akosyakov** [comment]
@vinokurig and the second error? i thought the quick open is already implemented. Is it a bug in the implementation, please open an issue.

**Comment by vinokurig** [comment]
@akosyakov Fixed the second error in the PR

**Comment by vinokurig** [comment]
@benoitf Can we go with current state?

**Comment by benoitf** [comment]
@vinokurig yes, please check first that commits are Signed (DCO and eca checks are failing)
