### PR TITLE
GH-838: Fixed multiple window management defect in electron.

### LINKED ISSUE #838: [electron] I cannot set the WS root (again)
Steps to reproduce:
 - `git clone https://github.com/theia-ide/theia.git && cd theia && rm -rf ~/.theia/ && yarn --force && yarn run rebuild:electron && cd examples/electron/ && yarn run start`
 - Select WS root.
 - File > Open...
 - Select another WS root.
 - Nothing happens.

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #838

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
Opening a new WS opens a new electron browser window, but closing is odd.

Start the electron app with WS1. Open WS2. The user can see two windows and can close WS2 without quitting the application. But when the user closes WS1 window, Theia stops.

**Comment by hexa00** [comment]
>Start the electron app with WS1. Open WS2. The user can see two windows and can close WS2 without quitting the application. But when the user closes WS1 window, Theia stops.

I just tested that and for me it works.. I can open WS2 and close WS1 and only that window closes... your code seems to take this into account too.

Is the comment outdated or could be osx specific?

**Comment by kittaakos** [comment]
> Is the comment outdated or could be osx specific?

Was before b481c06cfbb43c87b3e91c1dc8425a1809a0e5c6.

**Comment by kittaakos** [comment]
Introducing a custom binding for electron Window did not help, unfortunately. I need to find another approach. Closing the first window kills the application.

File: dev-packages/application-package/src/generator/frontend-generator.ts [hunk 1]
```diff
@@ -86,20 +86,27 @@ if (cluster.isMaster) {
...
             electron.app.quit();
         }
     });
-    electron.app.on('ready', function () {
+    electron.app.on('ready', () => {
         const path = require('path');
         const { fork } = require('child_process');
         // Check whether we are in bundled application or development mode.
-        const devMode = process.defaultApp || /node_modules[\\/]electron[\\/]/.test(process.execPath);
+        const devMode = process.defaultApp || /node_modules[\/]electron[\/]/.test(process.execPath);
```
Comment (kittaakos) [inline dev-packages/application-package/src/generator/frontend-generator.ts]: This should be fixed.

**Comment by kittaakos** [comment]
It seems to work on OS X in development mode. I need to verify this on Windows too. Also, I am planning to squash the commits.

**Comment by kittaakos** [comment]
I consider this PR ready for review.

**Comment by kittaakos** [comment]
> I need to verify this on Windows too

Done.

> Also, I am planning to squash the commits.

Done.

File: dev-packages/application-package/src/generator/frontend-generator.ts [hunk 2]
```diff
@@ -75,60 +75,99 @@ module.exports = Promise.resolve()${this.compileFrontendModuleImports(frontendMo
...
+const path = require('path');
+const { isMaster } = require('cluster');
+const { fork } = require('child_process');
+const electron = require('electron');
+const { app, BrowserWindow, ipcMain } = electron;
+
+// Workaround for https://github.com/electron/electron/issues/9225. Chrome has an issue where
+// in certain locales (e.g. PL), image metrics are wrongly computed. We explicitly set the
+// LC_NUMERIC to prevent this from happening (selects the numeric formatting category of the
+// C locale, http://en.cppreference.com/w/cpp/locale/LC_categories).
```
Comment (hexa00) [inline dev-packages/application-package/src/generator/frontend-generator.ts]: This was is cluster.isMaster before is there a reason it's not anymore ?

Comment (hexa00) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: I don't think it matters much... but it doesn't seem related to the current issue

File: dev-packages/application-package/src/generator/frontend-generator.ts [hunk 3]
```diff
@@ -75,60 +75,99 @@ module.exports = Promise.resolve()${this.compileFrontendModuleImports(frontendMo
...
+            options.show = true;
+            options.width = 1024;
+            options.height = 728;
+        });
     }
-    process.env.LC_NUMERIC = 'C';
-    const electron = require('electron');
-    electron.app.on('window-all-closed', function () {
+    windows.push(newWindow);
+    if (show) {
```
Comment (hexa00) [inline dev-packages/application-package/src/generator/frontend-generator.ts]: seems like you could just use theUrl here since show is not used by anything else

File: dev-packages/application-package/src/generator/frontend-generator.ts [hunk 4]
```diff
@@ -75,60 +75,99 @@ module.exports = Promise.resolve()${this.compileFrontendModuleImports(frontendMo
...
+        newWindow.loadURL(theUrl);
+    } else {
+        newWindow.on('ready-to-show', () => newWindow.show());
+    }
+    newWindow.on('closed', () => {
+        const index = windows.indexOf(newWindow);
+        if (index !== -1) {
+            let windowToClose = windows.splice(index, 1);
+            windowToClose = null;
```
Comment (hexa00) [inline dev-packages/application-package/src/generator/frontend-generator.ts]: Seems like just removing it from the array would delete it.. no need to create a var just to set it to null ?

File: dev-packages/application-package/src/generator/frontend-generator.ts [hunk 5]
```diff
@@ -75,60 +75,99 @@ module.exports = Promise.resolve()${this.compileFrontendModuleImports(frontendMo
...
+        }
+        if (windows.length === 0) {
+            app.exit(0);
+        }
+    });
+    return newWindow;
```
Comment (hexa00) [inline dev-packages/application-package/src/generator/frontend-generator.ts]: Not sure what this is doing ? first time I see a event handler return something..

File: packages/workspace/src/browser/browser-workspace-frontend-module.ts [hunk 6]
```diff
@@ -0,0 +1,53 @@
+/*
```
Comment (hexa00) [inline packages/workspace/src/browser/browser-workspace-frontend-module.ts]: why the name change ? isn't the directory enough ?

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 3 above)
Comment (kittaakos) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: We use `show`. See above.

Comment (hexa00) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: Ho right I had missed one :)

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 4 above)
Comment (kittaakos) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: I wanted to make sure it is picked up by the GC.

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 5 above)
Comment (kittaakos) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: Why would this be an event handler?

File: packages/workspace/src/browser/browser-workspace-frontend-module.ts (hunk 6 above)
Comment (kittaakos) [reply packages/workspace/src/browser/browser-workspace-frontend-module.ts]: See `browser-menu-module.ts` and `electron-menu-module.ts`.

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 3 above)
Comment (hexa00) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: I would use
` const newWindow = new BrowserWindow({ width: 1024, height: 728, show: !!theURL });`

It's just that if(show) makes no sense with the newWIndow open below...  both are showing something... just not the same thing..

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 2 above)
Comment (kittaakos) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: Then let's go with this.

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 4 above)
Comment (hexa00) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: Is that really helpful ? I'm curious about this...

Comment (hexa00) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: Seems like it would work if you were setting the value that windowClose points to to null, but in this case it's just the value of windowToClose that is set to null thus it's the same as just losing the reference in the array

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 5 above)
Comment (hexa00) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: Oops I missed the }): before it hehe

File: packages/workspace/src/browser/browser-workspace-frontend-module.ts (hunk 6 above)
Comment (hexa00) [reply packages/workspace/src/browser/browser-workspace-frontend-module.ts]: seems like it's `browser-menu-module.ts`  and `electron-menu-module.ts` that are wrong ? everything else is browser/something-frontend-module ?

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 2 above)
Comment (hexa00) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: I don't want to nitpick but we should avoid adding side changes like that unless necessary otherwise one gets the impression that this change is needed for the fix the work.

Moreover it can introduce bugs as it changes previous behavior.

File: packages/workspace/src/browser/browser-workspace-frontend-module.ts (hunk 6 above)
Comment (kittaakos) [reply packages/workspace/src/browser/browser-workspace-frontend-module.ts]: Did not find another place where we have customized bindings for electron and browser. Please show another example.

Comment (hexa00) [reply packages/workspace/src/browser/browser-workspace-frontend-module.ts]: monaco is an example. `monaco-frontend-module` `monaco-electron-module` 

But see: https://github.com/theia-ide/theia/wiki/Code-Organization

`Within the top level folders, that indicate what the contained code is about, we separate between the following platforms:`

Why separate in the filename what we already did in the directory?

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 2 above)
Comment (kittaakos) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: Funny, that we do exactly the opposite with `LC_ALL` than recommended in the ticket from the comment above: https://github.com/electron/electron/issues/9225#issuecomment-300175705

Also, the bug was fixed in `1.6.6` we use `1.7.6`. Finally, someone also mentions, that it should happen very early in the `main.js`, so it is at the wrong place. If I am not deleting it, I will pull up, right above the imports.

Comment (kittaakos) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: I have moved it up.

**Comment by kittaakos** [comment]
@hexa00, thank you for the review. I have updated the PR based on your feedback.

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 2 above)
Comment (hexa00) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: Why not remove it if the bug was fixed in our version ?

File: packages/workspace/package.json [hunk 7]
```diff
@@ -4,14 +4,16 @@
   "description": "Theia - Workspace Extension",
   "dependencies": {
     "@theia/core": "^0.2.1",
-    "@theia/filesystem": "^0.2.1"
+    "@theia/filesystem": "^0.2.1",
+    "electron": "1.7.6"
```
Comment (akosyakov) [inline packages/workspace/package.json]: it should be already declared in @theia/core. Why declare again here?

File: dev-packages/application-package/src/generator/frontend-generator.ts [hunk 8]
```diff
@@ -75,60 +75,83 @@ module.exports = Promise.resolve()${this.compileFrontendModuleImports(frontendMo
 
     protected compileElectronMain(): string {
         return `// @ts-check
-const cluster = require('cluster');
-if (cluster.isMaster) {
-    // Workaround for https://github.com/electron/electron/issues/9225. Chrome has an issue where
-    // in certain locales (e.g. PL), image metrics are wrongly computed. We explicitly set the
-    // LC_NUMERIC to prevent this from happening (selects the numeric formatting category of the
-    // C locale, http://en.cppreference.com/w/cpp/locale/LC_categories).
-    if (process.env.LC_ALL) {
```
Comment (akosyakov) [inline dev-packages/application-package/src/generator/frontend-generator.ts]: is it not necessary anymore? how SVG look without it? I think we added trying to demo yangster on the external monitor. It was looking bad.

File: packages/workspace/src/browser/workspace-service.ts [hunk 9]
```diff
@@ -120,11 +122,11 @@ export class WorkspaceService implements FrontendApplicationContribution {
     }
 
     protected reloadWindow(): void {
-        window.location.reload();
+        this.windowHelper.reloadWindow(window);
```
Comment (akosyakov) [inline packages/workspace/src/browser/workspace-service.ts]: is it necessary? i found 2 other places in code, there `window.location.reload()` is called, both in `@theia/core`. To make it right, we need to move `WindowHelper` in core.

File: packages/workspace/src/browser/window-helper.ts [hunk 10]
```diff
@@ -0,0 +1,39 @@
...
+ * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
+ */
+
+import { injectable } from 'inversify';
+
+/**
+ * Helper for opening new browser windows and reloading the content of existing ones.
+ */
+export const WindowHelper = Symbol('WindowHelper');
+export interface WindowHelper {
```
Comment (akosyakov) [inline packages/workspace/src/browser/window-helper.ts]: Could it be named `WindowService`?
Or maybe it should be `WindowOpenHandler` that implements `OpenHandler` interface and open URIs with http(s) schemas? `helper` does not communicate responsibilities, only that there is a bunch of reusable functions.

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 2 above)
Comment (kittaakos) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: I left the workaround in the code. https://github.com/theia-ide/theia/pull/843/files#r151832774

**Comment by kittaakos** [comment]
The builds are green; I am merging the changes to the master. One remark on this: I have left the workaround for the electron SVG image rendering issue as is.
