### PR TITLE
[vscode] unzip node_modules for built-in extensions

### LINKED ISSUE #5756: vscode emmet extension does not work anymore
```
Uncaught Error: Cannot find module 'vscode-emmet-helper'

Error: Cannot find module 'vscode-emmet-helper'
    at Function.Module._resolveFilename (/internal/modules/cjs/loader.js:582)
    at Function.Module._load (/internal/modules/cjs/loader.js:508)
    at Function.module._load (/workspace/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js:98)
    at Module.require (/internal/modules/cjs/loader.js:637)
    at require (/internal/modules/cjs/helpers.js:22)
    at Object.<anonymous> (/tmp/vscode-unpacked/vscode-builtin-emmet-0.1.0.tgz/package/dist/extension.js:1)
    at n (/tmp/vscode-unpacked/vscode-builtin-emmet-0.1.0.tgz/package/dist/extension.js:1)
    at Object.t.getEmmetHelper (/tmp/vscode-unpacked/vscode-builtin-emmet-0.1.0.tgz/package/dist/extension.js:1)
    at t.DefaultCompletionItemProvider.provideCompletionItemsInternal (/tmp/vscode-unpacked/vscode-builtin-emmet-0.1.0.tgz/package/dist/extension.js:1)
    at t.DefaultCompletionItemProvider.provideCompletionItems (/tmp/vscode-unpacked/vscode-builtin-emmet-0.1.0.tgz/package/dist/extension.js:1)
    at /vs/editor/editor.main.js:12536
/vs/editor/editor.main.js:12536 Uncaught Error: a.updateExtensionsPath is not a function

TypeError: a.updateExtensionsPath is not a function
    at c (/tmp/vscode-unpacked/vscode-builtin-emmet-0.1.0.tgz/package/dist/extension.js:1)
    at Object.t.getEmmetHelper (/tmp/vscode-unpacked/vscode-builtin-emmet-0.1.0.tgz/package/dist/extension.js:1)
    at t.DefaultCompletionItemProvider.provideCompletionItemsInternal (/tmp/vscode-unpacked/vscode-builtin-emmet-0.1.0.tgz/package/dist/extension.js:1)
    at t.DefaultCompletionItemProvider.provideCompletionItems (/tmp/vscode-unpacked/vscode-builtin-emmet-0.1.0.tgz/package/dist/extension.js:1)
    at CompletionAdapter.provideCompletionItems (/workspace/theia/packages/plugin-ext/lib/plugin/languages/completion.js:36)
    at /workspace/theia/packages/plugin-ext/lib/plugin/languages.js:149
    at LanguagesExtImpl.withAdapter (/workspace/theia/packages/plugin-ext/lib/plugin/languages.js:121)
    at LanguagesExtImpl.$provideCompletionItems (/workspace/theia/packages/plugin-ext/lib/plugin/languages.js:149)
    at RPCProtocolImpl.doInvokeHandler (/workspace/theia/packages/plugin-ext/lib/api/rpc-protocol.js:207)
    at RPCProtocolImpl.invokeHandler (/workspace/theia/packages/plugin-ext/lib/api/rpc-protocol.js:192)
    at /vs/editor/editor.main.js:12536
```

In order to reproduce, install it from https://registry.npmjs.org/@theia/vscode-builtin-emmet/-/vscode-builtin-emmet-0.2.1.tgz

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

fix #5756: unzip node_modules for built-in extensions

#### How to test

- install latest emmet extension with https://registry.npmjs.org/@theia/vscode-builtin-emmet/-/vscode-builtin-emmet-0.2.1.tgz
- verify that emmet content assist is present in HTML files

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully reviewed following [the review guidelines](https://github.com/theia-ide/theia/blob/ak/pr_template/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/ak/pr_template/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/plugin-ext-vscode/src/node/plugin-vscode-file-handler.ts [hunk 1]
```diff
@@ -41,6 +42,13 @@ export class PluginVsCodeFileHandler implements PluginDeployerFileHandler {
 
         const unpackedPath = path.resolve(this.unpackedFolder, path.basename(context.pluginEntry().path()));
         await context.unzip(context.pluginEntry().path(), unpackedPath);
+        if (context.pluginEntry().path().endsWith('.tgz')) {
+            const extensionPath = path.join(unpackedPath, 'package');
+            const vscodeNodeModulesPath = path.join(extensionPath, 'vscode_node_modules.zip');
```
Comment (akosyakov) [inline packages/plugin-ext-vscode/src/node/plugin-vscode-file-handler.ts]: built-in extensions are already republished with zip for node modules: https://github.com/theia-ide/vscode-builtin-extensions/commit/51e5e2797a110bdfe663a820fef1546a215d6642#diff-1b65ea7e7a9dd6aa50436ecdd461f0aaR23

**Comment by benoitf** [comment]
hello, why published file is not a vsix file ?

**Comment by akosyakov** [comment]
> hello, why published file is not a vsix file ?

Because npm does not accept such formats? Or do you mean package everything into vsix then push it to npm and then unpackage twice in Theia first from npm than from vsix? We could it do like that as well if someone will do it today. I don't have time to look at it.

**Comment by AlexTugarev** [comment]
testing right now...

**Comment by benoitf** [comment]
@akosyakov yes I mean embedding the vsix file inside the tgz archive so at the end we just deploy vsix files, not a custom archive

**Comment by akosyakov** [comment]
@benoitf Would it be fine to file an issue for it for now? There are probably would be gotchas since VS Code team does not package these extensions, some attributes or files could be missing and so on.

**Comment by akosyakov** [comment]
If no one is going to propose a PR with an alternative approach, we are going to merge it tomorrow.

**Comment by benoitf** [comment]
I'm fine. Also maybe we should release these vsix on github release page instead of npmjs

**Comment by akosyakov** [comment]
@benoitf an issues is here: https://github.com/theia-ide/vscode-builtin-extensions/issues/5
