### PR TITLE
fix #3965: isolate plugin deployment and fix localization

### LINKED ISSUE #3965: Isolate loading and deployment of plugins
I'm trying to bundle builtin VS Code extensions: https://github.com/theia-ide/theia/issues/3956#issuecomment-451946193

Some of the extensions are mispackaged, or there are bugs in our code to parse manifest of certain extensions. Whenever the plugin system stumbles at such extension it throws and interrupts processing of consequent extensions.

Some call stacks which I get:
```
root ERROR Uncaught Exception:  SyntaxError: Unexpected token P in JSON at position 28873
root ERROR SyntaxError: Unexpected token P in JSON at position 28873
    at JSON.parse (<anonymous>)
    at HostedPluginReader.getPluginMetadata (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-reader.js:71:27)
    at /workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-service.js:119:47
    at Array.forEach (<anonymous>)
    at HostedPluginServerImpl.deployBackendPlugins (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-service.js:118:24)
    at PluginDeployerImpl.<anonymous> (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/main/node/plugin-deployer-impl.js:192:41)
    at step (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/main/node/plugin-deployer-impl.js:56:23)
    at Object.next (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/main/node/plugin-deployer-impl.js:37:53)
    at /workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/main/node/plugin-deployer-impl.js:31:71
    at new Promise (<anonymous>)
```
```
root ERROR [hosted-plugin: 9591] { Error: Cannot find module '/tmp/vscode-unpacked/configuration-editing-1.0.0.vsix/extension/out/extension'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.module._load (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:94:33)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.loadPlugin (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js:68:28)
    at PluginManagerExtImpl.$init (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:123:44)
    at RPCProtocolImpl.doInvokeHandler (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:173:23)
    at RPCProtocolImpl.invokeHandler (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:158:41)
    at RPCProtocolImpl.receiveRequest (/workspace/vscode-builtin-extensions/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:122:45) code: 'MODULE_NOT_FOUND' }
```

I'm going to look into fixing packaging of VS Code extensions and individual parsing issues. Someone else can look into adding  `try - catch` at cases where we loop over plugins.

### PR DESCRIPTION
**Pull request by akosyakov**
fix #3965:
- fix how localization is done to allow loading of `emmet` extension
- isolate loading of plugin metadata to prevent one bogus extension breaking other

Emmets in Theia:
emmet

:)

### CODE REVIEW

File: packages/plugin-ext/src/hosted/node/plugin-service.ts [hunk 1]
```diff
@@ -78,37 +75,32 @@ export class HostedPluginServerImpl implements HostedPluginServer {
...
-            const pluginMetadata = this.reader.getPluginMetadata(frontendPluginDeployerEntry.path());
-            if (pluginMetadata) {
-                this.currentFrontendPluginsMetadata.push(pluginMetadata);
-                this.logger.info('HostedPluginServerImpl/ asking to deploy the frontend Plugin', frontendPluginDeployerEntry.path(), 'and model is', pluginMetadata.model);
+    async deployFrontendPlugins(frontendPlugins: PluginDeployerEntry[]): Promise<void> {
+        for (const plugin of frontendPlugins) {
+            const metadata = await this.reader.getPluginMetadata(plugin.path());
+            if (metadata) {
+                this.currentFrontendPluginsMetadata.push(metadata);
+                console.info(`Deploying frontend plugin "${metadata.model.name}@${metadata.model.version}" from "${metadata.model.entryPoint.frontend || plugin.path()}"`);
```
Comment (benoitf) [inline packages/plugin-ext/src/hosted/node/plugin-service.ts]: why console instead of logger ?

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-service.ts]: We've started with `Logger` and fought to use a primary API, but then learned that we cannot force all 3rd party libraries to use `Logger`, so we hooked up `console` to use `Logger` always. You can use `Logger` but it is just more code.

Comment (benoitf) [reply packages/plugin-ext/src/hosted/node/plugin-service.ts]: pls keep logger, it's avoid to see if ppl miss to use console just for printing their debug output.

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-service.ts]: >  it's avoid to see if ppl miss to use console just for printing their debug output.

Don't we have code reviews to detect it?

Let's discuss it tomorrow at dev meeting. We have [coding rules](https://github.com/theia-ide/theia/wiki/Coding-Guidelines) for the project. It should be agreed by everybody to avoid arguing over them during PRs. If something is not there it's up to everybody.

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/plugin-service.ts]: I've touched all these lines anyway.

Comment (benoitf) [reply packages/plugin-ext/src/hosted/node/plugin-service.ts]: so, please avoid to do big changes, just the fix or separate commits

**Comment by akosyakov** [comment]
Does anybody test whether this PR fixes underlying issues?

**Comment by designerbase** [comment]
@akosyakov  i've added the emmet in my project. but throwing a console error.
Uncaught Error: Cannot read property 'items' of undefined

TypeError: Cannot read property 'items' of undefined
    at editor.main.js:2056
    at Object.g [as _notify] (editor.main.js:141)
    at Object.enter (editor.main.js:145)
    at n.Class.derive._creator._run (editor.main.js:146)
    at n.Class.derive._creator._completed (editor.main.js:146)
    at Object.g [as _notify] (editor.main.js:141)
    at Object.enter (editor.main.js:145)
    at n.Class.derive._oncancel._run (editor.main.js:146)
    at n.Class.derive._oncancel._completed (editor.main.js:146)
    at Object.g [as _notify] (editor.main.js:141)
    at editor.main.js:158



here is my package.json
{
    "private": true,
    "dependencies": {
        "@theia/plugin-ext-vscode": "next",
        "@theia/preview": "next",
        "typescript": "latest",
        "@theia/core": "next",
        "@theia/editor": "next",
        "@theia/editorconfig": "next",
        "@theia/file-search": "next",
        "@theia/filesystem": "next",
        "@theia/git": "next",
        "@theia/json": "next",
        "@theia/keymaps": "next",
        "@theia/languages": "next",
        "@theia/markers": "next",
        "@theia/merge-conflicts": "next",
        "@theia/messages": "next",
        "@theia/mini-browser": "next",
        "@theia/monaco": "next",
        "@theia/navigator": "next",
        "@theia/outline-view": "next",
        "@theia/php": "next",
        "@theia/output": "next",
        "@theia/preferences": "next",
        "@theia/process": "next",
        "@theia/search-in-workspace": "next",
        "@theia/task": "next",
        "@theia/terminal": "next",
        "@theia/textmate-grammars": "next",
        "@theia/tslint": "next",
        "@theia/typescript": "next",
        "@theia/userstorage": "next",
        "@theia/workspace": "next"
    },
    "resolutions": {
        "onigasm": "2.2.1"
    },
    "devDependencies": {
        "@theia/cli": "next"
    },
     "scripts": {
        "postinstall": "download-debug-adapters"
    },
    "adapterDir": "plugins",
    "adapters": {
        "vscode-go": "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/Go/0.9.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"
    }
}


here is my dockerfile

FROM node:8-jessie-slim

ENV TZ=Europe/Bratislava
ENV UID=10000
ENV GID=1002

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt-get update && apt-get -y --no-install-recommends install sudo curl xz-utils wget git python build-essential \
    && apt install -y --no-install-recommends ca-certificates apt-transport-https \
    && wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add - \
    && echo "deb https://packages.sury.org/php/ jessie main" | tee /etc/apt/sources.list.d/php.list \
    && apt update \
    && apt install -y --no-install-recommends php7.2 \
    && apt install -y --no-install-recommends php7.2-cli php7.2-curl php7.2-json php7.2-mbstring \
    && curl -s -o composer-setup.php https://getcomposer.org/installer \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php \
    && rm -rf /var/lib/apt/lists/*

RUN addgroup --gid $GID theia \
    && adduser --disabled-password --gecos '' --uid $UID --gid $GID theia \
    && adduser theia sudo \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
    && chmod g+rw /home \
    && mkdir -p /home/project \
    && chown -R theia:theia /home/theia \
    && chown -R theia:theia /home/project

ENV THEIA_DEFAULT_PLUGINS=local-dir:/home/theia/plugins

USER theia

WORKDIR /home/theia
ADD package.json ./package.json

RUN yarn --cache-folder ./ycache \
    && rm -rf ./ycache \
    && NODE_OPTIONS="--max_old_space_size=4096" yarn theia build

EXPOSE 3000
ENV SHELL /bin/bash

ENTRYPOINT [ "yarn", "theia", "start", "/home/project", "--hostname=0.0.0.0" ]

let me know what the wrong with my configuration

thanks

**Comment by akosyakov** [comment]
See the discussion here:  https://spectrum.chat/theia/theiadevcon/emmet-extension-not-wokring~cb5f1b8f-20c3-4dbe-a21b-3bbe499cb5b7?m=MTU1OTgxMzI4NTQ4OQ==
