### PR TITLE
GH-5706: DIsposed the clipboard copy listener.

### LINKED ISSUE #5706: Copy and Paste is Break by #5466
### Description
@kittaakos @akosyakov 
Copy Download Link Break `Ctrl + C` on edit by #5466
temp

### Reproduction Steps
look gif

**OS and Theia version:**
latest next version

**Diagnostics:**

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #5706.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

Related: #5708.

### CODE REVIEW

File: packages/filesystem/src/browser/download/file-download-service.ts [hunk 1]
```diff
@@ -78,8 +79,15 @@ export class FileDownloadService {
...
                 const downloadUrl = `${this.endpoint()}/download/?id=${jsonResponse.id}`;
                 if (copyLink) {
+                    let disposable: Disposable | undefined = undefined;
                     if (document.documentElement) {
-                        addClipboardListener(document.documentElement, 'copy', e => this.handleCopy(e, downloadUrl));
+                        try {
+                            disposable = addClipboardListener(document.documentElement, 'copy', e => this.handleCopy(e, downloadUrl));
+                        } finally {
+                            if (disposable) {
+                                disposable.dispose();
```
Comment (akosyakov) [inline packages/filesystem/src/browser/download/file-download-service.ts]: it should be disposed within event handler before calling `this.handleCopy`.

File: packages/filesystem/src/browser/download/file-download-service.ts [hunk 2]
```diff
@@ -78,8 +79,15 @@ export class FileDownloadService {
                 progress.cancel();
                 const downloadUrl = `${this.endpoint()}/download/?id=${jsonResponse.id}`;
                 if (copyLink) {
+                    let disposable: Disposable | undefined = undefined;
                     if (document.documentElement) {
-                        addClipboardListener(document.documentElement, 'copy', e => this.handleCopy(e, downloadUrl));
+                        try {
+                            disposable = addClipboardListener(document.documentElement, 'copy', e => this.handleCopy(e, downloadUrl));
```
Comment (akosyakov) [inline packages/filesystem/src/browser/download/file-download-service.ts]:
```ts
 const toDispose = addClipboardListener(document.documentElement, 'copy', e => {
                            toDispose.dispose();
                            this.handleCopy(e, downloadUrl);
                        });
```

File: packages/filesystem/src/browser/download/file-download-service.ts (hunk 1 above)
Comment (kittaakos) [reply packages/filesystem/src/browser/download/file-download-service.ts]: Can you explain why?

File: packages/filesystem/src/browser/download/file-download-service.ts [hunk 3]
```diff
@@ -22,6 +22,7 @@ import { FileSystem } from '../../common/filesystem';
 import { FileDownloadData } from '../../common/download/file-download-data';
 import { MessageService } from '@theia/core/lib/common/message-service';
 import { addClipboardListener } from '@theia/core/lib/browser/widgets';
+import { Disposable } from '@theia/core/src/common/disposable';
```
Comment (akosyakov) [inline packages/filesystem/src/browser/download/file-download-service.ts]: /lib/

File: packages/filesystem/src/browser/download/file-download-service.ts (hunk 1 above)
Comment (akosyakov) [reply packages/filesystem/src/browser/download/file-download-service.ts]: because we want to wait till `copy` event is fired and remove a listener only after it? I don't understand how current change ensures it.

We use the same pattern in other places as well: https://github.com/theia-ide/theia/blob/60dcb3326ea5e70c8d1017dcd206013304a5c92e/packages/markers/src/browser/problem/problem-contribution.ts#L158-L168

**Comment by kittaakos** [comment]
I am OK merging this, but then the [static download link](https://github.com/theia-ide/theia/issues/5707) is gone.

**Comment by akosyakov** [comment]
@kittaakos let's merge it and deal with https://github.com/theia-ide/theia/issues/5707 separately?
