### PR TITLE
fix #2987: close a ws channel if a jsonrpc connection is disposed

### LINKED ISSUE #2987: Language client restart does not work
I rebased #2907 on current master, and I can't get my language server to be restarted.

The first time the `BaseLanguageClientContribution.restart()` method is called, the value of `this.toRestart` is not undefined, so something seems to happen.  But in the subsequent calls, `this.toRestart` is always undefined, which makes the call to `.restart()` a no-op.

### PR DESCRIPTION
**Pull request by akosyakov**

### CODE REVIEW

File: dev-packages/application-manager/src/application-process.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ import { ApplicationPackage } from '@theia/application-package';
 
 export class ApplicationProcess {
 
-    protected readonly defaultOptions = {
+    protected readonly defaultOptions =
```
Comment (AlexTugarev) [inline dev-packages/application-manager/src/application-process.ts]: typo?

**Comment by AlexTugarev** [comment]
Testing right now...

**Comment by AlexTugarev** [comment]
verified that the ts server is restarted properly and language support is ready to use again afterwards.

screen shot 2018-09-27 at 11 30 00

**Comment by AlexTugarev** [comment]
just one thing, and maybe you recall a discussion on that, when restarting the ts server very shortly after opening of a file in editor, I see errors about code action logged:

```
Uncaught Error: Language client is not ready yet

Error: Language client is not ready yet
    at MonacoLanguageClient.push.../../node_modules/vscode-base-languageclient/lib/client.js.BaseLanguageClient.sendRequest (/10.bundle.js:4930)
    at provideCodeActions (/10.bundle.js:4317)
    at Object.provideCodeActions (/10.bundle.js:4353)
    at Object.provideCodeActions (/10.bundle.js:2620)
    at Object.provideCodeActions (/10.bundle.js:1721)
    at Object.provideCodeActions (/vs/editor/editor.main.js:112152)
    at /vs/editor/editor.main.js:79102
    at /vs/editor/editor.main.js:14253
    at new Promise_ctor (/vs/editor/editor.main.js:11502)
    at Object.asWinJsPromise (/vs/editor/editor.main.js:14252)
    at MonacoLanguageClient.push.../../node_modules/vscode-base-languageclient/lib/client.js.BaseLanguageClient.sendRequest (/10.bundle.js:4930)
    at provideCodeActions (/10.bundle.js:4317)
    at Object.provideCodeActions (/10.bundle.js:4353)
    at Object.provideCodeActions (/10.bundle.js:2620)
    at Object.provideCodeActions (/10.bundle.js:1721)
    at Object.provideCodeActions (/vs/editor/editor.main.js:112152)
    at /vs/editor/editor.main.js:79102
    at /vs/editor/editor.main.js:14253
    at new Promise_ctor (/vs/editor/editor.main.js:11502)
    at Object.asWinJsPromise (/vs/editor/editor.main.js:14252)
    at /vs/editor/editor.main.js:12536
```

It's not directly related to this PR, but now I know how to reproduce this.
