### PR TITLE
GH-4395: Made the Git env variable validation less aggressive

### LINKED ISSUE #4395: [ci][git][travis] Browser tests fail on Linux
see 

```
@theia/example-browser: [chrome #0-4] 6 failing
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 1) terminal UI should open a new terminal and then close it:
@theia/example-browser: [chrome #0-4] unknown error: Element <div class="p-MenuBar-itemLabel">...</div> is not clickable at point (357, 14). Other element would receive the click: <p id="notification-text-3-...-|">Could not find Git on the PATH.</p>
@theia/example-browser: [chrome #0-4] Error: An unknown server-side error occurred while processing the command.
@theia/example-browser: [chrome #0-4]     at elementIdClick("0.5138757508818415-9") - click.js:20:22
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 2) call hierarchy view UI call hierarchy view should toggle-on then toggle-off:
@theia/example-browser: [chrome #0-4] unknown error: Element <div class="p-MenuBar-itemLabel">...</div> is not clickable at point (208, 14). Other element would receive the click: <div class="text">...</div>
@theia/example-browser: [chrome #0-4] Error: An unknown server-side error occurred while processing the command.
@theia/example-browser: [chrome #0-4]     at elementIdClick("0.5138757508818415-10") - click.js:20:22
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 3) extensions view UI extensions view should toggle-on then toggle-off:
@theia/example-browser: [chrome #0-4] unknown error: Element <div class="p-MenuBar-itemLabel">...</div> is not clickable at point (208, 14). Other element would receive the click: <div class="text">...</div>
@theia/example-browser: [chrome #0-4] Error: An unknown server-side error occurred while processing the command.
@theia/example-browser: [chrome #0-4]     at elementIdClick("0.5138757508818415-10") - click.js:20:22
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 4) files view UI files view should toggle-on then toggle-off:
@theia/example-browser: [chrome #0-4] unknown error: Element <div class="p-MenuBar-itemLabel">...</div> is not clickable at point (208, 14). Other element would receive the click: <div class="text">...</div>
@theia/example-browser: [chrome #0-4] Error: An unknown server-side error occurred while processing the command.
@theia/example-browser: [chrome #0-4]     at elementIdClick("0.5138757508818415-10") - click.js:20:22
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 5) git view UI git view should toggle-on then toggle-off:
@theia/example-browser: [chrome #0-4] unknown error: Element <div class="p-MenuBar-itemLabel">...</div> is not clickable at point (208, 14). Other element would receive the click: <div class="text">...</div>
@theia/example-browser: [chrome #0-4] Error: An unknown server-side error occurred while processing the command.
@theia/example-browser: [chrome #0-4]     at elementIdClick("0.5138757508818415-10") - click.js:20:22
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 6) search view UI should start with search view visible:
@theia/example-browser: [chrome #0-4] expected false to be true
@theia/example-browser: [chrome #0-4] AssertionError: expected false to be true
@theia/example-browser: [chrome #0-4]     at Context.<anonymous> (/home/travis/build/theia-ide/theia/examples/browser/lib/test/top-panel/top-panel.ui-spec.js:223:65)
@theia/example-browser: [chrome #0-4]     at new Promise (<anonymous>)
@theia/example-browser: [chrome #0-4]     at new F (/home/travis/build/theia-ide/theia/node_modules/core-js/library/modules/_export.js:36:28)
```

from https://api.travis-ci.org/v3/job/496059660/log.txt

it looks like git is not found on the PATH. `git version 2.15.1` should be available, according to system info from logs.

### PR DESCRIPTION
**Pull request by kittaakos**
This is an interim solution.

Rules:
 - Fails when the env variable was set, and we try to set another value.
 - Passes when the env variable was set, and we try to re-set the same.

Managing the external Git location via env vars is getting complicated:
 - `dugite` manages the non-embedded Git locations with env variables.
 - We have switched to connection scope DI-bindings for `DugiteGit`.

Closes #4395.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

----

This PR also contains the revert changes of #4371.
Q: OK, but why?
A: Travis does not set the default Git `protocol.version` to `2` anymore. And [this comment](
https://github.com/theia-ide/theia/issues/4395#issuecomment-465977089) mentions the non-zero exit code as part of #4395.

See: https://travis-ci.community/t/got-to-fail-carthage-outdated-command-because-of-git-protocol-version/2359/

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@kittaakos the errors still occur :(

**Comment by kittaakos** [comment]
> the errors still occur :(

Yeah, I have seen it. I was too naive; I am working on a more robust, temporary solution.

**Comment by kittaakos** [comment]
Here is the follow-up: https://github.com/theia-ide/theia/issues/4401

**Comment by vince-fugnitto** [comment]
Builds now pass :smile: ! 
I'll wait for the review of @AlexTugarev as it seems like a more complex `git` chnage than originally thought.

File: packages/git/src/node/init/git-init.ts [hunk 1]
```diff
@@ -53,27 +53,31 @@ export class DefaultGitInit implements GitInit {
...
+                // Instead of the executable path, we need the root directory of Git.
+                const dir = dirname(dirname(path));
+                const [execPathOk, pathOk, dirOk] = await Promise.all([pathExists(execPath), pathExists(path), pathExists(dir)]);
+                if (execPathOk && pathOk && dirOk) {
+                    if (typeof env.LOCAL_GIT_DIRECTORY !== 'undefined' && env.LOCAL_GIT_DIRECTORY !== dir) {
+                        this.logger.error(`Misconfigured env.LOCAL_GIT_DIRECTORY: ${env.LOCAL_GIT_DIRECTORY}. dir was: ${dir}`);
+                        await this.handleExternalNotFound('The LOCAL_GIT_DIRECTORY env variable was already set to a different value.');
                     }
+                    if (typeof env.GIT_EXEC_PATH !== 'undefined' && env.GIT_EXEC_PATH !== execPath) {
+                        this.logger.error(`Misconfigured env.GIT_EXEC_PATH: ${env.GIT_EXEC_PATH}. execPath was: ${execPath}`);
```
Comment (AlexTugarev) [inline packages/git/src/node/init/git-init.ts]: isn't it more of a warning that the configured `GIT_EXEC_PATH` will be ignored as `git` was found on the `PATH`?

File: packages/git/src/node/init/git-init.ts [hunk 2]
```diff
@@ -53,27 +53,31 @@ export class DefaultGitInit implements GitInit {
...
+                        await this.handleExternalNotFound('The GIT_EXEC_PATH env variable was already set to a different value.');
```
Comment (AlexTugarev) [inline packages/git/src/node/init/git-init.ts]: `Could not find Git on the PATH.` will be shown to the user, but in that case `git` was found.

Comment (AlexTugarev) [reply packages/git/src/node/init/git-init.ts]: also, could you please set a timeout for the `info` notification? or maybe `{ timeout: 0 }` to not dismiss automatically, WDYT? it's shown only 5s (?) by default, so if one doesn't pay attention...

File: packages/git/src/node/init/git-init.ts (hunk 1 above)
Comment (AlexTugarev) [reply packages/git/src/node/init/git-init.ts]: > Fails when the env variable was set, and we try to set another value.

Maybe I'm just confused. Should it fail or just yell?

File: packages/git/src/node/init/git-init.ts (hunk 2 above)
Comment (kittaakos) [reply packages/git/src/node/init/git-init.ts]: Yes to both 👍

File: packages/git/src/node/init/git-init.ts (hunk 1 above)
Comment (kittaakos) [reply packages/git/src/node/init/git-init.ts]: > `GIT_EXEC_PATH` will be ignored as `git` was found on the `PATH`?

`GIT_EXEC_PATH` is a different thing:
```
which git && `which git` --exec-path
/usr/local/bin/git
/usr/local/Cellar/git/2.20.1/libexec/git-core
```

Comment (kittaakos) [reply packages/git/src/node/init/git-init.ts]: > yell
