### PR TITLE
GH-2178: Update the global selection with the tree selection on activate

### LINKED ISSUE #2178: [navigator/git] Wrong context menu for selection
The context menu of files in navigator is confused after opening a change in diff editor from git widget.

1. open a change in diff editor from git widget
2. switch to `Files` navigator
3. call context menu; for a markdown file `Code Editor` is shown, but not `Preview`

This GIF shows it:

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #2178.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

File: packages/core/src/browser/tree/tree-widget.tsx [hunk 1]
```diff
@@ -201,6 +201,13 @@ export class TreeWidget extends ReactWidget implements StatefulWidget {
                     this.model.selectNode(firstChild);
                 }
             }
+        } else {
+            // On activate we have to "re-select" the nodes even if they were already selected.
+            // This is required because when toggling the side-bars (e.g. `Files`), we want to
+            // propagate the selection change to the global `SelectionService` by broadcasting
+            // the most recent tree selection state.
+            // https://github.com/theia-ide/theia/issues/2178
+            this.model.reconcileSelectionState();
```
Comment (akosyakov) [inline packages/core/src/browser/tree/tree-widget.tsx]: Why not override `onActivateRequest` in `FileNavigatorWidget` and set explicitly the global selection as for the editor widget: https://github.com/theia-ide/theia/blob/79f56f142956c7fbdf378b993bf49d24db27b935/packages/editor/src/browser/editor-widget.ts#L45-L49

Is it supposed to fix generically something else?

**Comment by AlexTugarev** [comment]
@kittaakos, @akosyakov, [FileNavigatorWidget.onActivateRequest](https://github.com/theia-ide/theia/pull/2545/files#diff-ac5113726f1b8d5d64fc9e3cf58e7e1aR99) seems to improve this significantly. I'd happy have this merged.

Knowing this implementation detail, there are other open cases:
