### PR TITLE
fix: [Plugin-API] complete QuickPick hide api

### LINKED ISSUE #5765: [vscode] window.createQuickPick hide is incomplete
### Description

See https://code.visualstudio.com/api/references/vscode-api#QuickPick. QuickPick Panel should hide UI when execute `hide` method. But theia only emit `onDidHide` event.

### PR DESCRIPTION
**Pull request by hacke2**
Fixes #5765 

#### What it does

See https://code.visualstudio.com/api/references/vscode-api#QuickPick. 
>Hides this input UI. This will also fire an QuickInput.onDidHide event.

when execute `hide` method, vscode will:

- Hide UI
- Emit onDidHide event

But theia only emit onDidHide event.

#### How to test

```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
  const disposable = vscode.commands.registerCommand('hide QuickPick after 2000ms', () => {
    const quickOpen = vscode.window.createQuickPick();

    quickOpen.items = [
      { label: 'A' }, {label: 'B'}
    ];

    quickOpen.show();

    setTimeout(() => {
       quickOpen.hide();
     }, 2000);
  });

  context.subscriptions.push(disposable);
}

```

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully reviewed following [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to review in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@hacke2 please follow https://github.com/theia-ide/theia/blob/ak/pr_template/doc/pull-requests.md#review-reqs

**Comment by hacke2** [comment]
@akosyakov I don't know how to test plugin in theia but I'm sure it's effective in monaco 0.14.

**Comment by kittaakos** [comment]
> how to test plugin in theia

@hacke2, here is a Wiki page describing how to test it: https://github.com/theia-ide/theia/wiki/Testing-VS-Code-Extensions
If you have any feedback on the docs, let us know. I'll make the adjustments.

**Comment by hacke2** [comment]
@akosyakov @kittaakos I've tested it. No problem.

What should I do next?

**Comment by akosyakov** [comment]
@hacke2 wait, someone has to verify it independently

File: packages/core/src/common/quick-pick-service.ts [hunk 1]
```diff
@@ -14,6 +14,8 @@
  * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
  ********************************************************************************/
 
+import { HideReason } from '../browser';
```
Comment (kittaakos) [inline packages/core/src/common/quick-pick-service.ts]: This is incorrect; you should not use anything from `browser` in `common.`

File: packages/monaco/src/browser/monaco-quick-open-service.ts [hunk 2]
```diff
@@ -71,6 +71,13 @@ export class MonacoQuickOpenService extends QuickOpenService {
         this.internalOpen(new MonacoQuickOpenControllerOptsImpl(model, this.keybindingRegistry, options));
     }
 
+    hide(reason?: HideReason): void {
+        const hideReason = reason === HideReason.ELEMENT_SELECTED ? monaco.quickOpen.HideReason.ELEMENT_SELECTED :
```
Comment (kittaakos) [inline packages/monaco/src/browser/monaco-quick-open-service.ts]: For the sake of readability, please use a switch-case and make sure it will have a return value of `never` in the `default` case. So whenever the monaco enums get updated, we will have a compiler error, instead of silently returning with `CANCELED`. Thanks!

Comment (marechal-p) [reply packages/monaco/src/browser/monaco-quick-open-service.ts]: > [...] a return value of `never` in the `default` case.

Does that means actually throwing an error in the default case?

File: packages/core/src/common/quick-pick-service.ts (hunk 1 above)
Comment (hacke2) [reply packages/core/src/common/quick-pick-service.ts]: Could I move it in packages/core/src/common/quick-pick-service.ts ?

File: packages/monaco/src/browser/monaco-quick-open-service.ts (hunk 2 above)
Comment (hacke2) [reply packages/monaco/src/browser/monaco-quick-open-service.ts]: Could I return `undefined` in `default` case?

```typescript
let hideReason: monaco.quickOpen.HideReason | undefined;
switch (reason) {
  case HideReason.ELEMENT_SELECTED:
    hideReason = monaco.quickOpen.HideReason.ELEMENT_SELECTED;
    break;
 case HideReason.FOCUS_LOST:
    hideReason = monaco.quickOpen.HideReason.FOCUS_LOST;
    break;
  case HideReason.CANCELED:
    hideReason = monaco.quickOpen.HideReason.CANCELED;
    break;
}
this.widget.hide(hideReason);
````

File: packages/core/src/common/quick-pick-service.ts (hunk 1 above)
Comment (kittaakos) [reply packages/core/src/common/quick-pick-service.ts]: 👍

File: packages/monaco/src/browser/monaco-quick-open-service.ts (hunk 2 above)
Comment (kittaakos) [reply packages/monaco/src/browser/monaco-quick-open-service.ts]: OK.

File: packages/core/src/common/quick-pick-service.ts (hunk 1 above)
Comment (hacke2) [reply packages/core/src/common/quick-pick-service.ts]: Done.

File: packages/monaco/src/browser/monaco-quick-open-service.ts (hunk 2 above)
Comment (hacke2) [reply packages/monaco/src/browser/monaco-quick-open-service.ts]: Done.

**Comment by kittaakos** [comment]
@hacke2, please squash your commits, and I do the review. Thanks!

**Comment by hacke2** [comment]
@kittaakos Done.

**Comment by hacke2** [comment]
hide

Add a Gif

**Comment by kittaakos** [comment]
@hacke2, can you share the `package.json` of your extension? I am trying to follow the steps defined [here](https://github.com/theia-ide/theia/wiki/Testing-VS-Code-Extensions) to verify your changes. Thanks!

**Comment by kittaakos** [comment]
> can you share the `package.json` of your extension?

Never mind. I added your example: https://github.com/kittaakos/vscode-extension-samples/commit/7f1230c616ef7faeee8f38ece1d78e992a553891

**Comment by kittaakos** [comment]
I have verified it. Without the changes, the _Command Palette_ does not close automatically after the 2000 ms timeout, it works with the changes. 👍

I am OK with the Theia related modifications, @benoitf  are you OK with the plugin API?

**Comment by JPinkney** [comment]
If its possible can we try to get this merged asap, I'm currently working on fixes for https://github.com/theia-ide/theia/pull/5187. In order to fix up the comments I have to go back and re-do the way the createQuickPick API works and it would be easier to build ontop of this if its expected to go through

**Comment by kittaakos** [comment]
@JPinkney, sure. Please find someone who approves the plugin API, and we can merge.

File: packages/core/src/common/quick-pick-service.ts [hunk 3]
```diff
@@ -54,4 +54,12 @@ export interface QuickPickService {
 
     show<T>(elements: QuickPickItem<T>[], options?: QuickPickOptions): Promise<T | undefined>;
 
+    hide(reason?: HideReason): void
+
+}
+
+export enum HideReason {
```
Comment (akosyakov) [inline packages/core/src/common/quick-pick-service.ts]: please give more specific naming, see https://github.com/theia-ide/theia/wiki/Coding-Guidelines#unique-names

i.e. `QuickPickHideReason`

File: packages/core/src/browser/quick-open/quick-open-service.ts [hunk 4]
```diff
@@ -17,6 +17,7 @@
 import { injectable } from 'inversify';
 import { QuickOpenModel } from './quick-open-model';
 import { MessageType } from '../../common/message-service-protocol';
+import { HideReason } from '../../common/quick-pick-service';
```
Comment (akosyakov) [inline packages/core/src/browser/quick-open/quick-open-service.ts]: `QuickOpenService` cannot use own clients, it introduce a cyclic dependency

Comment (akosyakov) [reply packages/core/src/browser/quick-open/quick-open-service.ts]: You can move `HideReason` to this file instead and rename to `QuickOpenHideReason`.

Comment (hacke2) [reply packages/core/src/browser/quick-open/quick-open-service.ts]: Sorry I don't understand. Why introduces a cyclic dependency? common/quick-pick-service was not require `quick-open-service.ts `

Comment (hacke2) [reply packages/core/src/browser/quick-open/quick-open-service.ts]: @akosyakov If I move `HideReason`  to this file instead and rename to `QuickOpenHideReason`. It will throw warning `Argument of type 'QuickPickHideReason | undefined' is not assignable to parameter of type 'QuickOpenHideReason | undefined'.` when quickpick invoke quickopen.

Comment (akosyakov) [reply packages/core/src/browser/quick-open/quick-open-service.ts]: conceptually, quick-pick is a specialization of quick-open, dependencies should be in one direction

either `hide` method should go to quick-pick, or a hide reason should go to quick-open

File: packages/monaco/src/browser/monaco-quick-open-service.ts [hunk 5]
```diff
@@ -24,6 +24,7 @@ import {
 import { KEY_CODE_MAP } from './monaco-keycode-map';
 import { ContextKey } from '@theia/core/lib/browser/context-key-service';
 import { MonacoContextKeyService } from './monaco-context-key-service';
+import { HideReason } from '@theia/core/lib/common/quick-pick-service';
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-quick-open-service.ts]: it cannot depend on quick-pick, it implementation of quick-open

File: packages/core/src/browser/quick-open/quick-open-service.ts (hunk 4 above)
Comment (hacke2) [reply packages/core/src/browser/quick-open/quick-open-service.ts]: I think `QuickOpenHideReason` is OK，but `quickopen` is browser module, `packages/core/src/common/quick-pick-service.ts` can't require broswer.

Comment (akosyakov) [reply packages/core/src/browser/quick-open/quick-open-service.ts]: We should move `quick-open` to common as well to be able to call it from the backend. For now we could just reference and add FIXME comment above import.

Comment (hacke2) [reply packages/core/src/browser/quick-open/quick-open-service.ts]: https://github.com/theia-ide/theia/issues/5797

Comment (akosyakov) [reply packages/core/src/browser/quick-open/quick-open-service.ts]: ok, could you update as mentioned here: https://github.com/theia-ide/theia/pull/5766/files#r306687286 and then we merge

Comment (hacke2) [reply packages/core/src/browser/quick-open/quick-open-service.ts]: Done.
