### PR TITLE
GH-2278: Fixed the commit message resizing issue.

### LINKED ISSUE #2278: [git] Commit message textArea does not resize correctly on browser refresh
Steps to reproduce:
 - Add a commit message: `a\n\b\nc`.
 - Activate `Files`.
 - Set the focus on an editor.
 - Refresh the browser.

This does not happen when the `Git` is active and then the user refreshes the browser.

Also: we must not restore the validation error/warnings when the commit message `textArea` is empty. Otherwise, the following happens.

 - Active the `Git` widget.
 - Press `Commit`.
 - Got the error which is expected.
 - Refresh the browser.
 - The error is still there, it should not be.

### PR DESCRIPTION
**Pull request by kittaakos**
We were unable to acquire the `textArea` height when it was not visible.

 - Also fixed the scroll-bar `overflow` issue.
 - Avoid restoring the validation message if the `textArea` is empty.

Closes #2278

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

File: packages/git/src/browser/git-widget.tsx [hunk 1]
```diff
@@ -120,8 +120,7 @@ export class GitWidget extends ReactWidget implements StatefulWidget {
     }
 
     storeState(): object {
-        const commitTextArea = document.getElementById(GitWidget.Styles.COMMIT_MESSAGE) as HTMLTextAreaElement;
-        const messageBoxHeight = commitTextArea ? commitTextArea.offsetHeight : GitWidget.MESSAGE_BOX_MIN_HEIGHT;
+        const messageBoxHeight = this.messageBoxHeight ? this.messageBoxHeight : GitWidget.MESSAGE_BOX_MIN_HEIGHT;
```
Comment (kittaakos) [inline packages/git/src/browser/git-widget.tsx]: This could be:
```ts
const messageBoxHeight = this.messageBoxHeight || GitWidget.MESSAGE_BOX_MIN_HEIGHT;
```

File: packages/git/src/browser/git-widget.tsx [hunk 2]
```diff
@@ -287,6 +287,16 @@ export class GitWidget extends ReactWidget implements StatefulWidget {
                 textArea.style.height = `${(textArea.scrollHeight * 2 - textArea.clientHeight)}px`;
             }
         }
+        const updatedHeight = textArea.style.height;
+        if (updatedHeight) {
+            this.messageBoxHeight = parseInt(updatedHeight, 10) || GitWidget.MESSAGE_BOX_MIN_HEIGHT;
+            if (this.messageBoxHeight > GitWidget.MESSAGE_BOX_MIN_HEIGHT) {
```
Comment (kittaakos) [inline packages/git/src/browser/git-widget.tsx]:
```ts
// Hide the scroll-bar if we shrink down the size.
const overflow = this.messageBoxHeight > GitWidget.MESSAGE_BOX_MIN_HEIGHT ? 'auto' : 'hidden';
textArea.style.overflow = overflow;
```

File: packages/git/src/browser/git-widget.tsx (hunk 1 above)
Comment (AlexTugarev) [reply packages/git/src/browser/git-widget.tsx]: yes. it's even true for height of `0`
