### PR TITLE
[plug-in] ensure uniqueness of status bar entries

### LINKED ISSUE #4027: [plug-in] Progress bar doesn't work correctly with plugins
Status bar has many instances of progress bar when vscode-java extension was ran as a plugin: 
screenshot-localhost-3000-2019 01 11-14-29-25

And many console errors like:
```
root ERROR Warning: Encountered two children with the same key, `Building workspace - 0%null1null`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

### LINKED ISSUE #4032: [plugin/status-bar] root ERROR Warning: Encountered two children with the same key
See tons of while using `debug-auto-launch` VS Code extension for status bar items registered via the plugin system.
```
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div
root ERROR Warning: Encountered two children with the same key, `Automatically attach to node.js processes in debug mode0extension.node-debug.toggleAutoAttach`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

### PR DESCRIPTION
**Pull request by akosyakov**
fix #4032, fix #4027

here `messageid` provided asynchronously:
https://github.com/theia-ide/theia/blob/603fe22b3b7e4a941775b97dba5528358a3fc8d2/packages/plugin-ext/src/plugin/status-bar/status-bar-item.ts#L108-L129

If second update happens (in another tick), before the previous is resolved then a new entry is created without removing previous. PR makes sure that ID is generated synchronously.

### CODE REVIEW

**Comment by akosyakov** [comment]
@svor Could you test please with java extension 0.36.0?

File: packages/plugin-ext/src/main/browser/status-bar-message-registry-main.ts [hunk 1]
```diff
@@ -13,13 +13,11 @@
  *
  * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
  ********************************************************************************/
-import {interfaces} from 'inversify';
+import { interfaces } from 'inversify';
```
Comment (benoitf) [inline packages/plugin-ext/src/main/browser/status-bar-message-registry-main.ts]: could we avoid all code style changes ?

File: packages/plugin-ext/src/api/plugin-api.ts [hunk 2]
```diff
@@ -257,14 +257,15 @@ export interface MessageRegistryMain {
 }
 
 export interface StatusBarMessageRegistryMain {
-    $setMessage(text: string | undefined,
+    $setElement(id: string,
```
Comment (benoitf) [inline packages/plugin-ext/src/api/plugin-api.ts]: why rename it as part of this issue ?

File: packages/plugin-ext/src/main/browser/status-bar-message-registry-main.ts [hunk 3]
```diff
@@ -46,31 +44,23 @@ export class StatusBarMessageRegistryMainImpl implements StatusBarMessageRegistr
         };
 
         this.entries.set(id, entry);
-        return this.delegate.setElement(id, entry).then(() => Promise.resolve(id));
+        await this.delegate.setElement(id, entry);
     }
 
-    $update(id: string, message: string): void {
+    $update(id: string, text: string): void {
```
Comment (benoitf) [inline packages/plugin-ext/src/main/browser/status-bar-message-registry-main.ts]: could you please avoid to rename the fields everywhere, very hard to review 
it seems you only add an await

File: packages/plugin-ext/src/plugin/status-bar/status-bar-item.ts [hunk 4]
```diff
@@ -140,4 +133,8 @@ export class StatusBarItemImpl implements theia.StatusBarItem {
     public dispose(): void {
         this.hide();
     }
+
+    static nextId(): string {
+        return 'plugin-status-bar-item:' + UUID.uuid4();
```
Comment (benoitf) [inline packages/plugin-ext/src/plugin/status-bar/status-bar-item.ts]: please keep the constant variable
const STATUS_BAR_MESSAGE_PRE = 'status-bar-entry';

File: packages/plugin-ext/src/main/browser/status-bar-message-registry-main.ts (hunk 1 above)
Comment (akosyakov) [reply packages/plugin-ext/src/main/browser/status-bar-message-registry-main.ts]: i think it is auto-format on save which apply project formatting. I guess file was misformatted before.

Comment (akosyakov) [reply packages/plugin-ext/src/main/browser/status-bar-message-registry-main.ts]: please add to dev meeting to discuss tomorrow

Comment (benoitf) [reply packages/plugin-ext/src/main/browser/status-bar-message-registry-main.ts]: yes, was waiting that someone to create entry :-) but I will create it if not created tomorrow

**Comment by akosyakov** [comment]
@benoitf I've reverted all renames, except whitespaces in imports. Could you have a look again?

**Comment by benoitf** [comment]
@akosyakov yes I know I could hide but the changes are still there. I added topic on dev meeting of tomorrow
