### PR TITLE
fix  :The input box is always fixed in the upper left corner

### LINKED ISSUE #5237: [editor] The input box is always fixed in the upper left corner
### Description
the input box of some input method is always fixed in the upper left corner.
E.g Microsoft Pinyin
image

### PR DESCRIPTION
**Pull request by kpge**
image
this issue (https://github.com/Microsoft/monaco-editor/issues/113#issuecomment-240406949) had been closed ,and textArea in monaco-editor  is no need to always float in the upper left corner,so this style can be deleted:
```css
/* FIXME when https://github.com/Microsoft/monaco-editor/issues/113#issuecomment-240406949 is fixed */
/* .monaco-editor .inputarea {
    position: fixed !important;
    top: 0 !important;
    left: 0 !important;
} */
```
image
Fixes #5237

### CODE REVIEW

File: packages/mini-browser/src/node/mini-browser-endpoint.ts [hunk 1]
```diff
@@ -190,7 +190,7 @@ export class MiniBrowserEndpoint implements BackendApplicationContribution, Mini
 }
 
 // See `EditorManager#canHandle`.
-const CODE_EDITOR_PRIORITY = 100;
+const CODE_EDITOR_PRIORITY = 200;
```
Comment (kittaakos) [inline packages/mini-browser/src/node/mini-browser-endpoint.ts]: If you change this, we would open, for instance, an SVG as an image, be we want to open the source.

File: packages/monaco/src/browser/style/index.css [hunk 2]
```diff
@@ -1,9 +1,9 @@
 /* FIXME when https://github.com/Microsoft/monaco-editor/issues/113#issuecomment-240406949 is fixed */
-.monaco-editor .inputarea {
+/* .monaco-editor .inputarea {
```
Comment (kittaakos) [inline packages/monaco/src/browser/style/index.css]: Can you please split up your PR into to separate ones. Or just revert the `CODE_EDITOR_PRIORITY` related change. That's not the fix for #5230 I believe.

Comment (kpge) [reply packages/monaco/src/browser/style/index.css]: it's my mistake ,I push that commit in the same branch

File: packages/mini-browser/src/node/mini-browser-endpoint.ts (hunk 1 above)
Comment (kpge) [reply packages/mini-browser/src/node/mini-browser-endpoint.ts]: I will make a new PR for this issue.

File: packages/monaco/src/browser/style/index.css [hunk 3]
```diff
@@ -1,9 +1,9 @@
 /* FIXME when https://github.com/Microsoft/monaco-editor/issues/113#issuecomment-240406949 is fixed */
```
Comment (akosyakov) [inline packages/monaco/src/browser/style/index.css]: @kpge please remove all comments then

Have you checked that you cannot reproduce https://github.com/microsoft/monaco-editor/issues/113#issue-171635379 anymore?

**Comment by kpge** [comment]
@akosyakov I've cleaned up all comments , please merge it , thx
