### PR TITLE
Handle uncaught plugin local dir does not exist

### LINKED ISSUE #4041: quiet LocalDirectoryPluginDeployerResolver if a folder does not exist
Right now:
```
root ERROR Uncaught Exception:  Error: The directory referenced by local-dir:../../plugins does not exist.
root ERROR Error: The directory referenced by local-dir:../../plugins does not exist.
    at LocalDirectoryPluginDeployerResolver.<anonymous> (/workspace/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:84:35)
    at step (/workspace/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:53:23)
    at Object.next (/workspace/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:34:53)
    at /workspace/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:28:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:24:12)
    at LocalDirectoryPluginDeployerResolver.resolve (/workspace/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:69:16)
    at PluginDeployerImpl.<anonymous> (/workspace/theia/packages/plugin-ext/lib/main/node/plugin-deployer-impl.js:267:82)
    at step (/workspace/theia/packages/plugin-ext/lib/main/node/plugin-deployer-impl.js:56:23)
    at Object.next (/workspace/theia/packages/plugin-ext/lib/main/node/plugin-deployer-impl.js:37:53)
root INFO Theia app listening on http://0.0.0.0:3000.
```

It would be enough to log with WARN level.

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #4041 

- handle the uncaught exception `Error: The directory referenced by local-dir:../../plugins does not exist.`.
- remove unecessary `await`.

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@benoitf would this be the appropriate time and location to catch the exception, or it should be at a lower level? (example: `resolvePlugins()` method)

**Comment by benoitf** [comment]
@vince-fugnitto 

I think there are 3-4 issues about the problem
https://github.com/theia-ide/theia/issues/4041 (and more)

I think we should catch at the lower level

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto
> 
> I think there are 3-4 issues about the problem
> #4041 (and more)
> 
> I think we should catch at the lower level

Thanks, I'll reference any issues I find and also make the necessary changes.

**Comment by benoitf** [comment]
@vince-fugnitto probably we can just log warn there https://github.com/theia-ide/theia/blob/a666893fe01c02d807b3c2540387a94f084cb7fc/packages/plugin-ext/src/main/node/resolvers/plugin-local-dir-resolver.ts#L45 instead of throwing an error

**Comment by benoitf** [comment]
also referenced there https://github.com/theia-ide/theia/issues/4150

**Comment by vince-fugnitto** [comment]
> also referenced there #4150

I won't reference that issue for the moment since there seems to be an additional change for windows to use `cross-env` and will require additional CQ.

**Comment by marechal-p** [comment]
@benoitf I was wondering about the state of the program if we were just to catch and log the error at the point were the throwing is done? Like when we throw, everything relying on the call to finish will be interrupted. But if it doesn't throw, then the rest of the execution might continue assuming that it succeeded. I just didn't know what assumptions were made, maybe nothing much would break anyway.

File: packages/plugin-ext/src/main/node/resolvers/plugin-local-dir-resolver.ts [hunk 1]
```diff
@@ -42,7 +42,8 @@ export class LocalDirectoryPluginDeployerResolver implements PluginDeployerResol
 
         // check directory exists
         if (!fs.existsSync(dirPath)) {
-            throw new Error('The directory referenced by ' + pluginResolverContext.getOriginId() + ' does not exist.');
+            console.warn('The directory referenced by ' + pluginResolverContext.getOriginId() + ' does not exist.');
```
Comment (benoitf) [inline packages/plugin-ext/src/main/node/resolvers/plugin-local-dir-resolver.ts]: could use string literal there

**Comment by akosyakov** [comment]
> I won't reference that issue for the moment since there seems to be an additional change for windows to use cross-env and will require additional CQ.

@benoitf @vince-fugnitto Would it be possible to introduce a cli option in addition to ENV variable? then we don't need `cross-env`, something like `theia start --plugins=local-dir:mypluginsdir`

**Comment by benoitf** [comment]
@akosyakov so it means that we link theia cli to plug-ins system ? I'm fine but I thought you never wanted to make it like part of 'core' stuff.

**Comment by akosyakov** [comment]
> so it means that we link theia cli to plug-ins system ?
@benoitf no, each extension package can contribute additional cli options: https://github.com/theia-ide/theia/blob/7d4fcadd8f5d206eef78412450fb646bc6293514/packages/core/src/node/cli.ts#L27

**Comment by benoitf** [comment]
@akosyakov ok perfect.

**Comment by benoitf** [comment]
@akosyakov BTW your comment is a fix for another issue so maybe we can still merge this PR for that time

**Comment by vince-fugnitto** [comment]
> @akosyakov ok perfect.

Would you like to handle the `CliContribution` changes in this PR or a follow-up?
I'm still trying to understand what would be needed to create the `CliContribution` for the plugin-system to define the default plugin directory.

**Comment by benoitf** [comment]
@vince-fugnitto to me it can be a follow-up (another problem to solve), was asking @akosyakov

**Comment by vince-fugnitto** [comment]
Thanks @benoitf ! If you'd like you can merge the PR, I am still unable to do so since im not an Eclipse committer as of yet.

**Comment by benoitf** [comment]
@vince-fugnitto ok added to agenda item of Theia dev meeting to start a new committer election for you :-)

**Comment by vince-fugnitto** [comment]
thank you @benoitf !
