### PR TITLE
fix #5280: synchronize preview with editor when scrolls

### LINKED ISSUE #5280: Markdown preview is not synchronized with the editor when scrolls
### Description
I guess it's more like a design problem. Currently, the preview window scrolls automatically only when the selected line is changed. And the first line in the preview window is corresponding to the selected line in editor. In vscode, however, it behaves quite differently: the preview window scrolls automatically when the editor is scrolled, and they are aligned based on the content of the first line. (But if you scroll the preview window instead, the editor will follow it, and behave exactly the same way as vscode does)

Should we adopt the behaviour of vscode on this? IMHO, the current behaviour is OK, but the one on vscode is more natural to me.

### Reproduction Steps
- Open a markdown and its preview on the other side
- Scroll the editor or the preview window, and see how the other one follows

**OS and Theia version:**
OS: linux
Theia: 0.6.0

**Diagnostics:** 
none

### PR DESCRIPTION
**Pull request by a1994846931931**
Signed-off-by: Cai Xuye <a1994846931931@gmail.com>

Synchronize markdown preview with editor when scrolls on both sides.

Before:
fix-markdown-preview-1

After:
fix-markdown-preview-2

### CODE REVIEW

**Comment by akosyakov** [comment]
@AlexTugarev Could you review please?

File: packages/monaco/src/browser/monaco-editor.ts [hunk 1]
```diff
@@ -139,6 +141,28 @@ export class MonacoEditor implements TextEditor {
                 event: e.event.browserEvent
             });
         }));
+        this.toDispose.push(codeEditor.onDidScrollChange(e => {
+            this.onScrollChangedEmitter.fire(undefined);
+        }));
+    }
+
+    getVisibleLineRange(): Range | undefined {
```
Comment (AlexTugarev) [inline packages/monaco/src/browser/monaco-editor.ts]: @a1994846931931, please just make use of `MonacoEditor.getControl().getVisibleRanges()` to implement this. also align naming.

File: packages/editor/src/browser/editor.ts [hunk 2]
```diff
@@ -168,6 +168,9 @@ export interface TextEditor extends Disposable, TextEditorSelection, Navigatable
 
     readonly onMouseDown: Event<EditorMouseEvent>;
 
+    readonly onScrollChanged: Event<void>;
+    getVisibleLineRange(): Range | undefined;
```
Comment (AlexTugarev) [inline packages/editor/src/browser/editor.ts]: please rename to `getVisibleRanges` then

File: packages/preview/src/browser/preview-contribution.ts [hunk 3]
```diff
@@ -115,6 +138,7 @@ export class PreviewContribution extends NavigatableWidgetOpenHandler<PreviewWid
     protected synchronizeScrollToEditor(previewWidget: PreviewWidget, editor: TextEditor): Disposable {
         return previewWidget.onDidScroll(sourceLine => {
             const line = Math.floor(sourceLine);
+            this.delayScrollSync(200); // avoid recursive scroll synchronization
```
Comment (AlexTugarev) [inline packages/preview/src/browser/preview-contribution.ts]: it tried the timeout-based sync so many times ;-) there is always an example that breaks.

Comment (AlexTugarev) [reply packages/preview/src/browser/preview-contribution.ts]: could you try to reproduce by scrolling faster and opening a large file?

Comment (a1994846931931) [reply packages/preview/src/browser/preview-contribution.ts]: Thanks a lot for your advise! I'll try it tomorrow, and see what I can do.

File: packages/monaco/src/browser/monaco-editor.ts (hunk 1 above)
Comment (a1994846931931) [reply packages/monaco/src/browser/monaco-editor.ts]: Thanks! Updated.

File: packages/editor/src/browser/editor.ts (hunk 2 above)
Comment (a1994846931931) [reply packages/editor/src/browser/editor.ts]: @AlexTugarev Done

File: packages/preview/src/browser/preview-contribution.ts (hunk 3 above)
Comment (a1994846931931) [reply packages/preview/src/browser/preview-contribution.ts]: @AlexTugarev Codes updated. It should work much better now.

fix-markdown-preview-2

The synchronization may break if you switch between scrolling on the editor and the preview quickly enough. But it has to be really quick. So in general, it works pretty well to me ：).

fix-markdown-preview-2-break

**Comment by a1994846931931** [comment]
@AlexTugarev I found another related issue - synchronization may break if the preview is quickly scrolled all the way up to the top. But it seems that it already exists on the current master. I think it's better to open a new issue on this. Also, the performance of finding the source code line could be improved.

fix-markdown-preview-2-break3

**Comment by AlexTugarev** [comment]
looks nice! reviewing right now

File: packages/preview/src/browser/preview-contribution.ts (hunk 3 above)
Comment (AlexTugarev) [reply packages/preview/src/browser/preview-contribution.ts]: It's a great improvement!

File: packages/monaco/src/browser/monaco-editor.ts [hunk 4]
```diff
@@ -139,6 +141,18 @@ export class MonacoEditor implements TextEditor {
                 event: e.event.browserEvent
             });
         }));
+        this.toDispose.push(codeEditor.onDidScrollChange(e => {
+            this.onScrollChangedEmitter.fire(undefined);
+        }));
+    }
+
+    getVisibleRanges(): Range[] {
+        return this.editor.getVisibleRanges().map(range =>
```
Comment (AlexTugarev) [inline packages/monaco/src/browser/monaco-editor.ts]:
```suggestion
        return this.editor.getVisibleRanges().map(range => this.m2p.asRange(change.range));
```

Comment (AlexTugarev) [reply packages/monaco/src/browser/monaco-editor.ts]: Please fix the position mapping: Monaco is 1-based, and LSP (used in TextEditor interface) is 0-based.

Comment (AlexTugarev) [reply packages/monaco/src/browser/monaco-editor.ts]: > synchronization may break if the preview is quickly scrolled all the way up to the top

this might be related, not sure though.

Comment (a1994846931931) [reply packages/monaco/src/browser/monaco-editor.ts]: @AlexTugarev Ah! I see! Both 'MonacoToProtocolConverter' and 'ProtocolToMonacoConverter' handle position mapping automatically, so the position mapping issue can be fixed by adopting this suggestion. Got a little confused at first ：)

**Comment by a1994846931931** [comment]
> Also, as you pointed out correctly, the sync story needs a second revision to get rid of this nasty setTimeout-based locks/unlocks.

Yes, indeed

**Comment by a1994846931931** [comment]
> ⚠️ Please apply the requested changes to the implementation of `getVisibleRanges`.

@AlexTugarev Thanks for your detailed review! Codes are updated now.
