### PR TITLE
[git/blame] Fix keybinding context for Escape

### LINKED ISSUE #2376: [editors] ESC doesn't close hover and signature help

### PR DESCRIPTION
**Pull request by AlexTugarev**
This PR introduces new keybinding context `showsBlameAnnotations` to make sure that the `Escape` keybinding is not preventing the delivery of key events to monaco, which causes #2376, #2334.

Additionally, this converts the "Show" command to a "Toggle" command.

Fixes #2376, #2334, #1951

### CODE REVIEW

File: packages/git/src/browser/blame/blame-contribution.ts [hunk 1]
```diff
@@ -131,22 +136,47 @@ export class BlameContribution implements FrontendApplicationContribution, Comma
...
-            context: EditorKeybindingContexts.strictEditorTextFocus,
+            context: BlameAnnotationsKeybindingContext.showsBlameAnnotations,
             keybinding: 'esc'
         });
     }
 
 }
+
+@injectable()
+export class BlameAnnotationsKeybindingContext implements KeybindingContext {
```
Comment (akosyakov) [inline packages/git/src/browser/blame/blame-contribution.ts]: Should not it extend `EditorTextFocusContext` similar to `JavaEditorTextFocusContext` that it is active only when an editor has focus?

Comment (AlexTugarev) [reply packages/git/src/browser/blame/blame-contribution.ts]: thought about that indeed. let me check if that works.

Comment (AlexTugarev) [reply packages/git/src/browser/blame/blame-contribution.ts]: works nicely, thanks @akosyakov!
