### PR TITLE
GH-1163: Fixed repository watcher issue.

### LINKED ISSUE #1163: [git] Git watcher issue
I am experiencing an odd behavior when multiple git watchers (let assume, two) are attached to the same repository. In such cases, the backend sends two notifications for each client. So we run the `git status` command twice on the backend, and each client gets notified twice.

AC: backend runs the `git diff` once, although two watchers are attached. Each client gets notified once.

### PR DESCRIPTION
**Pull request by kittaakos**
The Git watcher backend sent the same Git status change event multiple times if more than one subscriber were watching the changes in the same repository.

For instance, when there were three subscribers, then each subscriber got the same (but not identical) event three times.

Closes #1163.

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
What was the root cause?

File: packages/git/src/node/dugite-git-watcher.ts [hunk 1]
```diff
@@ -28,27 +30,53 @@ export class DugiteGitWatcherServer implements GitWatcherServer {
...
+        const repositoryWatcher = this.manager.getWatcher(repository);
+        const { localUri } = repository;
+        if (!this.watchers.has(localUri)) {
+            const disposable = new DisposableCollection();
+            disposable.push(repositoryWatcher.onStatusChanged(e => {
+                if (this.client) {
+                    this.client.onGitChanged(e);
+                }
+            }));
+            disposable.push(repositoryWatcher.watch());
```
Comment (akosyakov) [inline packages/git/src/node/dugite-git-watcher.ts]: This method should be called for each call of `watchGitChanges`, otherwise, new clients won't get the initial state. It seems that now it is called only for once for each repository URL.

Comment (kittaakos) [reply packages/git/src/node/dugite-git-watcher.ts]: > What was the root cause?

Well, we had two separate watchers after calling `watchChanges` twice.

You are right. The second `watchChanges` call will not notify once more. I need to work on this.

Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: > Well, we had two separate watchers after calling watchChanges twice.

Do you mean 2 instances of `GitRepositoryWatcher` for the same repository? `GitRepositoryManagerImpl.getWatcher` should not allow it.

Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: I see `MockRepositoryManager` is bogus.

Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: the issue is that there is only one watcher but for the same client multiple listeners are installed on it, I was able to fix it with the following `watchGitChanges`:
```ts
protected readonly watchers = new Map<number, Disposable>();
protected readonly subscriptions = new Map<string, DisposableCollection>();

constructor(
    @inject(GitRepositoryManager) protected readonly manager: GitRepositoryManager
) { }

dispose(): void {
    for (const watcher of this.watchers.values()) {
        watcher.dispose();
    }
    this.watchers.clear();
    this.subscriptions.clear();
}

async watchGitChanges(repository: Repository): Promise<number> {
    const watcher = this.manager.getWatcher(repository);

    const repositoryUri = repository.localUri;
    let subscriptions = this.subscriptions.get(repositoryUri);
    if (subscriptions === undefined) {
        const unsubscribe = watcher.onStatusChanged(e => {
            if (this.client) {
                this.client.onGitChanged(e);
            }
        });
        subscriptions = new DisposableCollection();
        subscriptions.onDispose(() => unsubscribe.dispose());
        this.subscriptions.set(repositoryUri, subscriptions);
    }

    const disposable = watcher.watch();
    subscriptions.push(disposable);
    const watcherId = this.watcherSequence++;
    this.watchers.set(watcherId, disposable);
    return watcherId;
}
```

It makes sure that only one event listener is installed by the same client for the same watcher and it is get removed when all watchers are stopped.

BTW What was the point to have mocks again? I see that tests can be rewritten without mocks at all.

Comment (kittaakos) [reply packages/git/src/node/dugite-git-watcher.ts]: > I was able to fix it with the following

The way you have simplified the (flawed) logic I have written... Big thanks for that! I would like to add a test for the _"..otherwise; new clients won't get the initial state..."_ case too. Plus at least one for the listener removal.

> What was the point to have mocks again?

Tests started to fail randomly on the CI because the `after` phase was unable to clean the Git repository, a process held it. I wanted to decouple the Git logic from the listeners and process. That was all.

> deleted all of them to make sure that exactly the same code is used in tests

👍

Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: > Tests started to fail randomly on the CI because the after phase...

Was it because of `GitRepositoryManager.run`? Maybe we can mock only one method, like `manager.run = (_, op) => op()`.

Comment (kittaakos) [reply packages/git/src/node/dugite-git-watcher.ts]: OK, let’s try that and see how it works on the CIs.

File: packages/git/src/node/dugite-git-watcher.ts [hunk 2]
```diff
@@ -28,19 +29,31 @@ export class DugiteGitWatcherServer implements GitWatcherServer {
             watcher.dispose();
         }
         this.watchers.clear();
+        this.subscriptions.clear();
```
Comment (hexa00) [inline packages/git/src/node/dugite-git-watcher.ts]: We should iterator over the subscriptions here and call dispose ?

Comment (kittaakos) [reply packages/git/src/node/dugite-git-watcher.ts]: OK.

Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: it should not be necessary, they should be removed on `watcher.dispose()`call.

File: packages/git/src/node/dugite-git-watcher.ts [hunk 3]
```diff
@@ -28,19 +29,31 @@ export class DugiteGitWatcherServer implements GitWatcherServer {
...
+                unsubscribe.dispose();
+                this.subscriptions.delete(repositoryUri);
+            });
+            this.subscriptions.set(repositoryUri, subscriptions);
+        }
+
+        const disposable = watcher.watch();
         const watcherId = this.watcherSequence++;
-        this.watchers.set(watcherId, disposable);
+        this.watchers.set(watcherId, subscriptions.push(disposable));
```
Comment (akosyakov) [inline packages/git/src/node/dugite-git-watcher.ts]: sorry, my bad, the code before was alright:
```js
const disposable = watcher.watch();
subscriptions.push(disposable); 
this.watchers.set(watcherId, disposable);
```

File: packages/git/src/node/dugite-git-watcher.ts (hunk 2 above)
Comment (hexa00) [reply packages/git/src/node/dugite-git-watcher.ts]: haa OK yes indeed.

File: packages/git/src/node/dugite-git-watcher.ts (hunk 3 above)
Comment (hexa00) [reply packages/git/src/node/dugite-git-watcher.ts]: Isn't that the same as the current code ?

```typescript
 const disposable = watcher.watch();
 const watcherId = this.watcherSequence++;    
  this.watchers.set(watcherId, subscriptions.push(disposable));
```

**Comment by kittaakos** [comment]
I have started another build cycle with the final state, hopefully. I have also tried to simplify the mock repository manager/watcher things. Please take another look and give feedback. Thanks!

File: packages/git/src/node/dugite-git-watcher.ts (hunk 3 above)
Comment (kittaakos) [reply packages/git/src/node/dugite-git-watcher.ts]: No, the trick is, (@akosyakov) can correct me, the latter one will remove itself from the disposable collection too.

Comment (hexa00) [reply packages/git/src/node/dugite-git-watcher.ts]: haaa right I see ok my bad..

File: packages/git/src/node/dugite-git-watcher.ts [hunk 4]
```diff
@@ -28,19 +29,34 @@ export class DugiteGitWatcherServer implements GitWatcherServer {
             watcher.dispose();
         }
         this.watchers.clear();
+        for (const disposable of this.subscriptions.values()) {
+            disposable.dispose();
```
Comment (hexa00) [inline packages/git/src/node/dugite-git-watcher.ts]: You don't need this after all...

Comment (kittaakos) [reply packages/git/src/node/dugite-git-watcher.ts]: True.

File: packages/git/src/node/dugite-git-watcher.ts (hunk 3 above)
Comment (hexa00) [reply packages/git/src/node/dugite-git-watcher.ts]: Just to recap this:
```
 subscriptions.push(disposable)
```
Returns a Disposable that will dispose of the disposable and clean it from the disposable collection.

So if you use:
`this.watchers.set(watcherId, subscriptions.push(disposable));`

You don't need to call ` for (const disposable of this.subscriptions.values()) { disposable.dispose() } `

But if you use:

```
subscriptions.push(disposable); 
this.watchers.set(watcherId, disposable);
```

It doesn't do that, but iterating over the this.watchers and calling dispose then clearing the subscription array is fine.

File: packages/git/src/node/dugite-git-watcher.ts (hunk 4 above)
Comment (kittaakos) [reply packages/git/src/node/dugite-git-watcher.ts]: Wait for a second; who is calling the `dispose` on the `subscriptions`?

Comment (hexa00) [reply packages/git/src/node/dugite-git-watcher.ts]: See this comment: https://github.com/theia-ide/theia/pull/1164#discussion_r164742038

File: packages/git/src/node/dugite-git-watcher.ts (hunk 3 above)
Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: @kittaakos please use the snippet from https://github.com/theia-ide/theia/pull/1164#discussion_r164732624, the current code won't stop watching

Comment (kittaakos) [reply packages/git/src/node/dugite-git-watcher.ts]: I think this is just partially correct. My understanding is that you do not have to remove the items explicitly from the disposable collection, but you have to dispose the collection itself.

Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: It gets disposed when all disposable are removed.

File: packages/git/src/node/dugite-git-watcher.ts (hunk 4 above)
Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: `DisposableCollection` gets disposed when all contained disposables are disposed.

File: packages/git/src/node/dugite-git-watcher.ts (hunk 3 above)
Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: `DisposableCollection.push` returns a disposable to remove a passed disposable. It does not dispose the original disposable, but it gets disposed together with an original disposable.

File: packages/git/src/node/dugite-git-watcher.ts (hunk 4 above)
Comment (kittaakos) [reply packages/git/src/node/dugite-git-watcher.ts]: I would propose documenting this behavior with some spec tests (as a follow-up task), so others who join the development fully understand it. I am not talking about JS-doc, that could get outdated anytime.

Obviously, it was not totally clear to me either. It is very easy to use once you got used to it but clearly, the logic is hidden in the details.

File: packages/git/src/node/dugite-git-watcher.ts (hunk 3 above)
Comment (hexa00) [reply packages/git/src/node/dugite-git-watcher.ts]: Given that the Diposable dispose method gets overloaded...

File: packages/git/src/node/dugite-git-watcher.ts (hunk 4 above)
Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: One should understand what `DisposableCollection` does and it should be enough. We can add jsdoc for it separately.

File: packages/git/src/node/dugite-git-watcher.ts (hunk 3 above)
Comment (akosyakov) [reply packages/git/src/node/dugite-git-watcher.ts]: In the second case, a stored disposable only removes an added disposable from a collection. It does not dispose an original disposable.

Comment (hexa00) [reply packages/git/src/node/dugite-git-watcher.ts]: Haaaa OK yes you're right! thx

**Comment by kittaakos** [comment]
Please take another look. I hope I did not miss anything this time and it is good to merge. Thanks!
