### PR TITLE
Save cycle fixes

### LINKED ISSUE #4463: [plugin] onWillSave callback never resolves
Saving exp is very slow with https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go and https://github.com/demo-apps/go-gin-app repo

Also auto formatting on save does not work always, but fails with
```
root ERROR Error: onWillSave listener loop timeout
    at https://3000-d776232d-4e50-43fd-b267-1d7ef7c1bf5d.ws-eu0.gitpod.io/19.bundle.js:807:36
```

### PR DESCRIPTION
**Pull request by akosyakov**
- align timeouts with VS Code: there is no general timeout anymore, each participant should take care, i.e. format on save, plugin host
- properly fire onWillSaveTextDocument event in the plugin host process, before it will resolve only for first listener or never resolve if there are no participants

fix #4463

### CODE REVIEW

File: packages/plugin-ext/src/main/browser/documents-main.ts [hunk 1]
```diff
@@ -54,7 +54,8 @@ export class DocumentsMainImpl implements DocumentsMain {
             this.proxy.$acceptModelSaved(m.textEditorModel.uri);
         }));
         this.toDispose.push(modelService.onModelWillSave(onWillSaveModelEvent => {
-            onWillSaveModelEvent.waitUntil(new Promise<monaco.editor.IIdentifiedSingleEditOperation[]>(async resolve => {
+            onWillSaveModelEvent.waitUntil(new Promise<monaco.editor.IIdentifiedSingleEditOperation[]>(async (resolve, reject) => {
+                setTimeout(() => reject('Aborted onWillSaveTextDocument-event after 1750ms'), 1750);
```
Comment (kittaakos) [inline packages/plugin-ext/src/main/browser/documents-main.ts]: Please reject with an `Error`. Where does `1750` come from?

File: packages/monaco/src/browser/monaco-editor-provider.ts [hunk 2]
```diff
@@ -178,6 +171,24 @@ export class MonacoEditorProvider {
...
+        }
+        const overrideIdentifier = editor.document.languageId;
+        const uri = editor.uri.toString();
+        const formatOnSave = this.editorPreferences.get({ preferenceName: 'editor.formatOnSave', overrideIdentifier }, undefined, uri)!;
+        if (!formatOnSave) {
+            return [];
+        }
+        const formatOnSaveTimeout = this.editorPreferences.get({ preferenceName: 'editor.formatOnSaveTimeout', overrideIdentifier }, undefined, uri)!;
+        await Promise.race([
+            new Promise(reject => setTimeout(() => reject(`Aborted format on save after ${formatOnSaveTimeout}ms`), formatOnSaveTimeout)),
```
Comment (kittaakos) [inline packages/monaco/src/browser/monaco-editor-provider.ts]: If possible, please reject with an error.

File: packages/plugin-ext/src/plugin/documents.ts [hunk 3]
```diff
@@ -81,34 +81,70 @@ export class DocumentsExtImpl implements DocumentsExt {
...
-                            resolve(editOperations);
-                        } else {
-                            resolve([]);
-                        }
+
+    async $acceptModelWillSave(strUrl: UriComponents, reason: theia.TextDocumentSaveReason): Promise<SingleEditOperation[]> {
+        const uri = URI.revive(strUrl).toString();
+        const operations: SingleEditOperation[] = [];
+        let didTimeout = false;
+        const didTimeoutHandle = setTimeout(() => didTimeout = true, 1500);
```
Comment (kittaakos) [inline packages/plugin-ext/src/plugin/documents.ts]: Above, you reject with `1750`. Why the difference? Can we use a shared constant instead?

Comment (akosyakov) [reply packages/plugin-ext/src/plugin/documents.ts]: there are 2 different processes, server process timeouts in 1750ms, plugin host process tries to timeout a bit earlier to squeeze at least some edits, if it timeouts later no edits will be provided

i could add the constant in some main-ext interfaces, they are shared between these processes.

Comment (kittaakos) [reply packages/plugin-ext/src/plugin/documents.ts]: It's fine. I just wanted to understand why the difference between the timeouts. Thanks!

File: packages/plugin-ext/src/main/browser/documents-main.ts [hunk 4]
```diff
@@ -54,7 +54,8 @@ export class DocumentsMainImpl implements DocumentsMain {
             this.proxy.$acceptModelSaved(m.textEditorModel.uri);
         }));
         this.toDispose.push(modelService.onModelWillSave(onWillSaveModelEvent => {
-            onWillSaveModelEvent.waitUntil(new Promise<monaco.editor.IIdentifiedSingleEditOperation[]>(async resolve => {
+            onWillSaveModelEvent.waitUntil(new Promise<monaco.editor.IIdentifiedSingleEditOperation[]>(async (resolve, reject) => {
+                setTimeout(() => reject(new Error('Aborted onWillSaveTextDocument-event after 1750ms')), 1750);
```
Comment (benoitf) [inline packages/plugin-ext/src/main/browser/documents-main.ts]: Hello, please extract 1750 to variable so in error message is synched with value of timeout ?

Also does-it make sense to have that timeout overridable ?

File: packages/plugin-ext/src/plugin/documents.ts [hunk 5]
```diff
@@ -81,34 +81,70 @@ export class DocumentsExtImpl implements DocumentsExt {
...
+            fireEvent: (e: theia.TextDocumentWillSaveEvent) => any,
+            accept: (operation: SingleEditOperation) => void
+        }): Promise<void> {
+
+        const promises: PromiseLike<TextEdit[] | any>[] = [];
+        fireEvent(Object.freeze({
+            document, reason,
+            waitUntil(p: PromiseLike<TextEdit[] | any>) {
+                if (Object.isFrozen(promises)) {
+                    throw new Error('waitUntil can not be called async');
```
Comment (benoitf) [inline packages/plugin-ext/src/plugin/documents.ts]: Hello, I'm not sure the message will be meaningful for end users

Also it looks like a copy from vscode.

Comment (akosyakov) [reply packages/plugin-ext/src/plugin/documents.ts]: End user should never see it. It's a programming error, extension developer should not call `waitUtil` async.

> Also it looks like a copy from vscode.

+1 will add copyrights

Comment (akosyakov) [reply packages/plugin-ext/src/plugin/documents.ts]: actually code is copied from https://github.com/theia-ide/theia/blob/ad9e62bd78bf4da3ce829b25de64f9aa3fc8aaeb/packages/monaco/src/browser/monaco-editor-model.ts#L344-L366

only async is adjusted to be as an error in VS Code

not sure that we should open CQs for it

**Comment by benoitf** [comment]
AFAIK, when the code is a copy it needs to covered by CQ (even if we postponed it right now it will be required in future).

**Comment by akosyakov** [comment]
@benoitf for copied code we need even now, we don't need CQs only for npm dependencies

I did not mean to merge, pressed by the mistake 🙈 will open a follow-up PR now
