### PR TITLE
files.enableTrash preference

### LINKED ISSUE #4334: [preferences] Allow overriding preference defaults for an application in package.json
In our use case we have the need to override the default values of workspace preferences without causing the system to save a config file.
Specifically we want the `workspace.preserveWindow` to default to `true` instead of `false` as declared in the workspace preferences schema.

A nice way this could work would be if the defaults could be read from the application `package.json` file, e.g. something like:

```json
{
  "theia": {
    "target": "browser",
    "frontend": {
      ...
    },
    "preferences": {
      "config": {
        "workspace": {
          "preserveWindow": true
        }
      }
    }
  }
}
```

Perhaps related to https://github.com/theia-ide/theia/pull/4296

Thoughts/other approaches?

cc @akosyakov

### LINKED ISSUE #4524: [featurerequest] A way to disable the creation of Trash folder upon deleting files
### Description
*Featurerequest:*  

I'm looking for a way to disable the creation of the 'Trash' folder when deleting files; it seems superfluous to have this Trash-folder show up; my workspace folder is already hosted on storage that allows filerecovery ánd git also allows recovery of files if they are deleted from a repository.

Currently this does not seem possible to configure.

I've brought this up on Theia's spectrum chat and was asked to file an issue:
**Anton Kosyakov: There is no such preference right name. VS Code has `files.enableTrash` preference, we can have similar.**

### Reproduction Steps
Delete a file; a folder ".Trash-10000" will appear at the root of your workspace.

OS and Theia version: any docker-image (https://hub.docker.com/u/theiaide)

### PR DESCRIPTION
**Pull request by akosyakov**
fix #4524: add files.enableTrash preference
fix #4334: allow to override default preference values:
  - files.enableTrash is overridden to `false` as an example [for the browser app](https://github.com/theia-ide/theia/blob/cc702f5b22639d1aa2508348b5050558e12fcd5c/examples/browser/package.json#L10-L12)
  - one can override it programmatically: [PreferenceSchemaProvider.getDefaultValue](https://github.com/theia-ide/theia/blob/cc702f5b22639d1aa2508348b5050558e12fcd5c/packages/core/src/browser/preferences/preference-contribution.ts#L178)

### CODE REVIEW

**Comment by akosyakov** [comment]
https://github.com/theia-ide/theia-apps/issues/159 to reconfigure docker image cc @marcdumais-work

File: packages/navigator/src/browser/navigator-filter.ts [hunk 1]
```diff
@@ -22,8 +22,6 @@ import { PreferenceChangeEvent } from '@theia/core/lib/browser/preferences';
 import { FileSystemPreferences, FileSystemConfiguration } from '@theia/filesystem/lib/browser/filesystem-preferences';
 import { FileNavigatorPreferences, FileNavigatorConfiguration } from './navigator-preferences';
 
-const FILES_EXCLUDE_PREFERENCE: keyof FileSystemConfiguration = 'files.exclude';
```
Comment (akosyakov) [inline packages/navigator/src/browser/navigator-filter.ts]: fyi: not all strings in TS are just string, some can be used for property access, i.e `myObject['myProp']`
preference proxies are statically typed, one cannot use other prop names and type is properly determined for a prop, there is NO need for a constant. I had to remove it here because it confused compiler. The type of `FILES_EXCLUDE_PREFERENCE` now is `'files.exclude' | 'files.enableTrash'`, so compiler cannot derive any more  a proper type where `FILES_EXCLUDE_PREFERENCE` is used.

cc @svor @kittaakos

**Comment by thegecko** [comment]
Hmm, getting the following error on this branch. Investigating....

Screen Shot 2019-04-01 at 11 53 09

**Comment by akosyakov** [comment]
@thegecko I've annotated the proxy factory as injectable to allow its subclassing in DI context. It seems to be used in process which does not load reflect metadata package.

**Comment by thegecko** [comment]
Ok, have you tried running this in electron? The js runtimes are quite restrictive

**Comment by akosyakov** [comment]
@thegecko good point, i will try

**Comment by akosyakov** [comment]
it's again because of cluster module. It uses proxy factories without installing reflect metadata package. I will move annotating proxy factories to browser module for now to make this PR work and then look into getting rid of cluster module.

**Comment by akosyakov** [comment]
@thegecko could you try again? It should work now

**Comment by AlexTugarev** [comment]
@akosyakov, what's the issue with DCO check?

**Comment by akosyakov** [comment]
@AlexTugarev i also wonder what is wrong with it. Eclipse sign-off check is green, so it's good to merge?
