### PR TITLE
compute resource context keys based on global selection

### LINKED ISSUE #4529: supporting on vscode plugin in menus setting is not stable
### Description
I write a vscode plugin to support a function that could add two commands when right click different  types files. It works very well in vscode, but not work in theia extension. The question is in vscode I set different "when" labels to add the different types of buttons, but the "when" labels work disorderly,it confused. By the way, the event I set is to click the button I add to open a url, it totally doesn't work in theia extension.

### Reproduction Steps
1.add some codes in package.json (add some labels i.e "menus" "when")
2. pack up as a .vsix
3.add the .vsix in plugins directory
4.run 

**OS and Theia version:**
1.The newest theia master branch codes
2.Docker version 1.12.6

**Diagnostics:** 
I wonder whether the support in vscode plugins could work better in theia extension.

### LINKED ISSUE #4539: Theia explorer context menu missing resource context for vscode extension
### Description
I've got a vscode extension that generates menu items from a "right-click" on the file explorer.  And depending on the context of the right click ( if it's a specifically named folder or a file ), it behaves differently.  In theia, the context items that it keys off of are always undefined.

I have a vsix that shows this behavior, linked below.

### Reproduction Steps
1. Download and run the vsix ( committed to this repo ) [https://github.com/dehru/vscode-explorer-context-extension](https://github.com/dehru/vscode-explorer-context-extension)
2. Download and use theia ide on this simple workspace [https://github.com/dehru/right-click-test-project](https://github.com/dehru/right-click-test-project)
3. Right Click ( Context Menu ) in the file explorer on the hello.js, world.js, and helloworld directory of the test project above
4. The context menu ( right click or option click ) does not show the expected menu items as expressed in the contributions property of the package.json

**OS and Theia version:**
MacOS 10.13.6, vscode@1.1.26, theia 0.4.0 ( and 0.3.19 ) 
 
**Diagnostics:** 
Vscode plugin contributions from package.json 
[https://github.com/dehru/vscode-explorer-context-extension/blob/master/package.json](https://github.com/dehru/vscode-explorer-context-extension/blob/master/package.json)

**Excerpt from package.json**:
```
"explorer/context": [
	{
		"command": "extension.hello",
		"when": "resourceFilename == hello.js"
	},
	{
		"command": "extension.world",
		"when": "resourceFilename == world.js"
	},
	{
		"command": "extension.helloWorld",
		"when": "explorerResourceIsFolder && resourceFilename == helloworld"
	}
],
```

When the menu is built in theia, the context is missing the resourceFilename ( undefined ), which is present in vscode as the item clicked on in the explorer.  I believe here is where the when statements are compared to the keyContext.  [ Link to monaco-context-key-service.ts](https://github.com/theia-ide/theia/blob/763ca8b4e1c3d1ce477efe79cea238c693b586dc/packages/monaco/src/browser/monaco-context-key-service.ts#L39)

**Vscode context in explorer when context-menu is folder:**
```
"explorerResourceIsFolder":true,
"resourceScheme":"file",
"resourceFilename":"helloworld",
"resourceLangId":null,
"resourceExtname":"",
```

**Theia context in explorer when context-menu is folder:**
```
"explorerResourceIsFolder":true,
"resourceScheme":undefined,
"resourceFilename":undefined,
"resourceExtname":undefined,
"resourceLangId":undefined
```

The vscode documentation on resource contexts:
https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

### Sample Projects Used to Discover This Issue ###

Sample vscode extension:
[https://github.com/dehru/vscode-explorer-context-extension](https://github.com/dehru/vscode-explorer-context-extension)

Sample workspace:
[https://github.com/dehru/right-click-test-project](https://github.com/dehru/right-click-test-project)

### PR DESCRIPTION
**Pull request by akosyakov**
fix #4529, fix #4539 and clean up global selection when owning widgets are disposed

tested with https://github.com/akosyakov/vscode-menus

### CODE REVIEW

**Comment by akosyakov** [comment]
@ouyangxizi Could you try?

File: packages/editor/src/browser/editor-contribution.ts [hunk 1]
```diff
@@ -36,29 +36,16 @@ export class EditorContribution implements FrontendApplicationContribution {
...
 
     onStart(): void {
-        this.initResourceContextKeys();
         this.initEditorContextKeys();
 
         this.updateStatusBar();
         this.editorManager.onCurrentEditorChanged(() => this.updateStatusBar());
     }
 
+    /** @default since 0.5.0 - will be removed in farther releases */
```
Comment (svenefftinge) [inline packages/editor/src/browser/editor-contribution.ts]: deprecated

**Comment by ouyangxizi** [comment]
> @ouyangxizi Could you try?

Test in newest Theia  master, it works very well!
