### PR TITLE
Umbrella PR for various Mini Browser issues

### LINKED ISSUE #1959: [navigator] Using "Open with -> Mini browser" on a file generates warning and shows empty on the client side
Try "Open with" -> "Mini Browser" on different files result in not opening on the client side.
Why is this option presented to the user if he cannot use it !

 [2018-05-25T14:29:11.086Z]  INFO: Theia/13600 on elxa36mbq32: (logger=root)
    [nsfw-watcher: 13640] Started watching: /home/lmcbout/theia/theia/package.json
     []

[2018-05-25T14:29:11.514Z]  WARN: Theia/13600 on elxa36mbq32: Cannot handle unexpected resource. URI: file:///home/lmcbout/theia/theia/package.json. [] (logger=root)

[2018-05-25T14:29:25.244Z]  INFO: Theia/13600 on elxa36mbq32: (logger=root)
    [nsfw-watcher: 13640] Started watching: /home/lmcbout/theia/theia/README.md
     []

[2018-05-25T14:29:25.678Z]  WARN: Theia/13600 on elxa36mbq32: Cannot handle unexpected resource. URI: file:///home/lmcbout/theia/theia/README.md. [] (logger=root)

### LINKED ISSUE #1972: [mini-browser] Add refresh button
the mini browser chrome needs a refresh button.

### LINKED ISSUE #1973: [Navigator] Images should open in preview
The default open handler of binary images (gif, png, jpg, jpeg) shall use the toolbar-less mini-browser as a preview.

### LINKED ISSUE #1997: [mini-browser] The Mini Browser cannot be closed with the `Alt+Shift+W` binding
when it has the focus. Probably, the `document` of the underlying `iframe` greedily percepts the key events and we never end up calling `KeybindingRegistry#run(KeyboardEvent)`. Removing the focus from the Mini Browser widget and selecting the `File` navigator solves the problem.

### PR DESCRIPTION
**Pull request by kittaakos**
- [x] [[Navigator] Images should open in preview](https://github.com/theia-ide/theia/issues/1973)
 - [x] [[navigator] Using "Open with -> Mini browser" on a file generates warning and shows empty on the client side](https://github.com/theia-ide/theia/issues/1959)
 - [x] [[mini-browser] Add refresh button](https://github.com/theia-ide/theia/issues/1972)
 - [x] [[mini-browser] The Mini Browser cannot be closed with the `Alt+Shift+W` binding](https://github.com/theia-ide/theia/issues/1997)

Closes #1973.
Closes #1959.
Closes #1972.
Closes #1997.

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

File: packages/mini-browser/src/browser/mini-browser-open-handler.ts [hunk 1]
```diff
@@ -22,7 +23,19 @@ export interface MiniBrowserOpenerOptions extends WidgetOpenerOptions, MiniBrows
 }
 
 @injectable()
-export class MiniBrowserOpenHandler extends WidgetOpenHandler<MiniBrowser> {
+export class MiniBrowserOpenHandler extends WidgetOpenHandler<MiniBrowser> implements FrontendApplicationContribution {
+
+    /**
+     * This is a **hack**.
```
Comment (svenefftinge) [inline packages/mini-browser/src/browser/mini-browser-open-handler.ts]: Why a hack? Isn't it more like an optimization (caching)?
I would prefer not to back such a big deal about it, since it doesn't really look odd.
This sort of comments will leave the impression that it has to be fixed somehow.

File: packages/mini-browser/src/node/mini-browser-endpoint.ts [hunk 2]
```diff
@@ -40,17 +40,39 @@ export const MiniBrowserEndpointHandler = Symbol('MiniBrowserEndpointHandler');
...
      * Responds back to the sender.
      */
     respond(statWithContent: FileStatWithContent, response: Response): MaybePromise<Response>;
 
+    /**
+     * Returns or resolves to a positive number if the current contribution can handle the resource with the given URI.
+     * The number indicates the priority of the endpoint contribution. If it is not a positive number, it means, the
+     * contribution cannot handle the URI.
+     */
+    priority(uri: string): MaybePromise<number>;
```
Comment (svenefftinge) [inline packages/mini-browser/src/node/mini-browser-endpoint.ts]: Given the current implementation, this should be done on the client side, too.

Comment (kittaakos) [reply packages/mini-browser/src/node/mini-browser-endpoint.ts]: This is exactly what we did and that caused the context menu issue because we could not run `async` code. Right now, we just assume if the extension can be handled, then it should [have a bigger priority than the `Code Editor`](https://github.com/theia-ide/theia/pull/1998/files#diff-efa0e82536aa80ae220e472ef9d04256R64).

File: packages/mini-browser/src/browser/mini-browser-open-handler.ts (hunk 1 above)
Comment (kittaakos) [reply packages/mini-browser/src/browser/mini-browser-open-handler.ts]: Well, do original idea did not include any caching but it did not work [due to the `sync`/`async` issue with the Phosphor context menu](https://github.com/theia-ide/theia/issues/1959). This change was introduced to work around that problem, but you're right, perhaps I could get rid of the `This is a hack` introduction.
