### PR TITLE
 [plugin-ext] Fix undefined path on windows

### LINKED ISSUE #3978: [ci][windows] undefined path in plugin-ext
https://ci.appveyor.com/project/kittaakos/theia/builds/21446239#L3527

### PR DESCRIPTION
**Pull request by marechal-p**
Some path returned by the filesystem was forced as non-undefined in the
code, while at runtime the value actually ended up undefined.

Hopefully improved filesystem access.

Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

An error about some `execute("return window.__coverage__")` kept
appearing in the test logs. Fixed.

Closes #3978

### CODE REVIEW

**Comment by marechal-p** [comment]
Please tell me if this breaks anything regarding plugins, as I tried to fix it for Windows, I am afraid for anything to break on Linux :/

Hopefully the CI jobs will be green now.

File: packages/filesystem/src/node/node-filesystem.ts [hunk 1]
```diff
@@ -259,7 +259,10 @@ export class FileSystemNode implements FileSystem {
         const _uri = new URI(uri);
         const stat = await this.doGetStat(_uri, 0);
         if (stat) {
-            throw FileSystemError.FileExists(uri, 'Error occurred while creating the directory.');
+            if (stat.isDirectory) {
+                return stat;
```
Comment (marechal-p) [inline packages/filesystem/src/node/node-filesystem.ts]: @akosyakov as an API consumer, I would assume that when I create a directory: if it is already there then I am happy.

Either that or an additional `ensureFolder` API? wdyt?

**Comment by marechal-p** [comment]
Well, now it is a new error on AppVeyor. But I think https://github.com/theia-ide/theia/pull/3961 might fix it...

One at the time, right? :)

**Comment by marechal-p** [comment]
Thanks @benoitf, merging.
