### PR TITLE
[plugins] terminate hosted plugin instance on dispose only if it is running

### LINKED ISSUE #5358: [plugins] error thrown 'hosted plugin instance is not running'
**Description**

An error is thrown whenever the frontend-application is closed, while the backend is still alive.

```
root ERROR Error: Hosted plugin instance is not running.
    at NodeHostedPluginRunner.AbstractHostedInstanceManager.terminate (/workspace/theia/packages/plugin-dev/lib/node/hosted-instance-manager.js:196:19)
    at HostedPluginServerImpl.dispose (/workspace/theia/packages/plugin-dev/lib/node/hosted-plugin-service.js:72:36)
    at /workspace/theia/packages/plugin-dev/lib/node/plugin-dev-backend-module.js:36:65
    at /workspace/theia/packages/core/lib/common/event.js:161:33
    at CallbackList.invoke (/workspace/theia/packages/core/lib/common/event.js:176:39)
    at Emitter.fire (/workspace/theia/packages/core/lib/common/event.js:264:29)
    at /workspace/theia/packages/core/lib/common/messaging/proxy-factory.js:153:58
    at CallbackList.invoke (/workspace/theia/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/workspace/theia/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at closeHandler (/workspace/theia/node_modules/vscode-jsonrpc/lib/main.js:221:26)
```

**Steps to Reproduce:**
1. Start the application (at the moment of testing, no plugins were present)
2. Open the frontend in a browser
3. Close the frontend
4. Notice the error thrown on the backend

**Additional Info**
- Master as of 92cfe9a
- OS Version: `MacOS 10.14`
- No plugins present

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #5358

- The `hosted-instance-manager` throws an error when calling the `terminate` method and no
hosted plugin instance is currently running. Instead of calling `terminate` on `dispose` each time,
trigger the termination of the hosted plugin only when there is a currently running instance.

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

File: packages/plugin-dev/src/node/hosted-plugin-service.ts [hunk 1]
```diff
@@ -39,7 +39,11 @@ export class HostedPluginServerImpl implements HostedPluginServer {
     private readonly hostedPlugin: HostedPluginSupport;
 
     dispose(): void {
-        this.hostedInstanceManager.terminate();
+        try {
+            this.hostedInstanceManager.terminate();
+        } catch (e) {
+            console.warn('Hosted plugin instance is not running.');
```
Comment (benoitf) [inline packages/plugin-dev/src/node/hosted-plugin-service.ts]: Why not log the error ?

File: packages/plugin-dev/src/node/hosted-plugin-service.ts [hunk 2]
```diff
@@ -66,7 +70,11 @@ export class HostedPluginServerImpl implements HostedPluginServer {
     }
 
     terminateHostedPluginInstance(): Promise<void> {
-        this.hostedInstanceManager.terminate();
+        try {
+            this.hostedInstanceManager.terminate();
+        } catch (e) {
+            console.warn('Hosted plugin instance is not running.');
```
Comment (benoitf) [inline packages/plugin-dev/src/node/hosted-plugin-service.ts]: Why not display e ?

**Comment by vince-fugnitto** [comment]
@benoitf are you fine with the updated changes?

**Comment by kittaakos** [comment]
As this happens each time I refresh the browser window in electron, logging an error instead of throwing it is not the fix. See: https://github.com/theia-ide/theia/issues/5358#issuecomment-499585418

**Comment by vince-fugnitto** [comment]
> As this happens each time I refresh the browser window in electron, logging an error instead of throwing it is not the fix. See: [#5358 (comment)](https://github.com/theia-ide/theia/issues/5358#issuecomment-499585418)

@kittaakos it seems as though the hosted plugin calls `terminate` or `dispose` each time the app is closed / refreshed. Since there is no hosted plugin currently active, it'd throw an error which is not caught. Instead, my change catches the error and logs it but I felt like there wasn't anything else needed to do as by design it looks like the hosted plugin wanted to dispose each time the app was refreshed. 

What do you think the appropriate fix would be?

**Comment by kittaakos** [comment]
> What do you think the appropriate fix would be?

Let's log an `INFO`; it was not running, nothing to stop. It is considered to be part of the normal lifecycle.

**Comment by vince-fugnitto** [comment]
> Let's log an `INFO`; it was not running, nothing to stop. It is considered to be part of the normal lifecycle.

@kittaakos
I'm sorry, I'm a little confused, I'm already catching and logging it as an `INFO` at the moment.

```
root INFO Hosted plugin instance is not running.
```

**Comment by kittaakos** [comment]
Sorry for the confusion, why do we throw the error here?
https://github.com/theia-ide/theia/blob/b29e615c9d769f793c4a20c4db02b828b78d17ac/packages/plugin-dev/src/node/hosted-instance-manager.ts#L166

You are catching an `any` and try to log its message, which can be `undefined`. Also, if something else throws an error you omit the stacktrace.

**Comment by vince-fugnitto** [comment]
> Sorry for the confusion, why do we throw the error here?
> https://github.com/theia-ide/theia/blob/b29e615c9d769f793c4a20c4db02b828b78d17ac/packages/plugin-dev/src/node/hosted-instance-manager.ts#L166
> 
> You are catching an `any` and try to log its message, which can be `undefined`. Also, if something else throws an error you omit the stacktrace.

Thank you for clarifying, yes I'm not sure why an error is thrown, perhaps @mmorhun can clarify?
Yes unfortunately I had to do that since it was a backend error, I'll have to follow the same design as the `filesystem errors`.

https://github.com/theia-ide/theia/blob/0b1b8532f6f142e3d9746a5f4d644d0a39332cbe/packages/filesystem/src/common/filesystem.ts#L275-L279

**Comment by kittaakos** [comment]
Let's figure out why does this error started to pop-up recently instead of just "swallowing" the error and logging the message. Thoughts?

**Comment by vince-fugnitto** [comment]
> Let's figure out why does this error started to pop-up recently instead of just "swallowing" the error and logging the message. Thoughts?

I agree!

**Comment by mmorhun** [comment]
Hello. Sorry for late response.
I've added throwing of that error to pass it to the client and display corresponding notification to the user. See `hosted-plugin-manager-client.ts`. Probably we should change this mechanism now.
As about recent changes, maybe @evidolob can say something.

**Comment by vince-fugnitto** [comment]
@kittaakos @mmorhun 
I've finally gotten a chance to re-look at the issue and I updated the PR.
The issue is that we were calling `terminate` on `dispose` which gets called for example on reload.
Instead of always calling the method and throwing an error, I first check if there currently is a `hosted instance` running.

I can either perform the check on `dispose` or perform a try-catch, what do you guys think?

**Comment by vince-fugnitto** [comment]
Actually, I think it's best if I do a try-catch, since the `terminate` method already checks for `isRunning` and I can keep a message.

**Comment by lmcbout** [comment]
I see that the message "Hosted plugin instance is not running" is gone, but I have a question: Why do we call "Dispose " when creating a new front-end UI. The call is done in plugin-dev-backend-module (line ~35)  and if there is no existing connection between the client-server, may be the test should be in this area and not call server.dispose if no connection exist?
What do you think !

**Comment by vince-fugnitto** [comment]
> I see that the message "Hosted plugin instance is not running" is gone, but I have a question: Why do we call "Dispose " when creating a new front-end UI. The call is done in plugin-dev-backend-module (line ~35) and if there is no existing connection between the client-server, may be the test should be in this area and not call server.dispose if no connection exist?
> What do you think !

The method `dispose` is not called when a frontend is created, it is called whenever the event `onDidCloseConnection` is fired since we are listening to it and executing the method in the callback.

https://github.com/theia-ide/theia/blob/9395eda975d3c76557a1c36c385ef3e22c3e62e8/packages/plugin-dev/src/node/plugin-dev-backend-module.ts#L35

**Comment by vince-fugnitto** [comment]
@kittaakos are you fine as well with the updated implementation?
