### PR TITLE
GH-4800: Fixed issue when exiting the electron app

### LINKED ISSUE #4800: [electron] unable to quit electron instance due to preference
**Description**

Due to the `application.confirmExit` preference, Electron cannot be closed in the following scenarios:
1. If the preference has the value of `always`.
2. If the preference has the value of `ifRequired` with a dirty editor (unsaved changes).
3. If the preference has the value of `ifRequired` and an extension wishes to prevent exit.

**Reproduction Steps** (Simple Scenario)
1. Start an Electron Theia instance.
2. Confirm that closing the Electron window works.
3. Start another Electron Theia instance.
4. Update the preferences by setting `application.confirmExit` to `always`.
5. Conform that closing the Electron window no longer works.

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #4800.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

File: packages/core/src/browser/frontend-application.ts [hunk 1]
```diff
@@ -251,7 +259,7 @@ export class FrontendApplication {
     /**
      * `beforeunload` listener implementation
      */
-    protected preventStop(): boolean {
+    preventStop(): boolean {
```
Comment (kittaakos) [inline packages/core/src/browser/frontend-application.ts]: @akosyakov, are you OK exposing this as a public method from the frontend application, or shall I introduce a service for this? Thanks!

Comment (akosyakov) [reply packages/core/src/browser/frontend-application.ts]: I would prefer it we abstract `window.addEventListener('beforeunload'` in a new service and implement it for an electron.

Comment (akosyakov) [reply packages/core/src/browser/frontend-application.ts]: Maybe `WindowService` can have an event?

Comment (kittaakos) [reply packages/core/src/browser/frontend-application.ts]: > I would prefer if we abstract `window.addEventListener('beforeunload'` in a new service

👍 

> and implement it for an electron.

The electron implementation is completely different. From `electron.BrowserWindow.on('close')`:
> Emitted when the window is going to be closed. It's emitted before the beforeunload and unload event of the DOM.

So it means, even if we add any logic for both electron and the browser, the electron `app` will quit because it has already received the close event...

But I got the message and I agree. Let's try not to expose it from the `FrontendApplication`. Thanks!

Comment (kittaakos) [reply packages/core/src/browser/frontend-application.ts]: I have made the suggested API changes. From now on, the `WindowService` will now if the window `canUnload`.

**Comment by kittaakos** [comment]
I have just tried it; it works.

**Comment by vince-fugnitto** [comment]
> I have just tried it; it works.

I'll try it again :)

File: packages/core/src/browser/common-frontend-contribution.ts [hunk 2]
```diff
@@ -615,7 +615,7 @@ export class CommonFrontendContribution implements FrontendApplicationContributi
         }
 
         window.document.addEventListener('keydown', event => {
-            this.shouldPreventClose = isCtrlCmd(event) || event.code === 'KeyW';
+            this.shouldPreventClose = isCtrlCmd(event) && event.code === 'KeyW';
```
Comment (AlexTugarev) [inline packages/core/src/browser/common-frontend-contribution.ts]: 🎉 Thanks @kittaakos! This works nicely now.

File: packages/core/src/browser/window/browser-window-module.ts [hunk 3]
```diff
@@ -15,8 +15,11 @@
...
 
 import { ContainerModule } from 'inversify';
-import { DefaultWindowService, WindowService } from '../../browser/window/window-service';
+import { WindowService } from '../../browser/window/window-service';
+import { DefaultWindowService } from '../../browser/window/default-window-service';
+import { FrontendApplicationContribution } from '../frontend-application';
 
 export default new ContainerModule(bind => {
     bind(WindowService).to(DefaultWindowService).inSingletonScope();
+    bind(FrontendApplicationContribution).toService(WindowService);
```
Comment (AlexTugarev) [inline packages/core/src/browser/window/browser-window-module.ts]: Q: `WindowService` is not necessarily a `FrontendApplicationContribution`, so shouldn't this be a service binding to `DefaultWindowService` (with the implication of an additional `DefaultWindowService` binding)

**Comment by AlexTugarev** [comment]
I just tried the electron and the browser example, and it works nicely!

@kittaakos, please rebase when you find the time.

**Comment by kittaakos** [comment]
> sorry I took so long to take a look and test the fix, it looks like the changes mean we still don't respect the preference `application.confirmExit`. Usually this preference means users will be prompted to confirm if they truly wish to exit the application (for instance if there are unsaved changes).

After merging the `master` into this branch to fix the merge conflicts, it does not work for me either. This could be related: https://github.com/theia-ide/theia/issues/5385. Something has been messed up :(

**Comment by AlexTugarev** [comment]
@kittaakos, I've tested the latest update on this branch and it still works nicely for me!

browser example:
 - confirmExit: always ✔️ 
 - confirmExit: ifRequired ✔️ 
 - confirmExit: never ✔️ 

electrong example:
 - confirmExit: always ✔️ 
 - confirmExit: ifRequired ✔️ 
 - confirmExit: never ✔️

**Comment by kittaakos** [comment]
> I've tested the latest update on this branch and it still works nicely for me!

I will try it once more and merge the changes if it works.

**Comment by kittaakos** [comment]
It worked. I accidentally enabled the auto-save last time, and that's why the `ifRequired` case did not happen.
