### PR TITLE
Catch electron-store errors

### LINKED ISSUE #4551: [electron] Exception in main process when resizing window
### Description
I get the following dialog when moving or resizing the window of the Electron example.

screenshot01

**OS version:**

Windows 7 Enterprise

### PR DESCRIPTION
**Pull request by spoenemann**
Fixes #4551.

 * Catch errors thrown by `electron-store` while saving the window state.
 * Added `setTimeout` to decrease the number of save operations. This significantly reduces the frequency of thrown errors.
 * When the window is maximized, don't store its bounds, but keep the previously stored bounds instead. This way the previous bounds are restored when unmaximizing.
 * Simplified parts of the code.

### CODE REVIEW

File: dev-packages/application-manager/src/generator/frontend-generator.ts [hunk 1]
```diff
@@ -183,19 +183,36 @@ if (isMaster) {
...
+                    });
+                } catch (e) {
+                    console.error("Error while saving window state.", e);
+                }
+            };
+            let delayedSaveTimeout;
+            const saveWindowStateDelayed = () => {
+                if (delayedSaveTimeout) {
+                    clearTimeout(delayedSaveTimeout);
+                }
```
Comment (jankeromnes) [inline dev-packages/application-manager/src/generator/frontend-generator.ts]: Nit: You don't need to check for `if (delayedSaveTimeout)`, because [Passing an invalid ID to `clearTimeout()` silently does nothing; no exception is thrown.](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearTimeout#Notes)

Or, if you really want to implement an `if`, please fix the logic by setting `delayedSaveTimeout = undefined` after clearing the timeout.

File: dev-packages/application-manager/src/generator/frontend-generator.ts [hunk 2]
```diff
@@ -183,19 +183,36 @@ if (isMaster) {
...
+                        height: bounds.height,
+                        x: bounds.x,
+                        y: bounds.y
+                    });
+                } catch (e) {
+                    console.error("Error while saving window state.", e);
+                }
+            };
+            let delayedSaveTimeout;
+            const saveWindowStateDelayed = () => {
```
Comment (jankeromnes) [inline dev-packages/application-manager/src/generator/frontend-generator.ts]: Nit: I think the correct term for "Delayed" is ["Debounced"](https://davidwalsh.name/javascript-debounce-function). If you agree, you could replace all occurrences of "Delayed" with "Debounced".

**Comment by marechal-p** [comment]
Does that mean that in the case where you would get an error, it wouldn't crash but it also wouldn't actually save the geometry?

File: dev-packages/application-manager/src/generator/frontend-generator.ts [hunk 3]
```diff
@@ -183,19 +183,36 @@ if (isMaster) {
...
+                if (delayedSaveTimeout) {
+                    clearTimeout(delayedSaveTimeout);
+                }
+                delayedSaveTimeout = setTimeout(saveWindowState, 1000);
```
Comment (jankeromnes) [inline dev-packages/application-manager/src/generator/frontend-generator.ts]: Why did you choose 1000ms for debouncing? As a user, I find such a delay extremely long (and would prefer something faster like 200ms).

File: dev-packages/application-manager/src/generator/frontend-generator.ts [hunk 4]
```diff
@@ -183,19 +183,36 @@ if (isMaster) {
...
-            }
-            newWindow.on('close', saveState);
-            newWindow.on('resize', saveState);
-            newWindow.on('move', saveState);
+            // Save the window geometry state on every change
+            const saveWindowState = () => {
+                try {
+                    let bounds;
+                    if (newWindow.isMaximized()) {
+                        bounds = electronStore.get(WINDOW_STATE, {});
```
Comment (jankeromnes) [inline dev-packages/application-manager/src/generator/frontend-generator.ts]: What is the point of re-doing `electronStore.get(WINDOW_STATE, {})` when the window is maximized? Also:

- Couldn't you just re-use `windowState` from above?

- It seems your are calling `electronStore.set()` with the same values you got from `electronStore.get()`. Maybe just skip saving window state when it's maximized?

**Comment by spoenemann** [comment]
Correct, but it might save the geometry on the next call of that function.

I have not been able to find out what is the root cause of the problem, and I doubt that would be feasible because it occurs only in a very specific environment, not on every Windows system. So you could argue that my change does not actually fix #4551, but at least it makes sure that the error is not propagated to the user and that the error becomes so rare that the geometry is stored "often enough".

**Comment by marechal-p** [comment]
https://github.com/sindresorhus/electron-store/issues/31#issuecomment-445156620

Maybe just a case of adding a debouncer?

File: dev-packages/application-manager/src/generator/frontend-generator.ts (hunk 1 above)
Comment (spoenemann) [reply dev-packages/application-manager/src/generator/frontend-generator.ts]: The link you provided points to the web API. Does it also hold for the Node.js API?

**Comment by marechal-p** [comment]
Which you did, didn't see the `setTimeout` before, my bad :)

File: dev-packages/application-manager/src/generator/frontend-generator.ts (hunk 3 above)
Comment (spoenemann) [reply dev-packages/application-manager/src/generator/frontend-generator.ts]: Yes, it happens in the background. The delay should be long enough to avoid file system problems on Windows.

File: dev-packages/application-manager/src/generator/frontend-generator.ts (hunk 4 above)
Comment (spoenemann) [reply dev-packages/application-manager/src/generator/frontend-generator.ts]: > What is the point of re-doing `electronStore.get(WINDOW_STATE, {})` when the window is maximized?

It makes sure that the bounds are kept, so after unmaximizing we get the same bounds we had before maximizing.

> Couldn't you just re-use windowState from above?

No, the stored bounds might have been changed in the meantime. We could write the bounds into the local variable on every store operation if we want to avoid the additional `get`.

> It seems your are calling electronStore.set() with the same values you got from electronStore.get().

No, the `isMaximized` property is changed.

File: dev-packages/application-manager/src/generator/frontend-generator.ts (hunk 2 above)
Comment (spoenemann) [reply dev-packages/application-manager/src/generator/frontend-generator.ts]: I think both terms are valid...
