### PR TITLE
Pass the DOM element as first argument to context menu command handlers

### LINKED ISSUE #1923: `Close All` closes tabs on the wrong side bar
It happens if a sidebar tab for which the context menu was triggered does not have focus.

### PR DESCRIPTION
**Pull request by spoenemann**
Fixes #1923.

When commands are called via context menu, their handlers get the DOM node that was right-clicked as first argument.

When commands are called via keybinding, the handlers fall back to the previous behavior of using the global `shell.currentWidget`.

### CODE REVIEW

**Comment by akosyakov** [comment]
@spoenemann DCO check

**Comment by akosyakov** [comment]
I cannot reproduce it only with `Plugins` view, since it has a bug https://github.com/theia-ide/theia/issues/4542.

But generally i like an improvement that commands get DOM context.

File: packages/core/src/browser/shell/application-shell.ts [hunk 1]
```diff
@@ -744,6 +744,34 @@ export class ApplicationShell extends Widget {
         }
     }
 
+    /**
+     * Find the widget that contains the given HTML element. The returned widget may be one
+     * that is managed by the application shell, or one that is embedded in another widget and
+     * not directly managed by the shell, or a tab bar.
+     */
+    findWidgetForElement(element: HTMLElement): Widget | undefined {
```
Comment (akosyakov) [inline packages/core/src/browser/shell/application-shell.ts]: How about:
```ts
for (const widget of this.widgets) {
    if (widget.node.contains(element)) {
        return widget;
    }
}
```

Comment (spoenemann) [reply packages/core/src/browser/shell/application-shell.ts]: That would not pick up widgets that are not tracked by the shell, such as tab bars.
