### PR TITLE
editorconfig: Apply properties to Monaco editor when opening/switching editor

### LINKED ISSUE #4308: editorconfig not working as expected
The `.editorconfig` file at the top of my workspace has no effect on any file.
See this screenshot, `foo.tsx` is not getting the indentation right:
image
My `package.json`:
```
{
  "private": true,
  "dependencies": {
    "@theia/callhierarchy": "latest",
    "@theia/editorconfig": "^0.3.19",
    "@theia/file-search": "latest",
    "@theia/git": "latest",
    "@theia/json": "latest",
    "@theia/markers": "latest",
    "@theia/merge-conflicts": "latest",
    "@theia/messages": "latest",
    "@theia/mini-browser": "^0.3.19",
    "@theia/navigator": "latest",
    "@theia/outline-view": "latest",
    "@theia/preferences": "latest",
    "@theia/preview": "latest",
    "@theia/python": "latest",
    "@theia/search-in-workspace": "latest",
    "@theia/terminal": "latest",
    "@theia/textmate-grammars": "latest",
    "@theia/typescript": "latest",
    "typescript": "latest"
  },
  "devDependencies": {
    "@theia/cli": "latest"
  }
}
```

### PR DESCRIPTION
**Pull request by simark**
Since commit 260d79499823 ("[editorconfig] Don't apply all properties on
open"), the editorconfig settings are not applied to the Monaco editor.
For example, if my .editorconfig file says that *.py files should use
tabs with a tab width of 7, I would expect the Monaco editor to be set
to "tab" and a tab width of 7 when I open a .py file.  At the moment,
this does not happen.

The method that applies these properties to the Monaco editor is
applyProperties.  This method is however not called anywhere outside
tests (the commit mentioned above removed the only call).

I have added back the call, such that when an editor is created or the
current editor changes, we apply the settings from the .editorconfig to
the Monaco editor.

I verified that the behavior the commit mentioned above meant to fix is
kept.  That is, no modification is done to the file contents as a result
of just opening the file (or switching to and editor where it is open).
Even if I have "trim_trailing_whitespace = true" in my .editorconfig,
opening the file does not cause the trailing whitespaces to be trimmed.
Pressing ctrl-s, however, does (even if the editor doesn't appear as
"dirty").

Fixes #4308

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>

### CODE REVIEW

**Comment by simark** [comment]
@adrienrenaud, could you give this a try?

File: packages/editorconfig/src/browser/editorconfig-document-manager.ts [hunk 1]
```diff
@@ -98,6 +98,7 @@ export class EditorconfigDocumentManager {
             const uri = editor.uri.toString();
             this.editorconfigServer.getConfig(uri).then(properties => {
                 this.properties[uri] = properties;
+                this.applyProperties(properties, editor);
```
Comment (akosyakov) [inline packages/editorconfig/src/browser/editorconfig-document-manager.ts]: @svenefftinge Did you remove it on purpose?

Comment (AlexTugarev) [reply packages/editorconfig/src/browser/editorconfig-document-manager.ts]: I think this change is ok, otherwise settings like [`end_of_line`](https://github.com/editorconfig/editorconfig/wiki/Plugin-Guidelines#end_of_line) won't work as expected.

Comment (akosyakov) [reply packages/editorconfig/src/browser/editorconfig-document-manager.ts]: pl

**Comment by simark** [comment]
Ping.

**Comment by AlexTugarev** [comment]
I'm testing it right now.

**Comment by simark** [comment]
> I'm testing it right now.

Thanks!

**Comment by AlexTugarev** [comment]
Unfortunately, the effect of this change is super weird. I guess it's colliding with the settings when trying with e.g. [`intend_size`](https://github.com/editorconfig/editorconfig/wiki/Plugin-Guidelines#indent_size). In the debugger I could see, this change was applied to the monaco model, but the change was not visible. On save it was then updated. (Undo appended a new empty line at the end, which might be just a follow up error.)

**Comment by simark** [comment]
Sorry, I don't understand the problem you are trying to describe.

**Comment by AlexTugarev** [comment]
The confit is not applied when opening the editor. In that case I‘ve added indent_size for json finds, but there seems to be no effect on open, only on save.

**Comment by simark** [comment]
> The confit is not applied when opening the editor. In that case I‘ve added indent_size for json finds, but there seems to be no effect on open, only on save.

Can you define what you mean by "the config is not applied".

What I expect my editor to do is just set the whitespace settings to what's defined in the .editorconfig file, such that when I'll press tab, or ask it to auto-format, it will use these settings.  But I don't expect the editor to modify the content of the file to match what's in the .editorconfig file just when I open a file.

So let's say your .editorconfig says to use indentation of 4 spaces for json files.  You open a json file that is currently indented with 2-spaces indents.  Opening the file should *not* change the file content to now have 4 spaces.  However, the whitespace settings (what you see in the status bar) should say "4 spaces".  If you ask Theia to auto-format the file (or save while having "format on save enabled"), it should do so using 4 spaces.

The behavior with this patch applied matches what I expect.  If you think the behavior is not the one we should have, please state clearly which steps you take, which behavior you see, and which behavior you would expect to see.

**Comment by AlexTugarev** [comment]
You are right! It works as expected. The insertion of a new line on undo is a separate issue.

**Comment by simark** [comment]
Ah ok I see what you mean by "undo" inserted a new line.  It doesn't look related to this patch.

**Comment by simark** [comment]
Thanks for the reviews, I am merging it.
