### PR TITLE
fix #5917: normalize the path of terminal link before openning it

### LINKED ISSUE #5917: Possible to open multiple editors for a file
### Description

It's possible to open multiple editors for one file by clicking terminal links with different paths but all lead to the single file.

duplicate-file-editor

### Reproduction Steps

**OS and Theia version:**
Ubuntu 18.04
Theia b23e3ccd53695df4c539a984655941456590367d

**Diagnostics:**

### PR DESCRIPTION
**Pull request by a1994846931931**
Signed-off-by: Cai Xuye <a1994846931931@gmail.com>

#### What it does
Normalize the paths of file links contributed by terminals to avoid opening multiple editors for the same file.

#### How to test
1. Create a new file, e.g. named package.json and open it
2. Print some file links in the terminal, for example:
  - run `echo "./package.json"`
  - run `echo ".///package.json"`
  - run `echo "../${parent}/package.json"`
  - run `echo "/${absolute/path/to/package.json}"`
3. Ctrl/cmd+click open these links and see if they all activate the same editor opened in step 1

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by a1994846931931** [comment]
I currently fix it in the `terminal-linkmatcher-files` level. But we can also do it in `EditorManager.open` and convert all URI parameters to normalized ones. Which one is better? Is there a situation where these URIs that actually refer to the same file SHOULD be regarded as different ones?

File: packages/terminal/src/browser/terminal-linkmatcher-files.ts [hunk 1]
```diff
@@ -86,12 +88,12 @@ export class TerminalLinkmatcherFiles extends AbstractCmdClickTerminalContributi
...
-        const path = await this.extractPath(match);
-        if (!path) {
+        const extractedPath = await this.extractPath(match);
+        if (!extractedPath) {
             return;
         }
-        const pathObj = new Path(path);
-        return pathObj.isAbsolute ? cwd.withPath(path) : cwd.resolve(path);
+        const pathObj = new Path(extractedPath);
+        return pathObj.isAbsolute ? cwd.withPath(extractedPath) : cwd.resolve(extractedPath);
```
Comment (a1994846931931) [inline packages/terminal/src/browser/terminal-linkmatcher-files.ts]: This refactor is to avoid `[tslint] Shadowed name: 'path' (no-shadowed-variable)` error, which comes from the introduction of Node.JS path module.

**Comment by akosyakov** [comment]
We cannot use Node.js apis, i.e. `path` module, in browser module. We either have to call to the server for normalization or our `Path` should implement `normalize` method, maybe using some existing npm package.

**Comment by a1994846931931** [comment]
> We cannot use Node.js apis, i.e. `path` module, in browser module. We either have to call to the server for normalization or our `Path` should implement `normalize` method, maybe using some existing npm package. Although i am not sure whether `normalize` method should be aware about backend operating system, if so then it can be done only by backend, i.e. paths should not be normalized against frontend OS.

@akosyakov Code updated. Changes include:

1. Normalize `uri` for all `NavigatableWidgetOpenHandler` (instead of normalization in `EditorManager` or link-matcher)
2. `Path.normalize` is implemented. Corresponding tests are added to `path.spec.ts` as well.

**Comment by a1994846931931** [comment]
Theia's `Path` supports both POSIX and Windows, but I have only tested it on Ubuntu. Could anyone try to test it on other platforms? @akosyakov

**Comment by akosyakov** [comment]
@a1994846931931 cool! actually i don't think we need to caret about POSIX and Windows, our URI always normalize path to use `/` as a separator, so it should not be platform dependent

I'm testing it now.

File: packages/core/src/browser/navigatable.ts [hunk 2]
```diff
@@ -87,7 +88,7 @@ export abstract class NavigatableWidgetOpenHandler<W extends NavigatableWidget>
     }
 
     protected serializeUri(uri: URI): string {
-        return uri.withoutFragment().toString();
+        return Path.normalize(uri.withoutFragment().toString());
```
Comment (akosyakov) [inline packages/core/src/browser/navigatable.ts]: `Path.nozmalize` should be applied only top the path, i.e.
`uri.withoutFragment().withPath(Path.normalize(uri.path)).toString`

alternatively we can `normalizePath` to a URI for a shortcut, i.e. `uri.normalizePath().withoutFragment().toString()`

Comment (akosyakov) [reply packages/core/src/browser/navigatable.ts]: actually having `normalize` on `Path` is good as well, it should return though another instance of `Path`

Comment (a1994846931931) [reply packages/core/src/browser/navigatable.ts]: > actually having `normalize` on `Path` is good as well, it should return though another instance of `Path`

Yes, I agree. I initially made `normalize` a static method which takes in a string and returns the normalized one because that's how Node.JS path implement it. But then I just realized that Node.JS path is quite different from ours.

How about making `normalize` a member function, i.e.
```typescript
normalize(): Path;
```

Comment (akosyakov) [reply packages/core/src/browser/navigatable.ts]: yes, i like it

**Comment by akosyakov** [comment]
@a1994846931931 i will invite you to Theia org as a contributor and after merging your PRs nominate as Theia committer. Quality of you PRs is superb!

**Comment by a1994846931931** [comment]
> @a1994846931931 i will invite you to Theia org as a contributor and after merging your PRs nominate as Theia committer. Quality of your PRs is superb!

Hey, thanks! It's a great honor!

File: packages/core/src/browser/navigatable.ts [hunk 3]
```diff
@@ -87,7 +87,7 @@ export abstract class NavigatableWidgetOpenHandler<W extends NavigatableWidget>
     }
 
     protected serializeUri(uri: URI): string {
-        return uri.withoutFragment().toString();
+        return uri.withoutFragment().path.normalize().toString();
```
Comment (akosyakov) [inline packages/core/src/browser/navigatable.ts]: it should return a serialized uri, not a path. Please use `withPath(path.normalize)` or add `normalizePath(): URI` to `URI` which does it

Comment (a1994846931931) [reply packages/core/src/browser/navigatable.ts]: @akosyakov Do you mean that finally, this line should be like
```return uri.withoutFragment().normalizePath().toString();```?

Comment (a1994846931931) [reply packages/core/src/browser/navigatable.ts]: And in `URI`, `normalizePath` would be like
```typescript
    normalizePath(): URI {
        return new URI(this.path.normalize().toString());
    }
```

Comment (akosyakov) [reply packages/core/src/browser/navigatable.ts]: yes

Comment (a1994846931931) [reply packages/core/src/browser/navigatable.ts]: @akosyakov OK. Code updated now.
