### PR TITLE
Fix 'enter' not working in the editor

### LINKED ISSUE #5891: Enter is not working in editor
### Description
Enter is not working in editor

### Reproduction Steps
Open some file and try to use Enter button.

**OS and Theia version:**
Ubuntu 18.04. Chrome.
0953ba77fe0b9c90bd7c122355acedc177ea5d0b

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does
Fixes #5891

- fixes an issue where the `enter` key no longer works in the editor.
- caused by a regression present in the `dialog.ts#handleEnter` method
which was not returning `false` if a dialog was not present.

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

#### How to test
- open an editor and attempt to add new lines using <kbd>enter</kbd>

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

File: packages/core/src/browser/dialogs.ts [hunk 1]
```diff
@@ -94,13 +94,15 @@ export class DialogOverlayService implements FrontendApplicationContribution {
         if (dialog) {
             dialog['handleEscape'](event);
```
Comment (akosyakov) [inline packages/core/src/browser/dialogs.ts]: here it should also return and for `handleEnter` as well
