### PR TITLE
refresh GitView when git repo changes

### LINKED ISSUE #3988: [Git] Git view shows data from another frontend workspace
Seems the data in the Git view is not workspace dependent.  I have two workspace open in separate tab and when I look at the changes in the GIT view from one workspace or the other, I see all changes from both workspaces.  One workspace, I have Theia and in the second workspace, I have "org.eclipse.egerrit", but in the GIT view, from any of two workspaces, I see the modified files from "org.eclipse.egerrit".

Note: running one backend with two frontends workspace on separate tabs.

gitdataoverlapsworkspace

### LINKED ISSUE #4107: git multi repos support is not reliable
I am working with nested repos recently and often ends up in situations when the status bar shows one repo, but the view another. When i try to run some git operations via UI then, it fails.

We should single source state in the view and status bar.

### LINKED ISSUE #4219: [git] Selected repository is not updated when opening multiple workspaces
Steps to reproduce:
 - Open a workspace.
 - Open another workspace but keep the previous as well.
 - Git shows the first workspace roots as the selected repository for both workspaces.

### PR DESCRIPTION
**Pull request by elaihau**
- With current theia code, GitView could be initialised with incorrect repository, and it fails to change its internal state when the right repository is found. With this change, GitView is refreshed if and only if the active git repository changes.
- fixed #3988
- fixed #4219

Signed-off-by: elaihau <liang.huang@ericsson.com>

### CODE REVIEW

File: packages/git/src/browser/git-widget.tsx [hunk 1]
```diff
@@ -85,28 +86,29 @@ export class GitWidget extends GitDiffWidget implements StatefulWidget {
 
     @postConstruct()
     protected init() {
-        this.toDispose.push(this.repositoryProvider.onDidChangeRepository(repository =>
```
Comment (akosyakov) [inline packages/git/src/browser/git-widget.tsx]: Why should it go in `initialize` method? Does it depend on `repository`?

**Comment by akosyakov** [comment]
`GitRepositoryProvider` is responsible for tracking a selected repository already. Why should it be duplicated in the widget? The real fix will be to make sure that `repository` is always used (by all Git UI) from `GitRepositoryProvider` and there is no race conditions, i.e. Git UI is not using a repository (via local variable in async code) which already is not a selected repository in `GitRepositoryProvider`.

File: packages/git/src/browser/git-widget.tsx (hunk 1 above)
Comment (elaihau) [reply packages/git/src/browser/git-widget.tsx]: `initialize` is just a function called by `init`, not the special one from `FrontendApplicationContribution`.

the state of the GitWidget is dependent on the value of `RepositoryProvider.selectedRepository` which can be changed by the users when theia is running. Every time `selectedRepository` changes, we need to refresh `GitWidget` to display the correct data.

The reason that i am moving this line into `initialize` function is that `toDispose.dispose()` from `initialize` disposes what this line does. and with the code before my change, the state of GitWidget would be out of sync with the rest of theia unless the user manually refreshes the widget.

**Comment by elaihau** [comment]
> `GitRepositoryProvider` is responsible for tracking a selected repository already. Why should it be duplicated in the widget? The real fix will be to make sure that `repository` is always used (by all Git UI) from `GitRepositoryProvider` and there is no race conditions, i.e. Git UI is not using a repository (via local variable in async code) which already is not a selected repository in `GitRepositoryProvider`.

I agree with you Anton. Please correct me if i am wrong:

I don't think changes in this PR have conflicts with what you described.

The change in this PR does not duplicate the job that `GitRepositoryProvider` does. Line 99 reacts to the `onDidChangeRepository` event to make sure the widget displays data from the repo that the user is working on, while Line 96 keeps the state of widget to avoid unnecessary refreshes.

**Comment by akosyakov** [comment]
> The change in this PR does not duplicate the job that `GitRepositoryProvider` does.

It duplicate the state, `GitWidget` should not store a selected repository as a property and sync it with `GitRepositoryProvider`, but just always use it from `GitRepositoryProvider`.

**Comment by elaihau** [comment]
> > The change in this PR does not duplicate the job that `GitRepositoryProvider` does.
> 
> It duplicate the state, `GitWidget` should not store a selected repository as a property and sync it with `GitRepositoryProvider`, but just always use it from `GitRepositoryProvider`.

Well, I don't have to store the selected repository in `GitWidget`. The code would work properly if I remove the following 2 lines:

```ts
        if (!Repository.equal(repository, this.activeRepository)) {
            this.activeRepository = repository;
```

the selected repository is store just to reduce the number of refreshes. If we refresh the widget more than needed, the widget would still have the correct data.

File: packages/git/src/browser/git-widget.tsx [hunk 2]
```diff
@@ -85,28 +86,29 @@ export class GitWidget extends GitDiffWidget implements StatefulWidget {
...
-                        this.lastHead = gitEvent.status.currentHead;
-                        this.lastCommit = gitEvent.status.currentHead ? await this.getLastCommit() : undefined;
+            if (repository) {
+                this.toDispose.push(this.repositoryProvider.onDidChangeRepository(newRepository => this.initialize(newRepository)));
+                this.toDispose.push(await this.gitWatcher.watchGitChanges(repository));
+                this.toDispose.push(this.gitWatcher.onGitEvent(async gitEvent => {
+                    if (GitStatusChangeEvent.is(gitEvent)) {
+                        if (gitEvent.status.currentHead !== this.lastHead) {
+                            this.lastHead = gitEvent.status.currentHead;
+                            this.lastCommit = gitEvent.status.currentHead ? await this.getLastCommit() : undefined;
```
[the remark this answers is not in the document]
Comment (elaihau) [reply packages/git/src/browser/git-widget.tsx]: Sure. I can remove `this.activeRepository` and use the repositoryProvider only.

File: packages/git/src/browser/git-widget.tsx [hunk 3]
```diff
@@ -85,17 +85,17 @@ export class GitWidget extends GitDiffWidget implements StatefulWidget {
...
+            this.toDispose.dispose();
+            this.initialize(newRepository);
+        }));
         this.gitNodes = [];
         this.update();
     }
 
     async initialize(repository: Repository | undefined): Promise<void> {
         if (repository) {
-            this.toDispose.dispose();
```
Comment (akosyakov) [inline packages/git/src/browser/git-widget.tsx]: Could you just move this line up before if and revert all other changes?

**Comment by akosyakov** [comment]
This PR does not fix #4107, see https://github.com/theia-ide/theia/issues/4107#issuecomment-460918123

screen shot 2019-02-06 at 07 45 45

Please update the commit message, that this issue does not get closed automatically.

**Comment by akosyakov** [comment]
#3988 and #4129 seem to be addressed, but better if @kittaakos and @lmcbout double check it

File: packages/git/src/browser/git-widget.tsx (hunk 3 above)
Comment (elaihau) [reply packages/git/src/browser/git-widget.tsx]: sorry, if i do that, ` this.toDispose.push(this.repositoryProvider.onDidChangeRepository(callback))` would be disposed when GitWidget is initialized.

Comment (elaihau) [reply packages/git/src/browser/git-widget.tsx]: although changing a single line wouldn't work, but I can 
1) reverse the order of `this.initialize(...)` and `this.toDispose.push(this.repositoryProvider.onDidChangeRepository(callback))`, and 
2) move this line up

do you prefer this solution than the current change?

Comment (akosyakov) [reply packages/git/src/browser/git-widget.tsx]: now, I understand your struggle, sorry took a while :)

`this.toDispose` should be only used to dispose the entire widget, not on each initialize.

Could you create a new `DisposableCollection` for `initialize` method, something like:
```ts
protected readonly toDisposeOnInitialize = new DisposableCollection();
toDisposeOnInitialize().. {
   this.toDisposeOnInitialize.dispose();
   this.toDispose.push(this.toDisposeOnInitialize);
   ... // use toDisposeOnInitialize below not toDispose
   this.toDisposeOnInitialize.push(this.gitWatche...);
}
```

Comment (elaihau) [reply packages/git/src/browser/git-widget.tsx]: i made the change that follows your design. please check if when you get the chance. Thank you for the review !

File: packages/git/src/browser/git-widget.tsx [hunk 4]
```diff
@@ -94,10 +98,10 @@ export class GitWidget extends GitDiffWidget implements StatefulWidget {
     }
 
     async initialize(repository: Repository | undefined): Promise<void> {
+        this.toDisposeOnInitialize.dispose();
```
Comment (akosyakov) [inline packages/git/src/browser/git-widget.tsx]: It will delete itself from all disposable collections, so you should to add it `this.toDispose` again on next line.

Comment (elaihau) [reply packages/git/src/browser/git-widget.tsx]: please correct me if i am wrong:

having `this.toDispose.push(this.toDisposeOnInitialize)` in the `initialize()` function would push one reference of `this.toDisposeOnInitialize` to `this.toDispose` every time GitWidget refreshes, and that would potentially leave many references of the same thing (i.e., `this.toDisposeOnInitialize`) in `this.toDispose` - it does not hurt, but it is not necessary.

i did some debugging and found `this.toDisposeOnInitialize.dispose()` removed all elements from `this.toDisposeOnInitialize.disposables` array, and leave elements in `this.toDispose.disposables` untouched. so i guess this line will not delete itself from `this.toDispose`.

Comment (akosyakov) [reply packages/git/src/browser/git-widget.tsx]: `DisposableCollection` remove any disposable which gets disposed to avoid disposing it again: https://github.com/theia-ide/theia/blob/87ad22b5da0598fc9d40ee422b053457adbf8a4d/packages/core/src/common/disposable.ts#L86

Comment (elaihau) [reply packages/git/src/browser/git-widget.tsx]: thank you for explaining ! i updated the PR.
