### PR TITLE
GH-5284: Debounced the menu update for electron.

### LINKED ISSUE #5284: [electron] improve startup performance
**Description**

This is an epic issue to discuss and tackle improving the startup performance for Electron.
Currently, starting an Electron application can take considerable time, therefore we should take measures to actively tackle performance issues on Electron, and consequently improve the overall performance and speed of the entire application.

**Considerations**
1. lazy load components which aren't necessary at startup.
2. improve minimization and compression.
3. revisit references of `initialize`, `initializeLayout` and `onStart`.
4. other ideas.

**Steps to Reproduce**

Created a streamlined Electron application ([**`package.json`**](https://gist.github.com/vince-fugnitto/3a77be12255c616efb331b110e96cd21)) and build it using:

```console
(yarn && yarn theia build --mode production && yarn theia rebuild:electron)
```

```json
{
    "private": true,
    "license": "EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0",
    "theia": {
        "target": "electron",
        "frontend": {
            "config": {
                "applicationName": "Theia Electron"
            }
        }
    },
    "dependencies": {
        "@theia/core": "next",
        "@theia/editor": "next",
        "@theia/electron": "next",
        "@theia/file-search": "next",
        "@theia/filesystem": "next",
        "@theia/monaco": "next",
        "@theia/navigator": "next",
        "@theia/preferences": "next",
        "@theia/search-in-workspace": "next",
        "@theia/terminal": "next",
        "@theia/textmate-grammars": "next",
        "@theia/typescript": "next",
        "@theia/workspace": "next",
        "typescript": "latest"
    },
    "devDependencies": {
        "@theia/cli": "next"
    }
}
```

**Results**

| Command | Description | # 1 (sec) | # 2 (sec) | # 3 (sec) | Avg (sec) |
|:---:|:---:|:---:|:---:|:---:|:---:|
| `yarn theia start` | Start application without a workspace | 3.66 | 3.73 | 3.65 | **3.68** | 
| `yarn theia start ~/theia-workspace-theia` | Start application w/ a workspace | 15.45 | 12.91 | 13.12 | **13.83** |

The performance degrades as more extensions are present, and if a workspace is opened on start-up which leads me to believe there might be an extension which slows down the startup or waits for other contributions to be ready.

If anyone had ideas on how the performance can be improved, please let me know :smiley: 

cc @marcdumais-work @marechal-p @lmcbout @thegecko @kittaakos 

----

**Updates**

| Type | Scenario | Time |
|:---|:---|:---|
| **`onStart`** | No Workspace | [560 ms ](https://gist.github.com/vince-fugnitto/d3e9e887dfc1e69d916008862c6e58b7) |
| **`onStart`** | Workspace | [17016 ms ](https://gist.github.com/vince-fugnitto/eb29ab96f865a64d3d244ce13673b421)|

| Target | Time |
|:---|:---:|
| Browser | [time](https://gist.github.com/vince-fugnitto/997656d5af5a41cab8a98c00c77c0456) |
| Electron | [time](https://gist.github.com/vince-fugnitto/53dc6e3275cdba27d67e32b51cea697e)|

### PR DESCRIPTION
**Pull request by kittaakos**
At application startup, we send out thousands of preference change
events. Each of them triggers a menu update. It seems to be expensive.
Debounced it.

Closes #5284.

Before:
Screen Shot 2019-06-06 at 22 44 45

After:
Screen Shot 2019-06-06 at 22 43 46

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

File: packages/core/src/electron-browser/menu/electron-main-menu-factory.ts [hunk 1]
```diff
@@ -39,12 +40,12 @@ export class ElectronMainMenuFactory {
...
         @inject(KeybindingRegistry) protected readonly keybindingRegistry: KeybindingRegistry
     ) {
-        preferencesService.onPreferenceChanged(() => {
+        preferencesService.onPreferenceChanged(debounce(() => {
             for (const item of this._toggledCommands) {
                 this._menu.getMenuItemById(item).checked = this.commandRegistry.isToggled(item);
-                electron.remote.getCurrentWindow().setMenu(this._menu);
             }
-        });
+            electron.remote.getCurrentWindow().setMenu(this._menu);
```
Comment (AlexTugarev) [inline packages/core/src/electron-browser/menu/electron-main-menu-factory.ts]: nice catch!
