### PR TITLE
fix the workspace pref not being applied on change

### LINKED ISSUE #4811: [workspace] misleading `isMultiRootWorkspaceOpened` implementation
The following implementation for the method `isMultiRootWorkspaceOpened()` is misleading.
https://github.com/theia-ide/theia/blob/a27cbd0bfcc03ccc36044e51c6bd341d7f5eb93a/packages/workspace/src/browser/workspace-service.ts#L267-L269

The method checks whether there is a workspace opened and that the preference is on. 
This is a false positive and does not accurately describe if a multi-root workspace is in fact opened.

Additional checks should be made to verify the source of the workspace 
(for example being a `*.theia-workspace` file) or a directory (single root).

@elaihau your thoughts?

### LINKED ISSUE #5446: Not all changes to workspace preference take effect
### Description

Changes to **some** preferences don't take effect. 

### Reproduction Steps

1. open preference editor
2. update `git.decorations.colors` in the "User" tab of pref editor. At this point, changes take effect. Everything looks normal.
3. switch to the "Workspace" tab of pref editor. Update `git.decorations.colors`.

what happens: Changes in the "Workspace" tab don't take effect
expected: changes in the "Workspace" tab should take effect, as Workspace preferences should override those in User preference.

Peek 2019-06-13 08-26

**OS and Theia version:**

Gitpod. Chrome browser. This problem can also be reproduced in the example browser running in Chrome, Ubuntu 16.04.

Theia version: master branch as of June 13 2019 https://github.com/theia-ide/theia/tree/741876b3ecba8a968ecf1200eb231639eb3b4074

**Diagnostics:** 

1. Changes made to `editor.font` in "Workspace" tab worked properly.

2. Changes made to `git.decorations.colors` in the "Workspace" tab fires [resource.onDidChangeContents](https://github.com/theia-ide/theia/blob/741876b3ecba8a968ecf1200eb231639eb3b4074/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L55), and there are no logical issues in [the preference change handler](https://github.com/theia-ide/theia/blob/741876b3ecba8a968ecf1200eb231639eb3b4074/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L188) either. Error occurred in [this line](https://github.com/theia-ide/theia/blob/741876b3ecba8a968ecf1200eb231639eb3b4074/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L201), where `this.getScope()` returns 3 on the change made to the "Workspace" tab and schemaValidator considered it invalid.

### PR DESCRIPTION
**Pull request by elaihau**
fix the workspace pref not being applied on change    
    
- FolderPreferenceProvider should be associated with PreferenceScope.Workspace when it is used as a delegate of WorkspacePreferenceProvider in a one-folder workspace, otherwise changes made to the workspace preferences would not be applied to the IDE.
- fixed #5446
    
Signed-off-by: elaihau <liang.huang@ericsson.com>

added WorkspaceService.isMultiRootWorkspaceEnabled()
    
- fixed #4811

Signed-off-by: elaihau <liang.huang@ericsson.com>

### CODE REVIEW

File: packages/preferences/src/browser/folder-preference-provider.ts [hunk 1]
```diff
@@ -36,9 +37,10 @@ export class FolderPreferenceProvider extends AbstractResourcePreferenceProvider
 
     readonly folderUri: URI;
 
+    @inject(WorkspaceService) protected readonly workspaceService: WorkspaceService;
+
     constructor(
-        @inject(FolderPreferenceProviderOptions) protected readonly options: FolderPreferenceProviderOptions,
-        @inject(FileSystem) protected readonly fileSystem: FileSystem
+        @inject(FolderPreferenceProviderOptions) protected readonly options: FolderPreferenceProviderOptions
```
Comment (elaihau) [inline packages/preferences/src/browser/folder-preference-provider.ts]: @akosyakov I am breaking the constructor. and as you can see, it is not a necessary change. 
are you ok with it ?

File: packages/workspace/src/browser/workspace-service.ts [hunk 2]
```diff
@@ -261,10 +261,18 @@ export class WorkspaceService implements FrontendApplicationContribution {
     }
 
     /**
-     * Returns `true` if there is an opened workspace in theia, and the workspace has more than one root.
+     * Returns `true` if there is an opened workspace, and theia supports having more than one root.
```
Comment (vince-fugnitto) [inline packages/workspace/src/browser/workspace-service.ts]: I'm not sure if we should add `... and theia supports having more than one root.` as we don't check the preference value here. Something like below would be more accurate, what do you think?

```ts
// Returns `true` if a multiple-root workspace is currently open.
```

Comment (elaihau) [reply packages/workspace/src/browser/workspace-service.ts]: you are right. i will change it.

Comment (elaihau) [reply packages/workspace/src/browser/workspace-service.ts]: you are right. i will change it.

File: packages/preferences/src/browser/folder-preference-provider.ts (hunk 1 above)
Comment (elaihau) [reply packages/preferences/src/browser/folder-preference-provider.ts]: after a second thought I removed constructor completely @akosyakov

**Comment by elaihau** [comment]
@akosyakov Are you fine with me merging this one for 0.8 release. This is a small PR, but in my opinion, it fixes a bug that users could easily hit.

**Comment by elaihau** [comment]
@svenefftinge Since Anton is not available this week, could you please take a quick look at [this line](https://github.com/theia-ide/theia/pull/5498/files#diff-408da694731a942d67fd00f039ff40f2L39) and confirm if you are OK with the breaking change? Thank you !

File: packages/preferences/src/browser/folder-preference-provider.ts [hunk 3]
```diff
@@ -34,21 +35,22 @@ export interface FolderPreferenceProviderOptions {
 @injectable()
 export class FolderPreferenceProvider extends AbstractResourcePreferenceProvider {
 
-    readonly folderUri: URI;
+    @inject(WorkspaceService) protected readonly workspaceService: WorkspaceService;
+    @inject(FolderPreferenceProviderOptions) protected options: FolderPreferenceProviderOptions;
```
Comment (kittaakos) [inline packages/preferences/src/browser/folder-preference-provider.ts]: Missing `readonly`.

File: packages/workspace/src/browser/workspace-service.ts [hunk 4]
```diff
@@ -261,10 +261,18 @@ export class WorkspaceService implements FrontendApplicationContribution {
     }
 
     /**
-     * Returns `true` if there is an opened workspace in theia, and the workspace has more than one root.
+     * Returns `true` if a multiple-root workspace is currently open.
      * @returns {boolean}
      */
     get isMultiRootWorkspaceOpened(): boolean {
+        return !!this.workspace && !this.workspace.isDirectory;
```
Comment (kittaakos) [inline packages/workspace/src/browser/workspace-service.ts]:
```ts
return this.opened && !this.workspace.isDirectory;
```
It would be aligned with the doc, you check `open` and not if the `_workspace` is defined, and with `isMultiRootWorkspaceEnabled` too.

File: packages/preferences/src/browser/workspace-preference-provider.ts [hunk 5]
```diff
@@ -109,9 +109,8 @@ export class WorkspacePreferenceProvider extends PreferenceProvider {
     }
 
     protected ensureResourceUri(): string | undefined {
-        const workspace = this.workspaceService.workspace;
-        if (workspace && workspace.isDirectory) {
-            return workspace.uri;
+        if (this.workspaceService.workspace && !this.workspaceService.isMultiRootWorkspaceOpened) {
+            return this.workspaceService.workspace!.uri;
```
Comment (kittaakos) [inline packages/preferences/src/browser/workspace-preference-provider.ts]: `!` is unnecessary here.

File: packages/preferences/src/browser/folders-preferences-provider.ts [hunk 6]
```diff
@@ -43,7 +43,6 @@ export class FoldersPreferencesProvider extends PreferenceProvider {
 
         this.updateProviders();
         this.workspaceService.onWorkspaceChanged(() => this.updateProviders());
-
```
Comment (kittaakos) [inline packages/preferences/src/browser/folders-preferences-provider.ts]: Please revert.

File: CHANGELOG.md [hunk 7]
```diff
@@ -12,6 +12,8 @@ Breaking changes:
     - `debug.restart` renamed to `workbench.action.debug.restart`
 - [preferences] renamed overridenPreferenceName to overriddenPreferenceName
 - [task] `cwd`, which used to be defined directly under `Task`, is moved into `Task.options` object
+- [preferences] removed constructor from the `FolderPreferenceProvider` class
```
Comment (kittaakos) [inline CHANGELOG.md]: Was there a problem with the constructor injection? 😊

File: packages/workspace/src/browser/workspace-service.ts (hunk 4 above)
Comment (kittaakos) [reply packages/workspace/src/browser/workspace-service.ts]: Can I open a multi-root workspace with `workspace.supportMultiRootWorkspace: false`?

**Comment by kittaakos** [comment]
Is this the correct behavior?
 - I have the Git decorations enabled in both the user and the workspace preferences. The labels are blue 👍
 - When I disable the _workspace_ one the _user_ setting seems to be ignored. The Git label decoration is off 😞

I had the multi-workspace support as the defualt: `false`.

screencast 2019-06-26 09-44-26

File: packages/workspace/src/browser/workspace-service.ts (hunk 4 above)
Comment (elaihau) [reply packages/workspace/src/browser/workspace-service.ts]: > ```ts
> return this.opened && !this.workspace.isDirectory;
> ```

this looks nice. however i am getting a typescript error that complains `this._workspace` can possibly be undefined.
```
[compile] src/browser/workspace-service.ts(268,32): error TS2532: Object is possibly 'undefined'.
```

I think we could either 
- leave the code as is, or 
- replace it with `return this.opened && !!this.workspace && !this.workspace.isDirectory;`

which do you prefer ?

File: CHANGELOG.md (hunk 7 above)
Comment (elaihau) [reply CHANGELOG.md]: there is nothing wrong with the contructor injection. I removed the them simply because none of the injected is referenced in the class. Also, in our coding standard / guidelines, we should try using property injection https://github.com/theia-ide/theia/wiki/Coding-Guidelines#property-injection over the constructor injection. 

If you are not happy with this change I can definitely remove it - having unused injected variables wouldn't cause any issues :)

File: packages/workspace/src/browser/workspace-service.ts (hunk 4 above)
Comment (elaihau) [reply packages/workspace/src/browser/workspace-service.ts]: > Can I open a multi-root workspace with `workspace.supportMultiRootWorkspace: false`?

no you cannot (at lease `shouldn't` :)). If it happened in your environment please create a github issue and assign it to me.

Comment (kittaakos) [reply packages/workspace/src/browser/workspace-service.ts]: > * leave the code as is

👍

**Comment by elaihau** [comment]
> Is this the correct behavior?
> 
> * I have the Git decorations enabled in both the user and the workspace preferences. The labels are blue +1
> * When I disable the _workspace_ one the _user_ setting seems to be ignored. The Git label decoration is off disappointed
> 
> I had the multi-workspace support as the defualt: `false`.
> 
> screencast 2019-06-26 09-44-26

Thank you for the review @kittaakos  ! The problem has been fixed and code updated.

**Comment by vince-fugnitto** [comment]
@elaihau I think there is a problem with your rebase, I see changes that were not initially part of your PR.
