### PR TITLE
Fix search-in-workspace widget error and notification message

### LINKED ISSUE #2287: Should hide/disable menu items applicable to workspaces when no workspace is present
General issue with Theia to hide/disable menu items which are in the context of a workspace when no workspace is currently present. 

Menu items such as:

- `File >  Open Workspace Preferences`
- `File > Save`
- `File > Save All`
- `Edit > Cut`
- `Edit > Copy`
- `Edit > Paste`
- `Edit > Search in Workspace`
- etc.

do not have meaning or value when no workspace is present, and thus should be hidden or disabled to avoid confusion.

### LINKED ISSUE #2297: Error thrown when attempting to search with no workspace present
Theia throws an error from the `Search Widget` when a search is performed without a current workspace. Instead of throwing an error, Theia should instead catch the error and display it as a meaningful message to end users. (ex: **Please open a workspace or file(s) before searching**)

no-workspace-root

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #2287
Fixes #2297

- Catch error thrown when `search-in-workspace` widget is used to search a workspace without a workspace being present.
- Disable menu item `Search in Workspace` when no workspace is present.
- Display notification message in `search-in-workspace` widget when no workspace is present.

selection_009

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

File: packages/search-in-workspace/src/browser/search-in-workspace-frontend-contribution.ts [hunk 1]
```diff
@@ -55,12 +57,13 @@ export class SearchInWorkspaceFrontendContribution extends AbstractViewContribut
...
 
     async initializeLayout(app: FrontendApplication): Promise<void> {
-        await this.openView({activate: false});
+        await this.openView({ activate: false });
     }
 
     registerCommands(commands: CommandRegistry): void {
         super.registerCommands(commands);
         commands.registerCommand(SearchInWorkspaceCommands.OPEN_SIW_WIDGET, {
+            isEnabled: () => this.workspaceService.tryGetRoots().length > 0,
```
Comment (lmcbout) [inline packages/search-in-workspace/src/browser/search-in-workspace-frontend-contribution.ts]: When entering data in the search field, you activate the "Refresh" button which is not necessary since there is no workspace to search !

Comment (vince-fugnitto) [reply packages/search-in-workspace/src/browser/search-in-workspace-frontend-contribution.ts]: I tried to have as minimal impact as possible to the code so I reuse the same notification and only display the message if the user in fact attempts to perform a search when no workspace is present, I don't persist the message or disable any of the buttons

Comment (vince-fugnitto) [reply packages/search-in-workspace/src/browser/search-in-workspace-frontend-contribution.ts]: Anyways @lmcbout, this isn't the location of where I add the checks, this only disables the menu item, as well as the quick-open-command for when no workspace is present and a user attempts to search.

Comment (vince-fugnitto) [reply packages/search-in-workspace/src/browser/search-in-workspace-frontend-contribution.ts]: I addressed the issue of not enabling the `Refresh` button if no workspace is present. 
This snippet however is not the cause of that issue. This `enable` only controls whether the `menu` and `command` for `Close Workspace` is enabled or not.

File: packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx [hunk 2]
```diff
@@ -57,6 +58,9 @@ export class SearchInWorkspaceWidget extends BaseWidget implements StatefulWidge
     protected resultContainer: HTMLElement;
 
     @inject(SearchInWorkspaceResultTreeWidget) protected readonly resultTreeWidget: SearchInWorkspaceResultTreeWidget;
+    @inject(WorkspaceService) protected readonly workspaceService: WorkspaceService;
+
+    protected isWorkspacePresent: boolean = false;
```
Comment (akosyakov) [inline packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx]: don't keep the duplicate state in the UI component, it will get out of sync with `WorkspaceService` state

How about replacing it with a function which checks `WorkspaceService` state each time?

**Comment by akosyakov** [comment]
@jbicker please review

File: packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx (hunk 2 above)
Comment (vince-fugnitto) [reply packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx]: thanks @akosyakov, I initially had it the way you suggested and I think its necessary in this case to check the state each time to keep the sync.

**Comment by vince-fugnitto** [comment]
@jbicker I'm not sure but maybe we shouldn't disable the items within the `View`. Vscode has the same behaviour where widgets are able to be opened, but messages are shown. If we disable the `Search` widget from the `View`, then it'd be also the case to disable most widgets since they don't make sense to be opened without a workspace.
