### PR TITLE
[electron] Remove cluster mode

### LINKED ISSUE #4349: [electron] Reloading the window or opening a new workspace crashes the app
When running the example electron application after a clean build, reloading the window kills the application.
The same is observed if a workspace is open while preserving the window (preferences - `workspace.preserveWindow`: true).

Tested on latest master (14th Feb 2019) with MacOS.

### PR DESCRIPTION
**Pull request by thegecko**
Signed-off-by: Rob Moran <rob.moran@arm.com>

Completely remove cluster mode.

This PR supersedes #4380 and fixes #4349, #3242, #4775

@akosyakov You mentioned you wanted to remove `extension-manager` too. Should that be a different PR?

### CODE REVIEW

File: packages/filesystem/src/node/filesystem-backend-module.ts [hunk 1]
```diff
@@ -36,18 +34,13 @@ export function bindFileSystem(bind: interfaces.Bind, props?: {
 }
 
 export function bindFileSystemWatcherServer(bind: interfaces.Bind): void {
-    if (cluster.isMaster) {
```
Comment (akosyakov) [inline packages/filesystem/src/node/filesystem-backend-module.ts]: We should preserve `--no-cluster` for single thread debugging.

File: packages/git/src/node/git-backend-module.ts [hunk 2]
```diff
@@ -53,17 +51,13 @@ export function bindGit(bind: interfaces.Bind, bindingOptions: GitBindingOptions
         child.bind(GitRepositoryWatcherOptions).toConstantValue(options);
         return child.get(GitRepositoryWatcher);
     });
-    if (cluster.isMaster) {
```
Comment (akosyakov) [inline packages/git/src/node/git-backend-module.ts]: We should preserve it, but based on check `--no-cluter` option.

**Comment by akosyakov** [comment]
@thegecko yes, different PR for `extension-manager` is fine. We should not remove it for now, since we want to rewrite it to use as UI for plugin system, but we should remove references to it that no one is using it now: https://github.com/theia-ide/theia/issues/4693

File: packages/filesystem/src/node/filesystem-backend-module.ts [hunk 3]
```diff
@@ -36,18 +34,13 @@ export function bindFileSystem(bind: interfaces.Bind, props?: {
...
-                error: (message, ...args) => logger.error(message, ...args)
-            });
+    bind(FileSystemWatcherServer).toDynamicValue(ctx => {
+        const logger = ctx.container.get<ILogger>(ILogger);
+        return new NsfwFileSystemWatcherServer({
+            info: (message, ...args) => logger.info(message, ...args),
+            error: (message, ...args) => logger.error(message, ...args)
         });
-    } else {
-        bind(FileSystemWatcherServerClient).toSelf();
```
Comment (akosyakov) [inline packages/filesystem/src/node/filesystem-backend-module.ts]: it's prod implementation.

File: packages/git/src/node/git-backend-module.ts [hunk 4]
```diff
@@ -53,17 +51,13 @@ export function bindGit(bind: interfaces.Bind, bindingOptions: GitBindingOptions
...
-                error: (message, ...args) => logger.error(message, ...args)
-            });
+    bind(GitLocator).toDynamicValue(ctx => {
+        const logger = ctx.container.get<ILogger>(ILogger);
+        return new GitLocatorImpl({
+            info: (message, ...args) => logger.info(message, ...args),
+            error: (message, ...args) => logger.error(message, ...args)
         });
-    } else {
-        bind(GitLocator).to(GitLocatorClient);
```
Comment (akosyakov) [inline packages/git/src/node/git-backend-module.ts]: it's prod implementation.

**Comment by akosyakov** [comment]
@thegecko I wonder did you always run your app into `--no-cluster` mode, in this way it would always watch fs and git in the main thread making the backend super slow on big workspaces.

File: packages/filesystem/src/node/filesystem-backend-module.ts (hunk 1 above)
Comment (thegecko) [reply packages/filesystem/src/node/filesystem-backend-module.ts]: Perhaps we should rename it as `--single-thread`?

Comment (akosyakov) [reply packages/filesystem/src/node/filesystem-backend-module.ts]: i would prefer to keep the name to avoid breaking existing launch configuration, i know that it is used by different clients for debugging

Comment (thegecko) [reply packages/filesystem/src/node/filesystem-backend-module.ts]: So you want these sections to be debugged by default in a single threaded way, although production doesn't run like that and you want the name kept referencing clustering although it isn't?

File: packages/filesystem/src/node/filesystem-backend-module.ts (hunk 3 above)
Comment (thegecko) [reply packages/filesystem/src/node/filesystem-backend-module.ts]: I'm not sure what you mean. Surely the difference here is that one way is using cluster mode and one doesn't, they should both be `production`

File: packages/filesystem/src/node/filesystem-backend-module.ts (hunk 1 above)
Comment (akosyakov) [reply packages/filesystem/src/node/filesystem-backend-module.ts]: I meant if there is `--no-cluster` option then fs and git watching should happen in own processes. If there is then they should not. Something like `process.argv.indexOf('--no-cluster') !== -1` for backward compatibility in launch configurations.

File: packages/filesystem/src/node/filesystem-backend-module.ts (hunk 3 above)
Comment (thegecko) [reply packages/filesystem/src/node/filesystem-backend-module.ts]: @akosyakov Can you confirm what you want here? Specifically, which section should be used in `--no-cluster` (single threaded mode) and which is `normal` mode.

Comment (akosyakov) [reply packages/filesystem/src/node/filesystem-backend-module.ts]: `normal` mode is `else` branch

**Comment by thegecko** [comment]
@akosyakov Thanks for the feedback. PR now updated keeping the `--no-cluster` switch as requested.

File: dev-packages/application-manager/src/generator/frontend-generator.ts [hunk 5]
```diff
@@ -124,167 +124,161 @@ process.env.LC_NUMERIC = 'C';
 
 const electron = require('electron');
 const { join, resolve } = require('path');
-const { isMaster } = require('cluster');
```
[the remark this answers is not in the document]
Comment (kittaakos) [reply dev-packages/application-manager/src/generator/frontend-generator.ts]: >  to bundle this change into an electron application

[the remark this answers is not in the document]
Comment (thegecko) [reply dev-packages/application-manager/src/generator/frontend-generator.ts]: Oh, an installed one, sorry!

**Comment by akosyakov** [comment]
@thegecko changes look good to me and app works, but tests are failing on travis

File: packages/core/src/node/cluster/main.ts [hunk 6]
```diff
@@ -1,71 +0,0 @@
...
-const args = yargs.option(MasterProcess.startupTimeoutOption, {
-    description: 'The number of milliseconds to wait for the server to start up. Pass a negative number to disable the timeout.',
-    type: 'number',
-    default: BackendApplicationConfigProvider.get().startupTimeout || MasterProcess.defaultStartupTimeoutOption
-}).help(false).argv;
-const noCluster = args['cluster'] === false;
-const isMaster = !noCluster && cluster.isMaster;
-const development = process.env.NODE_ENV === 'development';
-
-const startupTimeout = args[MasterProcess.startupTimeoutOption] as number;
```
Comment (kittaakos) [inline packages/core/src/node/cluster/main.ts]: If the startup timeout is removed, please deprecate https://github.com/theia-ide/theia/blob/ce2f145017ff6bca715cddb96f876366eb1a4b22/dev-packages/application-package/src/application-props.ts#L124

File: dev-packages/application-manager/src/generator/frontend-generator.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (kittaakos) [reply dev-packages/application-manager/src/generator/frontend-generator.ts]: I could not find a way to bundle it. I did the following: build Theia from this branch, copy the `packages` content into the electron app's `node_modules/@theia/`. It pulled another version. In the bundled application I have `/Users/akos.kitta/git/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/node_modules/@theia/core/lib/node/cluster/worker-reader.js`, it should not. I could not test it.

**Comment by thegecko** [comment]
> tests are failing on travis

Investigating now, I wonder if the tests are set up to run in `single threaded` too?

**Comment by thegecko** [comment]
@akosyakov Tests fixed, they needed to be run in `single threaded` mode with `--no-cluster`
@kittaakos I have removed the `startupTimeout` app setting and mentioned it in the CHANGELOG breaking changes

Ready for final review :)

**Comment by kittaakos** [comment]
> Ready for final review :)

I cannot verify it, unfortunately. I do not see a better option than merging it, trying it, and if it does not work, reverting it. If one has a brilliant idea on how to bundle the electron app from the source, please let me know.

**Comment by thegecko** [comment]
> how to bundle the electron app

Only by merging your [theia-electron app](https://github.com/theia-ide/theia-apps/tree/master/theia-electron) into the electron example.

**Comment by kittaakos** [comment]
> Only by merging your [theia-electron app](https://github.com/theia-ide/theia-apps/tree/master/theia-electron) into the electron example.

Correct me if I am wrong, but the electron-builder cannot follow the symlinks (from the `node_modules` folder), how would this work? Do you have a working solution for the bundling?

**Comment by thegecko** [comment]
> electron-builder cannot follow the symlinks

the `hard-links=false` env var may help in this case (untested)

> Do you have a working solution for the bundling

We do, but not for Theia. It's not impossible to set up, just time consuming.

**Comment by kittaakos** [comment]
> @kittaakos Can we try it like that?

I am OK trying it afterward, or maybe with [`derefsymlinks`](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#derefsymlinks) now, it will take 1-2 days to more.

**Comment by thegecko** [comment]
OK, shall I merge this?

**Comment by kittaakos** [comment]
> OK, shall I merge this?

I am OK with both; it is up to you. If it does not work, we will revert it anyway.

**Comment by thegecko** [comment]
> I will take care of the verification

Awesome thanks!
