### PR TITLE
[markers] fix false positive problem tabbar decorators

### LINKED ISSUE #6109: false positive error tabbar icon
### Description
image

### Reproduction Steps

- open a ts file
- type some error code
- fix error code
- save file

**OS and Theia version:**
**Diagnostics:**

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #6109

- fixes an issue where problem tabbar decorators wrongly display false positives
- with the change, only `error` and `warning` decorators are displayed in the tabbar which
is consistent with the problem decorators present in the explorer
- with the change, only one decorator (max severity) is ever decorated (no need for unnecessary rendering)

#### How to test

1. open the application with a workspace present
2. open an arbitrary file and produce `errors` and `warnings` 
3. the highest severity should be displayed in the tabbar as a decoration (`error` and `warning` only)
4. the decoration should match that of the `explorer`

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

File: packages/markers/src/browser/problem/problem-tabbar-decorator.ts [hunk 1]
```diff
@@ -49,9 +49,27 @@ export class ProblemTabBarDecorator implements TabBarDecorator {
...
+                    // Break early if an error marker is present, since it represents the highest severity.
+                    if (marker.data.severity === DiagnosticSeverity.Error) {
+                        maxSeverity = marker;
+                        break;
+                    } else if (marker.data.severity === DiagnosticSeverity.Warning) {
+                        maxSeverity = marker;
+                    }
+                }
+                // Decorate the tabbar with the highest marker severity if available.
+                return maxSeverity ? [this.toDecorator(maxSeverity)] : [];
```
Comment (akosyakov) [inline packages/markers/src/browser/problem/problem-tabbar-decorator.ts]: now it is really optimized 👍 so before there were as many icons as we have error/warning diagnostics?

Comment (vince-fugnitto) [reply packages/markers/src/browser/problem/problem-tabbar-decorator.ts]: Before, for a given `resourceUri` there would be for each marker we decorate the tabbar which would override the previous decoration (ex: error, error, error, info) and we'd end up with an info in the end since the list is unordered. Now, we only decorate once for the highest severity and only if the severity is an `error` or `warning`. I tried to optimize as much as possible :)

Comment (akosyakov) [reply packages/markers/src/browser/problem/problem-tabbar-decorator.ts]: I had an idea to keep here:
- a mapping between uri -> stat (count of warnings, errors, infos)
- and total stat

So when a change event happens we update a single stat by uri and then update a total stat by subtracting previous uri stat and adding new uri stat. So we can update problem stat in the status bar very fast, maybe even without any debouncing like now. It would require testing with many diagnostics though again, i.e. as in Dart extension support PR.

If we would also add an event like `onDidStatChanged`, then we could change `ProblemTabBarDecorator` based on it instead of changed to markers directly and decorate title also very fast by retrieving a uri stat and checking how many errors or warnings it has (so not traversing anymore).

**Comment by akosyakov** [comment]
@lmcbout could you please finish the review by testing, code-wise it looks to me, thank you!

**Comment by lmcbout** [comment]
@akosyakov looking at it right now.

File: packages/markers/src/browser/problem/problem-tabbar-decorator.ts (hunk 1 above)
Comment (vince-fugnitto) [reply packages/markers/src/browser/problem/problem-tabbar-decorator.ts]: > I had an idea to keep in [ProblemManager](https://github.com/theia-ide/theia/blob/master/packages/markers/src/browser/problem/problem-manager.ts):
> 
> * a mapping between uri -> stat (count of warnings, errors, infos)
> * and total stat
> 
> So when a change event happens we update a single stat by uri and then update a total stat by subtracting previous uri stat and adding new uri stat. So we can update problem stat in the status bar very fast, maybe even without any debouncing like now. It would require testing with many diagnostics though again, i.e. as in Dart extension support PR.
> 
> If we would also add an event like `onDidStatChanged(uri)`, then we could change `ProblemTabBarDecorator` based on uri stats instead of changes to markers directly and decorate title also very fast by retrieving a uri stat and checking how many errors or warnings it has (so traversing happens only once to compute stat for a uri, not by each client on each request).
> 
> It is just thoughts, i think everything works good now already.

I think that any optimization we can do would always be worth it :)
Where I think there can be improvements is the decoration present in the explorer for example, it is probably very costly at the moment.

Comment (akosyakov) [reply packages/markers/src/browser/problem/problem-tabbar-decorator.ts]: @vince-fugnitto Can you file an issue for it then please?

Comment (vince-fugnitto) [reply packages/markers/src/browser/problem/problem-tabbar-decorator.ts]: > @vince-fugnitto Can you file an issue for it then please?

Regarding your proposal or in general to optimize and improve decorations?

Comment (akosyakov) [reply packages/markers/src/browser/problem/problem-tabbar-decorator.ts]: general with a proposal in the body

**Comment by lmcbout** [comment]
I notice something, but code wise and performance, this PR is a good improvement.
Have the Problem view open at all times.
Test :

Open 2 files with hints/warnings: quick-open-task.ts(4 hints) and task-problem-pattern-registry.ts (1 hint)
inject and error `( const jj = 9;`) in file quick-open-task.ts
--> it shows the error in the file quick-open-task.ts: OK
but if you run in debug mode with a stop in problem-tabbar-decorator.ts ~ line 64, you notice that both open files are decorated each time there is a modification, not only the modified file. I think for improvement, if we just look for the modified file to set the decorator, it would improve the performance.

**Comment by vince-fugnitto** [comment]
@lmcbout does the PR work correctly and fix the bug? I'm not attempting to address the performance as part of the PR but rather I attempted to fix the bug and be as optimized as I can be.

I believe in general the performance should be handled by #6146

**Comment by vince-fugnitto** [comment]
> Works nicely
> Performance in other issue is fine

Thank you for the review! :+1:
