### PR TITLE
align "configure task" and "task quick open" with vs code

### LINKED ISSUE #4919: [tasks] unable to configure tasks when in a multi-root workspace
**Description**
Unable to `configure` tasks when in a multi-root workspace. 
```bash
task-service.ts:15 Uncaught (in promise) Error: Request 'createFile' failed
    at Proxy.<anonymous> (proxy-factory.ts:232)
    at TaskConfigurations.<anonymous> (task-configurations.ts:267)
    at step (task-configurations.ts:15)
    at Object.next (task-configurations.ts:15)
    at fulfilled (task-configurations.ts:15)
```

**Reproduction Steps**
1. Open a multi-root workspace.
2. Perform the command `Run Task...` and attempt to configure a task (small cog icon).
3. Notice that nothing occurs, and an uncaught error is thrown.

### LINKED ISSUE #5679: users shouldn't have the flexibility of customizing all properties of a detected task
### Description

In theia, when customizing a detected task, users could potentially change any property of the task:

Peek 2019-07-09 23-23

In vscode, users are only allowed to customize 3 things: 
```ts
export interface CustomizationProperties {
	group?: string | { kind?: string; isDefault?: boolean; };
	problemMatcher?: string | string[];
	isBackground?: boolean;
}
```
Peek 2019-07-09 23-27

We should align this behavior with vsCode. Conceptually, being able to customize anything is beyond "customization" - it is more like "using the existing task as a template to create a new task".

### Reproduction Steps

1, Open the list of tasks which includes at least one detected task
2, Click the gear icon right hand side of the detected task to customize it
3, Check what Theia adds to `.theia/tasks.json`

### LINKED ISSUE #5719: "configure task" should not add duplications to task.json
### Description

Configuring the same task multiple time adds duplications to the tasks.json file

Peek 2019-07-16 00-23

In VS code, if a detected task has been customized, the user won't be able to add a second customized config to tasks.json. 

### Reproduction Steps

1. take `npm install` for example, open "Run tasks"
2. configure `npm install`
3, repeat step 1 and 2
4, check data in tasks.json 

what happened: there are more than one objects added to `tasks.json` for `npm install`
what should happen: duplicated customization for the same detected task should be avoided

### LINKED ISSUE #5747: Configuring of a task
### Description
A task is not displayed in `configured tasks` section after configuring. 
Is it correct behavior?

### Reproduction Steps
1.`Terminal` => `Run Task` menu, select `npm:build` and click `cog` icon (configure task action)  
2. You can see that the configuration is copied to `tasks.json` file and you can edit it
3. Go again to `Terminal` => `Run Task` menu
4. You can see that the task still in `detected tasks` section

Please see the video: https://youtu.be/C5bp8mdSFgM

**Diagnostics:** 
I investigated a little source code and found that:
- after configuring of the `detected` task `npm:build`, it is copied to `tasks.json` file
- at reading  from `tasks.json` file the configuration [goes](https://github.com/theia-ide/theia/blob/3587c237cacc638dc54ec19dc3eaa755c2e69fb5/packages/task/src/browser/task-configurations.ts#L217-L220) to `customizations`, not to `configuredTasksArray`
- at [creating](https://github.com/theia-ide/theia/blob/3587c237cacc638dc54ec19dc3eaa755c2e69fb5/packages/task/src/browser/quick-open-task.ts#L69) `Run Task` menu `configured` tasks are taken, not `customizations`.
- `customizations` [are used](https://github.com/theia-ide/theia/blob/3587c237cacc638dc54ec19dc3eaa755c2e69fb5/packages/task/src/browser/task-service.ts#L321) at running of `detected` task

As result, `npm:build` task is not displayed in `configured tasks` section.    

So, what's the correct new behavior?
1. Will `configured tasks` section display only configurations from `tasks.json` which don't have 'parent' `detected` task?
2. What's the correct new behavior for 'recently used' section for `detected` and `customization` configs. I mean use case like described here: https://github.com/theia-ide/theia/issues/5067
3. Are overridden fields from `tasks.json` [applied](https://github.com/theia-ide/theia/blob/3587c237cacc638dc54ec19dc3eaa755c2e69fb5/packages/task/src/browser/task-service.ts#L319-L323) for a configuration which have 'parent' `detected` task?  

Thanks in advance!

### PR DESCRIPTION
**Pull request by elaihau**
- edit the right task.json when clicking "configure task" in multi-root
workspace (fixed #4919)

- in the current Theia, when users configure a detected task, the entire task config is written into tasks.json, which introduces redundancy. 
With this change, only properties that define the detected task, plus `problemMatcher`, are written into tasks.json. (fixed #5679)

- `TaskConfigurations.taskCustomizations` is a flat array, and the user can only customize one type of detected task in one way.
With this change Theia supports having different ways of task customization in different root folders.

- allow users to override any task properties other than `type`, and those that are used to define the in its task definition.

- The detected tasks, once customized, should be displayed as configured tasks in the quick open. (fixed #5747)

- The same task shouldn’t have more than one customization. Otherwise it would cause ambiguities and duplication in tasks.json (fixed #5719)

Signed-off-by: Liang Huang <liang.huang@ericsson.com>

### CODE REVIEW

**Comment by elaihau** [comment]
Configure tasks in different root folders of a multi root workspace:

Peek 2019-07-23 00-47


Once a detected task is configured, it is displayed as a configured task:

Peek 2019-07-23 00-48


The configured detected task cannot be configured for more than once:

Peek 2019-07-23 00-50


Lastly, as the GIFs shown above, with this change, "configure task" does not write the entire task object into the `tasks.json`. It only writes the properties that are used to defined the task, and `problemMatcher`.

File: packages/task/src/browser/task-configurations.ts [hunk 1]
```diff
@@ -179,8 +200,58 @@ export class TaskConfigurations implements Disposable {
...
+        }
+
+        const customizationInRootFolder = this.taskCustomizationMap.get(new URI(rootFolder).path.toString());
+        if (customizationInRootFolder) {
+            return customizationInRootFolder.filter(c => c.type === type);
+        }
+        return [];
+    }
+
+    getProblemMatchers(taskConfiguration: TaskConfiguration): (string | ProblemMatcherContribution)[] {
```
Comment (vince-fugnitto) [inline packages/task/src/browser/task-configurations.ts]: Should we document the following method?

File: packages/task/src/browser/task-service.ts [hunk 2]
```diff
@@ -203,13 +202,13 @@ export class TaskService implements TaskConfigurationClient {
...
     async getTasks(): Promise<TaskConfiguration[]> {
-        const configuredTasks = this.getConfiguredTasks();
+        const configuredTasks = await this.getConfiguredTasks();
         const providedTasks = await this.getProvidedTasks();
         return [...configuredTasks, ...providedTasks];
     }
 
     /** Returns an array of the task configurations which are configured in tasks.json files */
-    getConfiguredTasks(): TaskConfiguration[] {
+    getConfiguredTasks(): Promise<TaskConfiguration[]> {
```
Comment (vince-fugnitto) [inline packages/task/src/browser/task-service.ts]: Does this require a breaking change note?
Clients who call the following method will at least need to be `async` now.

File: packages/task/src/browser/task-configurations.ts [hunk 3]
```diff
@@ -179,8 +200,58 @@ export class TaskConfigurations implements Disposable {
         this.tasksMap.delete(source);
     }
 
-    getTaskCustomizations(type: string): TaskCustomization[] {
-        return this.taskCustomizations.filter(c => c.type === type);
+    removeTaskCustomizations(configFileUri: string) {
```
Comment (vince-fugnitto) [inline packages/task/src/browser/task-configurations.ts]: In general I guess we should try and document the `public` methods.

Comment (vince-fugnitto) [reply packages/task/src/browser/task-configurations.ts]: Not part of your change, but do you believe `task-configuration.ts` should also be unit tested?
I believe it is possible since there are no direct UI dependencies.

File: packages/task/src/browser/task-configurations.ts [hunk 4]
```diff
@@ -179,8 +200,58 @@ export class TaskConfigurations implements Disposable {
...
+        const source = this.getSourceFolderFromConfigUri(configFileUri);
+        this.taskCustomizationMap.delete(source);
+    }
+
+    /**
+     * Returns the task customizations by type from a given root folder in the workspace.
+     * @param type the type of task customizations
+     * @param rootFolder the root folder to find task customizations from. If `undefined`, this function returns an empty array.
+     */
+    getTaskCustomizations(type: string, rootFolder: string | undefined): TaskCustomization[] {
```
Comment (vince-fugnitto) [inline packages/task/src/browser/task-configurations.ts]: I guess this can be simplified to:

```ts
getTaskCuztomizations(type: string, root?: string): TaskCustomization[] { ... }
```

File: packages/task/src/browser/task-configurations.ts [hunk 5]
```diff
@@ -44,11 +45,14 @@ export class TaskConfigurations implements Disposable {
...
     /**
-     * Map of source (path of root folder that the task config comes from) and task config map.
+     * Map of source (path of root folder that the task configs come from) and task config map.
      * For the inner map (i.e., task config map), the key is task label and value TaskConfiguration
      */
     protected tasksMap = new Map<string, Map<string, TaskConfiguration>>();
-    protected taskCustomizations: TaskCustomization[] = [];
+    /**
+     * Map of source (path of root folder that the task configs come from) and task customizations map.
+     */
```
Comment (lmcbout) [inline packages/task/src/browser/task-configurations.ts]: The function header line 48 is the same as the comment inside the method (line 52-54)
This is duplication info in a few lines, may be just one would be enough.

Comment (vince-fugnitto) [reply packages/task/src/browser/task-configurations.ts]: It's not actually the same, one is `TaskConfiguration` while the other is `TaskCustomization`.

File: packages/task/src/browser/task-configurations.ts (hunk 3 above)
Comment (elaihau) [reply packages/task/src/browser/task-configurations.ts]: yes adding tests to `task-configuration.ts` would be helpful. I am going to make more changes to this file (hopefully in the next pr) and will add tests after.

**Comment by elaihau** [comment]
> Code seems ok with minor comments
> Can the 3 commits be squashed into one !
> Not tested the runtime exec yet

Thank you for the review @lmcbout  @vince-fugnitto !
I will also do more tests on my side.

**Comment by vince-fugnitto** [comment]
@elaihau I don't have any issues codewise :) 
Do you mind sharing on how we can successfully test the PR (mainly how to get `detected` tasks)?

**Comment by RomanNikitenko** [comment]
I tested the changes locally using `npm` extension and can confirm that:
- task after configuring is displayed as `configured`
- no redundant fields are present after configuring a `detected` task 
- it works well for a multi-root workspace
- user can configure a task only once

so, thank you @elaihau for the fix - well done!

I would like test the running a configuration from `recently used ` section after configuring and so on.
Do you know some vs code extension which provides task configurations with args available for editing by user? I mean it's hard to reproduce the described case above for `npm`, because this one has only `script` and `path` fields. Maybe you know some extension with tasks which allow to edit `command` filed or args and can be good example for testing.

thank you!

**Comment by elaihau** [comment]
> Maybe you know some extension with tasks which allow to edit `command` filed or args and can be good example for testing to check - is `configured` configuration is used for execution or `detected` one from `recently used` section.
> 
> thank you!

@RomanNikitenko Thank you for testing,  really appreciated !

from my understanding in vs code the `command` property can not be customized. And this patch does not support customizing the `command` either. 

As per our discussion in https://github.com/theia-ide/theia/issues/5679#issuecomment-511143582, I should add support to allow users to override all properties such as `command`. Please give me two days (sorry I am not working full time on this) and I will make a patch to this PR.

**Comment by elaihau** [comment]
> @elaihau I don't have any issues codewise :)
> Do you mind sharing on how we can successfully test the PR (mainly how to get `detected` tasks)?

We could install vs code extensions such as `npm` and `grunt` as plugins in theia. the npm scripts and grunt tasks defined in your project would be detected by those extension and get displayed in the task quick open.

**Comment by elaihau** [comment]
@RomanNikitenko with the latest change in this patch you would be able to override any properties, except for `type`, and those that are used to define your detected task.

take `npm` tasks for example, from its task definition
```json 
      {
        "type": "npm",
        "required": [
          "script"
        ],
        "properties": {
          "script": {
            "type": "string",
            "description": "%taskdef.script%"
          },
          "path": {
            "type": "string",
            "description": "%taskdef.path%"
          }
        }
      }
```
we know `script` and `path` are used to define tasks, and therefore we could override any properties other than `script`, `path`, and `type`.

Please see this GIF for example

Peek 2019-07-27 22-21

`npm lintAAA` executes `eslint .` on the first root folder of the workspace. with users overrridding `command`, `args`, and `options`, it runs `./task` script from the other root folder.

Please let me know if this supports what you needed. Thank you !

**Comment by RomanNikitenko** [comment]
@elaihau 
I'm going to test your changes today
Thank you very much!

**Comment by RomanNikitenko** [comment]
@elaihau 
I tested again cases mentioned [here](https://github.com/theia-ide/theia/pull/5777#issuecomment-514629414) after PR is updated, also tested [this case](https://github.com/theia-ide/theia/pull/5777#issuecomment-515727537). It works well for me!

For our assembly we need some adaptation, but looks like it's on our side, so @elaihau thank you for giving me time for testing and analyzing!

**Comment by elaihau** [comment]
Thank you for the review and testing @RomanNikitenko , really appreciated !
