### PR TITLE
[explorer] implement 'more' toolbar item for the explorer

### LINKED ISSUE #5951: [explorer/navigator] implement 'More' toolbar item with context menu
**Description**

Based on https://github.com/theia-ide/theia/issues/5946#issuecomment-521630400

Support _"More"_ toolbar item and context menu for the `explorer` widget which will contain helpful methods for the view (ex: `Add Folder to Workspace`)

A similar implementation is present in the `Git` explorer:

**Implementation Details**
1. should the toolbar item be always displayed? or should it only be displayed in a single-root workspace?
2. which context menu items should be displayed?

### LINKED ISSUE #6010: [multi-root] workspace roots not refreshed properly when removed
**Description**

If a **multi-root** workspace's roots are removed, the roots are not properly refreshed.
For instance, with no roots present, one can still execute commands based on the last available root.

**Steps to Reproduce**
- open a workspace (ex: `theia/packages/core`)
- ensure that the preference `workspace.supportMultiRootWorkspace` is enabled
- add a new root using the command `Add Folder to Workspace` (select `theia/packages/bunyan`)
- remove both roots by right clicking the root nodes in the tree and selecting `Remove Folder from Workspace`
- you should be left with a workspace without any available roots
- execute the command `File: New File`, a dialog appears with a file name and upon confirmation the file is added to the last available root

In my example, I create the file `vincent.ts` despite no workspace roots being available, and it still gets created at the last available root.

<div align='center'>

Screen Shot 2019-08-21 at 11 37 10 AM

</div>

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Fixes #5951
Fixes #6010

- Added a new toolbar item for the `explorer` which consists of mutliple commands.
- Adjusted the `WorkspaceRootUriAwareCommandHandler` to better handle commands which
can be used by the workspace root in both a single and multi-root workspace.
- Added the command `New File` to the toolbar item.
- Added the command `New Folder` to the toolbar item.
- Added the command `Add Folder to Workspace...` to the toolbar item.
- Added the command `Compare With...` to the toolbar item.

_Available Toolbar Item Commands_
- `New File`
- `New Folder`
- `Add Folder to Workspace...`
- `Compare With...`

<div align='center'>

Screen Shot 2019-08-21 at 3 40 20 PM

</div>

#### How to test

1. test the following commands in a single-root workspace
1.1. `New File`: creates a new file at the root if no selection is present, else it creates it at the selection.
1.2. `New Folder`: creates a new folder at the root if no selection is present, else it creates it at the selection
1.3. `Add Folder to Workspace...`: adds a folder to the workspace
1.4 `Compare With...`: if no selection it uses the root, else it uses the selection. prompts the user to select a branch to compare to

2. test the following commands in a multi-root workspace (**with roots**)
2.1. `New File`: creates a new file at the **first** root if no selection is present, else it creates it at the selection.
2.2. `New Folder`: creates a new folder at the **first** root if no selection is present, else it creates it at the selection
2.3. `Add Folder to Workspace...`: adds a folder to the workspace

3. test the following command in a multi-root workspace (**without any roots**)
3.1 `Add Folder to Workspace...`: adds a folder to the workspace

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

_Single-Root Workspace_

| Command | Toolbar | Selection |
|:---|:---:|:---:|
| `New File` | ✅ |  ✅ |
| `New Folder` | ✅| ✅|
| `Add Folder to Workspace...` | ✅| ✅|
| `Compare With...` | ✅| ✅|

_Multi-Root Workspace_

| Command | Toolbar | Selection |
|:---|:---:|:---:|
| `New File` | ✅<br /> (adds to first root) |  ✅ |
| `New Folder` | ✅<br /> (adds to first root) | ✅|
| `Add Folder to Workspace...` | ✅| ✅|
| `Compare With...` | ✅| ✅|

_Multi-Root Workspace (no roots)_

<div align='center'>

Screen Shot 2019-08-21 at 4 07 50 PM

</div>

<br />

| Command | Toolbar | Selection |
|:---|:---:|:---:|
| `Add Folder to Workspace...` | ✅| ✅|

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
I'm blocked for certain commands, example `Find in Folder`. The command currently exists in the `@theia/search-in-workspace` extension and it is currently added to the navigator through the context menu `NavigatorContextMenu.SEARCH`. I'm not sure if its possible to expose the `more` toolbar item to accept contributions from other extensions and mimic the behavior of the entire context menu for the root.

File: packages/workspace/src/browser/workspace-commands.ts [hunk 1]
```diff
@@ -447,6 +447,14 @@ export class WorkspaceRootUriAwareCommandHandler extends UriAwareCommandHandler<
         super(selectionService, handler);
     }
 
+    isEnabled(): boolean {
```
Comment (akosyakov) [inline packages/workspace/src/browser/workspace-commands.ts]: We should not override it. Why do we need it for this PR?

**Comment by akosyakov** [comment]
`@theia/search-in-workspace` has a depdency to `@theia/navigator`, so you can register toolbar item for the navigator in `SearchInWorkspaceFrontendContribution`.

File: packages/workspace/src/browser/workspace-commands.ts (hunk 1 above)
Comment (vince-fugnitto) [reply packages/workspace/src/browser/workspace-commands.ts]: I've updated for the moment in order to expose commands to the root of the workspace mimicking if a true root node was present. The `WorkspaceRootUriAwareCommandHandler` determines if a root node is selected but unfortunately this is impossible now with the newest implementation of the explorer.

**Comment by vince-fugnitto** [comment]
> `@theia/search-in-workspace` has a depdency to `@theia/navigator`, so you can register toolbar item for the navigator in `SearchInWorkspaceFrontendContribution`.

I wasn't aware that other extensions can contribute to the toolbar items defined in a different extension. Must I expose it somehow?

**Comment by akosyakov** [comment]
@vince-fugnitto I'm not sure what you want to expose? The registry of toolbar items is global. Any extension can register item and then do an instance check whether the current widget is a navigator or not for `isEnabled` and `isVisible` callback of an underlying toolbar item command.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I'm not sure what you want to expose? The registry of toolbar items is global. Any extension can register item and then do an instance check whether the current widget is a navigator or not for `isEnabled` and `isVisible` callback of an underlying toolbar item command.

Sorry I was just confused if it was possible to contribute to the same toolbar item, confused as to how it should be referenced from another extension.

**Comment by lmcbout** [comment]
The current menu item generates the correct behavior. Nevertheless, I think the following commands should also be available from the menu as a minimum:

- Compare With...
If the pref "workspace.supportMultiRootWorkspace" is available then
    - Add Folder to workspace
    - Remove folder from Workspace

I noticed that if I add a second root workspace, then remove it, the "..." in the menu bar does not come back, so unable to select any commands anymore

**Comment by vince-fugnitto** [comment]
Updated to include:
- `Add Folder to Workspace`
- `Compare With...`

**Comment by vince-fugnitto** [comment]
> * Compare With...

Added.

>   If the pref "workspace.supportMultiRootWorkspace" is available then
>   
>   * Add Folder to workspace
>   * Remove folder from Workspace

I only display `Add Folder to Workspace` if there is a single-root workspace present.
In the case of multi-root the default behavior is used. Select roots to add / remove.

> I noticed that if I add a second root workspace, then remove it, the "..." in the menu bar does not come back, so unable to select any commands anymore.

The toolbar is only displayed in a single-root workspace (no root node is visible in the tree).
For multi-root the default behavior should be used.

File: packages/navigator/src/browser/navigator-contribution.ts [hunk 2]
```diff
@@ -340,6 +352,44 @@ export class FileNavigatorContribution extends AbstractViewContribution<FileNavi
...
+            const commandId = item.command;
+            const id = 'navigator.tabbar.toolbar.' + commandId;
+            const command = this.commandRegistry.getCommand(commandId);
+            this.commandRegistry.registerCommand({ id, iconClass: command && command.iconClass }, {
+                execute: (w, ...args) => w instanceof FileNavigatorWidget
+                    && this.commandRegistry.executeCommand(commandId, ...args),
+                isEnabled: (w, ...args) => w instanceof FileNavigatorWidget
+                    && !!this.workspaceService.workspace && !this.workspaceService.isMultiRootWorkspaceOpened
+                    && this.commandRegistry.isEnabled(commandId, ...args),
+                isVisible: (w, ...args) => w instanceof FileNavigatorWidget
```
Comment (akosyakov) [inline packages/navigator/src/browser/navigator-contribution.ts]: `isToggled` missing?

File: packages/navigator/src/browser/navigator-contribution.ts [hunk 3]
```diff
@@ -340,6 +352,44 @@ export class FileNavigatorContribution extends AbstractViewContribution<FileNavi
...
+                    && !!this.workspaceService.workspace && !this.workspaceService.isMultiRootWorkspaceOpened
+                    && this.commandRegistry.isVisible(commandId, ...args),
+            });
+            item.command = id;
+            toolbarRegistry.registerItem(item);
+        };
+        navigatorRegisterItem({
+            id: WorkspaceCommands.NEW_FILE_ROOT.id,
+            command: WorkspaceCommands.NEW_FILE_ROOT.id,
```
Comment (akosyakov) [inline packages/navigator/src/browser/navigator-contribution.ts]: Why not to reuse `NEW_FILE` and create a file in a first root?

File: packages/workspace/src/browser/workspace-commands.ts [hunk 4]
```diff
@@ -195,47 +201,17 @@ export class WorkspaceCommandContribution implements CommandContribution {
...
-                            this.fileSystem.createFile(fileUri.toString()).then(() => {
-                                open(this.openerService, fileUri);
-                            });
-                        }
-                    });
-                }
-            })
+            execute: uri => this.getDirectory(uri).then(parent => this.createNewFile(parent))
         }));
+        registry.registerCommand(WorkspaceCommands.NEW_FILE_ROOT, {
```
Comment (akosyakov) [inline packages/workspace/src/browser/workspace-commands.ts]: Why do we need it? Should not we have one `NEW_FILE` command which work based on a selection in the navigator?

i.e. if there is not a selection only then a file should be created in the first root always, otherwise in the selected folder?

File: packages/navigator/src/browser/navigator-contribution.ts [hunk 5]
```diff
@@ -340,6 +352,44 @@ export class FileNavigatorContribution extends AbstractViewContribution<FileNavi
...
+        // Commands are available when there is a single-root workspace currently opened.
+        const navigatorRegisterItem = (item: Mutable<TabBarToolbarItem>) => {
+            const commandId = item.command;
+            const id = 'navigator.tabbar.toolbar.' + commandId;
+            const command = this.commandRegistry.getCommand(commandId);
+            this.commandRegistry.registerCommand({ id, iconClass: command && command.iconClass }, {
+                execute: (w, ...args) => w instanceof FileNavigatorWidget
+                    && this.commandRegistry.executeCommand(commandId, ...args),
+                isEnabled: (w, ...args) => w instanceof FileNavigatorWidget
+                    && !!this.workspaceService.workspace && !this.workspaceService.isMultiRootWorkspaceOpened
```
Comment (akosyakov) [inline packages/navigator/src/browser/navigator-contribution.ts]: I think we should allow registering the sam items for multi-root as well. They should be either executed on the current selection or on the first root if there is no.

Also Sven wants to add toggle auto reveal in a follow-up PR and it should be there always regardless to whether multi root workspace opened or not.

File: packages/terminal/src/browser/terminal-frontend-contribution.ts [hunk 6]
```diff
@@ -180,22 +188,16 @@ export class TerminalFrontendContribution implements TerminalService, CommandCon
...
-            execute: async uri => {
-                // Determine folder path of URI
-                const stat = await this.fileSystem.getFileStat(uri.toString());
-                if (!stat) {
-                    return;
+            execute: async uri => this.openTerminalAtUri(uri)
+        }));
+        commands.registerCommand(TerminalCommands.TERMINAL_CONTEXT_ROOT, {
+            execute: async () => {
+                if (this.workspaceService.workspace) {
```
Comment (akosyakov) [inline packages/terminal/src/browser/terminal-frontend-contribution.ts]: i don't think using `this.workspaceService.workspace` is correct generally, since it can be just a file. We should base command on the current selection and roots, not a workspace.

File: packages/navigator/src/browser/navigator-contribution.ts (hunk 2 above)
Comment (vince-fugnitto) [reply packages/navigator/src/browser/navigator-contribution.ts]: Thanks, I'll include `isToggled` as well for the toolbar commands.

File: packages/workspace/src/browser/workspace-commands.ts (hunk 4 above)
Comment (vince-fugnitto) [reply packages/workspace/src/browser/workspace-commands.ts]: I'll support this but updating the command-handler passed.
I thought of doing this as well but I wanted to try and limit the number of commands which had to be adjusted/updated. It looks like there is in fact no way around it but updating the commands to fallback to the root.

File: packages/navigator/src/browser/navigator-contribution.ts (hunk 5 above)
Comment (vince-fugnitto) [reply packages/navigator/src/browser/navigator-contribution.ts]: Sounds good, I'll make the adjustments.

**Comment by vince-fugnitto** [comment]
@akosyakov @lmcbout @svenefftinge 
Are there any additional commands which should be added in the initial implentation?

**Comment by vince-fugnitto** [comment]
> Although, the last command (Compare With...) does not work. It display the list of branches, but when I select another branch, there is no Files changed

The `Compare With...` command displays changes based on the current state compared to the branch chosen. It is highly likely that the `No files changed.` message is displayed for a package such as `bunyan` (which is not updated frequently).

Using a very old branch as comparison I can in fact see changes:

<div align='left'>

Screen Shot 2019-08-22 at 8 26 21 AM

</div> 

Also, please see the limitation which was discovered by @elaihau https://github.com/theia-ide/theia/issues/5999

**Comment by lmcbout** [comment]
The diff I am looking for is this current diff against master, I should have 4 files changed, but get nothing.

Diff5951WithMaster

**Comment by vince-fugnitto** [comment]
> The diff I am looking for is this current diff against master, I should have 4 files changed, but get nothing.
> 
> Diff5951WithMaster

@lmcbout 
If you look at your .gif, you are selecting .theia which likely has no changes.

**Comment by lmcbout** [comment]
@vince-fugnitto  Ok, so If I colalpse the workspace, there is no "..." to select and get to the "Compare with..." command. The minute I select any folder, impossible to select the "Compare with for the workspace ?
DiffCollapse

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Ok, so If I colalpse the workspace, there is no "..." to select and get to the "Compare with..." command. The minute I select any folder, impossible to select the "Compare with for the workspace ?

Correct, that is the proper implementation of panels in a view container. 
When collapsed, all toolbar items (including mine) are not visible. 

Verified in VSCode:
a

**Comment by lmcbout** [comment]
So, how to get to the "Compare with..." command if there has been a selection of file/folder and I want to compare the whole branch, not just a sub-folder ?

**Comment by vince-fugnitto** [comment]
> So, how to get to the "Compare with..." command if there has been a selection of file/folder and I want to compare the whole branch, not just a sub-folder ?
 
You can always un-select your selection, similarly to how you un-select in a native desktop dialog.

**Example:** (using <kbd>cmd</kbd>+click on OSX)

<div align='center'>

d

</div>

**Comment by lmcbout** [comment]
> You can always un-select your selection, similarly to how you un-select in a native desktop dialog.

I was not aware we could un-select on Ubuntu, (CTRL + mouse left click)
Did not find any documentation either about it
Since it is not a known command, we should have something to let the user know either:
- How to un-select  a file/ folder in his workspace,
- Have a command to un-select the current selection (should be intuitive)
- Have another command "Compare workspace with" which select the root folder before doing a "Compare with..." command

**Comment by vince-fugnitto** [comment]
> I was not aware we could un-select on Ubuntu, (CTRL + mouse left click)

I believe it's pretty standard across all operating systems, similar to multi-select.

> Since it is not a known command, we should have something to let the user know either:

I disagree, it's pretty well known how to select, un-select and multi-select.

> * How to un-select  a file/ folder in his workspace,

I guess it can be added in a general user guide in the future.
Currently we do not have a user guide at all.

> * Have a command to un-select the current selection (should be intuitive)

I think it'd be overkill to have such commands when it can easily be un-selected with a click.

> * Have another command "Compare workspace with" which select the root folder before doing a "Compare with..." command

The command `Compare With...` compares the branch history if no selection is present, else it compares the folder history. Initially I had a command solely for the root of the workspace but did not want to duplicate the command unnecessarily.

File: packages/workspace/src/browser/workspace-commands.ts [hunk 7]
```diff
@@ -447,15 +447,29 @@ export class WorkspaceRootUriAwareCommandHandler extends UriAwareCommandHandler<
         super(selectionService, handler);
     }
 
+    isVisible(): boolean {
+        return !!this.workspaceService.tryGetRoots().length;
```
Comment (akosyakov) [inline packages/workspace/src/browser/workspace-commands.ts]: Should not we call super.isVisible as well to make sure that handler validates a given uri? the same for `isEnabled`?

File: packages/git/src/browser/diff/git-diff-frontend-module.ts [hunk 8]
```diff
@@ -30,5 +31,6 @@ export function bindGitDiffModule(bind: interfaces.Bind): void {
     }));
 
     bindViewContribution(bind, GitDiffContribution);
+    bind(TabBarToolbarContribution).toService(GitDiffContribution);
```
Comment (akosyakov) [inline packages/git/src/browser/diff/git-diff-frontend-module.ts]: `inSingletonScope`

File: packages/git/src/browser/diff/git-diff-contribution.ts [hunk 9]
```diff
@@ -101,6 +111,33 @@ export class GitDiffContribution extends AbstractViewContribution<GitDiffWidget>
         }));
     }
 
+    registerToolbarItems(registry: TabBarToolbarRegistry): void {
+        // Register 'more actions...' toolbar item which consists of multiple commands.
+        const navigatorRegisterItem = (item: Mutable<TabBarToolbarItem>) => {
```
Comment (akosyakov) [inline packages/git/src/browser/diff/git-diff-contribution.ts]: Can we add a method on `FileNavigatorContribution`, inject it here, and call instead of copy pasting code?

```ts
@inject(FileNavigatorContribution)
protected readonly navigatorContribution: FileNavigatorContribution;

registerToolbarItems(): void {
    this.navigatorContribution.registerToolbarItem({
        //....
    });
}

**Comment by akosyakov** [comment]
@vince-fugnitto I think it is important to have this PR done for 0.10.0. If you can please make it your priority to wrap it up.

File: packages/git/src/browser/diff/git-diff-frontend-module.ts (hunk 8 above)
Comment (vince-fugnitto) [reply packages/git/src/browser/diff/git-diff-frontend-module.ts]: I verified the source code, each example binding for `TabBarToolBarContribution` does not set the `inSingletonScope`. Is this correct?

For example:
https://github.com/theia-ide/theia/blob/566ebda6b9ede33984ff0d06044e889b2191c9d7/packages/debug/src/browser/debug-frontend-module.ts#L91

https://github.com/theia-ide/theia/blob/566ebda6b9ede33984ff0d06044e889b2191c9d7/packages/keymaps/src/browser/keymaps-frontend-module.ts#L39

https://github.com/theia-ide/theia/blob/566ebda6b9ede33984ff0d06044e889b2191c9d7/packages/navigator/src/browser/navigator-frontend-module.ts#L45

Comment (akosyakov) [reply packages/git/src/browser/diff/git-diff-frontend-module.ts]: ah, it is `toService`, not `to`, yes then it is correct

**Comment by vince-fugnitto** [comment]
@akosyakov I've updated the code based on your comments :)

File: packages/navigator/src/browser/navigator-contribution.ts [hunk 10]
```diff
@@ -61,6 +61,16 @@ export namespace FileNavigatorCommands {
...
 }
 
+/**
+ * Navigator `More Actions...` toolbar item groups.
+ * Used in order to group items present in the toolbar.
+ */
+export namespace NavigatorMoreToolbarGroups {
+    export const NEW_OPEN = '1_navigator_new_open';
+    export const WORKSPACE = '2_navigator_workspace';
+    export const SCM = '3_navigator_scm';
```
Comment (akosyakov) [inline packages/navigator/src/browser/navigator-contribution.ts]: navigator should not be aware of SCM, please move it to git extension

File: packages/workspace/src/browser/workspace-commands.ts [hunk 11]
```diff
@@ -447,15 +447,29 @@ export class WorkspaceRootUriAwareCommandHandler extends UriAwareCommandHandler<
         super(selectionService, handler);
     }
 
+    isVisible(): boolean {
+        return super.isVisible();
```
Comment (akosyakov) [inline packages/workspace/src/browser/workspace-commands.ts]: I thought you want to some special checks here, if it just calls super then we call removed these methods all together

File: packages/workspace/src/browser/workspace-commands.ts [hunk 12]
```diff
@@ -447,15 +447,29 @@ export class WorkspaceRootUriAwareCommandHandler extends UriAwareCommandHandler<
...
         const uri = super.getUri();
-        if (this.workspaceService.isMultiRootWorkspaceEnabled) {
-            return uri;
-        }
+        // If the URI is available, return it immediately.
         if (uri) {
             return uri;
         }
-        const root = this.workspaceService.tryGetRoots()[0];
+        // If a multi-root workspace is currently opened with at least one root,
```
Comment (akosyakov) [inline packages/workspace/src/browser/workspace-commands.ts]: Why not return first root or `undefined`?

Code below will break if there mutli-root workspaces is opened without any roots. Please make sure to not use `this.workspaceService.workspace`, but only `roots`.

Comment (akosyakov) [reply packages/workspace/src/browser/workspace-commands.ts]: so just `this.workspaceService.tryGetRoots()[0]`;

File: packages/workspace/src/browser/workspace-commands.ts [hunk 13]
```diff
@@ -447,15 +447,29 @@ export class WorkspaceRootUriAwareCommandHandler extends UriAwareCommandHandler<
...
 
+    isVisible(): boolean {
+        return super.isVisible();
+    }
+
+    isEnabled(): boolean {
+       return super.isEnabled();
+    }
+
     protected getUri(): URI | undefined {
```
Comment (akosyakov) [inline packages/workspace/src/browser/workspace-commands.ts]: it is so strange that we don't pass varargs here to a super implementation. Is not it a bug?

**Comment by vince-fugnitto** [comment]
Thank you for the feedback @akosyakov, I now updated the code and also pass `args` to `isEnabled`, `isVisible` and `getUri`.

File: packages/workspace/src/browser/workspace-commands.ts [hunk 14]
```diff
@@ -447,16 +447,27 @@ export class WorkspaceRootUriAwareCommandHandler extends UriAwareCommandHandler<
...
     }
 
-    protected getUri(): URI | undefined {
-        const uri = super.getUri();
-        if (this.workspaceService.isMultiRootWorkspaceEnabled) {
-            return uri;
-        }
+    // tslint:disable-next-line: no-any
+    public isEnabled(...args: any[]): boolean {
+        return super.isEnabled(args) && !!this.workspaceService.tryGetRoots().length;
```
Comment (akosyakov) [inline packages/workspace/src/browser/workspace-commands.ts]: `...args`, otherwise only one array is passed as one arg, please fix in other places

Also should not it be `||`, since roots are only fallback, and not mandatory if super check is successful?

**Comment by akosyakov** [comment]
@vince-fugnitto please have a look again

File: packages/workspace/src/browser/workspace-commands.ts (hunk 14 above)
Comment (akosyakov) [reply packages/workspace/src/browser/workspace-commands.ts]: ok

**Comment by vince-fugnitto** [comment]
@akosyakov is there any other changes required before merging?

**Comment by akosyakov** [comment]
@vince-fugnitto code looks good to me now, i gave a quick test and it works well also

**Comment by akosyakov** [comment]
@vince-fugnitto please merge, as soon as you are online

**Comment by vince-fugnitto** [comment]
Thank you @akosyakov for the help and review :)
