### PR TITLE
GH-738: Fixed cluster issue when running a packaged electron app.

### LINKED ISSUE #738: Bundled electron application does not start
The application is using published npm packages. It starts in debug mode from VSCode, also starting as an individual node process work. Fails when starting as an application.

I did some "debugging" and it turned out, that the connection is `undefined` when we are creating the proxy workers. Both the message reader and writer looks OK.

```
reader WorkerMessageReader {
  errorEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  closeEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  partialMessageEmitter: Emitter { _options: undefined },
  worker: 
   Worker {
     domain: null,
     _events: { message: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     exitedAfterDisconnect: undefined,
     suicide: [Getter/Setter],
     state: 'none',
     id: 1,
     process: 
      ChildProcess {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        _closesNeeded: 2,
        _closesGot: 0,
        connected: true,
        signalCode: null,
        exitCode: null,
        killed: false,
        spawnfile: '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/dist/mac/theia-electron-app-example.app/Contents/Frameworks/theia-electron-app-example Helper.app/Contents/MacOS/theia-electron-app-example Helper',
        _handle: [Object],
        spawnargs: [Object],
        pid: 13433,
        stdin: null,
        stdout: null,
        stderr: null,
        stdio: [Object],
        channel: [Object],
        _channel: [Getter/Setter],
        _handleQueue: null,
        _pendingHandle: null,
        send: [Function],
        _send: [Function],
        disconnect: [Function],
        _disconnect: [Function] } } }


writer WorkerMessageWriter {
  errorEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  closeEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  worker: 
   Worker {
     domain: null,
     _events: { message: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     exitedAfterDisconnect: undefined,
     suicide: [Getter/Setter],
     state: 'none',
     id: 1,
     process: 
      ChildProcess {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        _closesNeeded: 2,
        _closesGot: 0,
        connected: true,
        signalCode: null,
        exitCode: null,
        killed: false,
        spawnfile: '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/dist/mac/theia-electron-app-example.app/Contents/Frameworks/theia-electron-app-example Helper.app/Contents/MacOS/theia-electron-app-example Helper',
        _handle: [Object],
        spawnargs: [Object],
        pid: 13433,
        stdin: null,
        stdout: null,
        stderr: null,
        stdio: [Object],
        channel: [Object],
        _channel: [Getter/Setter],
        _handleQueue: null,
        _pendingHandle: null,
        send: [Function],
        _send: [Function],
        disconnect: [Function],
        _disconnect: [Function] } } }


inspect
connection undefined
```

The resulting error is the following:
```
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/dist/mac/theia-electron-app-example.app/Contents/MacOS/undefined'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3

```

CC: @akosyakov

### PR DESCRIPTION
**Pull request by kittaakos**
The cluster module works by forking a Node.js process and passing
the current `argv` to it. If the application is bundled together,
then the cluster module will not get the correct `argv`.
(See:
https://github.com/electron/electron/issues/6337#issuecomment-230183287)

Closes #738.

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

TODOs: (Verified with 1a3e09c0a77d2650a1036eafaa087543b8526da7 with [`dedupe`](https://github.com/theia-ide/theia/issues/752#issuecomment-339943269) before calling `webpack`)
 - [x] Verify in the browser with `yarn start`.
 - [x] Verify in the browser by launching it from VS Code.
 - [x] Verify in electron with `yarn start`.
 - [x] Verify in electron by launching it from VS Code.
 - [x] Verify in electron with published packaged by launching it from VS Code.
 - [x] Verify in the browser with published packaged by launching it from VS Code.
 - [x] Verify in bundled electron application.

### CODE REVIEW

**Comment by akosyakov** [comment]
Does just forking via child processes ensure the rest of cluster contract? Like ports are shared between http servers of workers?

**Comment by kittaakos** [comment]
> forking via child processes

That was the recommended way. The application seems to work in both debug and bundled mode. How else can I make sure it?

**Comment by kittaakos** [comment]
But do not get me wrong, if you have a better working solution, we can go with that too.

**Comment by akosyakov** [comment]
From https://github.com/electron/electron/issues/6337#issuecomment-230183287 I don’t understand whether forking should be done instead of using cluster or in addition.

You can be only sure if you try to fork another process and will use the same allocated port.

**Comment by kittaakos** [comment]
I am confident with my fixes it is better than it was before. As the current state of the master: it does not start. I am fine if you prefer holding up this PR until we have a better, verified solution but please keep in mind this issue blocks #346.

CC: @svenefftinge

**Comment by akosyakov** [comment]
https://stackoverflow.com/questions/13367607/what-are-the-effective-differences-between-child-process-fork-and-cluster-fork - you cannot replace usage of cluster.fork with child_process.fork, it will break. What they meant in the comment that we should not use cluster at all in the packaged electron app. 

If you want to disable clustering use `—no-cluster` option. You can do it programmatically at the top if it is not possible to pass it.

**Comment by kittaakos** [comment]
> you cannot replace usage of cluster.fork with child_process.fork

I must be stupid for this, but where did I replace the usage of `cluster.fork` with `child_process.fork`? If I did that, it was not intentional. What I've done, I think, is I have spawned a process for the backend outside from electron. Can you please explain this then? Thanks!

By the way, we can close this PR if programmatically setting the `--no-cluster` argument is feasible and it solves the issue.

**Comment by akosyakov** [comment]
@kittaakos You are not, I am just trying to understand how it works. So it used to work like:

(1) `[electron-main process/master process]` -- `cluster.fork` --> `[worker process]`

now if it is bundled then:

(2.1) `[electron-main process]` -- `child_process.fork` --> `[master process]`
(2.2) `[master process]` -- `cluster.fork` --> `[worker process]`

if not then (1)

It makes sense to me now, thank you for patience! Maybe we could use (2) always later to have less special cases.

File: dev-packages/application-package/src/generator/backend-generator.ts [hunk 1]
```diff
@@ -59,9 +59,11 @@ module.exports = (port, host) => Promise.resolve()${this.compileBackendModuleImp
     }
 
     protected compileMain(backendModules: Map<string, string>): string {
-        return ` // @ts-check
+        return `// @ts-check
 const serverPath = require('path').resolve(__dirname, 'server');
-module.exports = require('@theia/core/lib/node/cluster/main').default(serverPath);
+module.exports = require('@theia/core/lib/node/cluster/main').default(serverPath).then(function (address) {
```
Comment (akosyakov) [inline dev-packages/application-package/src/generator/backend-generator.ts]: before it exported an instance of address, it looks that now it exports nothing, I think that electron relies on it in the dev mode.

Also this code is used for the browser and there `then` cause does not make sense.

File: dev-packages/application-package/src/generator/frontend-generator.ts [hunk 2]
```diff
@@ -87,25 +87,46 @@ if (cluster.isMaster) {
...
-        });
+        const mainPath = path.join(__dirname, '..', 'backend', 'main');
+        const loadMainWindow = function(port) {
+            mainWindow.loadURL(\`file://\${path.join(__dirname, '../../lib/index.html')}?port=\${port}\`);
+        };
+        // We need to distinguish between bundled application and development mode when starting the clusters.
+        // https://github.com/electron/electron/issues/6337#issuecomment-230183287
+        if (devMode) {
+            require(mainPath).then(address => {
+                loadMainWindow(address.port);
```
Comment (akosyakov) [inline dev-packages/application-package/src/generator/frontend-generator.ts]: Does it still work? It looks like `main.js` does not export an instance of address anymore, see: https://github.com/theia-ide/theia/pull/746/files#r147333752

Comment (kittaakos) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: It did work. Anyway, I do another check.

File: dev-packages/application-package/src/generator/backend-generator.ts (hunk 1 above)
Comment (kittaakos) [reply dev-packages/application-package/src/generator/backend-generator.ts]: I will verify it once more to make sure it does not break existing behavior.

Comment (kittaakos) [reply dev-packages/application-package/src/generator/backend-generator.ts]: I need do another iteration on this. You were right, it did not work in all cases. I have updated the PR description with the TODOs.

File: dev-packages/application-package/src/generator/frontend-generator.ts (hunk 2 above)
Comment (kittaakos) [reply dev-packages/application-package/src/generator/frontend-generator.ts]: Fixed with 1a3e09c0a77d2650a1036eafaa087543b8526da7.

**Comment by kittaakos** [comment]
Something is wrong when consuming published npm packaged. I do not know if that is related to my changes. I need to check what is wrong with the injection:

```
bundle.js:71925 Error: Cannot apply @injectable decorator multiple times.
    at bundle.js:69212
    at DecorateConstructor (bundle.js:41323)
    at Object.decorate (bundle.js:40912)
    at _decorate (bundle.js:4783)
    at Object.decorate (bundle.js:4796)
    at Object.defineProperty.value (bundle.js:34875)
    at __webpack_require__ (bundle.js:689)
    at fn (bundle.js:110)
    at Object.c (bundle.js:14057)
    at __webpack_require__ (bundle.js:689)
```

**Comment by kittaakos** [comment]
I have opened a follow up: #752.

**Comment by kittaakos** [comment]
@akosyakov, I have updated the generated `main.js` code, I have verified the behavior as described in the PR's [description](https://github.com/theia-ide/theia/pull/746#issue-268743789). Let me know if the changes could go the `master`. Cheers!
