### PR TITLE
Disable deleting workspace root (fixes #2132)

### LINKED ISSUE #2132: Should disable the ability to delete root folders from the navigator
Current behavior allows users the ability to **delete root folders** directly from the ``navigator`` view.
Once the root folder has been deleted, Theia incorrectly does not update the ``navigator`` view.

bug-theia-delete-root

Fix should instead disable the **delete** option from the menu, preserving the workspace context.

### PR DESCRIPTION
**Pull request by svenefftinge**

### CODE REVIEW

File: packages/workspace/src/browser/workspace-commands.ts [hunk 1]
```diff
@@ -144,7 +144,14 @@ export class WorkspaceCommandContribution implements CommandContribution {
...
             })
         }));
+        let rootUri: URI | undefined;
+        this.workspaceService.root.then(root => {
+            if (root) {
+                rootUri = new URI(root.uri);
+            }
+        });
         registry.registerCommand(WorkspaceCommands.FILE_DELETE, this.newMultiUriAwareCommandHandler({
+            isVisible: uris => !(rootUri && uris.some( uri => uri.toString() === rootUri!.toString())),
```
Comment (kittaakos) [inline packages/workspace/src/browser/workspace-commands.ts]: There is a formatting whitespace before the `uri` parameter. Plus, you could save the root URI as a string after resolving it, so that there is no need to call `toString()` multiple times.

But please hold on with the changes, I need to verify it especially because of your modifications in the `uri-command-handler`.

Comment (svenefftinge) [reply packages/workspace/src/browser/workspace-commands.ts]: I think the logic is broken. Or at least the type signature doesn't match.

Comment (kittaakos) [reply packages/workspace/src/browser/workspace-commands.ts]: I am OK changing it but then we need to get rid of `isValid`. Did you check other use-sites whether it breaks anything else?

Comment (svenefftinge) [reply packages/workspace/src/browser/workspace-commands.ts]: +1 I removed the isValid stuff.

Comment (svenefftinge) [reply packages/workspace/src/browser/workspace-commands.ts]: > Plus, you could save the root URI as a string after resolving it, so that there is no need to call toString() multiple times.

This is not a hot path, so I prefer it to be more readable (symmetrical).

Comment (kittaakos) [reply packages/workspace/src/browser/workspace-commands.ts]: :+1

Comment (svenefftinge) [reply packages/workspace/src/browser/workspace-commands.ts]: > Did you check other use-sites whether it breaks anything else?
Yes
