### PR TITLE
[keybings] properly translate to monaco keycodes (fixes #493)

### LINKED ISSUE #493: Keybindings in the menus differ from the command palette
For example:
 
Menu: Selection->Move line up is Alt+UpArrow according to the menu.

And that works.

But according to the command palette it's: Alt-H 

And that does not work.

### PR DESCRIPTION
**Pull request by svenefftinge**
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>

### CODE REVIEW

File: packages/monaco/src/browser/monaco-keycode-map.ts [hunk 1]
```diff
@@ -0,0 +1,155 @@
+/*---------------------------------------------------------------------------------------------
+ *  Copyright (c) Microsoft Corporation. All rights reserved.
+ *  Licensed under the MIT License. See License.txt in the project root for license information.
+ *--------------------------------------------------------------------------------------------*/
+
+import * as browser from "@theia/core/lib/browser";
+
+const KeyCode = monaco.KeyCode;
+
+export let KEY_CODE_MAP: { [keyCode: number]: monaco.KeyCode } = {};
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-keycode-map.ts]: it seems to contain the same info  as `MONACO_KEY_CODE_MAP`:
https://github.com/theia-ide/theia/blob/45884b21389ecf421b8d9cdfa2a708fb608faab5/packages/monaco/src/browser/monaco-keybinding.ts#L18-L155

Comment (svenefftinge) [reply packages/monaco/src/browser/monaco-keycode-map.ts]: Oh yes, I didn't see that. It's the other direction though. I would like to keep my copy (with proper copyrights) and remove this one with a function that iterates.
