### PR TITLE
Fix #5279 Leaking java debug process

### LINKED ISSUE #5279: [vscode]Leaking java debug process
### Description
When start debugging using vscode java-debug extension, the debug process will remain in OS process list and never be killed by theia process if the page is reloaded.
If I don't kill the debug process manually and start a new debug session, the debug console will show the exception of "Address already in use".

### Reproduction Steps
* install jdk and maven
```
apt-get install openjdk-11-jdk
apt-get install maven
```
* git clone https://github.com/theia-ide/theia.git && cd theia
* Delete theia java and java-debug extensions, for I only want to use debug function provided by vscode java-debug extension
```
sed -i '/theia\/java/d' examples/browser/package.json
mkdir plugins
wget https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/java/0.44.0/vspackage -O plugins/redhat.java-0.44.0.vsix
wget https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscjava/vsextensions/vscode-java-debug/0.15.0/vspackage -O plugins/vscjava.vscode-java-debug-0.15.0.vsix
```
* yarn
* cd examples/browser && yarn start
* Open a spring java project (you can git clone https://github.com/spring-projects/spring-petclinic ) and press F5 (for now you may need to press twice) to start debugging session.
* Click browser reload button and press F5 (Start Debugging button), the debug console will show error logs.
```
org.apache.catalina.util.LifecycleBase : Failed to start component [Connector[HTTP/1.1-8080]]
org.apache.catalina.LifecycleException: Protocol handler start failed
Caused by: java.net.BindException: Address already in use
```
**OS and Theia version:**
OS: Ubuntu 18.04
Theia version: latest master version

**Diagnostics:** 
1. click **Start Debugging** button and reload the page
leaking-debug-process-p1
2. click **Start Debugging** button again, but failed to start the debug session
leaking-debug-process-p2
3. there are some errors in **Debug Console**
leaking-debug-process-p3
4. leaking java debug process
normal-debug-process

### PR DESCRIPTION
**Pull request by tom-shan**
When start debugging using vscode java-debug extension,
the debug process will remain in OS process list and
never be killed by theia process if the page is reloaded.

When terminate plugin server, kill all child processes
of plugin-host process.

Signed-off-by: tom-shan <swt0008411@163.com>

### CODE REVIEW

**Comment by tom-shan** [comment]
fix https://github.com/theia-ide/theia/issues/5279

**Comment by tom-shan** [comment]
@benoitf @evidolob @akosyakov Would you mind reviewing this PR?

File: packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts [hunk 1]
```diff
@@ -120,13 +121,22 @@ export class HostedPluginProcess implements ServerPluginRunner {
             }
         });
         const hostedPluginManager = rpc.getProxy(MAIN_RPC_CONTEXT.HOSTED_PLUGIN_MANAGER_EXT);
+        this.killChildProcesses(cp.pid);
```
Comment (akosyakov) [inline packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: it should go in `then` case after after plugin got unloaded

Comment (tom-shan) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: Done

**Comment by akosyakov** [comment]
I don't think it is really resolves the issue. Usually child process should observer parent process and if it crasher then exit. Killing child processes from a parent process does not guarantee that it will happens always, e.g. if a parent process crashes it won't have a chance of doing it. I'm pretty sure that vscode java debug extension already has this logic, otherwise it won't work in VS Code as well. It bothers me why debug process exits only when a main server process dies. It seems that propagation of parent process id is done bogusly.

**Comment by tom-shan** [comment]
I have tested these two extensions in vscode(1.34.0) and got the similar results. 
If I kill the extension host process in the background, then the java process will be killed later. But the java debug process will remain in the background even when I have exited the vscode. 
If I click Start Debug, the debug console will show the same error.
image

**Comment by akosyakov** [comment]
@tom-shan you are right, just got the same

File: packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts [hunk 2]
```diff
@@ -122,11 +123,21 @@ export class HostedPluginProcess implements ServerPluginRunner {
...
 
     }
 
+    private killProcessTree(parentProcess: cp.ChildProcess): void {
+        const parentPid = parentProcess.pid;
+        // tslint:disable-next-line:no-any
+        psTree(parentPid, (err: Error, children: Array<any>) => {
+            parentProcess.kill();
+            // tslint:disable-next-line:no-any
+            cp.spawn('kill', children.map((p: any) => p.PID));
```
Comment (akosyakov) [inline packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: Will it work on windows? Would it make sense to run `taskkill` on Windows instead like here: https://github.com/microsoft/vscode/blob/a848f18df4efa9eb947bd01cbebcede418e66148/src/vs/workbench/contrib/debug/node/debugAdapter.ts#L269-L275

**Comment by akosyakov** [comment]
It probably solver https://github.com/theia-ide/theia/issues/4590
but we have to revert https://github.com/theia-ide/theia/pull/5257 (@amiramw sorry, but it caused issue which were discussed on the PR)
and look into proper solution where plugins are unloaded from fronted and initializes on reconnection again (i am going to look into it later this week)

**Comment by amiramw** [comment]
Will this problem happen also when two clients connect together? Like two different browsers.
Is this scenario expected to work in general with the plugins mechanism?

**Comment by akosyakov** [comment]
> Will this problem happen also when two clients connect together? Like two different browsers.
Is this scenario expected to work in general with the plugins mechanism?

I don't think it is related to the plugin system. When 2 users connect to the same backend they cannot expect to run anything on the same ports. Regarding debugging there is an issue to make debug session shared by default. That each client for the same workspace see all running debug sessions.

File: packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts (hunk 2 above)
Comment (tom-shan) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: I have tested the new commit on windows 10.
But then I found that when I close the browser page, there many errors which may related with some message received by plugin-host process , so I disconnect the parentProcess at first.
```
UnhandledPromiseRejectionWarning: Error: Unknown actor WorkspaceMain
...
UnhandledPromiseRejectionWarning: Error: Unknown actor LanguagesMain
...
UnhandledPromiseRejectionWarning: Error: Unknown actor CommandRegistryMain
...
```

Comment (tom-shan) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: @akosyakov Please let me know if you have any questions. :)

**Comment by tom-shan** [comment]
Hi @akosyakov, it seems like no other questions, could you help merge this PR?

File: packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts [hunk 3]
```diff
@@ -122,11 +123,26 @@ export class HostedPluginProcess implements ServerPluginRunner {
...
+            this.killProcessTree(cp);
         });
 
     }
 
+    private killProcessTree(parentProcess: cp.ChildProcess): void {
+        parentProcess.disconnect();
+        const parentPid = parentProcess.pid;
+        if (isWindows) {
+            cp.spawn('taskkill', ['/F', '/T', '/PID', parentPid.toString()]);
```
Comment (kittaakos) [inline packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: I had a very similar issue in one of my downstream projects. A few remarks on the PR:
 - Instead of doing `taskkill` on Windows and `kill` on *nix, just use `tree-kill`:
```ts
require('tree-kill')(yourPID);
```
 - You have to get the process tree on Windows as well. Not just in the `else` branch.

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: interesting that VS Code uses `taskkill` for it: https://github.com/microsoft/vscode/blob/a848f18df4efa9eb947bd01cbebcede418e66148/src/vs/workbench/contrib/debug/node/debugAdapter.ts#L269-L275

Comment (akosyakov) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: ah, i see tree-kill does it https://github.com/pkrumins/node-tree-kill/blob/master/index.js#L20

**Comment by akosyakov** [comment]
@tom-shan sorry, we still had not time to test this PR on different platforms

@kittaakos could we rebase, test it as it is and merge? or you will prefer to use `tree-kill`

Could you verify on windows please?

In order to test one can install nodejs vscode extensions (https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug + https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug2) instead of native (`@theia/debug-nodejs`) and then kill the backend during debugging and verify that processes are gone.

File: packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts (hunk 3 above)
Comment (tom-shan) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: Thanks for your recommendation, I will try to use this new npm package.

Comment (kittaakos) [reply packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts]: @tom-shan, please ping if you are done, I'll try to find time for the verification. Thanks!

**Comment by tom-shan** [comment]
@kittaakos @akosyakov Please have a review.

**Comment by kittaakos** [comment]
> Please have a review.

Sorry for the confusion, @tom-shan. I think what you did for the non-Windows version was the right way: you have to kill the children of the process you want to terminate, then the process. Something like this:
```ts
private killChildProcesses(parentPid: number): void {
    psTree(parentPid, (_, children) {
        for (const { PID } of children) {
            kill(PID);
        }
        kill(parentPid);
    });
}
```

**Comment by tom-shan** [comment]
But according to https://github.com/pkrumins/node-tree-kill/blob/master/index.js#L47-L56, it will kill child processes first. 
BTW, https://www.npmjs.com/package/terminate may be a better choice?

**Comment by kittaakos** [comment]
> But according to https://github.com/pkrumins/node-tree-kill/blob/master/index.js#L47-L56, it will kill child processes first.

The logic you have referenced does not run for Windows: https://github.com/pkrumins/node-tree-kill/blob/3b5b8feeb3175a3e16ea7e0e09fdf5b8d2b87b08/index.js#L20-L21

**Comment by tom-shan** [comment]
Got it. So we can use 'terminate' instead, because it has the right killing order and you can refer to https://github.com/dwyl/terminate/blob/master/handlePsTreeCallback.js#L17

**Comment by kittaakos** [comment]
> we can use 'terminate'

I have not used it yet, but if you want to use `terminate`, add it, I will verify.

**Comment by tom-shan** [comment]
I'm done.

**Comment by kittaakos** [comment]
I am verifying this on Windows.

**Comment by akosyakov** [comment]
please don't forget to check licenses of new dependencies: https://github.com/theia-ide/theia/wiki/Registering-CQs#wip---new-ecd-theia-intellectual-property-clearance-approach-experimental

cc @marcdumais-work

**Comment by kittaakos** [comment]
I tried to verify it on Windows in the electron example app. It did not work. I did the followings:
 - Removed `@theia/java` and `@theia/java-debug` from both the `browser` and `electron` `package.json` files.
 - Rebuilt the extensions without Theia Java.
 - Downloaded the two Java VS Code extensions.
```
root INFO unzipping the plugin ProxyPluginDeployerEntry {
  deployer:
   PluginVsCodeFileHandler {
     unpackedFolder: 'C:\\Users\\KITTAA~1\\AppData\\Local\\Temp\\vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'local-dir:../../plugins',
     pluginId: 'redhat.java-0.47.0.vsix',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath:
      'C:\\Users\\kittaakos\\dev\\theia\\plugins\\redhat.java-0.47.0.vsix',
     initPath:
      'C:\\Users\\kittaakos\\dev\\theia\\plugins\\redhat.java-0.47.0.vsix',
     resolved: true,
     resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
root INFO unzipping the plugin ProxyPluginDeployerEntry {
  deployer:
   PluginVsCodeFileHandler {
     unpackedFolder: 'C:\\Users\\KITTAA~1\\AppData\\Local\\Temp\\vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'local-dir:../../plugins',
     pluginId: 'vscjava.vscode-java-debug-0.20.0.vsix',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath:
      'C:\\Users\\kittaakos\\dev\\theia\\plugins\\vscjava.vscode-java-debug-0.20.0.vsix',
     initPath:
      'C:\\Users\\kittaakos\\dev\\theia\\plugins\\vscjava.vscode-java-debug-0.20.0.vsix',
     resolved: true,
     resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\r
edhat.java-0.47.0.vsix
root INFO Resolved "redhat.java-0.47.0.vsix" to a VS Code extension "java@0.47.0" with engines: { vscode: '^1.36.0' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\v
scjava.vscode-java-debug-0.20.0.vsix
root INFO Resolved "vscjava.vscode-java-debug-0.20.0.vsix" to a VS Code extension "vscode-java-debug@0.20.0" with engine
s: { vscode: '^1.32.0' }
root INFO Deploying backend plugin "java@0.47.0" from "C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\redhat.java-
0.47.0.vsix\extension\dist\extension"
root INFO Deploying backend plugin "vscode-java-debug@0.20.0" from "C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked
\vscjava.vscode-java-debug-0.20.0.vsix\extension\dist\extension"
```
 - Cloned https://github.com/spring-projects/spring-petclinic and opened it as my workspace.
```
root INFO [nsfw-watcher: 2572] Started watching: c:\Users\kittaakos\dev\spring-petclinic\.vscode\launch.json
root INFO [nsfw-watcher: 2572] Started watching: c:\Users\kittaakos\dev\spring-petclinic\.vscode\settings.json
root INFO Started watching the git repository: file:///c%3A/Users/kittaakos/dev/spring-petclinic
```
 - Waited for the LS to start and build.
```
root INFO [hosted-plugin: 3152] PLUGIN_HOST(3152): PluginManagerExtImpl/init()
PLUGIN_HOST(3152): initializing(java@0.47.0 with C:\Users\kittaakos\dev\theia\packages\plugin-ext-vscode\lib\node/plugin
-vscode-init.js)
PLUGIN_HOST(3152): initializing(vscode-java-debug@0.20.0 with C:\Users\kittaakos\dev\theia\packages\plugin-ext-vscode\li
b\node/plugin-vscode-init.js)
Debugger contribution has been registered: java
root INFO [hosted-plugin: 3152] PLUGIN_HOST(3152): PluginManagerExtImpl/loadPlugin(C:\Users\KITTAA~1\AppData\Local\Temp\
vscode-unpacked\redhat.java-0.47.0.vsix\extension\dist\extension)
root INFO [hosted-plugin: 3152] { message:
   'Starting Java server with: C:\\PROGRA~1\\Java\\JDK18~1.0_1\\bin\\java -Declipse.application=org.eclipse.jdt.ls.core.
id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=UTF-8 -DwatchPa
rentProcess=false -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar C:\\Users\\KITTAA~1\\AppData\\Local\\Te
mp\\vscode-unpacked\\redhat.java-0.47.0.vsix\\extension\\server\\plugins\\org.eclipse.equinox.launcher_1.5.500.v20190715
-1310.jar -configuration C:\\Users\\KITTAA~1\\AppData\\Local\\Temp\\vscode-unpacked\\redhat.java-0.47.0.vsix\\extension\
\server\\config_win -data C:\\Users\\kittaakos\\AppData\\Roaming\\.theia\\workspace-storage\\b57d6bdc8a5ce6f798acacd19bf
4aa59\\redhat.java\\jdt_ws',
  level: 'info',
  timestamp: '2019-07-31 09:39:52.756' }
```
 - Started the `Debug (Launch)-PetClinicApplication<spring-petclinic>` launch configuiration.
 - Had an error:
```
root INFO [hosted-plugin: 3152] PLUGIN_HOST(3152): PluginManagerExtImpl/loadPlugin(C:\Users\KITTAA~1\AppData\Local\Temp\
vscode-unpacked\vscjava.vscode-java-debug-0.20.0.vsix\extension\dist\extension)
root INFO [hosted-plugin: 3152] Debug configuration provider has been registered: java
root INFO [hosted-plugin: 3152] Cannot update debug settings. { Error: No delegateCommandHandler for vscode.java.updateD
ebugSettings
    at C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\redhat.java-0.47.0.vsix\extension\dist\extension.js:1:13690
    at C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\redhat.java-0.47.0.vsix\extension\dist\extension.js:1:13984
    at Immediate.k.size.setImmediate (C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\redhat.java-0.47.0.vsix\exten
sion\dist\extension.js:1:14345)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5) code: -32601, data: undefined }
root ERROR Error starting the debug session Error: It is not possible to provide debug adapter executable.
    at DebugExtImpl.<anonymous> (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\plugin\node\debug\debug.js:501:39)
    at step (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\plugin\node\debug\debug.js:32:23)
    at Object.next (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\plugin\node\debug\debug.js:13:53)
    at fulfilled (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\plugin\node\debug\debug.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Screen Shot 2019-07-31 at 09 48 58

**Comment by akosyakov** [comment]
@kittaakos Please try with node.js vscode extensions, they are in the better state.

> In order to test one can install nodejs vscode extensions (https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug + https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug2) instead of native (@theia/debug-nodejs) and then kill the backend close the window during debugging and verify that processes are gone. You will need to wait a bit because of #5257.

**Comment by marcdumais-work** [comment]
> please don't forget to check licenses of new dependencies: https://github.com/theia-ide/theia/wiki/Registering-CQs#wip---new-ecd-theia-intellectual-property-clearance-approach-experimental
> 
> cc @marcdumais-work

+1

[terminate](https://www.npmjs.com/package/terminate) is licensed under GPL v2.0 and so is not appropriate for an Eclipse Foundation project such as Theia.

**Comment by tom-shan** [comment]
OK, I will refactor this PR without `terminate`.

**Comment by tom-shan** [comment]
@kittaakos Please verify it again.

File: packages/plugin-ext/package.json [hunk 4]
```diff
@@ -29,6 +29,7 @@
     "getmac": "^1.4.6",
     "jsonc-parser": "^2.0.2",
     "lodash.clonedeep": "^4.5.0",
+    "ps-tree": "^1.2.0",
```
Comment (kittaakos) [inline packages/plugin-ext/package.json]: `ps-tree` is already declared with version `1.1.0` in `plugin-dev`, if you use that, there is no `yarn.lock` file changes.

If you insist on using `1.2.0`, can you please add the `@types/ps-tree` as well, so there is no need to use `any`s and `no-any`s linter rules. After adding the type definition for `ps-tree` as a dependency, you can do ES6 imports: `import * as psTree from 'ps-tree';`.

You're OK leaving everything as is.

**Comment by kittaakos** [comment]
> Please try with node.js vscode extensions

@akosyakov, how can I make sure it is a fix for the leaking Java process?

File: packages/plugin-ext/package.json (hunk 4 above)
Comment (tom-shan) [reply packages/plugin-ext/package.json]: Thanks for your suggestion, I will use 1.2.0 and add @types/ps-tree.

**Comment by tom-shan** [comment]
> I tried to verify it on Windows in the electron example app. It did not work. I did the followings:

I have tested with two vscode extensions: java 0.44.0 and java-debug 0.15.0 in Ubuntu and have the 
same error of `root ERROR Error starting the debug session Error: It is not possible to provide debug adapter executable.`

**Comment by kittaakos** [comment]
> have the
> same error of

Thanks for the note, @tom-shan.

Locally, I have rebased your code from the HEAD of Theia's `master`. Maybe, it was fixed.
If no, I will check with the exact same version you provided in the original [issue description](https://github.com/theia-ide/theia/issues/5279#issue-449133288). Very solid steps, by the way 👍🎖

**Comment by tom-shan** [comment]
If still have the same error, you can try with another [repo](https://github.com/ananthakumaran/maven-demo.git).

**Comment by tom-shan** [comment]
@kittaakos After the extra process of cleaning some data(`~/.theia` and `/tmp/vscode-unpacked`), the error of `root ERROR Error starting the debug session Error: It is not possible to provide debug adapter executable` is gone and the debug session can be started successfully in my vm.

**Comment by kittaakos** [comment]
Are we good license-wise for this PR, @marcdumais-work? Thanks!

**Comment by marcdumais-work** [comment]
> Are we good license-wise for this PR, @marcdumais-work? Thanks!

LGTM - the latest version of this PR adds no new dependency (`ps-tree` was already pulled from `@theia/plugin-dev`.

**Comment by kittaakos** [comment]
> LGTM

Thank you for your help!
