### PR TITLE
[lsp] handle reconnection & init errors gracefully

### LINKED ISSUE #1684: LSPs can cause multiple command registration error
A language server needs to register a command if it wants to use it as part of the menus and assign a shortcut. This is done with a `CommandContribution` and the command is registered at the start. If the LSP registers the same command via registerCapability for use with `workspace/executeCommand` calls an [Error is generated](https://github.com/theia-ide/theia/blob/187c6cec353894bb4d0f6a4f0c34beecd31c1bca/packages/core/src/common/command.ts#L115) for a duplicate command registration.

### LINKED ISSUE #2419: Manually start language server and send notification or request
Is there a method to manually start a language server in Theia?
I want to be able to send notifications or requests to the language server (i.e. the Java LSP) like `textDocument/didOpen`, `textDocument/didChange` or `workspace/didChangeWorkspaceFolders`.

Best case scenario would be something like this:
```
const javaLs: LanguageServer = this.someLsService.getLanguageServer("java");
const response = javaLs.textDocumentDidOpen("/path/to/my/file");
```

### LINKED ISSUE #2750: [ts] Superfluous error logging when cannot find the `tsserver` executable
I get the errors either periodically, or per file per WS. One would be enough. See attached screencast. Maybe the defect is not TS specific but a generic issue with the LS processes.

screencast 2018-08-31 20-33-11

### LINKED ISSUE #2995: Re-starting the server when two or more workspaces are in a browser generates errors.
Starting Theia in a browser generates errors on the server console
If you start Theia in a browser, it starts ok
If you add a second workspace in the browser, then select again Theia workspace 
Note: average loading time is also bad when there is more than one workspace available in a browser and re-starting the server . The secondd workspace could be very little, just a few files in it is enough.

Restart the server and press the refresh button of the browser for Theia workspace, then many errors appears on the server console.
1-
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

2-
root ERROR TypeScript: (node:24318) UnhandledPromiseRejectionWarning: Error: geterr timeout

3- List of warnings:
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.

### LINKED ISSUE #3224: Reconnecting issues
Steps to reproduce with **TS** (Java is below):

 - Close your browser.
 - Delete previous Theia settings: `rm -rf ~/.theia`. (I am not sure this is mandatory.)
 - Clone, build and start Theia's backend for the browser. (e619393d)
 - Set `theia` as your workspace root.
 - Open `os.ts` in Theia. Make sure your LS has started. You can verify with the CA.
 - Stop the backend.
 - Restart the backend.
 - You can see that something is already odd with the command registration.

```
yarn run start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 87960]
Server worker is ready to accept messages. [ID: 1 | PID: 87960]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 87961] Started watching: /Users/akos.kitta/git/theia/examples/browser/package.json
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}
Error: "f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}
Error: "shift+f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"pluginsView:toggle","keybinding":"ctrlcmd+shift+y"}  collided with  {"command":"debug:console:toggle","keybinding":"ctrlcmd+shift+y"}
root WARN Could not register keybinding:
  {"command":"pluginsView:toggle","keybinding":"ctrlcmd+shift+y"}
Error: "ctrlcmd+shift+y" is in collision with something else [scope:0]
root INFO [nsfw-watcher: 87974] Started watching: /Users/akos.kitta/Desktop/-1539695154767.log
root INFO [nsfw-watcher: 87974] Stopped watching: /Users/akos.kitta/Desktop/-1539695154767.log
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}
Error: "f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}
Error: "shift+f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"pluginsView:toggle","keybinding":"ctrlcmd+shift+y"}  collided with  {"command":"debug:console:toggle","keybinding":"ctrlcmd+shift+y"}
root WARN Could not register keybinding:
  {"command":"pluginsView:toggle","keybinding":"ctrlcmd+shift+y"}
Error: "ctrlcmd+shift+y" is in collision with something else [scope:0]
root INFO [nsfw-watcher: 87986] Started watching: /Users/akos.kitta/.theia
root INFO [nsfw-watcher: 87986] Started watching: /Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 87986] Started watching: /Users/akos.kitta/git/theia
task INFO Config file tasks.json does not exist under file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 87986] Started watching: /Users/akos.kitta/git/theia/packages/core/src/browser/status-bar/index.ts
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
^C
Akoss-MacBook-Pro:browser akos.kitta$ yarn run start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 88028]
Server worker is ready to accept messages. [ID: 1 | PID: 88028]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 88030] Started watching: /Users/akos.kitta/git/theia/examples/browser/package.json
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO [nsfw-watcher: 88031] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/theia
Started watching: /Users/akos.kitta/git/theia
Started watching: /Users/akos.kitta/git/theia/packages/core/src/browser/status-bar/index.ts
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 88058] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/theia
Started watching: /Users/akos.kitta/git/theia
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root INFO [nsfw-watcher: 88058] Started watching: /Users/akos.kitta/git/theia/packages/core/src/browser/status-bar/index.ts
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 88104] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 88104] Started watching: /Users/akos.kitta/git/theia
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root INFO [nsfw-watcher: 88104] Started watching: /Users/akos.kitta/git/theia/packages/core/src/browser/status-bar/index.ts
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
^C
```

----

Steps to reproduce with **Java** (TS is above):

 - Close your browser.
 - Delete previous Theia settings: `rm -rf ~/.theia`. (I am not sure this is mandatory.)
 - Clone, build and start Theia's backend for the browser. (e619393d)
 - Set [`eclipse.jdt.ls`](https://github.com/eclipse/eclipse.jdt.ls) as your workspace root.
 - Open `AbstractProjectImporter.java` in Theia. Make sure your LS has started. You can verify with the CA.
 - Stop the backend.
 - Restart the backend.
 - You can see how many times the Java LS has started after the backend restart.

```
yarn run start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 88629]
Server worker is ready to accept messages. [ID: 1 | PID: 88629]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 88630] Started watching: /Users/akos.kitta/git/theia/examples/browser/package.json
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536884/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536928/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536952/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536967/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536981/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536998/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537012/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537025/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537039/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537052/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537065/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537078/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537090/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537102/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537114/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537126/.metadata/.log
root INFO [nsfw-watcher: 88638] Started watching: /Users/akos.kitta/.theia
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88638] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936548770/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936549200/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936549226/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936549640/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936549990/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936550342/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936550626/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936550979/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936551202/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936551524/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936551604/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936551818/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936551848/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936552194/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936552448/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936552715/.metadata/.log
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88706] Started watching: /Users/akos.kitta/.theia
root INFO [nsfw-watcher: 88706] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88706] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88706] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java
^C
Akoss-MacBook-Pro:browser akos.kitta$ yarn run start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 88880]
Server worker is ready to accept messages. [ID: 1 | PID: 88880]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 88881] Started watching: /Users/akos.kitta/git/theia/examples/browser/package.json
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682261/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682279/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682293/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682308/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682331/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682349/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682367/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682384/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682401/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682423/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682445/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682457/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682470/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682482/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682493/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682505/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682516/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682528/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682539/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682551/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682562/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682575/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682586/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682597/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682609/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682620/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682632/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682643/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682654/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682665/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682677/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682689/.metadata/.log
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO [nsfw-watcher: 88889] Started watching: /Users/akos.kitta/.theia
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO [nsfw-watcher: 88889] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO [nsfw-watcher: 88889] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO [nsfw-watcher: 88889] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java
^C
Akoss-MacBook-Pro:browser akos.kitta$
Akoss-MacBook-Pro:browser akos.kitta$
```

Finally, it ends up with the following error:
```
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936500478/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936500506/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936500617/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936500661/.metadata/.log
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88555] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88555] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at RoundRobinHandle.add (internal/cluster/round_robin_handle.js:34:3)
    at queryServer (internal/cluster/master.js:316:10)
    at Worker.onmessage (internal/cluster/master.js:248:5)
    at ChildProcess.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
✨  Done in 19.78s.
```

Related issues: https://github.com/theia-ide/theia/issues/3150, https://github.com/theia-ide/theia/issues/3145, https://github.com/theia-ide/theia/pull/3148#issuecomment-428980689

### PR DESCRIPTION
**Pull request by akosyakov**
- fixes #2750: on the initialization error the server should be stopped, a user should be prompted to retry with a notification. There is also a command to start a language server if it is not running.
- fixes #2995, fixes #1684: commands should be properly disposed when a language server is stopped
- fixes #3224: ~not sure whether this issue still exists. I've only tested connection and initialization issues. The situation when a server goes completely down does not happen often in practice.~ - turned out to be the worst bug with a cycle between closing old channel and opening a new one, leading to a lot of duplicate channels
- closes #2419: one can activate/deactivate language contributions programmatically

### CODE REVIEW

**Comment by kittaakos** [comment]
I am verifying it...

**Comment by akosyakov** [comment]
@simark I've moved generic commands' registration to `LanguagesFrontendContribution`: https://github.com/theia-ide/theia/pull/3319/files#diff-778fc6e5def7d229046da1db3650e3b9R23

i.e. for start, stop and restart language servers

They don't need to be unregistered since they are based on a running state of language contribution.

**Comment by kittaakos** [comment]
I do not know whether it is intended to fix #3224, if so, it does not work. Each `root INFO Java: logs` entry means a LS start.

Steps to reproduce:
 - Open a WS with Java, wait until the Java LS starts.
 - Stop the backend.
 - Start the backend.

```
...
root INFO Registering scopes for language: java.
root INFO The scopes have been successfully registered for java.
root WARN A command java.edit.organizeImports is already registered.
^C
Akoss-MacBook-Pro:browser akos.kitta$ yarn run start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 41596]
Server worker is ready to accept messages. [ID: 1 | PID: 41596]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 41597] Started watching: /Users/akos.kitta/git/theia/examples/browser/package.json
root INFO Unregistering scopes for language: java.
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896492187/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896492201/.metadata/.log
root INFO The scopes have been successfully unregistered for java.
root INFO Started watching the git repository: file:///Users/akos.kitta/git/yang-lsp
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO [nsfw-watcher: 41605] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java
root INFO [nsfw-watcher: 41612] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources
root INFO [nsfw-watcher: 41612] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-tsm.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-tls.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-target.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-notification.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/pass/test8b.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/pass/test8c.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-vacm.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-usm.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-community.yang
root INFO [nsfw-watcher: 41612] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-engine.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-proxy.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/pass/test8d.yang
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/yang-lsp
root INFO Started watching the git repository: file:///Users/akos.kitta/git/yang-lsp
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896497351/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896497380/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896497417/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896497456/.metadata/.log
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 41725] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 41725] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/yang-lsp
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO Started watching the git repository: file:///Users/akos.kitta/git/yang-lsp
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896500886/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896500972/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896501103/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896501199/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896501270/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896501512/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896501664/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896501836/.metadata/.log
root INFO [nsfw-watcher: 41752] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 41752] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 41786] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources
root INFO [nsfw-watcher: 41752] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java
root INFO [nsfw-watcher: 41786] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources
root INFO [nsfw-watcher: 41786] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-tsm.yang
root INFO [nsfw-watcher: 41786] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp.yang
root INFO [nsfw-watcher: 41786] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-tls.yang
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 41786] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-target.yang
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/.theia
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-tsm.yang
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp.yang
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-tls.yang
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-target.yang
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-notification.yang
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/pass/test8b.yang
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/pass/test8c.yang
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-vacm.yang
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-usm.yang
root INFO [nsfw-watcher: 41846] Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-community.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-engine.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/ietf/ietf-snmp-proxy.yang
Started watching: /Users/akos.kitta/git/yang-lsp/yang-lsp/io.typefox.yang.ide/src/test/resources/RIFT.ware/test/pass/test8d.yang
root INFO Registering scopes for language: java.
root INFO The scopes have been successfully registered for java.
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896523431/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896523568/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896523636/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896523688/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896523766/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896523810/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896523842/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1540896523879/.metadata/.log
root INFO Registering scopes for language: java.
root ERROR The scopes are already registered for language: java.
root INFO Unregistering scopes for language: java.
root INFO The scopes have been successfully unregistered for java.
root ERROR The ws channel does not exist 296
root ERROR The ws channel does not exist 296
root ERROR The ws channel does not exist 296
root ERROR The ws channel does not exist 296
root ERROR The ws channel does not exist 297
root ERROR The ws channel does not exist 297
root ERROR The ws channel does not exist 297
root ERROR The ws channel does not exist 297
root ERROR The ws channel does not exist 299
root ERROR The ws channel does not exist 299
root ERROR The ws channel does not exist 299
root ERROR The ws channel does not exist 299
root ERROR The ws channel does not exist 298
root ERROR The ws channel does not exist 298
root ERROR The ws channel does not exist 298
root ERROR The ws channel does not exist 298
root ERROR The ws channel does not exist 292
root ERROR The ws channel does not exist 292
root ERROR The ws channel does not exist 292
root ERROR The ws channel does not exist 292
```

**Comment by akosyakov** [comment]
@kittaakos could you try again, please?

**Comment by simark** [comment]
> @simark I've moved generic commands' registration to `LanguagesFrontendContribution`: https://github.com/theia-ide/theia/pull/3319/files#diff-778fc6e5def7d229046da1db3650e3b9R23
> 
> i.e. for start, stop and restart language servers
> 
> They don't need to be unregistered since they are based on a running state of language contribution.

Ack.

**Comment by kittaakos** [comment]
It definitely works better with TS too. 👍 This is a great improvement. According to the logs, the reconnecting still has flaws, see how many times it starts watching the same file.

```
^C
Akoss-MacBook-Pro:browser akos.kitta$ yarn run start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 63361]
Server worker is ready to accept messages. [ID: 1 | PID: 63361]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 63362] Started watching: /Users/akos.kitta/Desktop/theia/examples/browser/package.json
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO [nsfw-watcher: 63363] Started watching: /Users/akos.kitta/.theia
root INFO [nsfw-watcher: 63363] Started watching: /Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 63363] Started watching: /Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 63363] Started watching: /Users/akos.kitta/git/theia/.theia/launch.json
root INFO [nsfw-watcher: 63363] Started watching: /Users/akos.kitta/git/theia/packages/core/src/common/os.ts
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 63378] Started watching: /Users/akos.kitta/.theia
root INFO [nsfw-watcher: 63378] Started watching: /Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 63378] Started watching: /Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 63378] Started watching: /Users/akos.kitta/git/theia/.theia/launch.json
root INFO [nsfw-watcher: 63378] Started watching: /Users/akos.kitta/git/theia/packages/core/src/common/os.ts
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 63390] Started watching: /Users/akos.kitta/.theia
root INFO [nsfw-watcher: 63390] Started watching: /Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 63390] Started watching: /Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 63390] Started watching: /Users/akos.kitta/git/theia/.theia/launch.json
root INFO [nsfw-watcher: 63390] Started watching: /Users/akos.kitta/git/theia/packages/core/src/common/os.ts
^C
```

The [`Started watching`](https://github.com/theia-ide/theia/blob/85890fd3818bcd50bca4591f00172facf265be16/packages/filesystem/src/node/nsfw-watcher/nsfw-filesystem-watcher.ts#L78) does **not** have the [`Stopped watching`](https://github.com/theia-ide/theia/blob/85890fd3818bcd50bca4591f00172facf265be16/packages/filesystem/src/node/nsfw-watcher/nsfw-filesystem-watcher.ts#L133) counterpart. Is it due to the logging or do we have stale file watchers after the restart?

File: packages/editor/src/browser/semantic-highlight/semantic-highlighting-service.ts [hunk 1]
```diff
@@ -44,29 +44,25 @@ export class SemanticHighlightingService implements Disposable {
      */
     register(languageId: string, scopes: string[][] | undefined): Disposable {
         if (scopes && scopes.length > 0) {
-            this.logger.info(`Registering scopes for language: ${languageId}.`);
+            this.logger.debug(`Registering scopes for language: ${languageId}.`);
```
Comment (kittaakos) [inline packages/editor/src/browser/semantic-highlight/semantic-highlighting-service.ts]: I believ this information is as relevant as any `Started watching` (`nsfw`) events, please change it back from `debug` to `info`. What do you think?

File: packages/languages/src/browser/language-client-contribution.ts [hunk 2]
```diff
@@ -88,40 +94,43 @@ export abstract class BaseLanguageClientContribution implements LanguageClientCo
...
-        const toDeactivate = new DisposableCollection();
-        toDeactivate.push(Disposable.create(() => {
-            options.reconnecting = false;
-        }));
+        toDeactivate.push(Disposable.create(() => options.reconnecting = false));
         this.connectionProvider.listen({
             path: LanguageContribution.getPath(this),
             onConnection: messageConnection => {
-                if (toDeactivate.disposed) {
+                if (this.toDeactivate.disposed) {
```
Comment (kittaakos) [inline packages/languages/src/browser/language-client-contribution.ts]: Q: Why do you use `this.toDeactivate` here and the `toDeactivate` argument above? Maybe I am missing something but wouldn't it be better to either use the argument or remove the argument and use `this.toDeactivate`? Presumably, it has the same effect; I still find it misleading (that's why I have asked).

File: packages/languages/src/browser/language-client-contribution.ts [hunk 3]
```diff
@@ -158,15 +167,21 @@ export abstract class BaseLanguageClientContribution implements LanguageClientCo
...
-                const detail = err instanceof Error ? `: ${err.message}` : '.';
-                this.messageService.error(`Failed to start ${this.name} language server${detail}`);
-                return false;
-            },
+            initializationFailedHandler: err => this.handleInitializationFailed(err),
             diagnosticCollectionName: id,
             initializationOptions
         };
     }
+    protected handleInitializationFailed(err: ResponseError<InitializeParams> | Error | any): boolean {
```
Comment (kittaakos) [inline packages/languages/src/browser/language-client-contribution.ts]: [minor]: Why did you declare the union type? An `any` would be sufficient. I bet you had a good reason, I would like to know.

File: packages/editor/src/browser/semantic-highlight/semantic-highlighting-service.ts (hunk 1 above)
Comment (akosyakov) [reply packages/editor/src/browser/semantic-highlight/semantic-highlighting-service.ts]: I will revert it. I think that logging watching of each opened file is super loud, but it is out of scope.

File: packages/languages/src/browser/language-client-contribution.ts (hunk 2 above)
Comment (akosyakov) [reply packages/languages/src/browser/language-client-contribution.ts]: good catch, thanks!

File: packages/languages/src/browser/language-client-contribution.ts (hunk 3 above)
Comment (akosyakov) [reply packages/languages/src/browser/language-client-contribution.ts]: I've copied typings from `vscode-languaclient` API. `any` is indeed sufficient for everything, but i find APIs giving a clue about what it can be are more helpful.

**Comment by akosyakov** [comment]
@kittaakos I've addressed your comments, could you have a look again, please?

**Comment by akosyakov** [comment]
> Looking into the logs, I have the feeling it is not yet the complete solution, but I won't hold this PR back.

There can be language server specific issues, e.g. java extension contributes organize import command via Theia and language server APIs leading to duplicate commands warning.

**Comment by kittaakos** [comment]
> leading to duplicate commands warning.

It is not about the duplicate commands but I can see the LS starts, for instance, four times.

**Comment by akosyakov** [comment]
@kittaakos it seems that `reconnecting-websocket` for some reasons fires `open` and `close` events several times leading to several reconnection. For fs-watcher we don't see stop logs because they happen in worker processes, on reconnect we ask workers to stop watchers and immediately terminate connection to them without awaiting stop logs.

**Comment by akosyakov** [comment]
@kittaakos good to merge? approve?

**Comment by kittaakos** [comment]
I am verifying once more locally with Java and TS. Also, I would like to try this out on Windows as well...

**Comment by kittaakos** [comment]
On Windows, after the backend stop, the Java LS process terminates, and then the backend (re)start, I can see two Java LS processes.

screen shot 2018-11-01 at 13 46 29

**Comment by kittaakos** [comment]
On OS X, there is only one Java LS process, the other three are from Gradle (via the LS).

screen shot 2018-11-01 at 13 56 29

```
Akoss-MacBook-Pro:browser akos.kitta$ pstree | grep java
 | |   \--- 22275 akos.kitta grep java
 |             \-+- 22169 akos.kitta /usr/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -jar /Users/akos.kitta/Desktop/theia/packages/java/server/plugins/org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar -configuration /Users/akos.kitta/Desktop/theia/packages/java/server/config_mac -data /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1541076961994
 |               |--= 22188 akos.kitta /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=US-ASCII -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/akos.kitta/.gradle/wrapper/dists/gradle-4.10.2-bin/cghg6c4gf4vkiutgsab8yrnwv/gradle-4.10.2/lib/gradle-launcher-4.10.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.10.2
 |               |--= 22198 akos.kitta /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=US-ASCII -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/akos.kitta/.gradle/wrapper/dists/gradle-4.3-bin/452wx51oxqsia28686mgqhot6/gradle-4.3/lib/gradle-launcher-4.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.3
 |               \--- 22192 akos.kitta /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=US-ASCII -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/akos.kitta/.gradle/wrapper/dists/gradle-3.0-bin/2z3tfybitalx2py5dr8rf2mti/gradle-3.0/lib/gradle-launcher-3.0.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 3.0
Akoss-MacBook-Pro:browser akos.kitta$ 
```

**Comment by akosyakov** [comment]
@kittaakos please open a follow-up issue for Windows, I will try to get Windows machine to reproduce it
