### PR TITLE
Fixed #5399: fixed breakpoint resizing error in Debug widget

### LINKED ISSUE #5399: [debug] debug widget breakpoint resizing error
**Description**

There is an issue regarding the `debug-widget` when resizing the `breakpoint` panel.
The file number associated with the breakpoint is lost, and the file-name becomes hidden instead of the standard ellipsis (...) displayed.

<div align='center'>

debug

</div>

In comparison, heres vscode:

<div align='center'>

debug-vs

</div>

### PR DESCRIPTION
**Pull request by fangnx**
Fixed #5399.

Fixed the resizing display issue with the breakpoint line in the Debug widget.

theia-debug-resize

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
I tried and got the following result:

<div align='left'>

image

</div>

**Comment by fangnx** [comment]
> I tried and got the following result:
> 
> image

It was a css naming typo. Just fixed it ;)

**Comment by fangnx** [comment]
> Looks good
> Can you add a tool-tip to show the "name + path" when the window size is too small, so the end-user would have some information available about the breakpoints

Sure, I will update the code.

File: packages/debug/src/browser/model/debug-breakpoint.tsx [hunk 1]
```diff
@@ -187,8 +187,10 @@ export class DebugBreakpoint extends DebugBreakpointData implements TreeElement
         return <div title={decoration.message.join('\n')} className={classNames.join(' ')}>
             <span className={'theia-debug-breakpoint-icon ' + decoration.className} />
             <input type='checkbox' checked={this.origins[0].enabled} onChange={this.setBreakpointEnabled} />
-            <span className='name'>{this.labelProvider.getName(this.uri)} </span>
-            <span className='path'>{this.labelProvider.getLongName(this.uri.parent)} </span>
+            <span className='line-info' title={this.labelProvider.getName(this.uri) + '    ' + this.labelProvider.getLongName(this.uri.parent)}>
```
Comment (vince-fugnitto) [inline packages/debug/src/browser/model/debug-breakpoint.tsx]: I'm not sure about the 4 spaces between the `name` and `path`, but perhaps since this is a minor feature the most appropriate implementation would be to do the same as the `explorer` which is to simply provide the `uri` including the `filename`.

```ts
this.labelProvider.getLongName(this.uri)
```

**Example**:
```
java-frontend-module.ts    packages/java/src/browser
```

would become:

```
packages/java/src/browser/java-frontend-module.ts
```

Comment (fangnx) [reply packages/debug/src/browser/model/debug-breakpoint.tsx]: Makes sense. Just updated the code
