### PR TITLE
GH-1688: Fixed `ESC doesn't close completion widget`.

### LINKED ISSUE #1688: [monaco] ESC doesn't close completion widget
The ESC key no longer closes the suggestion popups and hovers.

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #1688.

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

File: packages/editor/src/browser/editor-keybinding-contexts.ts [hunk 1]
```diff
@@ -23,7 +23,8 @@ export class EditorTextFocusContext implements KeybindingContext {
     protected readonly editorManager: EditorManager;
 
     isEnabled(): boolean {
-        return !!this.getEditor();
+        const editor = this.getEditor();
+        return !!editor && !editor.editor.isSuggestVisible();
```
Comment (akosyakov) [inline packages/editor/src/browser/editor-keybinding-contexts.ts]: We should consider to limit the scope of this change to the git blame by introducing the special keybinding context for the clean git annotation command or to introduce another context in the editor checking that there is no other widgets.

Generally it is true that the text editor has focus even if the suggest or other widgets are visible. Changing it could break some commands. You can observe it by trying enable git annotations with the suggest widget and without. It behaves differently. It does not harm so much in this case, but if there is a command enabling another editor widget (think about find references) then it won't work.

Could you please also check that it is not case for other widgets. It seems to be that find and rename widgets are affected as well, based on https://github.com/eamodio/vscode-gitlens/blob/57226d54d1e929be04b02ee31ca294c50305481b/package.json#L2857.

(minor) I've introduced `canHandle` for checking, that one does not need to change `isEnabled`.

File: packages/monaco/src/browser/monaco-editor.ts [hunk 2]
```diff
@@ -197,6 +202,10 @@ export class MonacoEditor implements TextEditor, IEditorReference {
         return this.onFocusChangedEmitter.event;
     }
 
+    isSuggestVisible(): boolean {
+        return SuggestState.Idle !== this.suggestController._model.state;
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-editor.ts]: `this.editor.getContribution('editor.contrib.suggestController')._widget.suggestWidgetVisible.get()` -  it is exactly the same as `suggestWidgetVisible` when context in VS Code

File: packages/monaco/src/browser/monaco-loader.ts [hunk 3]
```diff
@@ -69,6 +73,8 @@ export function loadMonaco(vsRequire: any): Promise<void> {
                     global.monaco.editorCommonExtensions = editorCommonExtensions;
                     global.monaco.modes = modes;
                     global.monaco.cancellation = cancellation;
+                    global.monaco.suggestModel = suggestModel;
```
Comment (akosyakov) [inline packages/monaco/src/browser/monaco-loader.ts]: if we use `editor.getContribution` then it should not be necessary, we will need only interfaces

File: packages/editor/src/browser/editor-keybinding-contexts.ts (hunk 1 above)
Comment (kittaakos) [reply packages/editor/src/browser/editor-keybinding-contexts.ts]: > Separate contexts for the text editor focus with widget and without

That was my [initial plan](https://github.com/theia-ide/theia/issues/1688#issuecomment-381175928) then I thought it adds unnecessary complexity. Let's split it into two separate contexts.

> Could you please also check

Sure.

> it is too much to assume and ask from editor implementors

I agree.

> rebind it in the monaco extension

I like it!

> minor

👍

File: packages/monaco/src/browser/monaco-editor.ts (hunk 2 above)
Comment (kittaakos) [reply packages/monaco/src/browser/monaco-editor.ts]: I have seen that. I do not know why would it be better to get this information from the widget with a string-based ID, but I do not mind going with this approach either.

File: packages/monaco/src/browser/monaco-loader.ts (hunk 3 above)
Comment (kittaakos) [reply packages/monaco/src/browser/monaco-loader.ts]: Let's do that; I do not have any objections unless it works.

File: packages/monaco/src/browser/monaco-editor.ts (hunk 2 above)
Comment (akosyakov) [reply packages/monaco/src/browser/monaco-editor.ts]: Both ways work for me as well. I commented it because of https://github.com/theia-ide/theia/pull/1706#discussion_r181582056 to reduce amount of dependencies on internals.

File: packages/editor/src/browser/editor-keybinding-contexts.ts (hunk 1 above)
Comment (kittaakos) [reply packages/editor/src/browser/editor-keybinding-contexts.ts]: > Could you please also check that it is not case for other widgets.

It is. For instance, I cannot hide the search and replace widget with `Esc`.

**Comment by kittaakos** [comment]
@akosyakov, I have made the changes based on your feedback. This PR is ready for the review.

File: packages/monaco/src/typings/monaco/index.d.ts [hunk 4]
```diff
@@ -618,3 +618,59 @@ declare module monaco.cancellation {
...
+
+        getId(): string;
+        dispose(): void;
+
+        /**
+         * Hack for checking whether the rename input HTML element is visible in the code editor or not. In VSCode source this is has `private` visibility.
+         */
+        readonly _renameInputVisible: {
+            get(): boolean;
+        }
```
Comment (svenefftinge) [inline packages/monaco/src/typings/monaco/index.d.ts]: missing semicolon

File: packages/monaco/src/typings/monaco/index.d.ts [hunk 5]
```diff
@@ -618,3 +618,59 @@ declare module monaco.cancellation {
...
+
+        getId(): string;
+        dispose(): void;
+
+        /**
+         * Hack for checking whether the find (and replace) widget is visible in code editor or not.
+         */
+        readonly _findWidgetVisible: {
+            get(): boolean;
+        }
```
Comment (svenefftinge) [inline packages/monaco/src/typings/monaco/index.d.ts]: missing semicolon

File: packages/monaco/src/typings/monaco/index.d.ts [hunk 6]
```diff
@@ -618,3 +618,59 @@ declare module monaco.cancellation {
...
+        /**
+         * Hack for checking whether the rename input HTML element is visible in the code editor or not. In VSCode source this is has `private` visibility.
+         */
+        readonly _renameInputVisible: {
+            get(): boolean;
+        }
+
+    }
+
+}
```
Comment (svenefftinge) [inline packages/monaco/src/typings/monaco/index.d.ts]: [tslint] file should end with a newline

**Comment by svenefftinge** [comment]
ESC works nicely again :-)
