### PR TITLE
GH-5116: Use `fork` to start the electron process.

### LINKED ISSUE #5116: Cannot start electron example on windows10 with error spawn UNKNOWN
### Description
clone theia and follow the quick start. A spawn UNKNOW error occurs when starting electron example.

### Reproduction Steps
execute the following instructions
```
git clone https://github.com/theia-ide/theia \
&& cd theia \
&& yarn \
&& yarn run rebuild:electron \
&& cd examples/electron \
&& yarn run start
```

**OS and Theia version:**
OS: Windows Server 2016 Standard and Windows 10 Pro 1703
Theia: fe6ea99291c177a1ba9278b99c1918611f624bbf

**Diagnostics:** 
```
PS D:\code\theia\examples\electron> yarn run start
yarn run v1.16.0
$ theia start --plugins=local-dir:../../plugins
command D:\code\theia\node_modules\electron\cli.js
args D:\code\theia\examples\electron\src-gen\frontend\electron-main.js,--plugins=local-dir:../../plugins
options [object Object]
{ Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn (child_process.js:538:9)
    at ApplicationProcess.spawn (D:\code\theia\dev-packages\application-manager\lib\application-process.js:34:19)
    at ApplicationPackageManager.<anonymous> (D:\code\theia\dev-packages\application-manager\lib\application-package-man
ager.js:197:30)
    at step (D:\code\theia\dev-packages\application-manager\lib\application-package-manager.js:58:23)
    at Object.next (D:\code\theia\dev-packages\application-manager\lib\application-package-manager.js:39:53)
    at D:\code\theia\dev-packages\application-manager\lib\application-package-manager.js:33:71
    at new Promise (<anonymous>)
    at __awaiter (D:\code\theia\dev-packages\application-manager\lib\application-package-manager.js:29:12)
    at ApplicationPackageManager.startElectron (D:\code\theia\dev-packages\application-manager\lib\application-package-m
anager.js:193:16) errno: 'UNKNOWN', code: 'UNKNOWN', syscall: 'spawn' }
error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by kittaakos**
Windows cannot do much with the `#!/usr/bin/env node`
if not invoked as an `npm` script.

Closes #5116.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

File: dev-packages/application-manager/src/application-package-manager.ts [hunk 1]
```diff
@@ -78,26 +78,41 @@ export class ApplicationPackageManager {
...
+            options
+        };
+    }
+
+    private get forkOptions(): cp.ForkOptions {
+        return {
+            stdio: [0, 1, 2, 'ipc'],
+            env: {
+                ...process.env,
+                THEIA_PARENT_PID: String(process.pid)
```
Comment (marechal-p) [inline dev-packages/application-manager/src/application-package-manager.ts]: Why do we keep setting this variable instead of using [`process.ppid`](https://nodejs.org/docs/latest-v10.x/api/process.html#process_process_ppid) ?

Comment (kittaakos) [reply dev-packages/application-manager/src/application-package-manager.ts]: I did not want to change the original logic:
https://github.com/theia-ide/theia/blob/dd9eb6b62419187dbd2616bb747fd7b321502019/dev-packages/application-manager/src/application-package-manager.ts#L91

Comment (marechal-p) [reply dev-packages/application-manager/src/application-package-manager.ts]: That I understand, we should not in this PR, but I was just wondering if you knew why it was like this in the first place. It is not really important for this PR :)
