### PR TITLE
GH-621: Support Git `push`, `pull`, `fetch`, and `merge` commands with arguments

### LINKED ISSUE #621: [git] Permission denied issues when executing `pull` and `push`
Moved from: https://github.com/theia-ide/theia/issues/583#issuecomment-336096605
Original message from @marcdumais-work:

I am trying the git extension using my Theia development environment. I have a few remotes defined. ATM I see that for pull and push operations, a random remote is picked (1st returned by "git remote" ?). It happens to be one I do not have permissions to push-to, and that doesn't contain the branch I am working on,  so push and pull operations fail. Fetch doesn't seem to do anything and outputs no error message.

I guess these problems will be addressed in this issue by permitting to pick a specific remote for the operations?

push:
``` 
The command `git push antoine task` exited with an unexpected code: 1. The caller should either handle this error, or expect that exit code.
To github.com:hexa00/theia.git
 ! [remote rejected]   task -> task (permission denied)
error: failed to push some refs to 'git@github.com:hexa00/theia.git'
```
pull: 
```
The command `git pull antoine` exited with an unexpected code: 1. The caller should either handle this error, or expect that exit code.
You asked to pull from the remote 'antoine', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.
```

PR: #650.

### PR DESCRIPTION
**Pull request by kittaakos**
Task: #621.
Closes #621.

### CODE REVIEW

File: packages/git/src/browser/git-quick-open-service.ts [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+    async merge(): Promise<void> {
+        const [repository, branches] = await Promise.all([this.getRepository(), this.getBranches()]);
+        const execute = (item: GitQuickOpenItem<Branch>) => this.git.merge(repository, { branch: item.getLabel()! });
+        const toLabel = (item: GitQuickOpenItem<Branch>) => item.ref.name;
+        const items = branches.map(branch => new GitQuickOpenItem<Branch>(branch, execute, toLabel));
+        const TODO_currentBranchName = ''; // Otherwise should be the branch name.
+        this.quickOpenService.open(this.getModel(items), this.getOptions(`Pick a branch to merge into the currently active ${TODO_currentBranchName} branch:`));
+    }
+
+    private getOptions(placeholder: string): QuickOpenOptions.Resolved {
```
Comment (akosyakov) [inline packages/git/src/browser/git-quick-open-service.ts]: It should be `QuickOpenOptions`, `Resolved` it is for `QuickOpenService` implementations

**Comment by kittaakos** [comment]
@marcdumais-work, could you please look into the changes and check the functionality? I look into the Windows CI issue as part of #568. Thank you!

**Comment by svenefftinge** [comment]
The PR looks good to me and has hung around for some time already. I'm merging it, since I need to rebase the file-open PR on this.
