### PR TITLE
Fix conversion of OS paths to DebugProtocol Source paths

### LINKED ISSUE #4026: [debug] Debug on Windows opens source files in new tabs
## Description

Debugging in Windows opens new tabs for already opened files and sets a full path. Original breakpoints are ignored.

## Steps to reproduce:
Platform: Windows
Version: Electron

1. Run Theia (tested on current master - https://github.com/theia-ide/theia/commit/98edc40630b09171ecd76097b69fd08e3777340d)
2. Create simple node example
3. Set few breakpoints
4. Run node debugger

Current behaviour:

5. New tab is opened in editor with full uri to the file. Breakpoints in original file are ignored.

Expected behaviour:

5. Theia should not open another tab for the same file. Breakpoints in original tab should be respected.

## Notes
- Issue exists only on Windows. Debug works correctly on Mac OSX.
- Issue is not new. I'm able to reproduce it also on older versions of Theia.
- Issue exists also for different adapters, not only for node.
- Quick investigation showed that issue may be connected with wrong URIs received from monaco
- Issue is not reproducible in vscode

## Gif example
theia-debug-windows
 
@akosyakov @thegecko @tolusha

### PR DESCRIPTION
**Pull request by thegecko**
Signed-off-by: Rob Moran <rob.moran@arm.com>

This PR fixes #4026 by ensuring conversion of paths between the debug adapter and the internal URIs are correct for both Windows and Unix.

This is done in two parts;

- New `withFile()` function on the `URI` object which internally uses `Uri.file()` to correctly parse Windows and Unix paths to URIs

- Usage of the `FileSystem.getFsPath()` function running on the backend to ensure paths being passed to the debug adapter are correct for the backend OS

Much of the PR was reworking classes and functions to enable an async call to an injected `FileSystem` object. One side effect of this is the static `DebugSource.toSource()` has had to be moved to be an instance function in an injectable class.

Tested on Mac and Windows.

cc @arekzaluski, @akosyakov

### CODE REVIEW

File: packages/core/src/common/uri.ts [hunk 1]
```diff
@@ -167,6 +167,13 @@ export default class URI {
         return this.withFragment('');
     }
 
+    /**
+     * return a new URI replacing the current with the given file
+     */
+    withFile(file: string): URI {
```
Comment (akosyakov) [inline packages/core/src/common/uri.ts]: I don't think it should be on `URI` to discourage creating/parsing file URIs on the frontend. Debug adapters are special case. How about moving `new URI(Uri.file(file))` to the debug extension?

It won't produce a normalized URI for the case when backend is Windows, but frontend is Linux, for instance
`\\home\\file.ts` path won't be transformed to `file:///home/file.ts`. In practice i have not seen such combination, so maybe it is fine for now.

cc @svenefftinge

**Comment by thegecko** [comment]
@akosyakov I have just confirmed this fix in the following scenarios where debugging and setting breakpoints works correctly for the node adapter and the file paths are correctly formatted for the backend:

- Electron on Windows
- Electron on Mac
- Browser on Windows (using backend on same machine)
- Browser on Windows (using backend served from a mac)
- Browser on Mac (using backend on same machine)
- Browser on Mac (using backend served from a Windows machine)

File: packages/core/src/common/uri.ts (hunk 1 above)
Comment (thegecko) [reply packages/core/src/common/uri.ts]: Hmm, I've just had this scenario working (backend Windows, frontend Mac).

I figured the `withFile()` function could be useful elsewhere and wanted to keep related functionality together. Would you prefer it was removed and I simply called `return new URI(Uri.file(raw.path));` instead?

Comment (thegecko) [reply packages/core/src/common/uri.ts]: @akosyakov I've removed the `withFile()` function

**Comment by thegecko** [comment]
Should appveyor be passing?

**Comment by akosyakov** [comment]
> Should appveyor be passing?

Have not seen it passing in a while.
