### PR TITLE
fix #6046: workspace configuration contributed by VSCode extension an…

### LINKED ISSUE #6046: Workspace configuration that is registered by a VSCode plugin sometimes doesn't take effect
### Description
Sometimes, VSCode plugin registered configurations doesn't work in workspace (user configuration does work, though). No error or warning is shown in the setting widget and everything seem to work nicely expect that the workspace configuration is actually ignored. It seems that these configuration is wrongly filtered.

### Reproduction Steps
This issue is kind of hard to reproduce. For one thing, it only happens in some VSCode plugins, for example, `cpptool`. For another, it doesn't always happen to them. So probably you need to try several times before it happens.

1. Launch theia with VSCode's cpptool plugin (attention: due to issue https://github.com/theia-ide/theia/issues/5899 , you need to clean `/tmp/vscode-unpacked/cpptool*` before restarting the background) or other VSCode plugins you want to test;
2. Play around with the configurations that is registered by the plugin, and make sure they work in user configuration;
3. Now refresh your browser and play around with the workspace configuration and see if they still take effect;
4. You may need to repeat step 3 several times;

There is another thing that I found interesting (or, weird) - the issue does not happen if all editors are closed. That is, it happens only when one or more files are opened.

#### Updated Reproduction Steps
Try reproduce by
https://github.com/theia-ide/theia/issues/6046#issuecomment-527334904

**OS and Theia version:**

Theia: 0.9.0
OS: Ubuntu

**Diagnostics:** 
None.

### PR DESCRIPTION
**Pull request by a1994846931931**
…d provided by .theia/settins.json is sometimes wrongly filtered out

Signed-off-by: Cai Xuye <a1994846931931@gmail.com>

#### What it does
fix #6046

For more information about this revision, please refer to https://github.com/theia-ide/theia/issues/6046#issuecomment-527330010

#### How to test
Test according to https://github.com/theia-ide/theia/issues/6046#issuecomment-527334904. In the fixed version, the start message should give you a correct value read from the workspace configuration.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
I wonder how it affects native extensions which not expecting invalid values.

**Comment by a1994846931931** [comment]
> I wonder how it affects native extensions which not expecting invalid values.

@akosyakov Yeah, this could cause a problem. Do you have a better idea?

But for now, even before this revision, invalid values in user configuration are not handled. In fact, only configurations under `${workspaceFolder}/.theia/settings.json` would be validated because of these lines (note that `this.configurations.getPaths()[0]` is `.theia`) https://github.com/theia-ide/theia/blob/1e67e74498a369c4665b28afd64e91ec5f6e0133/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L171-L177

**Comment by akosyakov** [comment]
> But for now, even before this revision, invalid values in user configuration are not handled.

Yeah, sound like it is working by the pure luck. I will think how we can go about it next days.

**Comment by svenefftinge** [comment]
I think removing the check is good. Having it different when the settings its in vscode folder is clearly surprising and native extension would be faced with wrong values that way already.

**Comment by akosyakov** [comment]
We can try to move the check to statically typed APIs to avoid breaking them: https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/preferences/preference-proxy.ts#L44

As you pointed out it should not be matter whether it is from which folder it comes.

**Comment by akosyakov** [comment]
@a1994846931931 Would you have time to try moving a check to statically typed proxies?

**Comment by a1994846931931** [comment]
> @a1994846931931 Would you have time to try moving a validation check to statically typed proxies?

OK, I'll give it a try. But can you give some advice on how I should test on it and, maybe also on what should happen when a value is invalid?

**Comment by akosyakov** [comment]
> OK, I'll give it a try. But can you please offer some advice on how I should test on it and, maybe also on what should happen when a value is invalid?

I meant to change https://github.com/theia-ide/theia/blob/78e0b2093c38a69633cfa69a728082859263ad47/packages/core/src/browser/preferences/preference-proxy.ts#L74 to something like:
```ts
        const value = preferences.get(preferenceName, defaultValue, resourceUri);
        if (preferences.validate(preferenceName, value)) {
            return value;
        }
        if (defaultValue !== undefined) {
            return defaultValue;
        }
        const values = preferences.inspect(preferenceName, resourceUri);
        return values && values.defaultValue;
```

and https://github.com/theia-ide/theia/blob/78e0b2093c38a69633cfa69a728082859263ad47/packages/core/src/browser/preferences/preference-proxy.ts#L79 to something like:
```ts
                const value = preferences.get(property);
                if (preferences.validate(property, value)) {
                    return value;
                }
                const values = preferences.inspect(property);
                return values && values.defaultValue;
```

You will need to implement `validate` by delegating to `PreferenceSchemaProvider`.

You can test it with [DebugConfiguration](https://github.com/theia-ide/theia/blob/78e0b2093c38a69633cfa69a728082859263ad47/packages/debug/src/browser/debug-preferences.ts#L46-L51) for example, just change setting to bogus values and check that default value is provided to clients.

File: packages/core/src/browser/preferences/preference-contribution.ts [hunk 1]
```diff
@@ -224,6 +224,10 @@ export class PreferenceSchemaProvider extends PreferenceProvider {
 
     protected readonly unsupportedPreferences = new Set<string>();
     validate(name: string, value: any): boolean {
+        const overridden = this.overriddenPreferenceName(name);
```
Comment (akosyakov) [inline packages/core/src/browser/preferences/preference-contribution.ts]: @a1994846931931 Could you elaborate why it is necessary? An idea was that a client should decide whether overridden preference name is to use or not. i.e it already happens here: https://github.com/theia-ide/theia/pull/6090/files#diff-ffb43b06d873f9f07d3ec2f4c762c96bR71 and it is not required here: https://github.com/theia-ide/theia/pull/6090/files#diff-ffb43b06d873f9f07d3ec2f4c762c96bR87 (returning overridden  value here is bogus)

Comment (a1994846931931) [reply packages/core/src/browser/preferences/preference-contribution.ts]: @akosyakov Oh, I see. The reason why I did this is that I got a lot of errors showing overridden preference name invalid.

So instead of getting overridden name for all validated preference, it should be done in the proxy, right?

Comment (akosyakov) [reply packages/core/src/browser/preferences/preference-contribution.ts]: @a1994846931931 wait maybe i'm wrong, could you help me to reproduce it?

Comment (a1994846931931) [reply packages/core/src/browser/preferences/preference-contribution.ts]: @akosyakov Yes. So after removed line 227-230 in `preference-contribution.ts`, I ended in getting a great number of errors like
```
root WARN "[jsonc].editor.renderIndentGuides" preference is not supported
root WARN "[jsonc].editor.renderLineHighlight" preference is not supported
root WARN "[jsonc].editor.useTabStops" preference is not supported
root WARN "[jsonc].editor.colorDecorators" preference is not supported
root WARN "[jsonc].editor.highlightActiveIndentGuide" preference is not supported
root WARN "[jsonc].editor.iconsInSuggestions" preference is not supported
root WARN "[jsonc].editor.showUnused" preference is not supported
root WARN "[jsonc].editor.scrollBeyondLastColumn" preference is not supported
root WARN "[jsonc].editor.suggestSelection" preference is not supported
root WARN "[jsonc].editor.fontWeight" preference is not supported
root WARN "[jsonc].diffEditor.renderSideBySide" preference is not supported
```

**Comment by a1994846931931** [comment]
@akosyakov Thanks to your comment, I just found out that validation of `overridePreferenceName` should be done in `getValue` function. Codes are updated. Does it look better now?

**Comment by akosyakov** [comment]
@a1994846931931 it looks good, i also tested with editor preferences and could not break it

Could you have a look at broken tests?

**Comment by a1994846931931** [comment]
> @a1994846931931 it looks good, i also tested with editor preferences and could not break it
> 
> Could you have a look at broken tests please?

@akosyakov Codes updated. both `mockPreference.validate` and `mockPreference.get` should return true now, so that the `this.preferences['editor.enablePreview']` in privew-manager could actually return true.

**Comment by akosyakov** [comment]
@a1994846931931 Are you already the official Eclipse committer or you need help with merging?

**Comment by a1994846931931** [comment]
> @a1994846931931 Are you already the official Eclipse committer or you need help with merging?

@akosyakov Oh, sorry, I just found out that I missed an e-mail from eclipse. I'll check it out soon. Thanks for reminding me of that!

**Comment by a1994846931931** [comment]
> @a1994846931931 Are you already the official Eclipse committer or you need help with merging?

@akosyakov Hi, I am still working on signing the document, but I think I need some help on filling  `ECLIPSE FOUNDATION, INC.
INDIVIDUAL COMMITTER AGREEMENT`.

Could you please tell me that, in `a Delaware not-for-profit corporation, and
__________________________ (“Committer”) an individual listed in the Eclipse Foundation’s`, what should I put here? Should I write my name "Xuye Cai", or my committer ID `xcaick5`?

Or, can you send me an example, through e-mail a1994846931931@gmail.com, if possible? It would be very helpful.

Thank you very much!

**Comment by akosyakov** [comment]
@theia-ide/ip-help Could someone help with https://github.com/theia-ide/theia/pull/6090#issuecomment-529397921 please?

**Comment by a1994846931931** [comment]
@akosyakov Hello, Kosyakov. My committer paperwork was declined because I wrongly put my username as "committer" in the document. I was unable to resign the document because it's already closed in "HelloSign" and I cannot create a new document because when I clicked on the "commit" button, it shows "There was an error creating the Hellosign Document. Please contact webmaster@eclipse.org for further instructions.". Clearly I was blocked in signing the document. I sent several emails to "webmaster@eclipse.org“ a week ago asking for help, but no response was received. And I just sent another one to "cydnie.smith@eclipse-foundation.org" (Cydnie Smith is the one who declined the document and asked me to resign it) this morning. I was still waiting for the reply, but I think I should inform you of what's happening in case I still need a hand from the theia community.

**Comment by akosyakov** [comment]
@a1994846931931 I think they should come back to you eventually. I will add it to tomorrow dev meeting, maybe someone has a better idea how to handle it. cc @marcdumais-work

**Comment by marcdumais-work** [comment]
@akosyakov I think the correct steps have been made on our side (thanks @a1994846931931) ; the Foundation has limited resources so we need to be patient. 

If this is not resolved in a couple of weeks, we can try to open a bugzilla.
