### PR TITLE
Fix the status-bar font color when offline

### LINKED ISSUE #2877: [status-bar][styling] Adjust the font color in the status bar when Theia is offline
Currently, it is the yellowish background with the white font. We should change it and use the [`--theia-warn-font-color0`](https://github.com/theia-ide/theia/blob/f93d2811e63555725ee999c7db1840d45352a434/packages/core/src/browser/style/variables-dark.useable.css#L127) so that we align the styles with Git and SIW.

screen shot 2018-09-13 at 17 48 39

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #2877 

| Online | Offline |
|:---:|:---:|
|screen shot 2018-11-16 at 2 48 19 pm|screen shot 2018-11-16 at 2 48 29 pm|

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

File: packages/core/src/browser/status-bar/status-bar.tsx [hunk 1]
```diff
@@ -103,12 +105,24 @@ export class StatusBarImpl extends ReactWidget implements StatusBar {
...
         this.backgroundColor = color;
         // tslint:disable-next-line:no-null-keyword
         this.node.style.backgroundColor = this.backgroundColor ? this.backgroundColor : null;
     }
 
+    protected internalSetForegroundColor(color?: string): void {
+        this.foregroundColor = color;
+        this.entries.forEach(entry => {
+            entry.color = this.foregroundColor ? this.foregroundColor : undefined;
+        });
```
Comment (lmcbout) [inline packages/core/src/browser/status-bar/status-bar.tsx]: @vince-fugnitto Foreground is black for most of the field except for the "ln and column" of an editor which are still white when offline

Comment (vince-fugnitto) [reply packages/core/src/browser/status-bar/status-bar.tsx]: @lmcbout do you mean this?
screen shot 2018-11-16 at 3 38 59 pm

**Comment by vince-fugnitto** [comment]
it looks like I'll have to try my original implementation of setting a `class name` to the status-bar in order to get the behaviour I want.

**Comment by elaihau** [comment]
> can you retest to see if everything is fine?

now everything looks dark ....
screenshot from 2018-11-19 08-29-15

**Comment by vince-fugnitto** [comment]
> > can you retest to see if everything is fine?
> 
> now everything looks dark ....

Thanks @elaihau I noticed it too, I forgot the initial call to `handleOnline()`

**Comment by elaihau** [comment]
now it looks good :)

File: packages/core/src/browser/status-bar/status-bar.tsx [hunk 2]
```diff
@@ -62,14 +62,21 @@ export const StatusBar = Symbol('StatusBar');
 
 export interface StatusBar {
     setBackgroundColor(color?: string): Promise<void>;
+    setClassName(state: StatusBarState): Promise<void>;
```
Comment (akosyakov) [inline packages/core/src/browser/status-bar/status-bar.tsx]: status bar should not care about it

Comment (vince-fugnitto) [reply packages/core/src/browser/status-bar/status-bar.tsx]: the issue with `setForegroundColor` or `setColor` is that it works initially but if a file is selected for instance after being offline it will be rendered with a white font.

Comment (vince-fugnitto) [reply packages/core/src/browser/status-bar/status-bar.tsx]: I tried many different combinations on what to do but the easiest sure way to do it for me was to update the status-bar class name when offline or online

Comment (akosyakov) [reply packages/core/src/browser/status-bar/status-bar.tsx]: > the issue with setForegroundColor or setColor is that it works initially but if a file is selected for instance after being offline it will be rendered with a white font.

What is the cause of its to be rendered with a white font after being offline?

Comment (vince-fugnitto) [reply packages/core/src/browser/status-bar/status-bar.tsx]: We re-render some status-bar items such as `line, column` if a new file is clicked while offline. Since our default css uses a white font color I believe it's using that color when rendering. Calling the `handleOffline()` is done once when the state is changed, so any updated to a status-bar item will not get the correct styling.

Comment (akosyakov) [reply packages/core/src/browser/status-bar/status-bar.tsx]: > Since our default css uses a white font color I believe it's using that color when rendering.

How about making sure that is using the last set foreground color and only if it is not set (`null`) use the default color?

Comment (akosyakov) [reply packages/core/src/browser/status-bar/status-bar.tsx]: Making `StatusBar` suitable only for a particular client (`ApplicationConnectionStatusContribution`)  is not a good API.

Comment (vince-fugnitto) [reply packages/core/src/browser/status-bar/status-bar.tsx]: thanks @akosyakov I'll make the changes

**Comment by vince-fugnitto** [comment]
@akosyakov I made updates to the PR, was this more in line with what you were thinking about ?

File: packages/core/src/browser/status-bar/status-bar.tsx [hunk 3]
```diff
@@ -109,6 +111,13 @@ export class StatusBarImpl extends ReactWidget implements StatusBar {
         this.node.style.backgroundColor = this.backgroundColor ? this.backgroundColor : null;
     }
 
+    async setColor(color?: string): Promise<void> {
```
Comment (marechal-p) [inline packages/core/src/browser/status-bar/status-bar.tsx]: `setBackgroundColor` is waiting for `this.ready`, should `setColor` do the same? As well as defining an internal method just to mimic what is done in `setBackgroundColor`?

File: packages/core/src/browser/status-bar/status-bar.tsx [hunk 4]
```diff
@@ -109,6 +111,13 @@ export class StatusBarImpl extends ReactWidget implements StatusBar {
...
+        this.color = color;
+        this.entries.forEach(entry => {
+            entry.color = this.color ? this.color : undefined;
```
Comment (akosyakov) [inline packages/core/src/browser/status-bar/status-bar.tsx]: Why `entry.color` should be updated? If a user provides a color should not we use it instead of the status bar color?

File: packages/core/src/browser/status-bar/status-bar.tsx (hunk 3 above)
Comment (akosyakov) [inline packages/core/src/browser/status-bar/status-bar.tsx]: How about calling `this.update` at the end of the method to trigger rendering? Otherwise, a new color won't be applied immediately.

Comment (vince-fugnitto) [reply packages/core/src/browser/status-bar/status-bar.tsx]: thanks I must have missed it in my updates

File: packages/core/src/browser/status-bar/status-bar.tsx (hunk 4 above)
Comment (vince-fugnitto) [reply packages/core/src/browser/status-bar/status-bar.tsx]: my understanding is we want both `setBackgroundColor` for the statusbar background and `setColor` is for the font color for the entire statusbar, is there a use case where we'd have mutliple font colors that we'd like to preserve?

File: packages/core/src/browser/status-bar/status-bar.tsx (hunk 3 above)
Comment (vince-fugnitto) [reply packages/core/src/browser/status-bar/status-bar.tsx]: yes sounds good!

Comment (akosyakov) [reply packages/core/src/browser/status-bar/status-bar.tsx]: no, `setBackgroundColor` mutates DOM node directly

File: packages/core/src/browser/status-bar/status-bar.tsx (hunk 4 above)
Comment (akosyakov) [reply packages/core/src/browser/status-bar/status-bar.tsx]: The client can provide a custom color for a particular entry, then this color should be used.

**Comment by vince-fugnitto** [comment]
@akosyakov @marechal-p 
I've updated the PR so it now works nicely and handles if the color has been defined by the user :)
