### PR TITLE
[debug] Add ability to fork a process for a debug adapter

### LINKED ISSUE #3176: [debug-cortex] External node process
I've spotted today that `gdb.js` in debug cortex plugin is spawned as a separate node process (https://github.com/theia-ide/theia/blob/debug-cortex/packages/debug-cortex/src/node/debug-cortex.ts#L141). It works well when Theia is started in development environment. Unfortunately it fails when it is packaged inside electron and installed on the system.
In that case the node is not found and the process crashes. Any idea on how it can be fixed?

### PR DESCRIPTION
**Pull request by thegecko**
Signed-off-by: Rob Moran <rob.moran@arm.com>

Building on #3637, this PR allows a debug adapter to use a forked node process instead of a spawned one.

Resolves #3176

### CODE REVIEW

File: packages/debug/src/node/debug-adapter.ts [hunk 1]
```diff
@@ -60,9 +63,19 @@ export class LaunchBasedDebugAdapterFactory implements DebugAdapterFactory {
...
+            !!forkOptions && !!forkOptions.modulePath;
+
+        const processOptions: RawProcessOptions | RawForkOptions = executable;
+        const options = { stdio: ['pipe', 'pipe', 2] };
+
+        if (isForkOptions(processOptions)) {
+            options.stdio.push('ipc');
+        }
+
+        processOptions.options = options;
```
Comment (akosyakov) [inline packages/debug/src/node/debug-adapter.ts]: looks like we mutate `executable` here, we should create a new copy

Comment (thegecko) [reply packages/debug/src/node/debug-adapter.ts]: ack, have updated the code to shallow-copy executable.
