### PR TITLE
Register the current EditorTheme and retrigger monaco tokenizing

### LINKED ISSUE #4550: textmate highlighting is missing
I've noticed that sometimes textmate highlighting is missing for new window. It is always there for a first window. Don't know how to reproduce yet.

### PR DESCRIPTION
**Pull request by jbicker**
...initially and after theme changed.
Additionally remove old css theme class from body.
Fixes #4550

As a test one should add a default theme to package.json different fro the dark theme. 

Thanks a lot to @akosyakov for helping with this fix!!!

### CODE REVIEW

File: packages/monaco/src/browser/textmate/monaco-textmate-service.ts [hunk 1]
```diff
@@ -99,17 +99,31 @@ export class MonacoTextmateService implements FrontendApplicationContribution {
...
+            monaco.editor.setTheme(currentEditorTheme);
         });
 
         for (const { id } of monaco.languages.getLanguages()) {
             monaco.languages.onLanguage(id, () => this.activateLanguage(id));
         }
     }
 
+    protected get currentEditorTheme(): string {
+        return this.themeService.getCurrentTheme().editorTheme || MonacoThemeRegistry.DARK_DEFAULT_THEME;;
```
Comment (akosyakov) [inline packages/monaco/src/browser/textmate/monaco-textmate-service.ts]: trailing ';'

File: packages/monaco/src/browser/textmate/monaco-textmate-service.ts [hunk 2]
```diff
@@ -99,17 +99,31 @@ export class MonacoTextmateService implements FrontendApplicationContribution {
...
+            const currentEditorTheme = this.currentEditorTheme;
+            document.body.classList.add(currentEditorTheme);
+
+            // first update registry to run tokenization with the proper theme
+            const theme = this.monacoThemeRegistry.getTheme(currentEditorTheme);
             if (theme) {
                 this.grammarRegistry.setTheme(theme);
             }
+
+            // then trigger tokenization but setting monaco theme
```
Comment (akosyakov) [inline packages/monaco/src/browser/textmate/monaco-textmate-service.ts]: `but` -> `by`

**Comment by akosyakov** [comment]
Just to sum up: the root cause was a race condition between updating textmate and monaco themes. Sometimes monaco theme will be updated before leading to coloring a file with an old theme. Now textmate should be updated before monaco theme.

Funny effect was that a file could end up be highlighted partially by old and new themes if an update of a textmate theme happens while monaco still running tokenization.
