### PR TITLE
fix #3697 Remove blocking await.

### LINKED ISSUE #3697: [performance] [filesystem] Slow loading with large workspace root
Theia takes an exceptionally long time starting when using a large directory as the workspace root. AFICT the issue started to manifest after the submission of https://github.com/theia-ide/theia/commit/543b119a32652f662968411370979ea002a1736a

### PR DESCRIPTION
**Pull request by caseyflynn-google**
PR removes blocking await when starting a file watcher. This is
particularly important when starting Theia with a large workspace root
as the file watch will block Theia loading.

Signed-off-by: Casey Flynn <caseyflynn@google.com>

### CODE REVIEW

File: packages/filesystem/src/node/nsfw-watcher/nsfw-filesystem-watcher.ts [hunk 1]
```diff
@@ -79,7 +79,7 @@ export class NsfwFileSystemWatcherServer implements FileSystemWatcherServer {
         const basePath = FileUri.fsPath(uri);
         this.debug('Starting watching:', basePath);
         if (fs.existsSync(basePath)) {
-            await this.start(watcherId, basePath, options);
```
Comment (akosyakov) [inline packages/filesystem/src/node/nsfw-watcher/nsfw-filesystem-watcher.ts]: we should implement the cancellation then, otherwise, it can be that `unwatchFileChanges` is called, do nothing and then watching actually started (which can be stopped anymore)

**Comment by akosyakov** [comment]
> PR removes blocking await when starting a file watcher.

I wonder how await can be blocking. Blocking code usually is synchronous and does not allow node process to handle new requests. In this case, the code seems to be async and should allow handling of other requests.

**Comment by marechal-p** [comment]
@akosyakov you are right that an await allow for non blocking code, unless something in the Theia boot-up sequence someone specifically wait for this before starting the application. Somewhere inside a `onStart` hook?

```
root WARN EditorNavigationContribution.onStart is slow, took: 46547 ms
```

When I opened Theia on `/`.

**Comment by akosyakov** [comment]
@marechal-p can you profile the frontend please and find out with the root cause why it takes 45s? We need to rewrite `EditorNavigationContribution` for sure, that it does not block the shell to load navigation history: https://github.com/theia-ide/theia/issues/3413 But I suspect it is not related to this issue or a follow-up effect.

I am also not against these changes. I want to understand why it helps and how I can verify it + unwatch should be handled properly.

**Comment by marechal-p** [comment]
@akosyakov the long wait is because of something silly:

`EditorNavigationContribution.onStart` needs to call some `WorkspaceStorageSerivce.getData` which will wait for `WorkspaceStorageService` to be "initialiazed", that happens when the `WorkspaceService` has resolved its roots. But somewhere in the root resolution, there was an await on the watchers.

I made a diff to see if I could fix it where the wrong components where waiting for it: https://github.com/theia-ide/theia/commit/e61e92516ab77e971838cd554f211ef84f9b1ef6

With this, the `EditorNavigationContribution.onStart` goes from [10 to 50] seconds down to ~400ms, when opening my system root (`/`)

**Comment by caseyflynn-google** [comment]
> With this, the `EditorNavigationContribution.onStart` goes from [10 to 50] seconds down to ~400ms, when opening my system root (`/`)

This seems to resolve the issue for me too. Can we apply this fix to Master?

**Comment by akosyakov** [comment]
@marechal-p thanks for the analysis, it is clear now

@caseyflynn-google as soon as tests are green

I've pushed one commit to address https://github.com/theia-ide/theia/pull/3699/files#r238060287 The `await` was there to make sure that the disposable object for a watcher is created. If we remove `await` we need to create this object earlier. I've pulled it up.
