### PR TITLE
[monaco] Fix `MonacoWorkspace.fireWillSave`

### LINKED ISSUE #3849: Saving files is slow
Saving files (I have auto-save disabled) is relatively slow since 7ad39cb4ba9c3b1092d486ca36538a6af4810e4e.  Before that, the little dot that indicates that a file is dirty would disappear almost instantly after hitting ctrl-s (at least for a small file on a local backend).  After this commit, it takes roughly one second.

For the purpose of the test, I test with a small `.txt` file, which means there is no associated language server.

### PR DESCRIPTION
**Pull request by marechal-p**
Since ad39cb4ba9c3b1092d486ca36538a6af4810e4e, saving took roughly one
second everytime, even for almost empty text files. The commit simply
made the model saving process properly wait for every listener, this
means that someone was behaving badly.

MonacoWorkspacer registered a promise on that event, which was never
resolved. This commit fixes it.

Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

Fix #3849

### CODE REVIEW

File: packages/monaco/src/browser/monaco-workspace.ts [hunk 1]
```diff
@@ -170,13 +170,24 @@ export class MonacoWorkspace implements lang.Workspace {
...
-                waitUntil: thenable => thenable.then(resolve)
-            })
-        );
+                waitUntil: thenable => {
+                    thenables.push(thenable);
+                }
+            });
+
+            for (const listenerEdits of await Promise.all(thenables)) {
+                allEdits.push(...listenerEdits);
```
Comment (simark) [inline packages/monaco/src/browser/monaco-workspace.ts]: It's still a mystery to me how edits from multiple sources, based on the same initial version, can apply cleanly in succession.  But if it works for our current use case, I won't ask questions.

**Comment by simark** [comment]
Just wondering, have you tested with format-on-save done by a language server?  I am not sure how to try that.

File: packages/monaco/src/browser/monaco-workspace.ts (hunk 1 above)
Comment (marechal-p) [reply packages/monaco/src/browser/monaco-workspace.ts]: In this case there is no listeners (which was also the reason why it never resolved before), so no collisions either :p

But I understand your concern, no idea how it works, maybe it is bogus, but I would like to keep that for later as it is beyond my understanding now.

Comment (marechal-p) [reply packages/monaco/src/browser/monaco-workspace.ts]: @svenefftinge do you or someone else know anything about this API and how it works?

Comment (marechal-p) [reply packages/monaco/src/browser/monaco-workspace.ts]: IIUC, in VS Code they do contribute [in sequence, no parallelism](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDocumentSaveParticipant.ts#L58-L69).

Comment (marechal-p) [reply packages/monaco/src/browser/monaco-workspace.ts]: So I don't really know how to mimic the behavior in VS Code without changing the API in Theia...

Comment (simark) [reply packages/monaco/src/browser/monaco-workspace.ts]: > So I don't really know how to mimic the behavior in VS Code without changing the API in Theia...

Do you mean the first contributor works with the original version of the document, then second contributor works with the version already modified by the first one, etc?

Comment (simark) [reply packages/monaco/src/browser/monaco-workspace.ts]: > In this case there is no listeners (which was also the reason why it never resolved before), so no collisions either :p
> 
> But I understand your concern, no idea how it works, maybe it is bogus, but I would like to keep that for later as it is beyond my understanding now.

Yes, I think we can merge your patch, but keep this in mind for later.  We can maybe come up with a synthetic test with two or more contributors that try to edit the same line to see what happens.

Comment (marechal-p) [reply packages/monaco/src/browser/monaco-workspace.ts]: > Do you mean the first contributor works with the original version of the document, then second contributor works with the version already modified by the first one, etc?

Yes.
